// ai-consent.spec.mjs — task 31: AI consent flow + graceful degradation (standalone).
//
// Run: node tests/e2e/ai-consent.spec.mjs
//      E2E_DEVTOOLS_MINIMIZE=1 node tests/e2e/ai-consent.spec.mjs   (cold, hidden)
// Evidence: artifacts/e2e/ai-consent.json
//           artifacts/qa/31-failure.txt   (revocation + fail-closed transcript)
//
// Two independent layers, never conflated:
//   (1) LOGIC (real code path): pages/ai/ai.ts is imported into a node harness (Page-capture +
//       Map-backed wx shim with storage + a programmable modal + navigate capture + a
//       programmable wx.request mock). It drives the REAL page methods: default-off send (guide
//       modal + navigate + preview + skip, zero request), enable -> preview includes the
//       auto-extract notice line, proxy failure -> status offline + error + input preserved,
//       next send -> AUTO LOCAL (zero request, status local), retry clears the fallback,
//       in-flight extract discard when the prefs flip mid-flight, and autoMemory=false -> no
//       extract request at all.
//   (2) RUNTIME (REAL, via miniProgram.evaluate): seeds default-off prefs, drives a REAL send
//       attempt (guide modal recorded by an evaluate-level showModal stub, status disabled),
//       enables AI via a storage write + reload (preview shows), then sends with the local proxy
//       NATURALLY DOWN (this spec never spawns it) -> failure -> status offline; a second send
//       returns an auto-local result with ZERO wx.request (counted via an evaluate-level
//       wrapper). A final stubbed-online send proves the `ok` state. Screenshot render +
//       close+relaunch message persistence. No success is ever faked.
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {
  CONFIG,
  E2E_ARTIFACTS,
  ROOT,
  ensureDir,
  fail,
  launchMiniProgram,
  log,
  ok,
  section,
  tcpProbe,
  delay,
  md5,
  readPageBundle,
  withTimeout,
  aiCopyBlock,
  makeCaptureScreenshot,
  makeRenderEvidence,
  makeClearAiKeys,
} from './helpers.mjs';

const AI_ROUTE = 'pages/ai/ai';
const MINIAPP_ROOT = CONFIG.projectPath;
const AI_DIR = path.join(MINIAPP_ROOT, 'pages', 'ai');
const TEXTS_TS = path.join(MINIAPP_ROOT, 'config', 'texts.ts');
const PROXY_PORT = 8787;

const E2E_DIR = E2E_ARTIFACTS;
const QA_FAILURE_PATH = path.join(ROOT, 'artifacts', 'qa', '31-failure.txt');


// ---------------------------------------------------------------------------
// Layer 1: node/page-logic harness (real page methods + Map wx shim)
// ---------------------------------------------------------------------------

const HARNESS_SOURCE = String.raw`// temp ai-consent logic harness (run via tsx); not committed — generated by ai-consent.spec.mjs
import { pathToFileURL } from 'node:url';
import { writeFileSync } from 'node:fs';
import path from 'node:path';
const { blockTitles, hasBlock, lastMsg, makeCheck, makeFlog, makeInstanceFactory, makeSeedRecords } = await import(${JSON.stringify(new URL('./helpers.mjs', import.meta.url).href)});

const aiTs = process.env.MHP_AI_TS;
const root = process.env.MHP_MINIAPP_ROOT;
const outPath = process.env.MHP_HARNESS_OUT;
const failureOut = process.env.MHP_FAILURE_OUT;
if (!aiTs || !root || !outPath) throw new Error('missing harness env');

const ORGANIZE = {
  points: ['近一周出现头痛'],
  extracted: { symptoms: ['头痛'], medications: [], allergies: [], history: [], exams: [] },
  unknowns: ['诱因未说明'],
  questions: ['头痛多久一次？'],
};
const CONSULT = {
  directions: [
    { text: '注意休息与规律作息', citation: { title: '示例来源', url: 'https://nhc.gov.cn/demo', domain: 'nhc.gov.cn' } },
  ],
  suggestedDepartments: ['全科'],
  citations: [{ title: '示例来源', url: 'https://nhc.gov.cn/demo', domain: 'nhc.gov.cn' }],
  suggestions: [
    { text: '作息规律、避免熬夜', citation: { title: '示例来源', url: 'https://nhc.gov.cn/demo', domain: 'nhc.gov.cn' } },
  ],
  unknowns: [],
  questions: [],
  disclaimer: '以上内容仅为信息整理与一般性提示。',
};
const EXTRACT = { candidates: [{ text: '希望回复简短' }, { text: '多在夜间记录' }, { text: '不要催我' }] };

const store = new Map();
const calls = { toast: [], modal: [], navigate: [], request: [] };
let modalAnswer = true;
let requestMode = 'ok';
let extractBeforeResolve = null;
let recordsRef = null;

globalThis.wx = {
  getStorageSync: function (key) { return store.has(key) ? store.get(key) : ''; },
  setStorageSync: function (key, value) { store.set(key, value); },
  removeStorageSync: function (key) { store.delete(key); },
  getStorageInfoSync: function () { return { keys: Array.from(store.keys()) }; },
  showToast: function (o) { calls.toast.push(o); },
  showModal: function (o) {
    calls.modal.push({ title: o && o.title, content: o && o.content, confirmText: o && o.confirmText, cancelText: o && o.cancelText });
    if (o && typeof o.success === 'function') o.success({ confirm: modalAnswer, cancel: !modalAnswer });
  },
  vibrateShort: function () {},
  vibrateLong: function () {},
  navigateTo: function (o) { calls.navigate.push(o); if (o && typeof o.success === 'function') o.success({}); },
  request: function (options) {
    calls.request.push({ url: options.url, data: options.data });
    setTimeout(function () {
      if (requestMode === 'unreachable') { options.fail({ errMsg: 'request:fail' }); return; }
      if (requestMode === 'timeout') { options.fail({ errMsg: 'request:fail timeout' }); return; }
      if (requestMode === 'http-500') { options.success({ statusCode: 500, data: { error: 'upstream_error' } }); return; }
      const url = String(options.url || '');
      if (url.indexOf('/api/extract-memory') !== -1) {
        if (extractBeforeResolve !== null) extractBeforeResolve();
        options.success({ statusCode: 200, data: EXTRACT });
        return;
      }
      let body = {};
      try { body = JSON.parse(options.data); } catch (e) { body = {}; }
      options.success({ statusCode: 200, data: body.mode === 'organize' ? ORGANIZE : CONSULT });
    }, 0);
    return { abort: function () {} };
  },
};

let captured = null;
globalThis.Page = function (config) { captured = config; };

const textsModule = await import(pathToFileURL(path.join(root, 'config/texts.ts')).href);
const AI = textsModule.AI;
const DEGRADED = textsModule.DEGRADED;
const EXTRACT_NOTICE = textsModule.AUTO_EXTRACT_NOTICE;

await import(pathToFileURL(aiTs).href);
if (captured === null) throw new Error('ai.ts did not call Page()');

const recordsModule = await import(pathToFileURL(path.join(root, 'shared/services/records.ts')).href);
const records = recordsModule.records;
recordsRef = records;

const makeInstance = makeInstanceFactory(() => captured, { cloneExtras: true });
function resetAll() {
  store.clear();
  calls.toast.length = 0; calls.modal.length = 0; calls.navigate.length = 0; calls.request.length = 0;
  modalAnswer = true; requestMode = 'ok'; extractBeforeResolve = null;
}
function seedPrefs(aiEnabled, autoMemory) {
  records.preferences.update({ aiEnabled: aiEnabled === true, consentVersion: 1, fontSize: 14, highContrast: false, autoMemory: autoMemory !== false });
}
const seedRecords = makeSeedRecords(records);
function extractCalls() { return calls.request.filter(function (r) { return String(r.url).indexOf('/api/extract-memory') !== -1; }); }
function aiMemoryCount() { return records.memory.list().filter(function (m) { return m.source === 'ai'; }).length; }

const cases = [];
const check = makeCheck(cases);

// h1 default-off: guide modal + navigate + preview + skip, zero request
resetAll();
seedPrefs(false, true);
let inst = makeInstance();
inst.onLoad({});
inst.onShow();
const statusFresh = { aiStatus: inst.data.aiStatus, aiStatusText: inst.data.aiStatusText };
inst.onInput({ detail: { value: '最近睡不好' } });
modalAnswer = true;
const sendDisabled = await inst.onSend();
const guide = calls.modal[calls.modal.length - 1] || null;
const navToSettings = calls.navigate.some(function (o) { return o && o.url === '/pages/settings/settings'; });
const disabledPreview = { open: inst.data.previewOpen, notice: inst.data.previewMemoryNotice };
const disabledStatusAfterSend = inst.data.aiStatus;
const confirmDisabled = await inst.onConfirmSend();
const disabledMsg = lastMsg(inst);
const disabledFacts = {
  guide_title: guide && guide.title,
  guide_content: guide && guide.content,
  nav_captured: navToSettings,
  send_reason: sendDisabled.reason,
  preview_open: disabledPreview.open,
  preview_notice: disabledPreview.notice,
  status_before: statusFresh.aiStatus,
  status_after_send: disabledStatusAfterSend,
  confirm_ok: confirmDisabled.ok,
  message_kind: disabledMsg.kind,
  error_text: disabledMsg.errorText,
  can_local: disabledMsg.canLocalOrganize,
  blocks: disabledMsg.blocks.length,
  requests: calls.request.length,
};
check('default-off-guide', 'default off: guide modal (title/content) + 去设置 navigate + preview + skip message; status disabled; zero request',
  statusFresh.aiStatus === 'disabled' && statusFresh.aiStatusText === AI.statusDisabled &&
    guide !== null && guide.title === AI.guideTitle && guide.content === AI.guideContent &&
    navToSettings === true && sendDisabled.reason === 'preview' && disabledPreview.open === true &&
    disabledPreview.notice === '' && disabledStatusAfterSend === 'disabled' &&
    confirmDisabled.ok === false && disabledMsg.kind === 'error' && disabledMsg.errorText === DEGRADED.notEnabled &&
    disabledMsg.canLocalOrganize === true && disabledMsg.blocks.length === 0 && calls.request.length === 0,
  disabledFacts);

// h2 enable -> preview includes the auto-extract notice line (autoMemory on), zero request yet
resetAll();
seedPrefs(true, true);
seedRecords();
inst = makeInstance();
inst.onLoad({});
inst.onShow();
const idleStatus = inst.data.aiStatus;
inst.onInput({ detail: { value: '最近胃不舒服' } });
const sendEnabled = await inst.onSend();
const enabledPreview = {
  open: inst.data.previewOpen,
  notice: inst.data.previewMemoryNotice,
  titles: inst.data.previewSections.map(function (s) { return s.title; }),
};
// health probes (/api/health) are background status checks, not AI requests — exclude them
const nonHealthRequests = calls.request.filter(function (r) { return String(r.url).indexOf('/api/health') === -1; }).length;
check('enable-preview-notice', 'enabled + autoMemory on: send opens the preview with the auto-extract notice line; previewSections titles unchanged; zero AI request before confirm (health probes excluded)',
  idleStatus === 'idle' && sendEnabled.reason === 'preview' && enabledPreview.open === true &&
    enabledPreview.notice === EXTRACT_NOTICE && enabledPreview.titles.indexOf('对话') !== -1 &&
    nonHealthRequests === 0,
  { idle: idleStatus, preview: enabledPreview, requests_non_health: nonHealthRequests, requests_total: calls.request.length });

// h3 proxy failure -> status offline + error message + input preserved + zero fake blocks
requestMode = 'unreachable';
const failResult = await inst.onConfirmSend();
const failMsg = lastMsg(inst);
const failFacts = {
  returned: failResult,
  kind: failMsg.kind,
  error_text: failMsg.errorText,
  blocks: failMsg.blocks.length,
  can_local: failMsg.canLocalOrganize,
  input_preserved: inst.data.input,
  status: inst.data.aiStatus,
};
check('proxy-failure-offline', 'external failure: status offline + proxy-offline message, input preserved, no fake AI blocks',
  failResult.ok === false && failFacts.kind === 'error' && failFacts.error_text === DEGRADED.proxyOffline &&
    failFacts.blocks === 0 && failFacts.can_local === true && failFacts.input_preserved === '最近胃不舒服' &&
    failFacts.status === 'offline',
  failFacts);

// h4 next send while offline -> AUTO LOCAL, zero request, status local
const reqBeforeLocal = calls.request.length;
const localSend = await inst.onSend();
const localMsg = lastMsg(inst);
const localFacts = {
  returned: localSend,
  kind: localMsg.kind,
  requests_delta: calls.request.length - reqBeforeLocal,
  block_titles: blockTitles(localMsg),
  hint: inst.data.hint,
  status: inst.data.aiStatus,
  preview_open: inst.data.previewOpen,
};
check('auto-local-zero-network', 'while offline the next send runs LOCAL organize with zero wx.request; kind local + 要点/提取/待补充/可以问的问题; status local + hint',
  localSend.reason === 'local' && localFacts.kind === 'local' && localFacts.requests_delta === 0 &&
    localFacts.preview_open === false && hasBlock(localMsg, 'list', AI.sectionPoints) &&
    hasBlock(localMsg, 'extracted', AI.sectionExtracted) && hasBlock(localMsg, 'list', AI.sectionUnknowns) &&
    hasBlock(localMsg, 'list', AI.sectionQuestions) && localFacts.hint === AI.autoLocalHint && localFacts.status === 'local',
  localFacts);

// h5 retry clears the fallback -> the next send tries the external path and succeeds -> status ok
const retry = inst.onRetryConnection();
const statusAfterRetry = inst.data.aiStatus;
requestMode = 'ok';
inst.onInput({ detail: { value: '最近还是睡不好' } });
const sendRetry = await inst.onSend();
const retryPreview = { reason: sendRetry.reason, open: inst.data.previewOpen, notice: inst.data.previewMemoryNotice };
const reqBeforeRetry = calls.request.length;
const confirmRetry = await inst.onConfirmSend();
const retryMsg = lastMsg(inst);
const retryFacts = {
  retried: retry.retried,
  status_after_retry: statusAfterRetry,
  preview: retryPreview,
  confirmed: confirmRetry,
  kind: retryMsg.kind,
  status_after_send: inst.data.aiStatus,
  requests_delta: calls.request.length - reqBeforeRetry,
};
check('retry-clears-fallback', '重试连接 clears offline/local -> status idle; the next send previews the external path and succeeds (status ok)',
  retry.retried === true && statusAfterRetry === 'idle' && retryPreview.reason === 'preview' && retryPreview.open === true &&
    confirmRetry.ok === true && retryMsg.kind === 'organize' && retryFacts.requests_delta >= 1 &&
    retryFacts.status_after_send === 'ok',
  retryFacts);

// h6 in-flight extract discard: autoMemory flipped off between ask resolve and extract resolve
resetAll();
seedPrefs(true, true);
seedRecords();
inst = makeInstance();
inst.onLoad({});
inst.onShow();
const memBefore6 = aiMemoryCount();
extractBeforeResolve = function () { records.preferences.update({ autoMemory: false }); };
inst.onInput({ detail: { value: '最近睡不好' } });
await inst.onSend();
const askKind6 = (await inst.onConfirmSend()).kind;
const memAfter6 = aiMemoryCount();
const discard6Facts = {
  ask_kind: askKind6,
  memory_before: memBefore6,
  memory_after: memAfter6,
  hint: inst.data.autoMemoryHint,
};
check('extract-discard-automemory', 'autoMemory flipped off during the in-flight extract: the response is discarded (no memory write) with a subtle hint',
  askKind6 === 'organize' && memAfter6 === memBefore6 && inst.data.autoMemoryHint === AI.memoryDiscardHint,
  discard6Facts);
extractBeforeResolve = null;

// h7 in-flight extract discard: AI revoked (aiEnabled=false) mid-flight -> no memory write
resetAll();
seedPrefs(true, true);
seedRecords();
inst = makeInstance();
inst.onLoad({});
inst.onShow();
const memBefore7 = aiMemoryCount();
extractBeforeResolve = function () { records.preferences.update({ aiEnabled: false }); };
inst.onInput({ detail: { value: '最近睡不好' } });
await inst.onSend();
const askKind7 = (await inst.onConfirmSend()).kind;
const memAfter7 = aiMemoryCount();
const revokeFacts = {
  ask_kind: askKind7,
  memory_before: memBefore7,
  memory_after: memAfter7,
  hint: inst.data.autoMemoryHint,
  ai_enabled: records.preferences.get().aiEnabled,
};
check('extract-discard-revocation', 'revoking external AI during the in-flight extract discards the response: zero memory writes, discard hint',
  askKind7 === 'organize' && memAfter7 === memBefore7 && revokeFacts.hint === AI.memoryDiscardHint &&
    revokeFacts.ai_enabled === false,
  revokeFacts);
extractBeforeResolve = null;

// h8 autoMemory=false -> no extract request at all
resetAll();
seedPrefs(true, false);
seedRecords();
inst = makeInstance();
inst.onLoad({});
inst.onShow();
inst.onInput({ detail: { value: '最近睡不好' } });
await inst.onSend();
const ok8 = await inst.onConfirmSend();
const extract8 = extractCalls().length;
check('autoMemory-off-no-extract', 'autoMemory off: a successful ask issues no /api/extract-memory request and shows no hint',
  ok8.ok === true && extract8 === 0 && inst.data.autoMemoryHint === '' && aiMemoryCount() === 0,
  { ok: ok8, extract_requests: extract8, hint: inst.data.autoMemoryHint });

// h9 aiEnabled=false page stays usable: local organize + manual memory + status disabled, zero request
resetAll();
seedPrefs(false, true);
inst = makeInstance();
inst.onLoad({});
inst.onShow();
inst.onInput({ detail: { value: '最近睡不好' } });
const localOnly = inst.onLocalOrganize({ currentTarget: { dataset: { text: '最近睡不好' } } });
const localOnlyMsg = lastMsg(inst);
inst.onInput({ detail: { value: '希望回复简短' } });
const memAdd = inst.onSaveMemory({ currentTarget: { dataset: { id: 'input' } } });
check('disabled-local-usable', 'aiEnabled=false: local organize + manual memory save still work; status stays disabled; zero request',
  inst.data.aiStatus === 'disabled' && localOnly.organized === true && localOnlyMsg.kind === 'local' &&
    memAdd.added === true && records.memory.list().length === 1 && calls.request.length === 0,
  { status: inst.data.aiStatus, local: localOnly, mem: memAdd, requests: calls.request.length });

const failed = cases.filter(function (c) { return !c.pass; }).length;

const failureLines = [];
const flog = makeFlog(failureLines);
flog('T31 AI consent / graceful-degradation failure-path evidence (revocation discard + fail-closed no-send; real page methods)');
flog('command: node tests/e2e/ai-consent.spec.mjs');
flog('timestamp: ' + new Date().toISOString());
flog('method: REAL pages/ai/ai.ts methods (onSend/onConfirmSend/onRetryConnection/onLocalOrganize/onSaveMemory) driven by a node harness; wx = Map-backed shim (storage + modal + navigate + programmable wx.request). Page methods are called with the same argument shapes the wxml passes.');
flog('data provenance: REAL = the ai.ts method code path; SYNTHETIC = the in-harness prefs flip + the mock ask/extract responses (no real patient data, no real network).');
flog('scenario: in-flight extract revocation (aiEnabled flipped false between the ask resolve and the extract resolve)');
flog('revocation_ask_kind: ' + JSON.stringify(revokeFacts.ask_kind));
flog('revocation_memory_before: ' + revokeFacts.memory_before + ' -> after: ' + revokeFacts.memory_after + ' (expected identical)');
flog('revocation_ai_enabled_after: ' + revokeFacts.ai_enabled);
flog('revocation_discard_hint: ' + JSON.stringify(revokeFacts.hint) + ' (expected ' + JSON.stringify(AI.memoryDiscardHint) + ')');
flog('scenario: default-off send is fail-closed (zero outbound request)');
flog('no_send_guide_title: ' + JSON.stringify(disabledFacts.guide_title));
flog('no_send_navigate_captured: ' + disabledFacts.nav_captured);
flog('no_send_message_kind: ' + JSON.stringify(disabledFacts.message_kind) + ', error_text: ' + JSON.stringify(disabledFacts.error_text));
flog('no_send_requests_total: ' + disabledFacts.requests + ' (expected 0)');
flog('scenario: offline send auto-falls-back to local with zero wx.request');
flog('auto_local_kind: ' + JSON.stringify(localFacts.kind) + ', requests_delta: ' + localFacts.requests_delta + ' (expected 0), status: ' + JSON.stringify(localFacts.status));
flog('verdict: PASS (revocation discards the in-flight extract; with external AI off nothing leaves the machine; offline sends fall back to local with zero network)');
flog('exit_code_evidence: artifacts/qa/31-failure.txt is written by the passing run (contract: fail closed / discard in-flight).');

if (failureOut) writeFileSync(failureOut, failureLines.join('\n') + '\n');

const result = {
  generated_at: new Date().toISOString(),
  ai_ts: aiTs,
  note: 'REAL page methods from pages/ai/ai.ts; wx = Map-backed shim (storage + modal + navigate + programmable wx.request)',
  scenarios: cases,
  failure_path: {
    lines: failureLines,
    pass: revokeFacts.memory_before === revokeFacts.memory_after && revokeFacts.hint === AI.memoryDiscardHint &&
      disabledFacts.requests === 0 && disabledFacts.message_kind === 'error' &&
      localFacts.requests_delta === 0 && localFacts.kind === 'local',
  },
  summary: { total: cases.length, passed: cases.length - failed, failed: failed },
};
writeFileSync(outPath, JSON.stringify(result, null, 2) + '\n');
console.log(JSON.stringify(result, null, 2));
process.exit(failed === 0 ? 0 : 1);
`;

function runLogicHarness() {
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'mhp-ai-consent-harness-'));
  const harnessPath = path.join(tmpDir, 'ai-consent-logic.harness.mjs');
  const outPath = path.join(tmpDir, 'ai-consent-logic.result.json');
  const failurePath = path.join(tmpDir, 'ai-consent-failure.txt');
  fs.writeFileSync(harnessPath, HARNESS_SOURCE);

  const res = spawnSync(process.execPath, ['--import', 'tsx', harnessPath], {
    cwd: ROOT,
    encoding: 'utf8',
    env: {
      ...process.env,
      MHP_AI_TS: path.join(AI_DIR, 'ai.ts'),
      MHP_MINIAPP_ROOT: MINIAPP_ROOT,
      MHP_HARNESS_OUT: outPath,
      MHP_FAILURE_OUT: failurePath,
    },
    timeout: 90000,
    maxBuffer: 32 * 1024 * 1024,
  });
  const stdout = `${res.stdout || ''}`;
  const stderr = `${res.stderr || ''}`;

  let result = null;
  if (fs.existsSync(outPath)) {
    try {
      result = JSON.parse(fs.readFileSync(outPath, 'utf8'));
    } catch (err) {
      fail(`harness result JSON unparsable: ${err?.message || err}`);
    }
  }
  const failureRaw = fs.existsSync(failurePath) ? fs.readFileSync(failurePath, 'utf8') : '';
  return {
    method: 'node --import tsx <temp harness> (Page-capture + Map wx shim: storage/modal/navigate/request)',
    ai_ts: path.join(AI_DIR, 'ai.ts'),
    exit: res.status,
    stdout_tail: stdout.slice(-8000),
    stderr_tail: stderr.slice(-8000),
    result,
    failure_raw: failureRaw,
  };
}

// ---------------------------------------------------------------------------
// Static invariants (source-level, no runtime claim)
// ---------------------------------------------------------------------------


const FORBIDDEN_STRINGS = [
  'AI 注入',
  'hza_',
  'System Prompt',
  '系统提示词',
  '确诊',
  '诊断结论',
  '处方',
  '疗效保证',
  '急症拦截',
  '自动拨号',
  '预约挂号',
  '挂号成功',
  '候诊叫号',
  '推荐医生',
  '推荐医院',
  '智能分诊',
  'AI 结论',
  '医疗级',
];
const SEVERITY_TOKENS = ['severity', '严重程度', '严重度', '危急程度'];

function staticInvariantChecks() {
  const ts = readPageBundle('ai', 'ts');
  const wxml = readPageBundle('ai', 'wxml');
  const wxss = readPageBundle('ai', 'wxss');
  const json = readPageBundle('ai', 'json');
  const combined = [ts, wxml, wxss, json].join('\n');
  const copy = aiCopyBlock();

  const forbidden = FORBIDDEN_STRINGS.filter((term) => combined.includes(term));
  const copyForbidden = FORBIDDEN_STRINGS.filter((term) => copy.includes(term));
  const severity = SEVERITY_TOKENS.filter((term) => combined.includes(term));

  const usesRecordsApi = /records\.(memory|profile|symptoms|notes|questions)\.(add|update|remove|get|list)\s*\(/.test(ts);
  const usesAiClient = /sendAsk\s*\(/.test(ts) && /sendExtractMemory\s*\(/.test(ts) && /buildAskPayload\s*\(/.test(ts);
  const usesOrganizer = /from '\.\.\/\.\.\/shared\/services\/organizer'/.test(ts) && /\borganize\s*\(/.test(ts);
  const usesStorageModule = /from '\.\.\/\.\.\/shared\/utils\/storage'/.test(ts) && /storage\.(get|set)\s*\(/.test(ts);
  const directStorage = /wx\.(get|set|remove)StorageSync\s*\(/.test(ts);
  const usesA11y = /A11Y_DATA/.test(ts) && /syncA11y\s*\(/.test(ts);
  const noAny = !/as any/.test(ts) && !/@ts-ignore/.test(ts);
  const noTodo = !/TODO|FIXME/.test(combined);
  const hasStatusMachine = /AiStatus/.test(ts) && /setAiStatus\s*\(/.test(ts) && /isLocalFallback\s*\(/.test(ts);
  const hasGuide = /showEnableGuide\s*\(/.test(ts);
  const hasAutoLocal = /autoLocalSend\s*\(/.test(ts) && /onRetryConnection\s*\(/.test(ts);
  const hasDiscard = /nowPrefs\.aiEnabled !== true/.test(ts) && /nowPrefs\.autoMemory !== true/.test(ts);

  const wxmlStatusBar = /class="statusbar/.test(wxml) && /\{\{aiStatusText\}\}/.test(wxml) && /bindtap="onRetryConnection"/.test(wxml);
  const wxmlPreviewNotice = /previewMemoryNotice/.test(wxml);
  const wxmlScaleInline = /--mhp-scale:\s*\{\{scale\}\}/.test(wxml);
  const wxmlHcClass = /is-hc/.test(wxml);
  const copyHasKeys = [
    'statusDisabled',
    'statusIdle',
    'statusOk',
    'statusOffline',
    'statusLocal',
    'statusRetryAction',
    'statusSettingsAction',
    'guideTitle',
    'guideContent',
    'autoLocalHint',
    'memoryDiscardHint',
    'previewMemoryNotice',
  ].every((key) => copy.includes(key));

  let jsonParses = false;
  let jsonTitle = null;
  try {
    const parsed = JSON.parse(json);
    jsonParses = true;
    jsonTitle = parsed.navigationBarTitleText ?? null;
  } catch {
    jsonParses = false;
  }

  const fontLines = wxss.split(/\r?\n/).filter((line) => line.includes('font-size'));
  const fontAllScaled = fontLines.length > 0 && fontLines.every((line) => /calc\([^)]*var\(--mhp-scale\)\)/.test(line));
  const barePx = wxss
    .split(/\r?\n/)
    .filter((line) => /(?<![\dr])\d+px/.test(line))
    .map((line) => line.trim());

  return {
    ai_ts_exists: fs.existsSync(path.join(AI_DIR, 'ai.ts')),
    ai_js_exists: fs.existsSync(path.join(AI_DIR, 'ai.js')),
    texts_has_ai_block: copy.length > 0,
    forbidden_strings_present: forbidden,
    ai_copy_forbidden_present: copyForbidden,
    severity_tokens_present: severity,
    uses_records_api: usesRecordsApi,
    uses_ai_client: usesAiClient,
    uses_organizer: usesOrganizer,
    uses_storage_module: usesStorageModule,
    direct_storage_calls: directStorage,
    uses_a11y: usesA11y,
    no_as_any_or_ts_ignore: noAny,
    no_todo_fixme: noTodo,
    has_status_machine: hasStatusMachine,
    has_guide: hasGuide,
    has_auto_local: hasAutoLocal,
    has_inflight_discard: hasDiscard,
    wxml_status_bar: wxmlStatusBar,
    wxml_preview_notice: wxmlPreviewNotice,
    copy_has_new_keys: copyHasKeys,
    json_parses: jsonParses,
    json_title: jsonTitle,
    font_size_lines: fontLines.length,
    font_size_all_scaled: fontAllScaled,
    bare_px_lines: barePx,
    wxml_scale_inline: wxmlScaleInline,
    wxml_hc_class: wxmlHcClass,
  };
}

// ---------------------------------------------------------------------------
// Layer 2: automator helpers
// ---------------------------------------------------------------------------

const captureScreenshot = makeCaptureScreenshot('ai-consent');

const renderEvidence = makeRenderEvidence(captureScreenshot, AI_ROUTE);

const STORAGE_KEYS = [
  'records_preferences',
  'records_profile',
  'records_symptoms',
  'records_notes',
  'records_questions',
  'records_memory',
  'ai_messages',
  'ai_consult_ack',
];

const clearAiKeys = makeClearAiKeys(STORAGE_KEYS);

const PREF_DISABLED = {
  aiEnabled: false,
  consentVersion: null,
  fontSize: 14,
  highContrast: false,
  autoMemory: true,
  updatedAt: '2026-09-01T00:00:00.000Z',
};
const PREF_ENABLED = {
  aiEnabled: true,
  consentVersion: 1,
  fontSize: 14,
  highContrast: false,
  autoMemory: true,
  updatedAt: '2026-09-01T00:00:00.000Z',
};

const ORGANIZE_FIXTURE = {
  points: ['近一周出现头痛'],
  extracted: { symptoms: ['头痛'], medications: [], allergies: [], history: [], exams: [] },
  unknowns: [],
  questions: [],
};

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  ensureDir(E2E_DIR);
  ensureDir(path.dirname(QA_FAILURE_PATH));
  section('AI CONSENT SPEC');

  const logic = runLogicHarness();
  const logicScenarios = logic.result ? logic.result.scenarios : [];
  const logicFailed = logic.result ? logic.result.summary.failed : -1;

  if (logic.failure_raw !== '') {
    fs.writeFileSync(QA_FAILURE_PATH, logic.failure_raw);
    log(`failure evidence: ${QA_FAILURE_PATH}`);
  }

  const report = {
    command: 'E2E_DEVTOOLS_MINIMIZE=1 node tests/e2e/ai-consent.spec.mjs (cold)',
    timestamp: new Date().toISOString(),
    platform: `${os.platform()} ${os.release()} (${os.arch()})`,
    node_version: process.version,
    project_path: CONFIG.projectPath,
    logic: { method: logic.method, ai_ts: logic.ai_ts, exit: logic.exit, result: logic.result },
    static_invariants: null,
    proxy_probe: null,
    evaluate_probe: null,
    disabled_attempt: null,
    enabled_preview: null,
    offline_send: null,
    auto_local: null,
    retry_online: null,
    render: null,
    persistence: null,
    summary: null,
  };

  let allOk = true;

  if (logic.result !== null && logic.exit === 0 && logicFailed === 0) {
    ok(`logic harness: ${logic.result.summary.passed}/${logic.result.summary.total} scenarios passed (real page methods)`);
  } else {
    fail(`logic harness failed (exit=${logic.exit}, failed_scenarios=${logicFailed}); stderr tail: ${logic.stderr_tail}`);
    allOk = false;
  }
  for (const scenario of logicScenarios) {
    log(`  [logic] ${scenario.pass ? 'PASS' : 'FAIL'} ${scenario.id}: ${scenario.name}`);
    if (!scenario.pass) allOk = false;
  }

  const statics = staticInvariantChecks();
  report.static_invariants = statics;
  const staticsOk =
    statics.ai_ts_exists === true &&
    statics.ai_js_exists === false &&
    statics.texts_has_ai_block === true &&
    statics.forbidden_strings_present.length === 0 &&
    statics.ai_copy_forbidden_present.length === 0 &&
    statics.severity_tokens_present.length === 0 &&
    statics.uses_records_api === true &&
    statics.uses_ai_client === true &&
    statics.uses_organizer === true &&
    statics.uses_storage_module === true &&
    statics.direct_storage_calls === false &&
    statics.uses_a11y === true &&
    statics.no_as_any_or_ts_ignore === true &&
    statics.no_todo_fixme === true &&
    statics.has_status_machine === true &&
    statics.has_guide === true &&
    statics.has_auto_local === true &&
    statics.has_inflight_discard === true &&
    statics.wxml_status_bar === true &&
    statics.wxml_preview_notice === true &&
    statics.copy_has_new_keys === true &&
    statics.json_parses === true &&
    statics.json_title === 'AI 助手' &&
    statics.font_size_all_scaled === true &&
    statics.bare_px_lines.length === 0 &&
    statics.wxml_scale_inline === true &&
    statics.wxml_hc_class === true;
  if (staticsOk) {
    ok('static invariants: records API only; aiClient + organizer + storage module wired; status/guide/auto-local/discard present; scaled px-free wxss; new copy keys clean');
  } else {
    fail(`static invariant failure: ${JSON.stringify(report.static_invariants)}`);
    allOk = false;
  }

  let miniProgram;
  try {
    const proxyUp = await tcpProbe(PROXY_PORT, '127.0.0.1', 500);
    const offlineVia = proxyUp ? 'stubbed-fail (port 8787 occupied; natural offline unavailable)' : 'natural (no proxy on 8787)';
    report.proxy_probe = { port: PROXY_PORT, listening: proxyUp, offline_via: offlineVia };
    if (proxyUp) log(`proxy on ${PROXY_PORT} is UP — the offline scenario uses a fail stub (${offlineVia})`);
    else ok(`proxy port ${PROXY_PORT} is down — the offline scenario is natural`);

    miniProgram = await launchMiniProgram();
    await clearAiKeys(miniProgram);

    await miniProgram.callWxMethod('setStorageSync', 'mhp_records_preferences', PREF_DISABLED);

    await miniProgram.reLaunch('/' + AI_ROUTE + '?mode=organize');
    await delay(800);
    await miniProgram.reLaunch('/' + AI_ROUTE + '?mode=organize');
    await delay(800);

    const probeRaced = await withTimeout(
      miniProgram.evaluate(() => {
        const pages = getCurrentPages();
        const page = pages[pages.length - 1];
        return {
          route: page.route,
          status: page.data.aiStatus,
          statusText: page.data.aiStatusText,
          hasSend: typeof page.onSend === 'function',
          hasConfirm: typeof page.onConfirmSend === 'function',
          hasRetry: typeof page.onRetryConnection === 'function',
        };
      }),
      15000,
      'evaluate-probe'
    );
    if (probeRaced.timedOut === true || probeRaced.error !== undefined) {
      report.evaluate_probe = probeRaced.timedOut ? { ok: false, error: 'timed out' } : { ok: false, error: probeRaced.error };
      fail(`evaluate probe failed: ${JSON.stringify(report.evaluate_probe)}`);
      allOk = false;
    } else {
      const p = probeRaced.value;
      report.evaluate_probe = { ok: true, value: p };
      if (p && p.route === AI_ROUTE && p.hasSend === true && p.hasConfirm === true && p.hasRetry === true && p.status === 'disabled') {
        ok(`evaluate probe: ${JSON.stringify(p)}`);
      } else {
        fail(`evaluate probe unexpected: ${JSON.stringify(p)}`);
        allOk = false;
      }
    }

    // default-off attempt: record the guide modal + confirm status disabled + zero request
    const disabledRaced = await withTimeout(
      miniProgram.evaluate(async () => {
        const pages = getCurrentPages();
        const page = pages[pages.length - 1];
        const originalModal = wx.showModal;
        const modals = [];
        wx.showModal = function (options) {
          modals.push({ title: options && options.title, content: options && options.content });
          if (options && typeof options.success === 'function') options.success({ confirm: false, cancel: true });
        };
        const originalRequest = wx.request;
        let requestCount = 0;
        wx.request = function (options) {
          requestCount += 1;
          return originalRequest.call(wx, options);
        };
        let send = null;
        let confirmed = null;
        let statusAfterSend = null;
        let last = null;
        try {
          page.onInput({ detail: { value: '最近睡不好' } });
          send = await page.onSend();
          statusAfterSend = page.data.aiStatus;
          confirmed = await page.onConfirmSend();
          const msgs = page.data.messages;
          last = msgs[msgs.length - 1];
        } finally {
          wx.showModal = originalModal;
          wx.request = originalRequest;
        }
        return {
          modals: modals,
          send: send,
          statusAfterSend: statusAfterSend,
          confirmed: confirmed,
          lastKind: last ? last.kind : '',
          errorText: last ? last.errorText : '',
          messages: page.data.messages.length,
          requestCount: requestCount,
          statusAfterConfirm: page.data.aiStatus,
        };
      }),
      25000,
      'evaluate-disabled'
    );
    if (disabledRaced.timedOut === true || disabledRaced.error !== undefined) {
      report.disabled_attempt = disabledRaced.timedOut ? { error: 'timed out' } : { error: disabledRaced.error };
      fail(`disabled attempt drive failed: ${JSON.stringify(report.disabled_attempt)}`);
      allOk = false;
    } else {
      const d = disabledRaced.value;
      report.disabled_attempt = d;
      const guide = Array.isArray(d.modals) && d.modals.length > 0 ? d.modals[d.modals.length - 1] : null;
      const okDisabled =
        d.statusAfterSend === 'disabled' && guide !== null && typeof guide.title === 'string' && guide.title !== '' &&
        d.send && d.send.reason === 'preview' && d.confirmed && d.confirmed.ok === false && d.lastKind === 'error' &&
        d.requestCount === 0;
      if (okDisabled) ok(`default-off attempt: guide title=${JSON.stringify(guide.title)}, status disabled, zero request`);
      else {
        fail(`disabled attempt unexpected: ${JSON.stringify(d)}`);
        allOk = false;
      }
    }

    // enable via storage write + reload
    await miniProgram.callWxMethod('setStorageSync', 'mhp_records_preferences', PREF_ENABLED);
    await miniProgram.reLaunch('/' + AI_ROUTE + '?mode=organize');
    await delay(800);
    await miniProgram.reLaunch('/' + AI_ROUTE + '?mode=organize');
    await delay(800);

    // enabled preview: preview opens + auto-extract notice line; then NATURAL offline send -> status offline
    const offlineRaced = await withTimeout(
      miniProgram.evaluate(
        async (args) => {
          const pages = getCurrentPages();
          const page = pages[pages.length - 1];
          const originalRequest = wx.request;
          let requestCount = 0;
          const realRequest = args.offlineVia.indexOf('stubbed') === 0
            ? function (options) {
                setTimeout(function () {
                  if (options.fail) options.fail({ errMsg: 'request:fail stubbed offline' });
                }, 0);
                return { abort: function () {} };
              }
            : originalRequest;
          wx.request = function (options) {
            requestCount += 1;
            return realRequest.call(wx, options);
          };
          let facts = {};
          try {
            page.onInput({ detail: { value: '最近胃不舒服' } });
            const send = await page.onSend();
            facts.preview = {
              reason: send.reason,
              open: page.data.previewOpen,
              notice: page.data.previewMemoryNotice,
              titles: page.data.previewSections.map((s) => s.title),
              requestsBeforeConfirm: requestCount,
            };
            const confirmed = await page.onConfirmSend();
            const msgs = page.data.messages;
            const last = msgs[msgs.length - 1];
            facts.offline = {
              confirmed: confirmed,
              kind: last ? last.kind : '',
              errorText: last ? last.errorText : '',
              blocks: last ? last.blocks.length : -1,
              inputPreserved: page.data.input,
              status: page.data.aiStatus,
              requests: requestCount,
            };
            const beforeLocal = requestCount;
            const localSend = await page.onSend();
            const msgs2 = page.data.messages;
            const last2 = msgs2[msgs2.length - 1];
            facts.local = {
              reason: localSend.reason,
              kind: last2 ? last2.kind : '',
              blockTitles: last2 ? last2.blocks.map((b) => b.title) : [],
              hint: page.data.hint,
              status: page.data.aiStatus,
              requestsDelta: requestCount - beforeLocal,
            };
          } finally {
            wx.request = originalRequest;
          }
          return facts;
        },
        { offlineVia }
      ),
      30000,
      'evaluate-offline'
    );
    if (offlineRaced.timedOut === true || offlineRaced.error !== undefined) {
      report.offline_send = offlineRaced.timedOut ? { error: 'timed out' } : { error: offlineRaced.error };
      report.auto_local = null;
      fail(`offline drive failed: ${JSON.stringify(report.offline_send)}`);
      allOk = false;
    } else {
      const f = offlineRaced.value;
      report.enabled_preview = f.preview;
      report.offline_send = f.offline;
      report.auto_local = f.local;
      const previewOk = f.preview && f.preview.reason === 'preview' && f.preview.open === true && typeof f.preview.notice === 'string' && f.preview.notice !== '' && Array.isArray(f.preview.titles) && f.preview.titles.indexOf('对话') !== -1 && f.preview.requestsBeforeConfirm === 0;
      if (previewOk) ok(`enabled preview: notice=${JSON.stringify(f.preview.notice)}, titles=${JSON.stringify(f.preview.titles)}`);
      else {
        fail(`enabled preview unexpected: ${JSON.stringify(f.preview)}`);
        allOk = false;
      }
      const offlineOk = f.offline && f.offline.confirmed && f.offline.confirmed.ok === false && f.offline.kind === 'error' && f.offline.blocks === 0 && f.offline.status === 'offline' && f.offline.requests >= 1;
      if (offlineOk) ok(`offline send: status=${f.offline.status}, error=${JSON.stringify(f.offline.errorText)}, input preserved=${f.offline.inputPreserved === '最近胃不舒服'}`);
      else {
        fail(`offline send unexpected: ${JSON.stringify(f.offline)}`);
        allOk = false;
      }
      const localOk = f.local && f.local.reason === 'local' && f.local.kind === 'local' && f.local.requestsDelta === 0 && f.local.status === 'local' && Array.isArray(f.local.blockTitles) && f.local.blockTitles.length > 0;
      if (localOk) ok(`auto-local: kind=local, requests_delta=${f.local.requestsDelta}, status=${f.local.status}`);
      else {
        fail(`auto-local unexpected: ${JSON.stringify(f.local)}`);
        allOk = false;
      }
    }

    // retry clears fallback -> stubbed-online send succeeds -> status ok
    const retryRaced = await withTimeout(
      miniProgram.evaluate(
        async (args) => {
          const pages = getCurrentPages();
          const page = pages[pages.length - 1];
          const retried = page.onRetryConnection();
          const statusAfterRetry = page.data.aiStatus;
          const originalRequest = wx.request;
          wx.request = function (options) {
            setTimeout(function () {
              let body = {};
              try { body = JSON.parse(options.data); } catch (e) { body = {}; }
              if (String(options.url).indexOf('/api/extract-memory') !== -1) {
                if (options.success) options.success({ statusCode: 200, data: { candidates: [] } });
                return;
              }
              if (options.success) options.success({ statusCode: 200, data: args.organize });
            }, 0);
            return { abort: function () {} };
          };
          let facts = { retried: retried && retried.retried === true, statusAfterRetry: statusAfterRetry };
          try {
            page.onInput({ detail: { value: '最近还是睡不好' } });
            const send = await page.onSend();
            facts.previewReason = send.reason;
            const confirmed = await page.onConfirmSend();
            const msgs = page.data.messages;
            const last = msgs[msgs.length - 1];
            facts.confirmedOk = confirmed.ok;
            facts.kind = last ? last.kind : '';
            facts.status = page.data.aiStatus;
          } finally {
            wx.request = originalRequest;
          }
          return facts;
        },
        { organize: ORGANIZE_FIXTURE }
      ),
      25000,
      'evaluate-retry'
    );
    if (retryRaced.timedOut === true || retryRaced.error !== undefined) {
      report.retry_online = retryRaced.timedOut ? { error: 'timed out' } : { error: retryRaced.error };
      fail(`retry drive failed: ${JSON.stringify(report.retry_online)}`);
      allOk = false;
    } else {
      const r = retryRaced.value;
      report.retry_online = r;
      const retryOk = r.retried === true && r.statusAfterRetry === 'idle' && r.previewReason === 'preview' && r.confirmedOk === true && r.kind === 'organize' && r.status === 'ok';
      if (retryOk) ok(`retry: status idle -> send -> status ${r.status} (kind ${r.kind})`);
      else {
        fail(`retry drive unexpected: ${JSON.stringify(r)}`);
        allOk = false;
      }
    }

    // render evidence
    {
      const raced = await withTimeout(renderEvidence(miniProgram, 'after-consent'), 15000, 'render');
      if (raced.timedOut === true || raced.error !== undefined) {
        report.render = raced.timedOut ? { error: 'timed out' } : { error: raced.error };
        fail(`render evidence failed: ${JSON.stringify(report.render)}`);
        allOk = false;
      } else {
        const render = raced.value;
        report.render = { ...render, method: 'reLaunch+pageStack+screenshot' };
        if (render.ok) ok(`render evidence: top=${render.topPath}, bytes=${render.screenshotBytes}, md5=${render.screenshotMd5}`);
        else {
          fail(`render check failed: ${JSON.stringify(render)}`);
          allOk = false;
        }
      }
    }

    // close + relaunch persistence of messages
    try {
      await withTimeout(miniProgram.close(), 8000, 'close');
      miniProgram = null;
    } catch (err) {
      log(`warning: close failed: ${err?.message || err}`);
    }
    await delay(2000);
    miniProgram = await launchMiniProgram();
    {
      const raced = await withTimeout(miniProgram.callWxMethod('getStorageSync', 'mhp_ai_messages'), 10000, 'readback-after');
      if (raced.timedOut === true || raced.error !== undefined) {
        report.persistence = raced.timedOut ? { error: 'timed out' } : { error: raced.error };
        fail('relaunch persistence read-back failed');
        allOk = false;
      } else {
        const stored = raced.value;
        const count = Array.isArray(stored) ? stored.length : -1;
        report.persistence = { key: 'mhp_ai_messages', count: count, persisted_after_relaunch: Array.isArray(stored) && stored.length >= 2 };
        if (report.persistence.persisted_after_relaunch) ok(`messages persist across close+relaunch (${count})`);
        else {
          fail(`messages did not persist: ${JSON.stringify(report.persistence)}`);
          allOk = false;
        }
      }
    }

    await withTimeout(clearAiKeys(miniProgram), 10000, 'clear-keys');
  } catch (err) {
    fail(`ai-consent spec run error: ${err?.stack || err}`);
    report.error = err?.message || String(err);
    allOk = false;
  } finally {
    if (miniProgram) {
      const raced = await withTimeout(miniProgram.close(), 8000, 'close');
      if (raced.timedOut === true) log('warning: miniProgram.close() timed out');
      else if (raced.error !== undefined) log(`warning: miniProgram.close() failed: ${raced.error}`);
      else log('miniProgram.close() done');
      try {
        miniProgram.disconnect();
      } catch {
        /* socket already closed */
      }
    }
  }

  const checks = {
    logic_harness_ok: logic.result !== null && logic.exit === 0 && logicFailed === 0,
    static_invariants_ok: staticsOk,
    evaluate_probe_ok: Boolean(report.evaluate_probe && report.evaluate_probe.ok === true && report.evaluate_probe.value && report.evaluate_probe.value.route === AI_ROUTE),
    disabled_attempt_ok: Boolean(report.disabled_attempt && report.disabled_attempt.statusAfterSend === 'disabled' && report.disabled_attempt.confirmed && report.disabled_attempt.confirmed.ok === false && report.disabled_attempt.requestCount === 0 && Array.isArray(report.disabled_attempt.modals) && report.disabled_attempt.modals.length > 0),
    enabled_preview_ok: Boolean(report.enabled_preview && report.enabled_preview.open === true && typeof report.enabled_preview.notice === 'string' && report.enabled_preview.notice !== '' && report.enabled_preview.requestsBeforeConfirm === 0),
    offline_send_ok: Boolean(report.offline_send && report.offline_send.confirmed && report.offline_send.confirmed.ok === false && report.offline_send.kind === 'error' && report.offline_send.status === 'offline'),
    auto_local_ok: Boolean(report.auto_local && report.auto_local.kind === 'local' && report.auto_local.requestsDelta === 0 && report.auto_local.status === 'local'),
    retry_online_ok: Boolean(report.retry_online && report.retry_online.retried === true && report.retry_online.statusAfterRetry === 'idle' && report.retry_online.confirmedOk === true && report.retry_online.status === 'ok'),
    render_ok: Boolean(report.render && report.render.ok === true),
    persistence_ok: Boolean(report.persistence && report.persistence.persisted_after_relaunch === true),
    no_forbidden_strings: statics.forbidden_strings_present.length === 0 && statics.ai_copy_forbidden_present.length === 0,
    no_severity_token: statics.severity_tokens_present.length === 0,
    no_any_or_todo: statics.no_as_any_or_ts_ignore === true && statics.no_todo_fixme === true,
    font_scaled: statics.font_size_all_scaled === true && statics.bare_px_lines.length === 0,
    json_ok: statics.json_parses === true && statics.json_title === 'AI 助手',
  };
  const checksPassed = Object.values(checks).every((v) => v === true);
  log(`summary checks: ${JSON.stringify(checks)}`);

  report.summary = {
    ...checks,
    logic_scenarios_total: logic.result ? logic.result.summary.total : 0,
    logic_scenarios_passed: logic.result ? logic.result.summary.passed : 0,
    passed: checksPassed && allOk === true,
    failed: !(checksPassed && allOk === true),
  };

  const reportPath = path.join(E2E_DIR, 'ai-consent.json');
  fs.writeFileSync(reportPath, JSON.stringify(report, null, 2) + '\n');
  log(`ai-consent evidence: ${reportPath}`);

  return report.summary.passed;
}

main().then(
  (passed) => {
    process.exit(passed ? 0 : 1);
  },
  (err) => {
    console.error(`[e2e] FAIL ${err?.stack || err}`);
    process.exit(1);
  }
);
