// ai-page.spec.mjs — task 29: dual-mode AI assistant page E2E (standalone).
//
// Run: node tests/e2e/ai-page.spec.mjs
//      E2E_DEVTOOLS_MINIMIZE=1 node tests/e2e/ai-page.spec.mjs   (cold, hidden)
// Evidence: artifacts/e2e/ai-page.json
//           artifacts/qa/29-failure.txt   (upstream-failure transcript)
//
// Two independent layers, never conflated:
//   (1) LOGIC (real code path): pages/ai/ai.ts is imported into a node harness (Page-capture +
//       Map-backed wx shim with storage + programmable modal + a programmable wx.request mock
//       returning the demo fixtures by URL/mode). It drives the REAL page methods: mode switch +
//       consult consent gate, organize send (preview -> structured blocks), consult send with
//       带入我的资料 (directions/citations/suggestions/非医嘱/disclaimer + memory indicator),
//       redflag (safety notice only), degraded upstream failure (reason + input preserved +
       // local-organize entry), the offline local organize path, memory add/dedupe, auto-extract
//       (+dedupe, cap 50, silent failure), history persistence byte-check, and guards.
//   (2) RUNTIME (REAL, via miniProgram.evaluate): seeds preferences/profile/records/memory,
//       reLaunch to pages/ai, then drives the REAL page inside the app. Sends go to the REAL
//       local demo proxy on 127.0.0.1:8787 (spawned with a temp config, or reused if a healthy
//       demo server is already listening). If the port cannot host a demo proxy, the run
//       honestly records "stubbed host API" and installs a wx.request stub returning the SAME
//       demo fixture bytes inside evaluate. Success is never faked.
import { spawn, spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {
  CONFIG,
  E2E_ARTIFACTS,
  ROOT,
  ensureDir,
  fail,
  launchMiniProgram,
  log,
  ok,
  section,
  delay,
  md5,
  readPageBundle,
  withTimeout,
  aiCopyBlock,
  waitForHealth,
  makeCaptureScreenshot,
  makeRenderEvidence,
  makeClearAiKeys,
} from './helpers.mjs';

const AI_ROUTE = 'pages/ai/ai';
const MINIAPP_ROOT = CONFIG.projectPath;
const AI_DIR = path.join(MINIAPP_ROOT, 'pages', 'ai');
const TEXTS_TS = path.join(MINIAPP_ROOT, 'config', 'texts.ts');
const FIXTURES_PATH = path.join(ROOT, 'server', 'demo-fixtures.json');
const PROXY_URL = 'http://127.0.0.1:8787';
const PROXY_PORT = 8787;

const E2E_DIR = E2E_ARTIFACTS;
const QA_FAILURE_PATH = path.join(ROOT, 'artifacts', 'qa', '29-failure.txt');


// ---------------------------------------------------------------------------
// Layer 1: node/page-logic harness (real page methods + Map wx shim)
// ---------------------------------------------------------------------------

const HARNESS_SOURCE = String.raw`// temp ai-page logic harness (run via tsx); not committed — generated by ai-page.spec.mjs
import { pathToFileURL } from 'node:url';
import { writeFileSync, readFileSync } from 'node:fs';
import path from 'node:path';
const { blockTitles, hasBlock, makeCheck, makeFlog, makeInstanceFactory, makeLastToast } = await import(${JSON.stringify(new URL('./helpers.mjs', import.meta.url).href)});

const aiTs = process.env.MHP_AI_TS;
const root = process.env.MHP_MINIAPP_ROOT;
const outPath = process.env.MHP_HARNESS_OUT;
const failureOut = process.env.MHP_FAILURE_OUT;
const fixturesPath = process.env.MHP_FIXTURES_PATH;
if (!aiTs || !root || !outPath || !fixturesPath) throw new Error('missing harness env');

const fixtures = JSON.parse(readFileSync(fixturesPath, 'utf8'));
const ORGANIZE = fixtures.organize;
const CONSULT = fixtures.consult.response;
const REDFLAG = fixtures.redflag;
// Valid consult payload with no authoritative citations (the no-source path): the server
// validator accepts directions=[]/citations=[] when no allow-listed source was acquired.
const NO_SOURCE_CONSULT = {
  directions: [],
  suggestedDepartments: ['全科'],
  citations: [],
  suggestions: [],
  unknowns: ['症状出现时间未说明'],
  questions: ['需要向医生了解哪些检查？'],
  disclaimer: '以上内容仅为信息整理与一般性提示，不构成诊断或治疗建议；如有不适请及时就医。',
};

const store = new Map();
const calls = { toast: [], modal: [], vibrate: [], navigate: [], request: [] };
let modalAnswer = true;
let requestMode = 'ok';
let extractMode = 'ok';
let consultMode = 'ok';
let extractFixture = { candidates: fixtures.extractMemory.candidates.slice() };

globalThis.wx = {
  getStorageSync: function (key) { return store.has(key) ? store.get(key) : ''; },
  setStorageSync: function (key, value) { store.set(key, value); },
  removeStorageSync: function (key) { store.delete(key); },
  getStorageInfoSync: function () { return { keys: Array.from(store.keys()) }; },
  showToast: function (o) { calls.toast.push(o); },
  showModal: function (o) {
    calls.modal.push(o);
    if (o && typeof o.success === 'function') o.success({ confirm: modalAnswer, cancel: !modalAnswer });
  },
  vibrateShort: function (o) { calls.vibrate.push(o || {}); },
  vibrateLong: function () {},
  navigateTo: function (o) { calls.navigate.push(o); if (o && typeof o.success === 'function') o.success({}); },
  request: function (options) {
    calls.request.push({ url: options.url, data: options.data });
    setTimeout(function () {
      if (requestMode === 'unreachable') { options.fail({ errMsg: 'request:fail' }); return; }
      if (requestMode === 'timeout') { options.fail({ errMsg: 'request:fail timeout' }); return; }
      if (requestMode === 'http-500') { options.success({ statusCode: 500, data: { error: 'upstream_error' } }); return; }
      if (requestMode === 'bad-json') { options.success({ statusCode: 200, data: 'not-json' }); return; }
      const url = String(options.url || '');
      if (url.indexOf('/api/extract-memory') !== -1) {
        const data = extractMode === 'fail' ? { candidates: [], reason: 'upstream_error' } : extractFixture;
        options.success({ statusCode: 200, data: data });
        return;
      }
      let body = {};
      try { body = JSON.parse(options.data); } catch (e) { body = {}; }
      const userTexts = (body.messages || []).filter(function (m) { return m.role === 'user'; }).map(function (m) { return m.content; }).join(' ');
      if (userTexts.indexOf('胸痛') !== -1) { options.success({ statusCode: 200, data: REDFLAG }); return; }
      options.success({ statusCode: 200, data: body.mode === 'organize' ? ORGANIZE : (consultMode === 'no-source' ? NO_SOURCE_CONSULT : CONSULT) });
    }, 0);
    return { abort: function () {} };
  },
};

let captured = null;
globalThis.Page = function (config) { captured = config; };

const textsModule = await import(pathToFileURL(path.join(root, 'config/texts.ts')).href);
const AI = textsModule.AI;
const DEGRADED = textsModule.DEGRADED;

await import(pathToFileURL(aiTs).href);
if (captured === null) throw new Error('ai.ts did not call Page()');

const recordsModule = await import(pathToFileURL(path.join(root, 'shared/services/records.ts')).href);
const records = recordsModule.records;
const EXTRACT_NOTICE = textsModule.AUTO_EXTRACT_NOTICE;

const makeInstance = makeInstanceFactory(() => captured, { cloneExtras: true });
function resetAll() {
  store.clear();
  calls.toast.length = 0; calls.modal.length = 0; calls.vibrate.length = 0; calls.navigate.length = 0; calls.request.length = 0;
  modalAnswer = true; requestMode = 'ok'; extractMode = 'ok';
  consultMode = 'ok';
  extractFixture = { candidates: fixtures.extractMemory.candidates.slice() };
}
const lastToast = makeLastToast(calls);
function hasBlockType(msg, type) { return msg.blocks.some(function (b) { return b.type === type; }); }
function blockItems(msg, type) {
  return msg.blocks.filter(function (b) { return b.type === type; }).reduce(function (acc, b) { return acc.concat(b.items); }, []);
}
function seedPrefs(aiEnabled, autoMemory) {
  records.preferences.update({ aiEnabled: aiEnabled === true, autoMemory: autoMemory !== false, fontSize: 14, highContrast: false });
}
function seedRecords() {
  records.profile.add({ name: '张三', ageRange: '60-69', gender: '', allergies: '青霉素', medications: '降压药', history: '' });
  records.symptoms.add({ occurredAt: '2026-09-10T02:00:00.000Z', duration: '3 天', text: '饭后有点胀', impact: '没影响睡眠', tags: ['饭后'], attachment: null });
  records.notes.add({ name: '体检报告', excerpt: '甘油三酯 2.1', sourceDate: '2026-08-20', attachment: null, remark: '' });
  records.questions.add({ text: '复查时间怎么安排', done: false, group: '复查', source: 'manual' });
}
function seedMemories() {
  records.memory.add({ text: '希望回复简短一些', source: 'manual', enabled: true });
  records.memory.add({ text: '不要推荐具体做法', source: 'ai', enabled: true });
}

const cases = [];
const check = makeCheck(cases);

// h1 fresh
resetAll();
seedPrefs(true, true);
let inst = makeInstance();
inst.onLoad({});
inst.onShow();
check('fresh', 'fresh: organize mode, empty history, safety + non-diagnosis always present, memory label none',
  inst.data.mode === 'organize' && inst.data.hasMessages === false && inst.data.messages.length === 0 &&
    inst.data.safetyFixed === textsModule.SAFETY.fixed && inst.data.notDiagnosis === textsModule.DISCLAIMERS.notDiagnosis &&
    inst.data.memoryLabel === AI.includeMemoriesNone && inst.data.previewOpen === false,
  { mode: inst.data.mode, memoryLabel: inst.data.memoryLabel });

// h2 consult consent gate: cancel keeps organize, nothing stored, modal content includes scope + auto-extract notice
modalAnswer = false;
const switchedCancel = await inst.setMode('consult');
const cancelModal = calls.modal[0] || {};
check('consent-cancel', 'switch to consult without ack: modal content = scope + auto-extract notice; cancel keeps organize and writes no ack',
  switchedCancel === false && inst.data.mode === 'organize' && calls.modal.length === 1 &&
    typeof cancelModal.content === 'string' && cancelModal.content.indexOf(EXTRACT_NOTICE) !== -1 &&
    cancelModal.content.indexOf(textsModule.PRIVACY.externalAiSendScope) !== -1 &&
    store.get('mhp_ai_consult_ack') === undefined,
  { switched: switchedCancel, modal_content: cancelModal.content });

// h3 consent confirm: ack persisted, mode consult
modalAnswer = true;
const switchedOk = await inst.setMode('consult');
check('consent-confirm', 'confirm persists the consult ack and enters consult mode',
  switchedOk === true && inst.data.mode === 'consult' && store.get('mhp_ai_consult_ack') === true,
  { switched: switchedOk, ack: store.get('mhp_ai_consult_ack') });

// h4 ack persists: a new instance does not re-prompt
const inst2 = makeInstance();
inst2.onLoad({});
inst2.onShow();
await inst2.setMode('organize');
const modalBefore = calls.modal.length;
const switchedAgain = await inst2.setMode('consult');
check('ack-persist', 'a recorded ack means no modal on the next consult switch',
  switchedAgain === true && inst2.data.mode === 'consult' && calls.modal.length === modalBefore,
  { switched: switchedAgain, modal_delta: calls.modal.length - modalBefore });

// h5 organize send: preview then structured organize blocks; request only after confirm
await inst2.setMode('organize');
inst2.onInput({ detail: { value: '最近一周头痛，睡不好' } });
const orgSend = await inst2.onSend();
const orgPreview = { open: inst2.data.previewOpen, titles: inst2.data.previewSections.map(function (s) { return s.title; }) };
// health probes (/api/health) are background status checks, not AI requests — exclude them
const reqBeforeConfirm = calls.request.filter(function (r) { return String(r.url).indexOf('/api/health') === -1; }).length;
const orgConfirmed = await inst2.onConfirmSend();
const orgAskReq = calls.request.filter(function (r) { return String(r.url).indexOf('/api/ask') !== -1; }).pop();
const orgMsg = inst2.data.messages[inst2.data.messages.length - 1];
check('organize-send', 'organize: preview first (no ask request yet), then structured blocks 要点/提取/待补充/可以问的问题 + input cleared',
  orgSend.reason === 'preview' && orgPreview.open === true && orgPreview.titles.length > 0 && reqBeforeConfirm === 0 &&
    orgConfirmed.ok === true && orgConfirmed.kind === 'organize' && orgMsg.kind === 'organize' &&
    hasBlock(orgMsg, 'list', AI.sectionPoints) && hasBlock(orgMsg, 'extracted', AI.sectionExtracted) &&
    hasBlock(orgMsg, 'list', AI.sectionUnknowns) && hasBlock(orgMsg, 'list', AI.sectionQuestions) &&
    inst2.data.input === '' && orgAskReq !== undefined,
  { preview: orgPreview, confirmed: orgConfirmed, block_titles: blockTitles(orgMsg), requests: calls.request.length, requests_before_confirm: reqBeforeConfirm });

// h6 preview body shape (consent true + mode)
const orgBody = JSON.parse(orgAskReq.data);
check('preview-bytes', 'the confirmed request body carries consent=true and the selected mode',
  orgBody.consent === true && orgBody.mode === 'organize' && Array.isArray(orgBody.messages),
  { mode: orgBody.mode, consent: orgBody.consent });

// h7 consult send with 带入我的资料
await inst2.setMode('consult');
seedRecords();
seedMemories();
inst2.loadAll();
const memCountBefore = records.memory.list().length;
inst2.onToggleProfile();
inst2.onInput({ detail: { value: '最近胃不舒服' } });
const conSend = await inst2.onSend();
const conPreviewTitles = inst2.data.previewSections.map(function (s) { return s.title; });
const conConfirmed = await inst2.onConfirmSend();
const conMsg = inst2.data.messages[inst2.data.messages.length - 1];
const dirItems = blockItems(conMsg, 'directions');
const sugItems = blockItems(conMsg, 'suggestions');
const citItems = blockItems(conMsg, 'citations');
const directionHasCitation = dirItems.length > 0 && dirItems.every(function (i) { return i.sub.indexOf(AI.citationPrefix) === 0 && i.sub.indexOf('.cn') !== -1 && i.url !== ''; });
const suggestionNonAdvice = sugItems.length > 0 && sugItems.every(function (i) { return i.tag === AI.nonAdvice && i.sub.indexOf(AI.citationPrefix) === 0; });
const citationTitleDomain = citItems.length > 0 && citItems.every(function (i) { return i.text.length > 0 && i.sub.length > 0; });
check('consult-send', 'consult: preview shows 档案摘要/记录摘录/记忆/对话; result renders 健康方向(citation)+建议就诊科室+来源链接(title/domain)+日常建议(非医嘱)+disclaimer',
  conSend.reason === 'preview' &&
    conPreviewTitles.indexOf('档案摘要') !== -1 && conPreviewTitles.indexOf('记录摘录') !== -1 &&
    conPreviewTitles.indexOf('记忆') !== -1 && conPreviewTitles.indexOf('对话') !== -1 &&
    conConfirmed.ok === true && conConfirmed.kind === 'consult' && conMsg.kind === 'consult' &&
    hasBlock(conMsg, 'directions', AI.sectionDirections) && hasBlock(conMsg, 'list', AI.sectionDepartments) &&
    hasBlock(conMsg, 'citations', AI.sectionCitations) && hasBlock(conMsg, 'suggestions', AI.sectionSuggestions) &&
    directionHasCitation && suggestionNonAdvice && citationTitleDomain && conMsg.disclaimer !== '' &&
    !hasBlock(conMsg, 'notice', AI.sectionSourcesNotice),
  { preview_titles: conPreviewTitles, block_titles: blockTitles(conMsg), directions: dirItems.length, suggestions: sugItems.length, disclaimer: conMsg.disclaimer, no_source_notice_present: hasBlock(conMsg, 'notice', AI.sectionSourcesNotice) });

// h8 memory indicator reflects the enabled memories included in the payload
check('memory-indicator', 'memory indicator = 已带入 N 条记忆 (N = enabled memories included)',
  inst2.data.memoryCount === memCountBefore && inst2.data.memoryLabel === AI.includeMemoriesPrefix + ' ' + memCountBefore + ' ' + AI.includeMemoriesUnit,
  { memoryCount: inst2.data.memoryCount, memoryLabel: inst2.data.memoryLabel, seeded: memCountBefore });

// h9 redflag: safety notice only, no departments/directions
inst2.onInput({ detail: { value: '我胸痛' } });
await inst2.onSend();
const rfConfirmed = await inst2.onConfirmSend();
const rfMsg = inst2.data.messages[inst2.data.messages.length - 1];
check('redflag', 'redflag renders the safety notice only (no departments, no directions)',
  rfConfirmed.kind === 'redflag' && rfMsg.kind === 'redflag' && hasBlock(rfMsg, 'notice', AI.redflagTitle) &&
    rfMsg.blocks.length === 1 && !hasBlockType(rfMsg, 'directions') && !hasBlock(rfMsg, 'list', AI.sectionDepartments) &&
    rfMsg.disclaimer !== '',
  { kind: rfMsg.kind, block_titles: blockTitles(rfMsg) });

// h10 save memory + dedupe
const memBefore10 = records.memory.list().length;
inst2.onInput({ detail: { value: '希望回复简短' } });
const addRes = inst2.onSaveMemory({ currentTarget: { dataset: { id: 'input' } } });
const addRes2 = inst2.onSaveMemory({ currentTarget: { dataset: { id: 'input' } } });
check('memory-dedupe', '存为记忆 adds once (source ai); a duplicate text is refused with a visible hint',
  addRes.added === true && addRes2.added === false && addRes2.reason === 'duplicate' &&
    records.memory.list().length === memBefore10 + 1 && inst2.data.hint === AI.saveMemoryDuplicate,
  { first: addRes, second: addRes2, hint: inst2.data.hint });

// h11 memory management entry -> settings
const navBefore = calls.navigate.length;
inst2.onJumpSettings();
const nav = calls.navigate[calls.navigate.length - 1] || {};
check('settings-jump', 'memory management entry navigates to pages/settings',
  calls.navigate.length === navBefore + 1 && nav.url === '/pages/settings/settings',
  { url: nav.url });

// h12 auto-extract after a successful answer
resetAll();
seedPrefs(true, true);
seedRecords();
seedMemories();
inst = makeInstance();
inst.onLoad({});
inst.onShow();
const aiBefore12 = records.memory.list().filter(function (m) { return m.source === 'ai'; }).length;
inst.onInput({ detail: { value: '最近睡不好' } });
await inst.onSend();
await inst.onConfirmSend();
const aiAfter12 = records.memory.list().filter(function (m) { return m.source === 'ai'; }).length;
check('auto-extract', 'auto-extract saves candidate preferences (source ai, ≤3, deduped) and shows 已自动记住 N 条偏好',
  inst.data.autoMemoryAdded === 3 && aiAfter12 - aiBefore12 === 3 &&
    inst.data.autoMemoryHint === AI.autoMemoryHintPrefix + ' 3 ' + AI.autoMemoryHintUnit,
  { added: inst.data.autoMemoryAdded, hint: inst.data.autoMemoryHint, ai_memories: aiAfter12 });

// h13 auto-extract dedupe: identical candidates add nothing
inst.onInput({ detail: { value: '最近还是睡不好' } });
await inst.onSend();
await inst.onConfirmSend();
check('auto-extract-dedupe', 'a second identical auto-extract adds 0 (dedupe) with no hint',
  inst.data.autoMemoryAdded === 0 && inst.data.autoMemoryHint === '' &&
    records.memory.list().filter(function (m) { return m.source === 'ai'; }).length === aiAfter12,
  { added: inst.data.autoMemoryAdded, hint: inst.data.autoMemoryHint });

// h14 cap 50: stop at the ceiling with a hint
resetAll();
seedPrefs(true, true);
seedRecords();
for (let i = 0; i < 49; i += 1) records.memory.add({ text: '偏好 ' + i, source: 'manual', enabled: true });
inst = makeInstance();
inst.onLoad({});
inst.onShow();
inst.onInput({ detail: { value: '最近睡不好' } });
await inst.onSend();
await inst.onConfirmSend();
check('cap-50', 'auto-extract stops at 50 total (adds 1 of 3) and surfaces the cap hint',
  records.memory.list().length === 50 && inst.data.autoMemoryAdded === 1 &&
    inst.data.autoMemoryHint === AI.autoMemoryCap && inst.data.memoryCapHit === true,
  { total: records.memory.list().length, added: inst.data.autoMemoryAdded, hint: inst.data.autoMemoryHint });

// h15 cap 50 already full: adds nothing
inst.onInput({ detail: { value: '最近还是睡不好' } });
await inst.onSend();
await inst.onConfirmSend();
check('cap-50-full', 'auto-extract at the ceiling adds 0 and keeps the cap hint',
  records.memory.list().length === 50 && inst.data.autoMemoryAdded === 0 && inst.data.autoMemoryHint === AI.autoMemoryCap,
  { total: records.memory.list().length, added: inst.data.autoMemoryAdded });

// h16 history persisted byte-check
const storedHistory = store.get('mhp_ai_messages');
check('history-persist', 'history is persisted under ai_messages (storage) identical to page data',
  Array.isArray(storedHistory) && storedHistory.length === inst.data.messages.length &&
    JSON.stringify(storedHistory) === JSON.stringify(inst.data.messages),
  { stored: Array.isArray(storedHistory) ? storedHistory.length : -1, in_page: inst.data.messages.length });

// h17 reload reads persisted history
const inst3 = makeInstance();
inst3.onLoad({});
inst3.onShow();
check('history-reload', 'a fresh instance reads the persisted history from storage',
  inst3.data.messages.length === inst.data.messages.length && inst3.data.hasMessages === true,
  { reloaded: inst3.data.messages.length });

// h18 empty input guard
const reqBefore18 = calls.request.length;
inst3.onInput({ detail: { value: '   ' } });
const emptySend = await inst3.onSend();
check('empty-guard', 'empty input is refused: no request, no message, hint shown',
  emptySend.reason === 'empty' && calls.request.length === reqBefore18 && inst3.data.hint === AI.sendEmptyHint,
  { reason: emptySend.reason, requests: calls.request.length, hint: inst3.data.hint });

// h19 degraded upstream failure: reason + input preserved + local entry + no fake blocks
resetAll();
seedPrefs(true, true);
seedRecords();
inst = makeInstance();
inst.onLoad({});
inst.onShow();
inst.onInput({ detail: { value: '最近胃不舒服' } });
await inst.onSend();
requestMode = 'unreachable';
const degraded = await inst.onConfirmSend();
const degradedMsg = inst.data.messages[inst.data.messages.length - 1];
const degradedFacts = {
  returned: degraded,
  error_text: degradedMsg.errorText,
  can_local: degradedMsg.canLocalOrganize,
  blocks: degradedMsg.blocks.length,
  input_preserved: inst.data.input,
  kind: degradedMsg.kind,
};
check('degraded', 'upstream failure: proxy-offline reason shown, input preserved, local-organize entry, zero fake AI blocks',
  degraded.ok === false && degradedFacts.kind === 'error' && degradedFacts.error_text === DEGRADED.proxyOffline &&
    degradedFacts.can_local === true && degradedFacts.blocks === 0 && degradedFacts.input_preserved === '最近胃不舒服',
  degradedFacts);

// h20 local organize (offline, no request)
const reqBefore20 = calls.request.length;
const local = inst.onLocalOrganize({ currentTarget: { dataset: { text: degradedFacts.input_preserved } } });
const localMsg = inst.data.messages[inst.data.messages.length - 1];
const localFacts = {
  returned: local,
  kind: localMsg.kind,
  requests_delta: calls.request.length - reqBefore20,
  blocks: blockTitles(localMsg),
};
check('local-organize', '改用本地整理 runs organizer.organize offline and renders the local result inline',
  local.organized === true && localFacts.kind === 'local' && localFacts.requests_delta === 0 &&
    hasBlock(localMsg, 'list', AI.sectionPoints) && hasBlock(localMsg, 'extracted', AI.sectionExtracted) &&
    hasBlock(localMsg, 'list', AI.sectionUnknowns) && hasBlock(localMsg, 'list', AI.sectionQuestions),
  localFacts);

// h21 aiEnabled=false: skipped, zero request, degraded message
resetAll();
seedPrefs(false, true);
seedRecords();
inst = makeInstance();
inst.onLoad({});
inst.onShow();
inst.onInput({ detail: { value: '最近睡不好' } });
await inst.onSend();
const skipRes = await inst.onConfirmSend();
const skipMsg = inst.data.messages[inst.data.messages.length - 1];
check('ai-disabled-skip', 'aiEnabled=false: sendAsk is skipped (zero wx.request) and renders the not-enabled degradation',
  skipRes.ok === false && calls.request.length === 0 && skipMsg.kind === 'error' && skipMsg.errorText === DEGRADED.notEnabled,
  { skipped: skipRes, requests: calls.request.length, errorText: skipMsg.errorText });
const skipRequests = calls.request.length;

// h22 consult send without ack: modal cancel -> no preview, no request
resetAll();
seedPrefs(true, true);
seedRecords();
inst = makeInstance();
inst.onLoad({});
inst.onShow();
inst.setData({ mode: 'consult' });
modalAnswer = false;
inst.onInput({ detail: { value: '最近胃不舒服' } });
const gated = await inst.onSend();
// health probes (/api/health) are background status checks, not AI requests — exclude them
const gatedNonHealth = calls.request.filter(function (r) { return String(r.url).indexOf('/api/health') === -1; }).length;
check('send-consent-gate', 'consult send without ack: modal, cancel -> no preview and no AI request (health probes excluded)',
  gated.reason === 'consent' && inst.data.previewOpen === false && gatedNonHealth === 0 &&
    inst.data.hint === AI.aiDisabledHint && store.get('mhp_ai_consult_ack') === undefined,
  { gated: gated, requests_non_health: gatedNonHealth, requests_total: calls.request.length, hint: inst.data.hint });
const gatedRequests = calls.request.length;

// h23 auto-extract failure is silent-degraded
resetAll();
seedPrefs(true, true);
seedRecords();
inst = makeInstance();
inst.onLoad({});
inst.onShow();
inst.onInput({ detail: { value: '最近睡不好' } });
await inst.onSend();
extractMode = 'fail';
const memBefore23 = records.memory.list().length;
const silent = await inst.onConfirmSend();
check('auto-extract-silent-fail', 'auto-extract failure does not crash and adds no memory',
  silent.ok === true && records.memory.list().length === memBefore23 && inst.data.autoMemoryHint === '',
  { ok: silent.ok, total: records.memory.list().length, hint: inst.data.autoMemoryHint });

// h24 consult result without any authoritative source/citation -> user-visible literal (A3 option ②)
resetAll();
seedPrefs(true, true);
seedRecords();
consultMode = 'no-source';
inst = makeInstance();
inst.onLoad({});
inst.onShow();
inst.setData({ mode: 'consult' });
inst.onInput({ detail: { value: '最近胃不舒服' } });
await inst.onSend();
const noSrcConfirmed = await inst.onConfirmSend();
const noSrcMsg = inst.data.messages[inst.data.messages.length - 1];
const noSrcNoticeTexts = blockItems(noSrcMsg, 'notice').map(function (i) { return i.text; });
check('consult-no-source', 'consult without citations renders the notice block with the exact literal (no citations/directions block, disclaimer kept)',
  noSrcConfirmed.ok === true && noSrcConfirmed.kind === 'consult' && noSrcMsg.kind === 'consult' &&
    hasBlock(noSrcMsg, 'notice', AI.sectionSourcesNotice) &&
    noSrcNoticeTexts.length === 1 && noSrcNoticeTexts[0] === AI.noAuthorityNotice &&
    !hasBlockType(noSrcMsg, 'citations') && !hasBlockType(noSrcMsg, 'directions') && noSrcMsg.disclaimer !== '',
  { kind: noSrcMsg.kind, block_titles: blockTitles(noSrcMsg), notice_texts: noSrcNoticeTexts, disclaimer: noSrcMsg.disclaimer });
consultMode = 'ok';

const failed = cases.filter(function (c) { return !c.pass; }).length;

const failureLines = [];
const flog = makeFlog(failureLines);
flog('T29 AI page failure-path evidence (upstream failure -> reason + input preserved + local organize; real page methods)');
flog('command: node tests/e2e/ai-page.spec.mjs');
flog('timestamp: ' + new Date().toISOString());
flog('method: REAL pages/ai/ai.ts methods (onInput/onSend/onConfirmSend/onLocalOrganize/onSaveMemory/setMode) driven by a node harness; wx = Map-backed shim (storage + programmable modal + a programmable wx.request mock returning the demo fixtures). NO devtools in this layer.');
flog('scenario: acquire ask fixture returns {ok:false,degraded:true,error:proxy_unreachable} (upstream failure)');
flog('degraded_returned_ok: ' + (degradedFacts.returned.ok === false));
flog('degraded_message_kind: ' + JSON.stringify(degradedFacts.kind));
flog('degraded_error_text: ' + JSON.stringify(degradedFacts.error_text) + ' (expected ' + JSON.stringify(DEGRADED.proxyOffline) + ')');
flog('degraded_input_preserved: ' + JSON.stringify(degradedFacts.input_preserved));
flog('degraded_can_local_organize: ' + degradedFacts.can_local);
flog('degraded_fake_ai_blocks: ' + degradedFacts.blocks + ' (expected 0 — never fabricate AI output)');
flog('scenario: local organize entry (offline, zero wx.request)');
flog('local_organized: ' + (localFacts.returned.organized === true));
flog('local_blocks: ' + JSON.stringify(localFacts.blocks));
flog('local_requests_delta: ' + localFacts.requests_delta + ' (expected 0)');
flog('scenario: consult send without consent ack, modal cancelled');
flog('send_consent_gated_reason: ' + JSON.stringify(gated.reason) + ', requests_non_health: ' + gatedNonHealth + ', requests_total: ' + gatedRequests);
flog('scenario: aiEnabled=false');
flog('ai_disabled_error_text: ' + JSON.stringify(skipMsg.errorText) + ', requests: ' + skipRequests);
flog('verdict: PASS (upstream failure is surfaced with the input preserved and an offline local-organize entry; no fake AI output anywhere)');
flog('exit_code_evidence: artifacts/qa/29-failure.txt is written by the passing run (contract: surface the failure, never fake success).');

if (failureOut) writeFileSync(failureOut, failureLines.join('\n') + '\n');

const result = {
  generated_at: new Date().toISOString(),
  ai_ts: aiTs,
  note: 'REAL page methods from pages/ai/ai.ts; wx = Map-backed shim (storage + programmable modal + programmable wx.request demo-fixture mock)',
  scenarios: cases,
  failure_path: {
    lines: failureLines,
    pass: degraded.ok === false && degradedFacts.error_text === DEGRADED.proxyOffline && degradedFacts.input_preserved !== '' && degradedFacts.can_local === true && degradedFacts.blocks === 0 && local.organized === true,
  },
  summary: { total: cases.length, passed: cases.length - failed, failed: failed },
};
writeFileSync(outPath, JSON.stringify(result, null, 2) + '\n');
console.log(JSON.stringify(result, null, 2));
process.exit(failed === 0 ? 0 : 1);
`;

function runLogicHarness() {
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'mhp-ai-page-harness-'));
  const harnessPath = path.join(tmpDir, 'ai-page-logic.harness.mjs');
  const outPath = path.join(tmpDir, 'ai-page-logic.result.json');
  const failurePath = path.join(tmpDir, 'ai-page-failure.txt');
  fs.writeFileSync(harnessPath, HARNESS_SOURCE);

  const res = spawnSync(process.execPath, ['--import', 'tsx', harnessPath], {
    cwd: ROOT,
    encoding: 'utf8',
    env: {
      ...process.env,
      MHP_AI_TS: path.join(AI_DIR, 'ai.ts'),
      MHP_MINIAPP_ROOT: MINIAPP_ROOT,
      MHP_HARNESS_OUT: outPath,
      MHP_FAILURE_OUT: failurePath,
      MHP_FIXTURES_PATH: FIXTURES_PATH,
    },
    timeout: 90000,
    maxBuffer: 32 * 1024 * 1024,
  });
  const stdout = `${res.stdout || ''}`;
  const stderr = `${res.stderr || ''}`;

  let result = null;
  if (fs.existsSync(outPath)) {
    try {
      result = JSON.parse(fs.readFileSync(outPath, 'utf8'));
    } catch (err) {
      fail(`harness result JSON unparsable: ${err?.message || err}`);
    }
  }
  const failureRaw = fs.existsSync(failurePath) ? fs.readFileSync(failurePath, 'utf8') : '';
  return {
    method: 'node --import tsx <temp harness> (Page-capture + Map wx shim: storage/modal/request)',
    ai_ts: path.join(AI_DIR, 'ai.ts'),
    exit: res.status,
    stdout_tail: stdout.slice(-8000),
    stderr_tail: stderr.slice(-8000),
    result,
    failure_raw: failureRaw,
  };
}

// ---------------------------------------------------------------------------
// Static invariants (source-level, no runtime claim)
// ---------------------------------------------------------------------------


const FORBIDDEN_STRINGS = [
  'AI 注入',
  'hza_',
  'System Prompt',
  '系统提示词',
  '确诊',
  '诊断结论',
  '处方',
  '疗效保证',
  '急症拦截',
  '自动拨号',
  '预约挂号',
  '挂号成功',
  '候诊叫号',
  '推荐医生',
  '推荐医院',
  '智能分诊',
  'AI 结论',
  '医疗级',
];
const SEVERITY_TOKENS = ['severity', '严重程度', '严重度', '危急程度'];

function staticInvariantChecks() {
  const ts = readPageBundle('ai', 'ts');
  const wxml = readPageBundle('ai', 'wxml');
  const wxss = readPageBundle('ai', 'wxss');
  const json = readPageBundle('ai', 'json');
  const combined = [ts, wxml, wxss, json].join('\n');
  const copy = aiCopyBlock();

  const forbidden = FORBIDDEN_STRINGS.filter((term) => combined.includes(term));
  const copyForbidden = FORBIDDEN_STRINGS.filter((term) => copy.includes(term));
  const severity = SEVERITY_TOKENS.filter((term) => combined.includes(term));

  const usesRecordsApi = /records\.(memory|profile|symptoms|notes|questions)\.(add|update|remove|get|list)\s*\(/.test(ts);
  const usesAiClient = /buildAskPayload\s*\(/.test(ts) && /sendAsk\s*\(/.test(ts) && /sendExtractMemory\s*\(/.test(ts);
  const usesOrganizer = /from '\.\.\/\.\.\/shared\/services\/organizer'/.test(ts) && /\borganize\s*\(/.test(ts);
  const usesStorageModule = /from '\.\.\/\.\.\/shared\/utils\/storage'/.test(ts) && /storage\.(get|set)\s*\(/.test(ts);
  const directStorage = /wx\.(get|set|remove)StorageSync\s*\(/.test(ts);
  const usesA11y = /A11Y_DATA/.test(ts) && /syncA11y\s*\(/.test(ts);
  const usesModeSwitch = /bindtap="onSwitchMode"/.test(wxml) && /data-mode="consult"/.test(wxml) && /data-mode="organize"/.test(wxml);
  const wxmlSafety = /\{\{safetyFixed\}\}/.test(wxml) && /\{\{notDiagnosis\}\}/.test(wxml);
  const wxmlMemory = /memoryLabel/.test(wxml) && /autoMemoryHint/.test(wxml);
  const wxmlCitations = /entry\.url/.test(wxml) || /citations/.test(wxml) || /entry\.sub/.test(wxml);

  let jsonParses = false;
  let jsonTitle = null;
  try {
    const parsed = JSON.parse(json);
    jsonParses = true;
    jsonTitle = parsed.navigationBarTitleText ?? null;
  } catch {
    jsonParses = false;
  }

  const fontLines = wxss.split(/\r?\n/).filter((line) => line.includes('font-size'));
  const fontAllScaled = fontLines.length > 0 && fontLines.every((line) => /calc\([^)]*var\(--mhp-scale\)\)/.test(line));
  const barePx = wxss
    .split(/\r?\n/)
    .filter((line) => /(?<![\dr])\d+px/.test(line))
    .map((line) => line.trim());
  const wxmlScaleInline = /--mhp-scale:\s*\{\{scale\}\}/.test(wxml);
  const wxmlHcClass = /is-hc/.test(wxml);

  return {
    ai_ts_exists: fs.existsSync(path.join(AI_DIR, 'ai.ts')),
    ai_js_exists: fs.existsSync(path.join(AI_DIR, 'ai.js')),
    texts_has_ai_block: copy.length > 0,
    forbidden_strings_present: forbidden,
    ai_copy_forbidden_present: copyForbidden,
    severity_tokens_present: severity,
    uses_records_api: usesRecordsApi,
    uses_ai_client: usesAiClient,
    uses_organizer: usesOrganizer,
    uses_storage_module: usesStorageModule,
    direct_storage_calls: directStorage,
    uses_a11y: usesA11y,
    uses_mode_switch: usesModeSwitch,
    wxml_safety: wxmlSafety,
    wxml_memory: wxmlMemory,
    wxml_citations: wxmlCitations,
    json_parses: jsonParses,
    json_title: jsonTitle,
    font_size_lines: fontLines.length,
    font_size_all_scaled: fontAllScaled,
    bare_px_lines: barePx,
    wxml_scale_inline: wxmlScaleInline,
    wxml_hc_class: wxmlHcClass,
  };
}

// ---------------------------------------------------------------------------
// Layer 2: automator helpers
// ---------------------------------------------------------------------------

const captureScreenshot = makeCaptureScreenshot('ai');

const renderEvidence = makeRenderEvidence(captureScreenshot, AI_ROUTE);

const STORAGE_KEYS = [
  'records_preferences',
  'records_profile',
  'records_symptoms',
  'records_notes',
  'records_questions',
  'records_memory',
  'ai_messages',
  'ai_consult_ack',
];

const clearAiKeys = makeClearAiKeys(STORAGE_KEYS);

const SEED_PREFERENCES = {
  aiEnabled: true,
  consentVersion: 1,
  fontSize: 14,
  highContrast: false,
  autoMemory: true,
  updatedAt: '2026-09-01T00:00:00.000Z',
};
const SEED_PROFILE = [
  {
    id: 'prof_seed_1',
    createdAt: '2026-08-01T01:00:00.000Z',
    updatedAt: '2026-08-01T01:00:00.000Z',
    name: '张三',
    ageRange: '60-69',
    gender: '',
    allergies: '青霉素',
    medications: '降压药',
    history: '',
  },
];
const SEED_SYMPTOMS = [
  {
    id: 'sym_seed_1',
    createdAt: '2026-09-01T01:00:00.000Z',
    updatedAt: '2026-09-01T01:00:00.000Z',
    occurredAt: '2026-09-10T02:00:00.000Z',
    duration: '3 天',
    text: '饭后有点胀',
    impact: '没影响睡眠',
    tags: ['饭后'],
    attachment: null,
  },
];
const SEED_NOTES = [
  {
    id: 'note_seed_1',
    createdAt: '2026-09-03T01:00:00.000Z',
    updatedAt: '2026-09-03T01:00:00.000Z',
    name: '体检报告',
    excerpt: '甘油三酯 2.1',
    sourceDate: '2026-08-20',
    attachment: null,
    remark: '',
  },
];
const SEED_QUESTIONS = [
  {
    id: 'ques_seed_1',
    createdAt: '2026-09-04T01:00:00.000Z',
    updatedAt: '2026-09-04T01:00:00.000Z',
    text: '复查时间怎么安排',
    done: false,
    group: '复查',
    source: 'manual',
  },
];
const SEED_MEMORY = [
  {
    id: 'mem_seed_1',
    createdAt: '2026-09-05T01:00:00.000Z',
    updatedAt: '2026-09-05T01:00:00.000Z',
    text: '希望回复简短一些',
    source: 'manual',
    enabled: true,
  },
];

function probePort(port) {
  return spawnSync('lsof', ['-nP', `-iTCP:${port}`, '-sTCP:LISTEN'], { encoding: 'utf8' }).stdout.trim() !== '';
}


async function stopServer(child, configPath) {
  if (child !== null && child.exitCode === null && child.signalCode === null) {
    child.kill('SIGTERM');
    const deadline = Date.now() + 3000;
    while (child.exitCode === null && child.signalCode === null && Date.now() < deadline) await delay(100);
    if (child.exitCode === null && child.signalCode === null) child.kill('SIGKILL');
  }
  if (configPath) {
    try {
      fs.rmSync(configPath, { force: true });
    } catch {
      /* ignore */
    }
  }
}

/** Ensure a demo proxy on 127.0.0.1:8787; returns { mode, child, configPath, health }. */
async function ensureDemoProxy() {
  if (probePort(PROXY_PORT)) {
    const health = await waitForHealth(`${PROXY_URL}/api/health`, 3000);
    if (health.response && health.response.demo === true) {
      return { mode: 'reused-demo-proxy', child: null, configPath: null, health };
    }
    return { mode: 'occupied-not-demo', child: null, configPath: null, health };
  }
  const configPath = path.join(os.tmpdir(), `mhp-ai-proxy-${process.pid}-${Date.now()}.json`);
  fs.writeFileSync(
    configPath,
    `${JSON.stringify(
      {
        port: PROXY_PORT,
        demo: true,
        llm: { baseUrl: '', apiKey: 'sk-demo-llm', model: 'demo-model' },
        search: { baseUrl: '', apiKey: 'sk-demo-search' },
        authorityDomains: [],
      },
      null,
      2
    )}\n`
  );
  const child = spawn('node', ['server/index.ts'], {
    cwd: ROOT,
    env: { ...process.env, MHP_CONFIG_PATH: configPath },
    stdio: ['ignore', 'pipe', 'pipe'],
  });
  const health = await waitForHealth(`${PROXY_URL}/api/health`, 10000);
  return { mode: 'spawned-demo-proxy', child, configPath, health };
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  ensureDir(E2E_DIR);
  ensureDir(path.dirname(QA_FAILURE_PATH));
  section('AI PAGE SPEC');

  const logic = runLogicHarness();
  const logicScenarios = logic.result ? logic.result.scenarios : [];
  const logicFailed = logic.result ? logic.result.summary.failed : -1;

  if (logic.failure_raw !== '') {
    fs.writeFileSync(QA_FAILURE_PATH, logic.failure_raw);
    log(`failure evidence: ${QA_FAILURE_PATH}`);
  }

  const report = {
    command: 'E2E_DEVTOOLS_MINIMIZE=1 node tests/e2e/ai-page.spec.mjs (cold)',
    timestamp: new Date().toISOString(),
    platform: `${os.platform()} ${os.release()} (${os.arch()})`,
    node_version: process.version,
    project_path: CONFIG.projectPath,
    logic: { method: logic.method, ai_ts: logic.ai_ts, exit: logic.exit, result: logic.result },
    static_invariants: null,
    proxy: null,
    evaluate_probe: null,
    drive_organize: null,
    consent: null,
    drive_consult: null,
    drive_redflag: null,
    storage_readback: null,
    render: null,
    persistence: null,
    summary: null,
  };

  let allOk = true;

  if (logic.result !== null && logic.exit === 0 && logicFailed === 0) {
    ok(`logic harness: ${logic.result.summary.passed}/${logic.result.summary.total} scenarios passed (real page methods)`);
  } else {
    fail(`logic harness failed (exit=${logic.exit}, failed_scenarios=${logicFailed}); stderr tail: ${logic.stderr_tail}`);
    allOk = false;
  }
  for (const scenario of logicScenarios) {
    log(`  [logic] ${scenario.pass ? 'PASS' : 'FAIL'} ${scenario.id}: ${scenario.name}`);
    if (!scenario.pass) allOk = false;
  }

  const statics = staticInvariantChecks();
  report.static_invariants = statics;
  const staticsOk =
    statics.ai_ts_exists === true &&
    statics.ai_js_exists === false &&
    statics.texts_has_ai_block === true &&
    statics.forbidden_strings_present.length === 0 &&
    statics.ai_copy_forbidden_present.length === 0 &&
    statics.severity_tokens_present.length === 0 &&
    statics.uses_records_api === true &&
    statics.uses_ai_client === true &&
    statics.uses_organizer === true &&
    statics.uses_storage_module === true &&
    statics.direct_storage_calls === false &&
    statics.uses_a11y === true &&
    statics.uses_mode_switch === true &&
    statics.wxml_safety === true &&
    statics.wxml_memory === true &&
    statics.wxml_citations === true &&
    statics.json_parses === true &&
    statics.json_title === 'AI 助手' &&
    statics.font_size_all_scaled === true &&
    statics.bare_px_lines.length === 0 &&
    statics.wxml_scale_inline === true &&
    statics.wxml_hc_class === true;
  if (staticsOk) {
    ok('static invariants: records API only; aiClient + organizer wired; storage module only; a11y/scale/hc wired; scaled px-free wxss; no forbidden token');
  } else {
    fail(`static invariant failure: ${JSON.stringify(report.static_invariants)}`);
    allOk = false;
  }

  let fixtures = null;
  try {
    fixtures = JSON.parse(fs.readFileSync(FIXTURES_PATH, 'utf8'));
  } catch (err) {
    fail(`cannot read demo fixtures: ${err?.message || err}`);
    allOk = false;
  }

  let proxy = null;
  let miniProgram;
  try {
    proxy = await ensureDemoProxy();
    const proxyUsable = proxy.health && proxy.health.response && proxy.health.response.demo === true;
    const stubMode = !proxyUsable;
    report.proxy = {
      mode: stubMode ? 'stubbed host API (no demo proxy available)' : proxy.mode,
      url: PROXY_URL,
      health: proxy.health ? proxy.health.response : null,
      stubbed: stubMode,
    };
    if (stubMode) {
      log(`proxy: ${report.proxy.mode} — falling back to an evaluate-level wx.request stub`);
    } else {
      ok(`proxy: ${proxy.mode}, health=${JSON.stringify(proxy.health.response)}`);
    }

    miniProgram = await launchMiniProgram();
    await clearAiKeys(miniProgram);

    await miniProgram.callWxMethod('setStorageSync', 'mhp_records_preferences', SEED_PREFERENCES);
    await miniProgram.callWxMethod('setStorageSync', 'mhp_records_profile', SEED_PROFILE);
    await miniProgram.callWxMethod('setStorageSync', 'mhp_records_symptoms', SEED_SYMPTOMS);
    await miniProgram.callWxMethod('setStorageSync', 'mhp_records_notes', SEED_NOTES);
    await miniProgram.callWxMethod('setStorageSync', 'mhp_records_questions', SEED_QUESTIONS);
    await miniProgram.callWxMethod('setStorageSync', 'mhp_records_memory', SEED_MEMORY);

    if (stubMode) {
      const raced = await withTimeout(
        miniProgram.evaluate(
          (fx) => {
            wx.request = function (options) {
              let body = {};
              try {
                body = JSON.parse(options.data);
              } catch (e) {
                body = {};
              }
              const userTexts = (body.messages || [])
                .filter((m) => m.role === 'user')
                .map((m) => m.content)
                .join(' ');
              setTimeout(function () {
                if (String(options.url).indexOf('/api/extract-memory') !== -1) {
                  if (options.success) options.success({ statusCode: 200, data: { candidates: fx.extract.candidates } });
                  return;
                }
                if (userTexts.indexOf('胸痛') !== -1) {
                  if (options.success) options.success({ statusCode: 200, data: fx.redflag });
                  return;
                }
                if (options.success) options.success({ statusCode: 200, data: body.mode === 'organize' ? fx.organize : fx.consult });
              }, 0);
              return { abort: function () {} };
            };
            return { installed: true };
          },
          {
            organize: fixtures.organize,
            consult: fixtures.consult.response,
            redflag: fixtures.redflag,
            extract: fixtures.extractMemory,
          }
        ),
        15000,
        'evaluate-stub-request'
      );
      if (raced.timedOut === true || raced.error !== undefined) {
        report.proxy.stub_install = raced.timedOut ? 'timed out' : raced.error;
        fail(`stub install failed: ${JSON.stringify(report.proxy.stub_install)}`);
        allOk = false;
      } else {
        report.proxy.stub_install = raced.value;
        ok('wx.request demo-fixture stub installed inside evaluate (stubbed host API)');
      }
    }

    await miniProgram.reLaunch('/' + AI_ROUTE + '?mode=organize');
    await delay(800);
    await miniProgram.reLaunch('/' + AI_ROUTE + '?mode=organize');
    await delay(800);

    // evaluate capability probe
    let probe = null;
    {
      const raced = await withTimeout(
        miniProgram.evaluate(() => {
          const pages = getCurrentPages();
          const page = pages[pages.length - 1];
          return {
            route: page.route,
            mode: page.data.mode,
            hasSend: typeof page.onSend,
            hasConfirm: typeof page.onConfirmSend,
            hasLocal: typeof page.onLocalOrganize,
            hasSaveMemory: typeof page.onSaveMemory,
            hasSetMode: typeof page.setMode,
            safety: typeof page.data.safetyFixed,
          };
        }),
        15000,
        'evaluate-probe'
      );
      if (raced.timedOut === true) {
        report.evaluate_probe = { ok: false, error: 'timed out' };
        fail('evaluate probe timed out');
        allOk = false;
      } else if (raced.error !== undefined) {
        report.evaluate_probe = { ok: false, error: raced.error };
        fail(`evaluate probe failed: ${raced.error}`);
        allOk = false;
      } else {
        probe = raced.value;
        report.evaluate_probe = { ok: true, value: probe };
        ok(`miniProgram.evaluate probe: ${JSON.stringify(probe)}`);
      }
    }

    const probeOk = Boolean(probe && probe.route === AI_ROUTE && probe.hasConfirm === 'function' && probe.hasSetMode === 'function');

    if (probeOk) {
      // organize round
      const raced = await withTimeout(
        miniProgram.evaluate(async () => {
          const pages = getCurrentPages();
          const page = pages[pages.length - 1];
          page.onInput({ detail: { value: '最近一周头痛，睡不好' } });
          const send = await page.onSend();
          const previewTitles = page.data.previewSections.map((s) => s.title);
          const confirmed = await page.onConfirmSend();
          const msgs = page.data.messages;
          const last = msgs[msgs.length - 1];
          return {
            send: send,
            previewTitles: previewTitles,
            confirmed: confirmed,
            mode: page.data.mode,
            messages: msgs.length,
            lastKind: last ? last.kind : '',
            blockTitles: last ? last.blocks.map((b) => b.title) : [],
            inputCleared: page.data.input === '',
          };
        }),
        20000,
        'evaluate-organize'
      );
      if (raced.timedOut === true || raced.error !== undefined) {
        report.drive_organize = raced.timedOut ? { error: 'timed out' } : { error: raced.error };
        fail(`organize drive failed: ${JSON.stringify(report.drive_organize)}`);
        allOk = false;
      } else {
        const d = raced.value;
        report.drive_organize = d;
        const okOrganize = d && d.send && d.send.reason === 'preview' && d.confirmed && d.confirmed.ok === true && d.lastKind === 'organize' && d.inputCleared === true && d.messages >= 2;
        if (okOrganize) ok(`organize round driven: preview=${JSON.stringify(d.previewTitles)}, blocks=${JSON.stringify(d.blockTitles)}`);
        else {
          fail(`organize drive unexpected: ${JSON.stringify(d)}`);
          allOk = false;
        }
      }

      // consent gate + consult switch (stub showModal to auto-confirm and record)
      const consentRaced = await withTimeout(
        miniProgram.evaluate(async () => {
          const pages = getCurrentPages();
          const page = pages[pages.length - 1];
          const originalModal = wx.showModal;
          const modals = [];
          wx.showModal = function (options) {
            modals.push({ title: options && options.title, content: options && options.content });
            if (options && typeof options.success === 'function') options.success({ confirm: true, cancel: false });
          };
          let switched = false;
          try {
            switched = await page.setMode('consult');
          } finally {
            wx.showModal = originalModal;
          }
          return { switched: switched, modals: modals, mode: page.data.mode, ack: wx.getStorageSync('mhp_ai_consult_ack') };
        }),
        15000,
        'evaluate-consent'
      );
      if (consentRaced.timedOut === true || consentRaced.error !== undefined) {
        report.consent = consentRaced.timedOut ? { error: 'timed out' } : { error: consentRaced.error };
        fail(`consent drive failed: ${JSON.stringify(report.consent)}`);
        allOk = false;
      } else {
        report.consent = consentRaced.value;
        const c = consentRaced.value;
        const okConsent = c && c.switched === true && c.mode === 'consult' && c.ack === true && Array.isArray(c.modals) && c.modals.length >= 1;
        if (okConsent) ok('consult consent: modal shown, confirmed, ack persisted, mode=consult');
        else {
          fail(`consent drive unexpected: ${JSON.stringify(c)}`);
          allOk = false;
        }
      }

      // consult round with 带入我的资料
      const consultRaced = await withTimeout(
        miniProgram.evaluate(async () => {
          const pages = getCurrentPages();
          const page = pages[pages.length - 1];
          page.onToggleProfile();
          page.onInput({ detail: { value: '最近胃不舒服' } });
          const send = await page.onSend();
          const previewTitles = page.data.previewSections.map((s) => s.title);
          const confirmed = await page.onConfirmSend();
          const msgs = page.data.messages;
          const last = msgs[msgs.length - 1];
          const dirs = last ? last.blocks.filter((b) => b.type === 'directions').reduce((a, b) => a.concat(b.items), []) : [];
          const sugs = last ? last.blocks.filter((b) => b.type === 'suggestions').reduce((a, b) => a.concat(b.items), []) : [];
          const cits = last ? last.blocks.filter((b) => b.type === 'citations').reduce((a, b) => a.concat(b.items), []) : [];
          return {
            send: send,
            previewTitles: previewTitles,
            confirmed: confirmed,
            lastKind: last ? last.kind : '',
            blockTitles: last ? last.blocks.map((b) => b.title) : [],
            directions: dirs,
            suggestions: sugs,
            citations: cits,
            disclaimer: last ? last.disclaimer : '',
            memoryLabel: page.data.memoryLabel,
            memoryCount: page.data.memoryCount,
            autoMemoryAdded: page.data.autoMemoryAdded,
            safetyFixed: page.data.safetyFixed,
            notDiagnosis: page.data.notDiagnosis,
          };
        }),
        20000,
        'evaluate-consult'
      );
      if (consultRaced.timedOut === true || consultRaced.error !== undefined) {
        report.drive_consult = consultRaced.timedOut ? { error: 'timed out' } : { error: consultRaced.error };
        fail(`consult drive failed: ${JSON.stringify(report.drive_consult)}`);
        allOk = false;
      } else {
        const c = consultRaced.value;
        report.drive_consult = c;
        const dirOk = Array.isArray(c.directions) && c.directions.length > 0 && c.directions.every((i) => i.sub.indexOf('来源：') === 0 && i.url !== '');
        const sugOk = Array.isArray(c.suggestions) && c.suggestions.length > 0 && c.suggestions.every((i) => i.tag === '非医嘱');
        const citOk = Array.isArray(c.citations) && c.citations.length > 0 && c.citations.every((i) => i.text !== '' && i.sub !== '');
        const okConsult =
          c && c.confirmed && c.confirmed.ok === true && c.lastKind === 'consult' && dirOk && sugOk && citOk &&
          c.disclaimer !== '' && c.memoryCount >= 1 && c.safetyFixed !== '' && c.notDiagnosis !== '';
        if (okConsult) {
          ok(`consult round driven: directions=${c.directions.length}, suggestions(非医嘱)=${c.suggestions.length}, citations=${c.citations.length}, memory=${c.memoryLabel}, autoAdded=${c.autoMemoryAdded}`);
        } else {
          fail(`consult drive unexpected: ${JSON.stringify(c)}`);
          allOk = false;
        }
      }

      // redflag round
      const rfRaced = await withTimeout(
        miniProgram.evaluate(async () => {
          const pages = getCurrentPages();
          const page = pages[pages.length - 1];
          page.onInput({ detail: { value: '我胸痛' } });
          await page.onSend();
          const confirmed = await page.onConfirmSend();
          const msgs = page.data.messages;
          const last = msgs[msgs.length - 1];
          return {
            confirmed: confirmed,
            lastKind: last ? last.kind : '',
            blockTypes: last ? last.blocks.map((b) => b.type) : [],
            blockTitles: last ? last.blocks.map((b) => b.title) : [],
            disclaimer: last ? last.disclaimer : '',
          };
        }),
        20000,
        'evaluate-redflag'
      );
      if (rfRaced.timedOut === true || rfRaced.error !== undefined) {
        report.drive_redflag = rfRaced.timedOut ? { error: 'timed out' } : { error: rfRaced.error };
        fail(`redflag drive failed: ${JSON.stringify(report.drive_redflag)}`);
        allOk = false;
      } else {
        const r = rfRaced.value;
        report.drive_redflag = r;
        const rfOk =
          r && r.confirmed && r.confirmed.kind === 'redflag' && r.lastKind === 'redflag' &&
          r.blockTypes.length === 1 && r.blockTypes[0] === 'notice' && r.disclaimer !== '';
        if (rfOk) ok(`redflag round driven: blocks=${JSON.stringify(r.blockTitles)} (safety notice only)`);
        else {
          fail(`redflag drive unexpected: ${JSON.stringify(r)}`);
          allOk = false;
        }
      }
    }

    // storage read-back + render evidence
    {
      const raced = await withTimeout(miniProgram.callWxMethod('getStorageSync', 'mhp_ai_messages'), 10000, 'readback');
      if (raced.timedOut === true || raced.error !== undefined) {
        report.storage_readback = raced.timedOut ? { error: 'timed out' } : { error: raced.error };
        fail('history read-back failed');
        allOk = false;
      } else {
        const stored = raced.value;
        const count = Array.isArray(stored) ? stored.length : -1;
        report.storage_readback = { key: 'mhp_ai_messages', count: count, is_array: Array.isArray(stored) };
        if (Array.isArray(stored) && stored.length >= 2) ok(`history persisted under mhp_ai_messages (${stored.length} messages)`);
        else {
          fail(`history read-back unexpected: ${JSON.stringify(report.storage_readback)}`);
          allOk = false;
        }
      }
    }

    {
      const raced = await withTimeout(renderEvidence(miniProgram, 'after-consult'), 15000, 'render');
      if (raced.timedOut === true || raced.error !== undefined) {
        report.render = raced.timedOut ? { error: 'timed out' } : { error: raced.error };
        fail(`render evidence failed: ${JSON.stringify(report.render)}`);
        allOk = false;
      } else {
        const render = raced.value;
        report.render = { ...render, method: 'reLaunch+pageStack+screenshot' };
        if (render.ok) ok(`render evidence: top=${render.topPath}, bytes=${render.screenshotBytes}, md5=${render.screenshotMd5}`);
        else {
          fail(`render check failed: ${JSON.stringify(render)}`);
          allOk = false;
        }
      }
    }

    // close + relaunch persistence
    try {
      await withTimeout(miniProgram.close(), 8000, 'close');
      miniProgram = null;
    } catch (err) {
      log(`warning: close failed: ${err?.message || err}`);
    }
    await delay(2000);
    miniProgram = await launchMiniProgram();
    {
      const raced = await withTimeout(miniProgram.callWxMethod('getStorageSync', 'mhp_ai_messages'), 10000, 'readback-after');
      if (raced.timedOut === true || raced.error !== undefined) {
        report.persistence = raced.timedOut ? { error: 'timed out' } : { error: raced.error };
        fail('relaunch persistence read-back failed');
        allOk = false;
      } else {
        const stored = raced.value;
        const count = Array.isArray(stored) ? stored.length : -1;
        report.persistence = { key: 'mhp_ai_messages', count: count, persisted_after_relaunch: Array.isArray(stored) && stored.length >= 2 };
        if (report.persistence.persisted_after_relaunch) ok(`history persists across close+relaunch (${count} messages)`);
        else {
          fail(`history did not persist: ${JSON.stringify(report.persistence)}`);
          allOk = false;
        }
      }
    }

    await withTimeout(clearAiKeys(miniProgram), 10000, 'clear-keys');
  } catch (err) {
    fail(`ai-page spec run error: ${err?.stack || err}`);
    report.error = err?.message || String(err);
    allOk = false;
  } finally {
    if (miniProgram) {
      const raced = await withTimeout(miniProgram.close(), 8000, 'close');
      if (raced.timedOut === true) log('warning: miniProgram.close() timed out');
      else if (raced.error !== undefined) log(`warning: miniProgram.close() failed: ${raced.error}`);
      else log('miniProgram.close() done');
      try {
        miniProgram.disconnect();
      } catch {
        /* socket already closed */
      }
    }
    if (proxy && proxy.child) {
      await stopServer(proxy.child, proxy.configPath);
      log('demo proxy child stopped');
    }
  }

  const checks = {
    logic_harness_ok: logic.result !== null && logic.exit === 0 && logicFailed === 0,
    static_invariants_ok: staticsOk,
    proxy_ok: Boolean(report.proxy && (report.proxy.stubbed === true || (report.proxy.health && report.proxy.health.demo === true))),
    evaluate_probe_ok: Boolean(report.evaluate_probe && report.evaluate_probe.ok === true && report.evaluate_probe.value && report.evaluate_probe.value.route === AI_ROUTE),
    organize_round_ok: Boolean(report.drive_organize && report.drive_organize.confirmed && report.drive_organize.confirmed.ok === true && report.drive_organize.lastKind === 'organize'),
    consent_ok: Boolean(report.consent && report.consent.switched === true && report.consent.ack === true),
    consult_round_ok: Boolean(
      report.drive_consult &&
        report.drive_consult.confirmed &&
        report.drive_consult.confirmed.ok === true &&
        report.drive_consult.lastKind === 'consult' &&
        Array.isArray(report.drive_consult.directions) &&
        report.drive_consult.directions.length > 0 &&
        Array.isArray(report.drive_consult.suggestions) &&
        report.drive_consult.suggestions.every((i) => i.tag === '非医嘱') &&
        Array.isArray(report.drive_consult.citations) &&
        report.drive_consult.citations.length > 0 &&
        report.drive_consult.disclaimer !== ''
    ),
    redflag_round_ok: Boolean(report.drive_redflag && report.drive_redflag.lastKind === 'redflag' && report.drive_redflag.blockTypes.length === 1 && report.drive_redflag.blockTypes[0] === 'notice'),
    storage_readback_ok: Boolean(report.storage_readback && report.storage_readback.is_array === true && report.storage_readback.count >= 2),
    render_ok: Boolean(report.render && report.render.ok === true),
    persistence_ok: Boolean(report.persistence && report.persistence.persisted_after_relaunch === true),
    no_forbidden_strings: statics.forbidden_strings_present.length === 0 && statics.ai_copy_forbidden_present.length === 0,
    no_severity_token: statics.severity_tokens_present.length === 0,
    font_scaled: statics.font_size_all_scaled === true && statics.bare_px_lines.length === 0,
    json_ok: statics.json_parses === true && statics.json_title === 'AI 助手',
  };
  const checksPassed = Object.values(checks).every((v) => v === true);
  log(`summary checks: ${JSON.stringify(checks)}`);

  report.summary = {
    ...checks,
    logic_scenarios_total: logic.result ? logic.result.summary.total : 0,
    logic_scenarios_passed: logic.result ? logic.result.summary.passed : 0,
    passed: checksPassed && allOk === true,
    failed: !(checksPassed && allOk === true),
  };

  const reportPath = path.join(E2E_DIR, 'ai-page.json');
  fs.writeFileSync(reportPath, JSON.stringify(report, null, 2) + '\n');
  log(`ai-page evidence: ${reportPath}`);

  return report.summary.passed;
}

main().then(
  (passed) => {
    process.exit(passed ? 0 : 1);
  },
  (err) => {
    console.error(`[e2e] FAIL ${err?.stack || err}`);
    process.exit(1);
  }
);
