// ai-to-records.spec.mjs — task 30: save AI results into local records (standalone).
//
// Run: node tests/e2e/ai-to-records.spec.mjs
//      E2E_DEVTOOLS_MINIMIZE=1 node tests/e2e/ai-to-records.spec.mjs   (cold, hidden)
// Evidence: artifacts/e2e/ai-to-records.json
//           artifacts/qa/30-failure.txt   (duplicate-refusal + all-dup-questions transcript)
//
// Two independent layers, never conflated:
//   (1) LOGIC (real code path): pages/ai/ai.ts is imported into a node harness (Page-capture +
//       Map-backed wx shim), seeded with a crafted AiMessage history (organize + consult, whose
//       blocks carry note/ask flags exactly like the real builders). It drives the REAL page
//       methods: save-as-note draft (prefill from the message dataset), draft edit (the edited
//       excerpt — not the original — must land in the stored DocumentNote), citation source
//       persistence into remark, duplicate refusal with a byte-identical notes store, cancel, the
//       empty guards, and the questions importMany path (mixed new + all-duplicate + empty).
//   (2) RUNTIME (REAL, via miniProgram.evaluate): seeds the SAME synthetic history into
//       mhp_ai_messages via callWxMethod, reLaunches pages/ai, drives the REAL page methods with
//       the same dataset shapes the wxml passes, then reads back mhp_records_notes /
//       mhp_records_questions via callWxMethod and asserts exact field sets/values (edited text
//       + source in remark). It then reLaunches pages/notes + pages/questions and proves the
//       saved content changes the render vs an empty baseline, and close+relaunches to prove
//       persistence. No network is used (saves are local).
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {
  CONFIG,
  E2E_ARTIFACTS,
  ROOT,
  ensureDir,
  fail,
  launchMiniProgram,
  log,
  ok,
  section,
  delay,
  md5,
  readSafe,
  withTimeout,
  aiCopyBlock,
  makeCaptureScreenshot,
} from './helpers.mjs';

const AI_ROUTE = 'pages/ai/ai';
const NOTES_ROUTE = 'pages/notes/notes';
const QUESTIONS_ROUTE = 'pages/questions/questions';
const MINIAPP_ROOT = CONFIG.projectPath;
const AI_DIR = path.join(MINIAPP_ROOT, 'pages', 'ai');
const TEXTS_TS = path.join(MINIAPP_ROOT, 'config', 'texts.ts');

const E2E_DIR = E2E_ARTIFACTS;
const QA_FAILURE_PATH = path.join(ROOT, 'artifacts', 'qa', '30-failure.txt');

// Mirrors config/texts.ts AI section (runtime seed can't import the TS module in plain node).
const T = {
  points: '要点',
  extracted: '提取',
  unknowns: '待补充',
  questions: '可以问的问题',
  directions: '健康方向',
  departments: '建议就诊科室',
  citations: '来源链接',
  suggestions: '日常建议',
  symptoms: '症状',
  nonAdvice: '非医嘱',
};
const QUESTIONS_ALL_DUP = '没有新增：这些问题都已经在清单中。';
const NOTE_DUPLICATE_HINT = '这条摘录已经在资料中';
const NOTE_SAVED_HINT = '已保存为资料摘录';
const EDITED_EXCERPT = '医生解释：规律作息有帮助';
const NOTE_KEYS = 'attachment,createdAt,excerpt,id,name,remark,sourceDate,updatedAt';
const QUESTION_KEYS = 'createdAt,done,group,id,source,text,updatedAt';
const SRC_TITLE = '国家卫生健康委员会：就医准备与信息整理提示';
const SRC_DOMAIN = 'nhc.gov.cn';
const SRC_URL = 'https://nhc.gov.cn/health/demo-1';
const SRC_SUB = '来源：' + SRC_TITLE + ' · ' + SRC_DOMAIN;


// ---------------------------------------------------------------------------
// Layer 1: node/page-logic harness (real page methods + Map wx shim)
// ---------------------------------------------------------------------------

const HARNESS_SOURCE = String.raw`// temp ai-to-records logic harness (run via tsx); not committed — generated by ai-to-records.spec.mjs
import { pathToFileURL } from 'node:url';
import { writeFileSync } from 'node:fs';
import path from 'node:path';
const { clone, makeCheck, makeFlog, makeInstanceFactory, makeRawList } = await import(${JSON.stringify(new URL('./helpers.mjs', import.meta.url).href)});

const aiTs = process.env.MHP_AI_TS;
const root = process.env.MHP_MINIAPP_ROOT;
const outPath = process.env.MHP_HARNESS_OUT;
const failureOut = process.env.MHP_FAILURE_OUT;
if (!aiTs || !root || !outPath) throw new Error('missing harness env');

const store = new Map();
const calls = { toast: [], modal: [] };
globalThis.wx = {
  getStorageSync: function (key) { return store.has(key) ? store.get(key) : ''; },
  setStorageSync: function (key, value) { store.set(key, value); },
  removeStorageSync: function (key) { store.delete(key); },
  getStorageInfoSync: function () { return { keys: Array.from(store.keys()) }; },
  showToast: function (o) { calls.toast.push(o); },
  showModal: function (o) { calls.modal.push(o); if (o && typeof o.success === 'function') o.success({ confirm: true, cancel: false }); },
  vibrateShort: function () {},
  vibrateLong: function () {},
};

let captured = null;
globalThis.Page = function (config) { captured = config; };

const textsModule = await import(pathToFileURL(path.join(root, 'config/texts.ts')).href);
const AI = textsModule.AI;
const QUESTIONS = textsModule.QUESTIONS;

await import(pathToFileURL(aiTs).href);
if (captured === null) throw new Error('ai.ts did not call Page()');

const recordsModule = await import(pathToFileURL(path.join(root, 'shared/services/records.ts')).href);
const records = recordsModule.records;

const SRC_TITLE = '国家卫生健康委员会：就医准备与信息整理提示';
const SRC_DOMAIN = 'nhc.gov.cn';
const SRC_URL = 'https://nhc.gov.cn/health/demo-1';
const SRC_SUB = '来源：' + SRC_TITLE + ' · ' + SRC_DOMAIN;
const EDITED = '医生解释：规律作息有帮助';
const NOTE_KEYS = 'attachment,createdAt,excerpt,id,name,remark,sourceDate,updatedAt';
const QUESTION_KEYS = 'createdAt,done,group,id,source,text,updatedAt';

function block(type, title, items, flags) {
  const out = { type: type, title: title, items: items };
  if (flags && flags.note === true) out.note = true;
  if (flags && flags.ask === true) out.ask = true;
  return out;
}
function item(text, sub, url, tag) { return { text: text, sub: sub || '', url: url || '', tag: tag || '' }; }

const SEED_HISTORY = [
  { id: 'aimsg_seed_u1', role: 'user', mode: 'organize', kind: 'text', content: '最近一周头痛，睡不好', memoryDraft: '最近一周头痛，睡不好', blocks: [], disclaimer: '', errorText: '', canLocalOrganize: false, localText: '', createdAt: '2026-09-20T01:00:00.000Z' },
  { id: 'aimsg_seed_o1', role: 'assistant', mode: 'organize', kind: 'organize', content: '', memoryDraft: '近一周出现头痛', blocks: [
      block('list', AI.sectionPoints, [item('近一周出现头痛')], { note: true }),
      block('extracted', AI.sectionExtracted, [item('头痛', '', '', AI.extractedSymptoms)], { note: true }),
      block('list', AI.sectionUnknowns, [item('头痛诱因与持续时间未说明')]),
      block('list', AI.sectionQuestions, [item('头痛从何时开始、多久一次？'), item('需要记录哪些伴随症状？')], { ask: true }),
    ], disclaimer: '', errorText: '', canLocalOrganize: false, localText: '', createdAt: '2026-09-20T01:00:01.000Z' },
  { id: 'aimsg_seed_u2', role: 'user', mode: 'consult', kind: 'text', content: '最近胃不舒服', memoryDraft: '最近胃不舒服', blocks: [], disclaimer: '', errorText: '', canLocalOrganize: false, localText: '', createdAt: '2026-09-21T01:00:00.000Z' },
  { id: 'aimsg_seed_c1', role: 'assistant', mode: 'consult', kind: 'consult', content: '', memoryDraft: '注意休息与规律作息', blocks: [
      block('directions', AI.sectionDirections, [item('注意休息与规律作息', SRC_SUB, SRC_URL)], { note: true }),
      block('list', AI.sectionDepartments, [item('全科')]),
      block('citations', AI.sectionCitations, [item(SRC_TITLE, SRC_DOMAIN, SRC_URL)]),
      block('suggestions', AI.sectionSuggestions, [item('作息规律、避免熬夜', SRC_SUB, SRC_URL, AI.nonAdvice)], { note: true }),
      block('list', AI.sectionQuestions, [item('需要向医生了解哪些检查或注意事项？')], { ask: true }),
    ], disclaimer: '以上内容仅为信息整理与一般性提示，不构成诊断或治疗建议；如有不适请及时就医。', errorText: '', canLocalOrganize: false, localText: '', createdAt: '2026-09-21T01:00:01.000Z' },
];

const makeInstance = makeInstanceFactory(() => captured, { cloneExtras: true });
function evt(mid, bi, ei) { return { currentTarget: { dataset: { messageId: mid, blockIndex: bi, itemIndex: ei } } }; }
const rawList = makeRawList(store);
function snapshot(key) { return JSON.stringify(store.get(key)); }
function resetAll() { store.clear(); calls.toast.length = 0; calls.modal.length = 0; }
function seedPrefs() {
  records.preferences.update({ aiEnabled: true, autoMemory: false, fontSize: 14, highContrast: false });
}
function seedHistory() { store.set('mhp_ai_messages', clone(SEED_HISTORY)); }

const cases = [];
const check = makeCheck(cases);

// h1: history loads; the real block flags decide which actions render
resetAll();
seedPrefs();
seedHistory();
let inst = makeInstance();
inst.onLoad({});
inst.onShow();
const organize = inst.data.messages.filter(function (m) { return m.role === 'assistant' && m.mode === 'organize'; })[0];
const consult = inst.data.messages.filter(function (m) { return m.role === 'assistant' && m.mode === 'consult'; })[0];
const flagsOk = organize.blocks[0].note === true && organize.blocks[1].note === true &&
  organize.blocks[2].note === undefined && organize.blocks[2].ask === undefined &&
  organize.blocks[3].ask === true && organize.blocks[3].note === undefined &&
  consult.blocks[0].note === true && consult.blocks[3].note === true && consult.blocks[4].ask === true &&
  consult.blocks[1].note === undefined && consult.blocks[2].note === undefined;
check('load-flags', 'seeded history loads; note/ask flags sit on exactly the savable blocks (points/extracted/directions/suggestions + questions)',
  inst.data.hasMessages === true && inst.data.messages.length === 4 && flagsOk,
  { messages: inst.data.messages.length, organize_flags: organize.blocks.map(function (b) { return [b.title, b.note === true, b.ask === true]; }),
    consult_flags: consult.blocks.map(function (b) { return [b.title, b.note === true, b.ask === true]; }) });

// h2: save-as-note opens an editable draft prefilled from the item
const r2 = inst.onSaveAsNote(evt(organize.id, 0, 0));
check('draft-prefill', '存为资料 opens a draft prefilled from the clicked item (name=section, excerpt=item text, remark from citation)',
  r2.opened === true && inst.data.draftOpen === true && inst.data.draftForm.name === AI.sectionPoints &&
    inst.data.draftForm.excerpt === '近一周出现头痛' && inst.data.draftForm.remark === '',
  { returned: r2, draft: inst.data.draftForm });

// h3: edit the draft then confirm -> the EDITED value (not the original) lands in DocumentNote
inst.onDraftInput({ currentTarget: { dataset: { field: 'excerpt' } }, detail: { value: EDITED } });
const editedInDraft = inst.data.draftForm.excerpt;
const r3 = inst.onDraftConfirm();
const notes3 = rawList('mhp_records_notes');
const n0 = notes3[0];
const noteKeysOk = n0 !== undefined && Object.keys(n0).sort().join(',') === NOTE_KEYS;
check('note-save-edited', 'confirm writes records.notes.add with the EDITED draft excerpt; exact DocumentNote field set; draft closes with a saved hint',
  editedInDraft === EDITED && r3.saved === true && notes3.length === 1 && noteKeysOk &&
    n0.excerpt === EDITED && n0.excerpt !== '近一周出现头痛' && n0.name === AI.sectionPoints &&
    n0.sourceDate === '' && n0.attachment === null && n0.remark === '' &&
    inst.data.draftOpen === false && inst.data.draftForm.excerpt === '' && inst.data.hint === AI.noteSavedHint,
  { edited: editedInDraft, stored: n0, field_keys: n0 ? Object.keys(n0).sort().join(',') : '', hint: inst.data.hint });

// h4: saving a consult direction persists the citation (title + domain + url) into remark
const r4 = inst.onSaveAsNote(evt(consult.id, 0, 0));
const remarkPrefill = inst.data.draftForm.remark;
const r4c = inst.onDraftConfirm();
const notes4 = rawList('mhp_records_notes');
const d0 = notes4[1];
check('note-source', 'a citation-carrying item prefills remark with 来源 title · domain + url and persists all three into the stored note',
  r4.opened === true && r4c.saved === true && notes4.length === 2 && d0 !== undefined &&
    d0.excerpt === '注意休息与规律作息' && d0.name === AI.sectionDirections &&
    remarkPrefill.indexOf(SRC_TITLE) !== -1 && remarkPrefill.indexOf(SRC_DOMAIN) !== -1 && remarkPrefill.indexOf(SRC_URL) !== -1 &&
    d0.remark.indexOf(SRC_TITLE) !== -1 && d0.remark.indexOf(SRC_DOMAIN) !== -1 && d0.remark.indexOf(SRC_URL) !== -1,
  { remark_prefill: remarkPrefill, stored_remark: d0 ? d0.remark : '' });

// h5: duplicate save refused with a visible hint and ZERO write (notes store byte-identical)
const before5 = snapshot('mhp_records_notes');
const r5o = inst.onSaveAsNote(evt(organize.id, 0, 0));
inst.onDraftInput({ currentTarget: { dataset: { field: 'excerpt' } }, detail: { value: EDITED } });
const r5c = inst.onDraftConfirm();
const after5 = snapshot('mhp_records_notes');
const notesCount5 = rawList('mhp_records_notes').length;
const dupFacts = {
  attempted_excerpt: EDITED,
  returned_reason: r5c.reason,
  draft_hint: inst.data.draftHint,
  page_hint: inst.data.hint,
  store_bytes_identical: before5 === after5,
  notes_count_before: 2,
  notes_count_after: notesCount5,
};
check('note-duplicate', 'saving the same trimmed excerpt again is refused (reason duplicate) with a visible hint and a byte-identical notes store',
  r5o.opened === true && r5c.saved === false && r5c.reason === 'duplicate' &&
    dupFacts.draft_hint === AI.noteDuplicateHint && dupFacts.page_hint === AI.noteDuplicateHint &&
    dupFacts.store_bytes_identical === true && notesCount5 === 2,
  dupFacts);

// h6: duplicate detection is on the TRIMMED excerpt (padded whitespace still refuses)
const r6o = inst.onSaveAsNote(evt(organize.id, 1, 0));
inst.onDraftInput({ currentTarget: { dataset: { field: 'excerpt' } }, detail: { value: '   ' + EDITED + '   ' } });
const before6 = snapshot('mhp_records_notes');
const r6c = inst.onDraftConfirm();
const after6 = snapshot('mhp_records_notes');
check('note-duplicate-trim', 'duplicate detection trims: a whitespace-padded copy of an existing excerpt is refused with no write',
  r6o.opened === true && r6c.saved === false && r6c.reason === 'duplicate' && before6 === after6,
  { returned: r6c, bytes_identical: before6 === after6, hint: inst.data.draftHint });
inst.onDraftCancel();

// h7: empty excerpt guard (no write)
const r7o = inst.onSaveAsNote(evt(organize.id, 0, 0));
inst.onDraftInput({ currentTarget: { dataset: { field: 'excerpt' } }, detail: { value: '   ' } });
const before7 = snapshot('mhp_records_notes');
const r7c = inst.onDraftConfirm();
const after7 = snapshot('mhp_records_notes');
const r7bad = inst.onSaveAsNote({ currentTarget: { dataset: { messageId: 'missing', blockIndex: 0, itemIndex: 0 } } });
check('note-empty-guard', 'empty/whitespace excerpt is refused (no write); an unknown message dataset is refused with the empty hint',
  r7o.opened === true && r7c.saved === false && r7c.reason === 'empty' && before7 === after7 &&
    r7bad.opened === false && r7bad.reason === 'empty' && inst.data.hint === AI.noteDraftEmpty,
  { confirm: r7c, bad: r7bad, bytes_identical: before7 === after7, hint: inst.data.hint });
inst.onDraftCancel();

// h8: cancel closes the draft and writes nothing
const before8 = snapshot('mhp_records_notes');
const r8o = inst.onSaveAsNote(evt(organize.id, 1, 0));
const r8c = inst.onDraftCancel();
check('note-cancel', '取消 closes the draft, clears the form, and writes nothing',
  r8o.opened === true && r8c.cancelled === true && inst.data.draftOpen === false &&
    inst.data.draftForm.name === '' && inst.data.draftForm.excerpt === '' && before8 === snapshot('mhp_records_notes'),
  { cancel: r8c, draft_open: inst.data.draftOpen, bytes_identical: before8 === snapshot('mhp_records_notes') });

// h9: questions import via importMany (mixed new + repeated) with exact QuestionList field set
const r9a = inst.onAddToQuestions(evt(organize.id, 3, 0));
const r9b = inst.onAddToQuestions(evt(organize.id, 3, 1));
const qs2 = rawList('mhp_records_questions');
const qKeysOk = qs2.length === 2 && qs2.every(function (q) { return Object.keys(q).sort().join(',') === QUESTION_KEYS; });
const r9c = inst.onAddToQuestions(evt(consult.id, 4, 0));
const qs3 = rawList('mhp_records_questions');
check('questions-import', '加入待问清单 calls records.questions.importMany {source:ai, group:""}; two new + one more import; exact QuestionList field set',
  r9a.added === 1 && r9a.skipped === 0 && r9b.added === 1 && r9c.added === 1 &&
    qs2.length === 2 && qKeysOk && qs3.length === 3 &&
    qs3.every(function (q) { return q.source === 'ai' && q.group === '' && q.done === false; }),
  { add1: r9a, add2: r9b, add3: r9c, field_keys: qs2.length ? Object.keys(qs2[0]).sort().join(',') : '', stored: qs3.map(function (q) { return q.text; }) });

// h10: all-duplicate questions import -> added 0, visible hint, byte-identical store
const before10 = snapshot('mhp_records_questions');
const r10 = inst.onAddToQuestions(evt(organize.id, 3, 0));
const after10 = snapshot('mhp_records_questions');
const allDupFacts = {
  added: r10.added,
  skipped: r10.skipped,
  hint: inst.data.hint,
  store_bytes_identical: before10 === after10,
};
check('questions-all-dup', 're-adding an existing question returns added 0 with the all-duplicate hint (never silent) and a byte-identical store',
  r10.added === 0 && r10.skipped === 1 && inst.data.hint === QUESTIONS.importAllDup &&
    allDupFacts.store_bytes_identical === true,
  allDupFacts);

// h11: empty questions guard (unknown dataset -> no write, visible hint)
const before11 = snapshot('mhp_records_questions');
const r11 = inst.onAddToQuestions({ currentTarget: { dataset: { messageId: 'missing', blockIndex: 0, itemIndex: 0 } } });
check('questions-empty-guard', 'an unknown message dataset adds nothing and surfaces the empty hint (store unchanged)',
  r11.added === 0 && inst.data.hint === AI.questionAddedEmpty && before11 === snapshot('mhp_records_questions'),
  { returned: r11, hint: inst.data.hint, bytes_identical: before11 === snapshot('mhp_records_questions') });

const failed = cases.filter(function (c) { return !c.pass; }).length;

const failureLines = [];
const flog = makeFlog(failureLines);
flog('T30 AI-result-to-records failure-path evidence (duplicate note refusal + all-duplicate questions import; real page methods)');
flog('command: node tests/e2e/ai-to-records.spec.mjs');
flog('timestamp: ' + new Date().toISOString());
flog('method: REAL pages/ai/ai.ts methods (onSaveAsNote/onDraftInput/onDraftConfirm/onDraftCancel/onAddToQuestions) driven by a node harness; wx = Map-backed shim (storage + toast). Page methods are called with the same dataset shapes the wxml passes (messageId/blockIndex/itemIndex).');
flog('data provenance: REAL = the ai.ts method code path; SYNTHETIC = the seeded AiMessage history (no real patient data, no network).');
flog('scenario: save a note, then attempt to save the same excerpt again');
flog('duplicate_attempted_excerpt: ' + JSON.stringify(dupFacts.attempted_excerpt));
flog('duplicate_returned_reason: ' + JSON.stringify(dupFacts.returned_reason) + ' (expected "duplicate")');
flog('duplicate_draft_hint: ' + JSON.stringify(dupFacts.draft_hint) + ' (expected ' + JSON.stringify(AI.noteDuplicateHint) + ')');
flog('duplicate_page_hint: ' + JSON.stringify(dupFacts.page_hint));
flog('duplicate_store_bytes_identical: ' + dupFacts.store_bytes_identical + ' (zero write)');
flog('duplicate_notes_count: ' + dupFacts.notes_count_before + ' -> ' + dupFacts.notes_count_after + ' (unchanged)');
flog('scenario: re-import an already-listed question via 加入待问清单');
flog('all_dup_added: ' + allDupFacts.added + ', skipped: ' + allDupFacts.skipped);
flog('all_dup_hint: ' + JSON.stringify(allDupFacts.hint) + ' (expected ' + JSON.stringify(QUESTIONS.importAllDup) + ')');
flog('all_dup_store_bytes_identical: ' + allDupFacts.store_bytes_identical);
flog('scenario: empty excerpt guard + unknown message dataset');
flog('empty_guard_reason: ' + JSON.stringify(r7c.reason) + ', bad_dataset_opened: ' + r7bad.opened + ', hint: ' + JSON.stringify(inst.data.hint));
flog('verdict: PASS (duplicates are refused with a visible hint and zero write; questions duplicates surface the all-duplicate hint; nothing is ever silent)');
flog('exit_code_evidence: artifacts/qa/30-failure.txt is written by the passing run (contract: dedupe or explicit hint).');

if (failureOut) writeFileSync(failureOut, failureLines.join('\n') + '\n');

const result = {
  generated_at: new Date().toISOString(),
  ai_ts: aiTs,
  note: 'REAL page methods from pages/ai/ai.ts; wx = Map-backed shim; history is a synthetic seeded AiMessage list',
  scenarios: cases,
  failure_path: {
    lines: failureLines,
    pass: dupFacts.store_bytes_identical === true && dupFacts.returned_reason === 'duplicate' &&
      allDupFacts.added === 0 && allDupFacts.store_bytes_identical === true,
  },
  summary: { total: cases.length, passed: cases.length - failed, failed: failed },
};
writeFileSync(outPath, JSON.stringify(result, null, 2) + '\n');
console.log(JSON.stringify(result, null, 2));
process.exit(failed === 0 ? 0 : 1);
`;

function runLogicHarness() {
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'mhp-ai-to-records-harness-'));
  const harnessPath = path.join(tmpDir, 'ai-to-records-logic.harness.mjs');
  const outPath = path.join(tmpDir, 'ai-to-records-logic.result.json');
  const failurePath = path.join(tmpDir, 'ai-to-records-failure.txt');
  fs.writeFileSync(harnessPath, HARNESS_SOURCE);

  const res = spawnSync(process.execPath, ['--import', 'tsx', harnessPath], {
    cwd: ROOT,
    encoding: 'utf8',
    env: {
      ...process.env,
      MHP_AI_TS: path.join(AI_DIR, 'ai.ts'),
      MHP_MINIAPP_ROOT: MINIAPP_ROOT,
      MHP_HARNESS_OUT: outPath,
      MHP_FAILURE_OUT: failurePath,
    },
    timeout: 90000,
    maxBuffer: 32 * 1024 * 1024,
  });
  const stdout = `${res.stdout || ''}`;
  const stderr = `${res.stderr || ''}`;

  let result = null;
  if (fs.existsSync(outPath)) {
    try {
      result = JSON.parse(fs.readFileSync(outPath, 'utf8'));
    } catch (err) {
      fail(`harness result JSON unparsable: ${err?.message || err}`);
    }
  }
  const failureRaw = fs.existsSync(failurePath) ? fs.readFileSync(failurePath, 'utf8') : '';
  return {
    method: 'node --import tsx <temp harness> (Page-capture + Map wx shim)',
    ai_ts: path.join(AI_DIR, 'ai.ts'),
    exit: res.status,
    stdout_tail: stdout.slice(-8000),
    stderr_tail: stderr.slice(-8000),
    result,
    failure_raw: failureRaw,
  };
}

// ---------------------------------------------------------------------------
// Static invariants (source-level, no runtime claim)
// ---------------------------------------------------------------------------


const FORBIDDEN_STRINGS = [
  'AI 注入',
  'hza_',
  'System Prompt',
  '系统提示词',
  '确诊',
  '诊断结论',
  '处方',
  '疗效保证',
  '急症拦截',
  '自动拨号',
  '预约挂号',
  '挂号成功',
  '候诊叫号',
  '推荐医生',
  '推荐医院',
  '智能分诊',
  'AI 结论',
  '医疗级',
];
const SEVERITY_TOKENS = ['severity', '严重程度', '严重度', '危急程度'];

function staticInvariantChecks() {
  const ts = readSafe(path.join(AI_DIR, 'ai.ts'));
  const wxml = readSafe(path.join(AI_DIR, 'ai.wxml'));
  const wxss = readSafe(path.join(AI_DIR, 'ai.wxss'));
  const json = readSafe(path.join(AI_DIR, 'ai.json'));
  const combined = [ts, wxml, wxss, json].join('\n');
  const copy = aiCopyBlock();

  const forbidden = FORBIDDEN_STRINGS.filter((term) => combined.includes(term));
  const copyForbidden = FORBIDDEN_STRINGS.filter((term) => copy.includes(term));
  const severity = SEVERITY_TOKENS.filter((term) => combined.includes(term));

  const usesNotesAdd = /records\.notes\.add\s*\(/.test(ts);
  const usesNotesList = /records\.notes\.list\s*\(/.test(ts);
  const usesImportMany = /records\.questions\.importMany\s*\(/.test(ts);
  const usesStorageModule = /from '\.\.\/\.\.\/shared\/utils\/storage'/.test(ts) && /storage\.(get|set)\s*\(/.test(ts);
  const directStorage = /wx\.(get|set|remove)StorageInfoSync|wx\.(get|set|remove)StorageSync\s*\(/.test(ts);
  const usesA11y = /A11Y_DATA/.test(ts) && /syncA11y\s*\(/.test(ts);
  const noAny = !/as any/.test(ts) && !/@ts-ignore/.test(ts);
  const noTodo = !/TODO|FIXME/.test(combined);

  const wxmlNoteFlag = /block\.note/.test(wxml);
  const wxmlAskFlag = /block\.ask/.test(wxml);
  const wxmlSaveTap = /bindtap="onSaveAsNote"/.test(wxml);
  const wxmlAskTap = /bindtap="onAddToQuestions"/.test(wxml);
  const wxmlDataset = /data-message-id="\{\{item\.id\}\}"/.test(wxml) && /data-block-index="\{\{bIndex\}\}"/.test(wxml) && /data-item-index="\{\{eIndex\}\}"/.test(wxml);
  const wxmlDraft = /draftForm\.name/.test(wxml) && /draftForm\.excerpt/.test(wxml) && /draftForm\.remark/.test(wxml) &&
    /bindtap="onDraftConfirm"/.test(wxml) && /bindtap="onDraftCancel"/.test(wxml) && /data-field="excerpt"/.test(wxml);

  const copyHasKeys = ['saveAsNote', 'addToQuestions', 'noteDraftTitle', 'noteDraftConfirm', 'noteSavedHint', 'noteDuplicateHint', 'questionAddedPrefix'].every((key) => copy.includes(key));

  let jsonParses = false;
  let jsonTitle = null;
  try {
    const parsed = JSON.parse(json);
    jsonParses = true;
    jsonTitle = parsed.navigationBarTitleText ?? null;
  } catch {
    jsonParses = false;
  }

  const fontLines = wxss.split(/\r?\n/).filter((line) => line.includes('font-size'));
  const fontAllScaled = fontLines.length > 0 && fontLines.every((line) => /calc\([^)]*var\(--mhp-scale\)\)/.test(line));
  const barePx = wxss
    .split(/\r?\n/)
    .filter((line) => /(?<![\dr])\d+px/.test(line))
    .map((line) => line.trim());
  const wxmlScaleInline = /--mhp-scale:\s*\{\{scale\}\}/.test(wxml);
  const wxmlHcClass = /is-hc/.test(wxml);

  return {
    ai_ts_exists: fs.existsSync(path.join(AI_DIR, 'ai.ts')),
    ai_js_exists: fs.existsSync(path.join(AI_DIR, 'ai.js')),
    texts_has_ai_block: copy.length > 0,
    forbidden_strings_present: forbidden,
    ai_copy_forbidden_present: copyForbidden,
    severity_tokens_present: severity,
    uses_notes_add: usesNotesAdd,
    uses_notes_list: usesNotesList,
    uses_import_many: usesImportMany,
    uses_storage_module: usesStorageModule,
    direct_storage_calls: directStorage,
    uses_a11y: usesA11y,
    no_as_any_or_ts_ignore: noAny,
    no_todo_fixme: noTodo,
    wxml_note_flag: wxmlNoteFlag,
    wxml_ask_flag: wxmlAskFlag,
    wxml_save_tap: wxmlSaveTap,
    wxml_ask_tap: wxmlAskTap,
    wxml_dataset: wxmlDataset,
    wxml_draft: wxmlDraft,
    copy_has_new_keys: copyHasKeys,
    json_parses: jsonParses,
    json_title: jsonTitle,
    font_size_lines: fontLines.length,
    font_size_all_scaled: fontAllScaled,
    bare_px_lines: barePx,
    wxml_scale_inline: wxmlScaleInline,
    wxml_hc_class: wxmlHcClass,
  };
}

// ---------------------------------------------------------------------------
// Layer 2: automator helpers
// ---------------------------------------------------------------------------

const captureScreenshot = makeCaptureScreenshot('ai-rec');

async function renderEvidence(miniProgram, tag, route) {
  const stack = await miniProgram.pageStack();
  const top = Array.isArray(stack) && stack.length > 0 ? stack[stack.length - 1] : null;
  const shot = await captureScreenshot(miniProgram, tag);
  return {
    pageStack: stack.length,
    topPath: top ? top.path : null,
    screenshotBytes: shot.bytes,
    screenshotMd5: shot.md5,
    pngMagic: shot.pngMagic,
    ok: stack.length >= 1 && top !== null && top.path === route && shot.pngMagic && shot.bytes > 5000,
  };
}

const STORAGE_KEYS = [
  'records_preferences',
  'records_profile',
  'records_symptoms',
  'records_notes',
  'records_questions',
  'records_memory',
  'ai_messages',
  'ai_consult_ack',
];

async function clearKeys(miniProgram) {
  for (const raw of STORAGE_KEYS) {
    await miniProgram.callWxMethod('removeStorageSync', 'mhp_' + raw);
  }
}

const SEED_PREFERENCES = {
  aiEnabled: true,
  consentVersion: 1,
  fontSize: 14,
  highContrast: false,
  autoMemory: false,
  updatedAt: '2026-09-01T00:00:00.000Z',
};

const SEED_HISTORY = [
  { id: 'aimsg_seed_u1', role: 'user', mode: 'organize', kind: 'text', content: '最近一周头痛，睡不好', memoryDraft: '最近一周头痛，睡不好', blocks: [], disclaimer: '', errorText: '', canLocalOrganize: false, localText: '', createdAt: '2026-09-20T01:00:00.000Z' },
  {
    id: 'aimsg_seed_o1', role: 'assistant', mode: 'organize', kind: 'organize', content: '', memoryDraft: '近一周出现头痛',
    blocks: [
      { type: 'list', title: T.points, items: [{ text: '近一周出现头痛', sub: '', url: '', tag: '' }], note: true },
      { type: 'extracted', title: T.extracted, items: [{ text: '头痛', sub: '', url: '', tag: T.symptoms }], note: true },
      { type: 'list', title: T.unknowns, items: [{ text: '头痛诱因与持续时间未说明', sub: '', url: '', tag: '' }] },
      { type: 'list', title: T.questions, items: [{ text: '头痛从何时开始、多久一次？', sub: '', url: '', tag: '' }, { text: '需要记录哪些伴随症状？', sub: '', url: '', tag: '' }], ask: true },
    ],
    disclaimer: '', errorText: '', canLocalOrganize: false, localText: '', createdAt: '2026-09-20T01:00:01.000Z',
  },
  { id: 'aimsg_seed_u2', role: 'user', mode: 'consult', kind: 'text', content: '最近胃不舒服', memoryDraft: '最近胃不舒服', blocks: [], disclaimer: '', errorText: '', canLocalOrganize: false, localText: '', createdAt: '2026-09-21T01:00:00.000Z' },
  {
    id: 'aimsg_seed_c1', role: 'assistant', mode: 'consult', kind: 'consult', content: '', memoryDraft: '注意休息与规律作息',
    blocks: [
      { type: 'directions', title: T.directions, items: [{ text: '注意休息与规律作息', sub: SRC_SUB, url: SRC_URL, tag: '' }], note: true },
      { type: 'list', title: T.departments, items: [{ text: '全科', sub: '', url: '', tag: '' }] },
      { type: 'citations', title: T.citations, items: [{ text: SRC_TITLE, sub: SRC_DOMAIN, url: SRC_URL, tag: '' }] },
      { type: 'suggestions', title: T.suggestions, items: [{ text: '作息规律、避免熬夜', sub: SRC_SUB, url: SRC_URL, tag: T.nonAdvice }], note: true },
      { type: 'list', title: T.questions, items: [{ text: '需要向医生了解哪些检查或注意事项？', sub: '', url: '', tag: '' }], ask: true },
    ],
    disclaimer: '以上内容仅为信息整理与一般性提示，不构成诊断或治疗建议；如有不适请及时就医。', errorText: '', canLocalOrganize: false, localText: '', createdAt: '2026-09-21T01:00:01.000Z',
  },
];

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  ensureDir(E2E_DIR);
  ensureDir(path.dirname(QA_FAILURE_PATH));
  section('AI TO RECORDS SPEC');

  const logic = runLogicHarness();
  const logicScenarios = logic.result ? logic.result.scenarios : [];
  const logicFailed = logic.result ? logic.result.summary.failed : -1;

  if (logic.failure_raw !== '') {
    fs.writeFileSync(QA_FAILURE_PATH, logic.failure_raw);
    log(`failure evidence: ${QA_FAILURE_PATH}`);
  }

  const report = {
    command: 'E2E_DEVTOOLS_MINIMIZE=1 node tests/e2e/ai-to-records.spec.mjs (cold)',
    timestamp: new Date().toISOString(),
    platform: `${os.platform()} ${os.release()} (${os.arch()})`,
    node_version: process.version,
    project_path: CONFIG.projectPath,
    logic: { method: logic.method, ai_ts: logic.ai_ts, exit: logic.exit, result: logic.result },
    static_invariants: null,
    evaluate_probe: null,
    drive_save: null,
    notes_baseline: null,
    notes_seeded: null,
    questions_baseline: null,
    questions_seeded: null,
    storage_readback: null,
    persistence: null,
    summary: null,
  };

  let allOk = true;

  if (logic.result !== null && logic.exit === 0 && logicFailed === 0) {
    ok(`logic harness: ${logic.result.summary.passed}/${logic.result.summary.total} scenarios passed (real page methods)`);
  } else {
    fail(`logic harness failed (exit=${logic.exit}, failed_scenarios=${logicFailed}); stderr tail: ${logic.stderr_tail}`);
    allOk = false;
  }
  for (const scenario of logicScenarios) {
    log(`  [logic] ${scenario.pass ? 'PASS' : 'FAIL'} ${scenario.id}: ${scenario.name}`);
    if (!scenario.pass) allOk = false;
  }

  const statics = staticInvariantChecks();
  report.static_invariants = statics;
  const staticsOk =
    statics.ai_ts_exists === true &&
    statics.ai_js_exists === false &&
    statics.texts_has_ai_block === true &&
    statics.forbidden_strings_present.length === 0 &&
    statics.ai_copy_forbidden_present.length === 0 &&
    statics.severity_tokens_present.length === 0 &&
    statics.uses_notes_add === true &&
    statics.uses_notes_list === true &&
    statics.uses_import_many === true &&
    statics.uses_storage_module === true &&
    statics.direct_storage_calls === false &&
    statics.uses_a11y === true &&
    statics.no_as_any_or_ts_ignore === true &&
    statics.no_todo_fixme === true &&
    statics.wxml_note_flag === true &&
    statics.wxml_ask_flag === true &&
    statics.wxml_save_tap === true &&
    statics.wxml_ask_tap === true &&
    statics.wxml_dataset === true &&
    statics.wxml_draft === true &&
    statics.copy_has_new_keys === true &&
    statics.json_parses === true &&
    statics.json_title === 'AI 助手' &&
    statics.font_size_all_scaled === true &&
    statics.bare_px_lines.length === 0 &&
    statics.wxml_scale_inline === true &&
    statics.wxml_hc_class === true;
  if (staticsOk) {
    ok('static invariants: records.notes/questions API only; storage module only; scaled px-free wxss; note/ask predicates + draft wired; no forbidden token');
  } else {
    fail(`static invariant failure: ${JSON.stringify(report.static_invariants)}`);
    allOk = false;
  }

  let miniProgram;
  try {
    miniProgram = await launchMiniProgram();
    await clearKeys(miniProgram);

    await miniProgram.callWxMethod('setStorageSync', 'mhp_records_preferences', SEED_PREFERENCES);

    // empty baselines for the two target pages
    await miniProgram.reLaunch('/' + NOTES_ROUTE);
    await delay(800);
    await miniProgram.reLaunch('/' + NOTES_ROUTE);
    await delay(800);
    const notesBaseline = await renderEvidence(miniProgram, 'notes-baseline', NOTES_ROUTE);
    report.notes_baseline = { ...notesBaseline, method: 'reLaunch+pageStack+screenshot' };
    if (notesBaseline.ok) ok(`notes baseline render: top=${notesBaseline.topPath}, md5=${notesBaseline.screenshotMd5}`);
    else {
      fail(`notes baseline render failed: ${JSON.stringify(notesBaseline)}`);
      allOk = false;
    }

    await miniProgram.reLaunch('/' + QUESTIONS_ROUTE);
    await delay(800);
    await miniProgram.reLaunch('/' + QUESTIONS_ROUTE);
    await delay(800);
    const questionsBaseline = await renderEvidence(miniProgram, 'questions-baseline', QUESTIONS_ROUTE);
    report.questions_baseline = { ...questionsBaseline, method: 'reLaunch+pageStack+screenshot' };
    if (questionsBaseline.ok) ok(`questions baseline render: top=${questionsBaseline.topPath}, md5=${questionsBaseline.screenshotMd5}`);
    else {
      fail(`questions baseline render failed: ${JSON.stringify(questionsBaseline)}`);
      allOk = false;
    }

    // seed the synthetic AI history + go to the ai page
    await miniProgram.callWxMethod('setStorageSync', 'mhp_ai_messages', SEED_HISTORY);
    await miniProgram.reLaunch('/' + AI_ROUTE + '?mode=organize');
    await delay(800);
    await miniProgram.reLaunch('/' + AI_ROUTE + '?mode=organize');
    await delay(800);

    const probe = await withTimeout(
      miniProgram.evaluate(() => {
        const pages = getCurrentPages();
        const page = pages[pages.length - 1];
        return {
          route: page.route,
          messages: page.data.messages.length,
          hasSave: typeof page.onSaveAsNote === 'function',
          hasDraftInput: typeof page.onDraftInput === 'function',
          hasDraftConfirm: typeof page.onDraftConfirm === 'function',
          hasDraftCancel: typeof page.onDraftCancel === 'function',
          hasAsk: typeof page.onAddToQuestions === 'function',
        };
      }),
      15000,
      'evaluate-probe'
    );
    if (probe.timedOut === true || probe.error !== undefined) {
      report.evaluate_probe = probe.timedOut ? { ok: false, error: 'timed out' } : { ok: false, error: probe.error };
      fail(`evaluate probe failed: ${JSON.stringify(report.evaluate_probe)}`);
      allOk = false;
    } else {
      report.evaluate_probe = { ok: true, value: probe.value };
      if (probe.value && probe.value.route === AI_ROUTE && probe.value.hasSave === true) {
        ok(`evaluate probe: ${JSON.stringify(probe.value)}`);
      } else {
        fail(`evaluate probe unexpected: ${JSON.stringify(probe.value)}`);
        allOk = false;
      }
    }

    const drive = await withTimeout(
      miniProgram.evaluate(
        (args) => {
          const pages = getCurrentPages();
          const page = pages[pages.length - 1];
          const msgs = page.data.messages;
          const organize = msgs.filter((m) => m.role === 'assistant' && m.mode === 'organize')[0];
          const consult = msgs.filter((m) => m.role === 'assistant' && m.mode === 'consult')[0];
          const findBlock = (msg, type, title) => {
            for (let i = 0; i < msg.blocks.length; i += 1) {
              const b = msg.blocks[i];
              if (b.type === type && b.title === title) return i;
            }
            return -1;
          };
          const ds = (mid, bi, ei) => ({ currentTarget: { dataset: { messageId: mid, blockIndex: bi, itemIndex: ei } } });
          const notesRead = () => wx.getStorageSync('mhp_records_notes');
          const qRead = () => wx.getStorageSync('mhp_records_questions');
          const pIdx = findBlock(organize, 'list', args.titles.points);
          const qIdx = findBlock(organize, 'list', args.titles.questions);
          const dIdx = findBlock(consult, 'directions', args.titles.directions);
          const facts = { route: page.route, indices: { points: pIdx, questions: qIdx, directions: dIdx } };

          const open1 = page.onSaveAsNote(ds(organize.id, pIdx, 0));
          const prefill1 = { name: page.data.draftForm.name, excerpt: page.data.draftForm.excerpt, remark: page.data.draftForm.remark };
          page.onDraftInput({ currentTarget: { dataset: { field: 'excerpt' } }, detail: { value: args.editedExcerpt } });
          const draftEdited = page.data.draftForm.excerpt;
          const confirm1 = page.onDraftConfirm();
          facts.note1 = { open: open1, prefill: prefill1, draftEdited, confirm: confirm1, hint: page.data.hint, notes: notesRead() };

          const open2 = page.onSaveAsNote(ds(consult.id, dIdx, 0));
          const remarkPrefill = page.data.draftForm.remark;
          const confirm2 = page.onDraftConfirm();
          facts.note2 = { open: open2, remarkPrefill, confirm: confirm2, notes: notesRead() };

          const open3 = page.onSaveAsNote(ds(organize.id, pIdx, 0));
          page.onDraftInput({ currentTarget: { dataset: { field: 'excerpt' } }, detail: { value: args.editedExcerpt } });
          const notesBeforeDup = notesRead();
          const confirm3 = page.onDraftConfirm();
          const notesAfterDup = notesRead();
          facts.dup = { open: open3, confirm: confirm3, draftHint: page.data.draftHint, pageHint: page.data.hint, before: notesBeforeDup, after: notesAfterDup };
          page.onDraftCancel();

          const add1 = page.onAddToQuestions(ds(organize.id, qIdx, 0));
          const add2 = page.onAddToQuestions(ds(organize.id, qIdx, 1));
          const hintAfterAdd = page.data.hint;
          const add1Again = page.onAddToQuestions(ds(organize.id, qIdx, 0));
          const hintAfterDup = page.data.hint;
          facts.questions = { add1, add2, add1Again, hintAfterAdd, hintAfterDup, stored: qRead() };
          facts.safety = { fixed: page.data.safetyFixed !== '', notDiagnosis: page.data.notDiagnosis !== '' };
          return facts;
        },
        { titles: { points: T.points, questions: T.questions, directions: T.directions }, editedExcerpt: EDITED_EXCERPT }
      ),
      20000,
      'evaluate-save'
    );

    if (drive.timedOut === true || drive.error !== undefined) {
      report.drive_save = drive.timedOut ? { error: 'timed out' } : { error: drive.error };
      fail(`save drive failed: ${JSON.stringify(report.drive_save)}`);
      allOk = false;
    } else {
      const d = drive.value;
      report.drive_save = d;
      const notes1 = Array.isArray(d.note1 && d.note1.notes) ? d.note1.notes : [];
      const notes2 = Array.isArray(d.note2 && d.note2.notes) ? d.note2.notes : [];
      const qs = Array.isArray(d.questions && d.questions.stored) ? d.questions.stored : [];
      const n0 = notes1[0];
      const d0 = notes2[1];
      const noteKeysOk = n0 !== undefined && Object.keys(n0).sort().join(',') === NOTE_KEYS;
      const qKeysOk = qs.length > 0 && qs.every((q) => Object.keys(q).sort().join(',') === QUESTION_KEYS);
      const dupZeroWrite = JSON.stringify(d.dup && d.dup.before) === JSON.stringify(d.dup && d.dup.after);
      const saveOk =
        d.route === AI_ROUTE && d.indices.points >= 0 && d.indices.questions >= 0 && d.indices.directions >= 0 &&
        d.note1.open.opened === true && d.note1.prefill.name === T.points && d.note1.prefill.excerpt === '近一周出现头痛' &&
        d.note1.draftEdited === EDITED_EXCERPT && d.note1.confirm.saved === true && d.note1.hint === NOTE_SAVED_HINT &&
        notes1.length === 1 && noteKeysOk && n0.excerpt === EDITED_EXCERPT && n0.name === T.points &&
        n0.sourceDate === '' && n0.attachment === null && n0.remark === '' &&
        d.note2.open.opened === true && d.note2.confirm.saved === true && notes2.length === 2 &&
        d0 !== undefined && d0.excerpt === '注意休息与规律作息' &&
        d0.remark.indexOf(SRC_TITLE) !== -1 && d0.remark.indexOf(SRC_DOMAIN) !== -1 && d0.remark.indexOf(SRC_URL) !== -1 &&
        d.dup.confirm.saved === false && d.dup.confirm.reason === 'duplicate' &&
        d.dup.draftHint === NOTE_DUPLICATE_HINT && dupZeroWrite && notes2.length === 2 &&
        d.questions.add1.added === 1 && d.questions.add2.added === 1 && d.questions.add1Again.added === 0 &&
        d.questions.hintAfterDup === QUESTIONS_ALL_DUP &&
        qs.length === 2 && qKeysOk && qs.every((q) => q.source === 'ai' && q.group === '' && q.done === false) &&
        d.safety.fixed === true && d.safety.notDiagnosis === true;
      if (saveOk) {
        ok(`save drive: note1 excerpt=${JSON.stringify(n0.excerpt)}, note2 source persisted, dup refused (zero write), questions=${qs.length}`);
      } else {
        fail(`save drive unexpected: ${JSON.stringify({ dup: d.dup && { confirm: d.dup.confirm, hint: d.dup.draftHint }, note1: d.note1 && d.note1.confirm, questions: d.questions && { add1: d.questions.add1, add1Again: d.questions.add1Again }, qs: qs.length })}`);
        allOk = false;
      }
      report.storage_readback = {
        notes_key: 'mhp_records_notes',
        notes: notes2,
        questions_key: 'mhp_records_questions',
        questions: qs,
      };
      report.notes_expected = notes2;
      report.questions_expected = qs;
    }

    // notes page render changed vs empty baseline
    await miniProgram.reLaunch('/' + NOTES_ROUTE);
    await delay(800);
    const notesSeeded = await renderEvidence(miniProgram, 'notes-seeded', NOTES_ROUTE);
    report.notes_seeded = { ...notesSeeded, changed_vs_baseline_md5: notesSeeded.screenshotMd5 !== notesBaseline.screenshotMd5 };
    if (notesSeeded.ok && report.notes_seeded.changed_vs_baseline_md5) {
      ok(`notes render changed after the AI save (md5 ${notesBaseline.screenshotMd5} -> ${notesSeeded.screenshotMd5})`);
    } else {
      fail(`notes render did not change: ${JSON.stringify(report.notes_seeded)}`);
      allOk = false;
    }

    await miniProgram.reLaunch('/' + QUESTIONS_ROUTE);
    await delay(800);
    const questionsSeeded = await renderEvidence(miniProgram, 'questions-seeded', QUESTIONS_ROUTE);
    report.questions_seeded = { ...questionsSeeded, changed_vs_baseline_md5: questionsSeeded.screenshotMd5 !== questionsBaseline.screenshotMd5 };
    if (questionsSeeded.ok && report.questions_seeded.changed_vs_baseline_md5) {
      ok(`questions render changed after the AI import (md5 ${questionsBaseline.screenshotMd5} -> ${questionsSeeded.screenshotMd5})`);
    } else {
      fail(`questions render did not change: ${JSON.stringify(report.questions_seeded)}`);
      allOk = false;
    }

    // close + relaunch persistence
    try {
      await withTimeout(miniProgram.close(), 8000, 'close');
      miniProgram = null;
    } catch (err) {
      log(`warning: close failed: ${err?.message || err}`);
    }
    await delay(2000);
    miniProgram = await launchMiniProgram();
    const notesAfter = await withTimeout(miniProgram.callWxMethod('getStorageSync', 'mhp_records_notes'), 10000, 'readback-notes');
    const questionsAfter = await withTimeout(miniProgram.callWxMethod('getStorageSync', 'mhp_records_questions'), 10000, 'readback-questions');
    if (notesAfter.timedOut === true || notesAfter.error !== undefined || questionsAfter.timedOut === true || questionsAfter.error !== undefined) {
      report.persistence = { error: 'read-back failed' };
      fail('relaunch persistence read-back failed');
      allOk = false;
    } else {
      const notesMatch = JSON.stringify(notesAfter.value) === JSON.stringify(report.notes_expected);
      const questionsMatch = JSON.stringify(questionsAfter.value) === JSON.stringify(report.questions_expected);
      report.persistence = {
        notes_key: 'mhp_records_notes',
        notes_count: Array.isArray(notesAfter.value) ? notesAfter.value.length : -1,
        notes_match: notesMatch,
        questions_key: 'mhp_records_questions',
        questions_count: Array.isArray(questionsAfter.value) ? questionsAfter.value.length : -1,
        questions_match: questionsMatch,
        persisted_after_relaunch: notesMatch && questionsMatch,
      };
      if (report.persistence.persisted_after_relaunch) {
        ok(`saved records persist across close+relaunch (notes=${report.persistence.notes_count}, questions=${report.persistence.questions_count})`);
      } else {
        fail(`saved records did not persist: ${JSON.stringify(report.persistence)}`);
        allOk = false;
      }
    }

    await withTimeout(clearKeys(miniProgram), 10000, 'clear-keys');
  } catch (err) {
    fail(`ai-to-records spec run error: ${err?.stack || err}`);
    report.error = err?.message || String(err);
    allOk = false;
  } finally {
    if (miniProgram) {
      const raced = await withTimeout(miniProgram.close(), 8000, 'close');
      if (raced.timedOut === true) log('warning: miniProgram.close() timed out');
      else if (raced.error !== undefined) log(`warning: miniProgram.close() failed: ${raced.error}`);
      else log('miniProgram.close() done');
      try {
        miniProgram.disconnect();
      } catch {
        /* socket already closed */
      }
    }
  }

  const checks = {
    logic_harness_ok: logic.result !== null && logic.exit === 0 && logicFailed === 0,
    static_invariants_ok: staticsOk,
    evaluate_probe_ok: Boolean(report.evaluate_probe && report.evaluate_probe.ok === true && report.evaluate_probe.value && report.evaluate_probe.value.route === AI_ROUTE),
    save_drive_ok: Boolean(report.drive_save && report.drive_save.note1 && report.drive_save.note1.confirm.saved === true && report.drive_save.note2 && report.drive_save.note2.confirm.saved === true && report.drive_save.dup && report.drive_save.dup.confirm.saved === false && JSON.stringify(report.drive_save.dup.before) === JSON.stringify(report.drive_save.dup.after) && report.drive_save.questions && report.drive_save.questions.add1Again.added === 0),
    notes_render_changed: Boolean(report.notes_seeded && report.notes_seeded.changed_vs_baseline_md5 === true),
    questions_render_changed: Boolean(report.questions_seeded && report.questions_seeded.changed_vs_baseline_md5 === true),
    persistence_ok: Boolean(report.persistence && report.persistence.persisted_after_relaunch === true),
    no_forbidden_strings: statics.forbidden_strings_present.length === 0 && statics.ai_copy_forbidden_present.length === 0,
    no_severity_token: statics.severity_tokens_present.length === 0,
    no_any_or_todo: statics.no_as_any_or_ts_ignore === true && statics.no_todo_fixme === true,
    font_scaled: statics.font_size_all_scaled === true && statics.bare_px_lines.length === 0,
    json_ok: statics.json_parses === true && statics.json_title === 'AI 助手',
  };
  const checksPassed = Object.values(checks).every((v) => v === true);
  log(`summary checks: ${JSON.stringify(checks)}`);

  report.summary = {
    ...checks,
    logic_scenarios_total: logic.result ? logic.result.summary.total : 0,
    logic_scenarios_passed: logic.result ? logic.result.summary.passed : 0,
    passed: checksPassed && allOk === true,
    failed: !(checksPassed && allOk === true),
  };

  const reportPath = path.join(E2E_DIR, 'ai-to-records.json');
  fs.writeFileSync(reportPath, JSON.stringify(report, null, 2) + '\n');
  log(`ai-to-records evidence: ${reportPath}`);

  return report.summary.passed;
}

main().then(
  (passed) => {
    process.exit(passed ? 0 : 1);
  },
  (err) => {
    console.error(`[e2e] FAIL ${err?.stack || err}`);
    process.exit(1);
  }
);
