// ai.spec.mjs — task 33: AI page E2E matrix (mock upstream + full stack).
//
// Run: node tests/e2e/ai.spec.mjs
//      E2E_DEVTOOLS_MINIMIZE=1 node tests/e2e/ai.spec.mjs   (cold, hidden)
// Evidence: artifacts/e2e/ai-matrix.json
//           artifacts/qa/33-failure.txt   (broken-upstream degradation transcript)
//
// Full-stack honesty: the miniapp talks to the REAL local server on 127.0.0.1:8787
// (`node server/index.ts`, demo=false) which runs the REAL orchestrator (red-flag
// detection, output validation/interception, citation allow-listing, memory
// injection, memory extraction). ONLY the LLM/search upstream is faked by
// `server/mock-upstream.mjs` (task 26). Nothing about the success path is stubbed.
//
// Matrix coverage (runtime, via miniProgram.evaluate driving the REAL page):
//   - dual mode (organize + consult) with preview-before-send
//   - citations rendered with allow-listed domains/links
//   - consult first-use consent (modal; cancel -> no send; confirm -> ack persisted)
//   - >=5 red-flag inputs -> the server's fixed safety-notice sentence ONLY
//   - "找哪个医生" -> no specific-doctor / referral content can render
//   - consult always carries the 「日常建议」 block with per-item citations
//   - boundary inputs (empty / whitespace / long)
//   - clear state -> relaunch -> consistent empty state
//   - memory: enabled appears in preview AND payload; disabled/deleted not sent;
//     auto-extract adds a candidate then dedupes; autoMemory off -> zero extract calls
//   - mock adversarial (MOCK_ADVERSARIAL=1): a banned-word consult answer is
//     intercepted by the server validator and never rendered
//   - degradation: broken upstream (LLM dead) and broken proxy (server dead)
//
// Fixed strings (SAFETY_NOTICE / disclaimer / controlled departments / copy) are
// imported from their single sources via a one-shot tsx harness — never eyeballed.
import { spawn, spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {
  CONFIG,
  E2E_ARTIFACTS,
  ROOT,
  ensureDir,
  fail,
  launchMiniProgram,
  log,
  ok,
  section,
  tcpProbe,
  delay,
  md5,
  withTimeout,
  hasPngMagic,
  waitForHealth,
} from './helpers.mjs';

const AI_ROUTE = 'pages/ai/ai';
const MINIAPP_ROOT = CONFIG.projectPath;
const MOCK_SCRIPT = path.join(ROOT, 'server', 'mock-upstream.mjs');
const SERVER_ENTRY = 'server/index.ts';
const PROXY_URL = 'http://127.0.0.1:8787';
const PROXY_PORT = 8787;
const AUTOMATION_PORT = CONFIG.port;

const E2E_DIR = E2E_ARTIFACTS;
const QA_FAILURE_PATH = path.join(ROOT, 'artifacts', 'qa', '33-failure.txt');
const MATRIX_PATH = path.join(E2E_DIR, 'ai-matrix.json');

const AUTHORITY_DOMAINS = ['nhc.gov.cn', 'chinacdc.cn'];


const STORAGE_KEYS = [
  'records_preferences',
  'records_profile',
  'records_symptoms',
  'records_notes',
  'records_questions',
  'records_memory',
  'ai_messages',
  'ai_consult_ack',
];

// Red-flag inputs chosen to hit distinct `server/redflags.ts` rules:
// 胸痛 / 呼吸困难 / 晕厥 / 大出血 / 中风征象 / 剧烈头痛 / 一侧无力.
const RED_FLAG_INPUTS = ['胸痛', '呼吸困难', '晕厥', '大出血', '中风征象', '剧烈头痛', '一侧无力'];

// ---------------------------------------------------------------------------
// Fixed-string harness (single source: server/*.ts + config/texts.ts)
// ---------------------------------------------------------------------------

const SOURCES_HARNESS = String.raw`// temp fixed-string harness (run via tsx); not committed — generated by ai.spec.mjs
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

const root = process.env.MHP_ROOT;
const out = process.env.MHP_SOURCES_OUT;
if (!root || !out) throw new Error('missing harness env');

const redflags = await import(pathToFileURL(path.join(root, 'server/redflags.ts')).href);
const prompts = await import(pathToFileURL(path.join(root, 'server/prompts.ts')).href);
const validate = await import(pathToFileURL(path.join(root, 'server/validate.ts')).href);
const texts = await import(pathToFileURL(path.join(root, 'hospital-ai-miniapp/config/texts.ts')).href);

const src = { title: 'mock source', url: 'https://nhc.gov.cn/health/mock-1', snippet: '', domain: 'nhc.gov.cn' };
const opts = { sources: [src], authorityDomains: ['nhc.gov.cn'] };

// Referral guard seam: a direction naming a specific clinician must be rejected.
const referral = validate.validateConsultOutput({
  directions: [{ text: '建议找张医生看看', citation: src.url }],
  suggestedDepartments: ['全科'], suggestions: [], unknowns: [], questions: [],
}, opts);
// Suggestion guard seam: a dose/self-medication phrasing must be rejected.
const dose = validate.validateConsultOutput({
  directions: [{ text: '注意休息与规律作息', citation: src.url }],
  suggestedDepartments: ['全科'],
  suggestions: [{ text: '按说明书剂量使用', citation: src.url }],
  unknowns: [], questions: [],
}, opts);
// Control: a valid consult payload must be accepted.
const valid = validate.validateConsultOutput({
  directions: [{ text: '注意休息与规律作息', citation: src.url }],
  suggestedDepartments: ['全科'],
  suggestions: [{ text: '作息规律避免熬夜', citation: src.url }],
  unknowns: [], questions: [],
}, opts);

const payload = {
  safetyNotice: redflags.SAFETY_NOTICE,
  redFlagTerms: redflags.RED_FLAG_TERMS,
  consultDisclaimer: prompts.CONSULT_DISCLAIMER,
  controlledDepartments: prompts.CONTROLLED_DEPARTMENTS,
  decisionTerms: validate.DECISION_TERMS,
  referralTerms: validate.REFERRAL_TERMS,
  emergencyCue: validate.hasEmergencyCue(redflags.SAFETY_NOTICE),
  aiCopy: texts.AI,
  degraded: texts.DEGRADED,
  safety: texts.SAFETY,
  disclaimers: texts.DISCLAIMERS,
  demo: texts.DEMO,
  privacy: texts.PRIVACY,
  autoExtractNotice: texts.AUTO_EXTRACT_NOTICE,
  guards: {
    referral_rejected: referral.ok === false,
    dose_rejected: dose.ok === false,
    valid_accepted: valid.ok === true,
  },
};
writeFileSync(out, JSON.stringify(payload, null, 2));
`;

function runSourcesHarness() {
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'mhp-ai-sources-'));
  const harnessPath = path.join(tmpDir, 'sources.harness.mjs');
  const outPath = path.join(tmpDir, 'sources.json');
  fs.writeFileSync(harnessPath, SOURCES_HARNESS);
  const res = spawnSync(process.execPath, ['--import', 'tsx', harnessPath], {
    cwd: ROOT,
    encoding: 'utf8',
    env: { ...process.env, MHP_ROOT: ROOT, MHP_SOURCES_OUT: outPath },
    timeout: 90000,
    maxBuffer: 16 * 1024 * 1024,
  });
  let parsed = null;
  if (fs.existsSync(outPath)) {
    try {
      parsed = JSON.parse(fs.readFileSync(outPath, 'utf8'));
    } catch (err) {
      fail(`sources harness JSON unparsable: ${err?.message || err}`);
    }
  }
  return { exit: res.status, stderr: `${res.stderr || ''}`.slice(-4000), sources: parsed };
}

// ---------------------------------------------------------------------------
// Page-side evaluate functions (serialized into the runtime; no outer refs)
// ---------------------------------------------------------------------------

function pageProbe() {
  const pages = getCurrentPages();
  const page = pages[pages.length - 1];
  return {
    route: page.route,
    mode: page.data.mode,
    hasMessages: page.data.hasMessages,
    messageCount: page.data.messages.length,
    memoryCount: page.data.memoryCount,
    candidateCount: page.data.candidateCount,
    hasConfirm: typeof page.onConfirmSend,
    hasSetMode: typeof page.setMode,
    aiStatus: page.data.aiStatus,
    safetyFixed: page.data.safetyFixed,
    notDiagnosis: page.data.notDiagnosis,
  };
}

function pageConsent(args) {
  const pages = getCurrentPages();
  const page = pages[pages.length - 1];
  const origModal = wx.showModal;
  const origReq = wx.request;
  const modals = [];
  let req = 0;
  wx.showModal = function (o) {
    modals.push({ title: o && o.title, content: o && o.content, confirmText: o && o.confirmText, cancelText: o && o.cancelText });
    if (o && typeof o.success === 'function') o.success({ confirm: args.confirm === true, cancel: args.confirm !== true });
  };
  wx.request = function (o) { req += 1; return origReq.call(wx, o); };
  let switched = null;
  let err = '';
  return Promise.resolve()
    .then(function () { return page.setMode('consult'); })
    .then(function (v) { switched = v; })
    .catch(function (e) { err = String((e && e.message) || e); })
    .then(function () {
      wx.showModal = origModal;
      wx.request = origReq;
      return {
        switched: switched,
        mode: page.data.mode,
        hasConsent: page.hasConsultConsent(),
        ack: wx.getStorageSync('mhp_ai_consult_ack') === true,
        modals: modals,
        requests: req,
        error: err,
      };
    });
}

function pageDrive(args) {
  const pages = getCurrentPages();
  const page = pages[pages.length - 1];
  const origReq = wx.request;
  const origModal = wx.showModal;
  const askBodies = [];
  const modals = [];
  let extractCount = 0;
  wx.request = function (options) {
    const url = String((options && options.url) || '');
    if (url.indexOf('/api/extract-memory') !== -1) extractCount += 1;
    else if (url.indexOf('/api/ask') !== -1) {
      // The evaluate sandbox JSON.parse throws a realm/instanceof error, so capture the raw
      // request string here and parse it back in Node.
      try { askBodies.push(typeof options.data === 'string' ? options.data : ''); } catch (e) { askBodies.push(''); }
    }
    return origReq.call(wx, options);
  };
  wx.showModal = function (o) {
    modals.push({ title: o && o.title });
    if (o && typeof o.success === 'function') o.success({ confirm: args.confirmConsent !== false, cancel: args.confirmConsent === false });
  };
  async function run() {
    const out = { switched: null, modals: modals };
    try {
      page.loadAll();
      if (args.mode && page.data.mode !== args.mode) out.switched = await page.setMode(args.mode);
      if (args.includeProfile === true && page.data.profileAvailable === true && page.data.includeProfile !== true) page.onToggleProfile();
      page.onInput({ detail: { value: args.text } });
      const send = await page.onSend();
      out.send = { reason: send && send.reason, sent: send && send.sent };
      const sections = page.data.previewSections || [];
      out.preview = {
        open: page.data.previewOpen,
        titles: sections.map(function (s) { return s.title; }),
        memoryText: (sections.filter(function (s) { return s.key === 'memories'; })[0] || {}).text || '',
        excerptText: (sections.filter(function (s) { return s.key === 'recordExcerpts'; })[0] || {}).text || '',
      };
      const confirmed = await page.onConfirmSend();
      const msgs = page.data.messages || [];
      const last = msgs[msgs.length - 1];
      out.confirmed = confirmed;
      out.messageCount = msgs.length;
      out.last = last ? {
        kind: last.kind,
        mode: last.mode,
        disclaimer: last.disclaimer,
        errorText: last.errorText,
        canLocalOrganize: last.canLocalOrganize,
        localText: last.localText,
        content: last.content,
        blocks: last.blocks.map(function (b) {
          return {
            type: b.type,
            title: b.title,
            items: b.items.map(function (it) { return { text: it.text, sub: it.sub, url: it.url, tag: it.tag }; }),
          };
        }),
      } : null;
      out.status = page.data.aiStatus;
      out.memoryCount = page.data.memoryCount;
      out.memoryLabel = page.data.memoryLabel;
      out.autoMemoryAdded = page.data.autoMemoryAdded;
      out.autoMemoryHint = page.data.autoMemoryHint;
      out.input = page.data.input;
      out.hint = page.data.hint;
      out.extractCount = extractCount;
      out.askBodiesRaw = askBodies;
    } finally {
      wx.request = origReq;
      wx.showModal = origModal;
    }
    return out;
  }
  return run();
}

function pageRedflags(args) {
  const pages = getCurrentPages();
  const page = pages[pages.length - 1];
  const out = [];
  const origModal = wx.showModal;
  wx.showModal = function (o) { if (o && typeof o.success === 'function') o.success({ confirm: true, cancel: false }); };
  async function loop() {
    try {
      for (let i = 0; i < args.terms.length; i += 1) {
        const term = args.terms[i];
        if (page.data.mode !== 'organize') { try { await page.setMode('organize'); } catch (e) {} }
        page.onInput({ detail: { value: term } });
        await page.onSend();
        const confirmed = await page.onConfirmSend();
        const msgs = page.data.messages || [];
        const last = msgs[msgs.length - 1];
        out.push({
          term: term,
          confirmedKind: confirmed && confirmed.kind,
          kind: last ? last.kind : '',
          disclaimer: last ? last.disclaimer : '',
          blockCount: last ? last.blocks.length : -1,
          blockTypes: last ? last.blocks.map(function (b) { return b.type; }) : [],
          blockTitles: last ? last.blocks.map(function (b) { return b.title; }) : [],
          noticeText: last && last.blocks[0] && last.blocks[0].items[0] ? last.blocks[0].items[0].text : '',
        });
      }
    } finally {
      wx.showModal = origModal;
    }
    return out;
  }
  return loop();
}

function pageClearAll(args) {
  const keys = args.keys || [];
  for (let i = 0; i < keys.length; i += 1) { try { wx.removeStorageSync(keys[i]); } catch (e) {} }
  return { cleared: keys.length };
}

function pageReadState() {
  const pages = getCurrentPages();
  const page = pages[pages.length - 1];
  return {
    route: page.route,
    mode: page.data.mode,
    hasMessages: page.data.hasMessages,
    messageCount: page.data.messages.length,
    memoryCount: page.data.memoryCount,
    candidateCount: page.data.candidateCount,
    hasConsent: page.hasConsultConsent(),
    ack: wx.getStorageSync('mhp_ai_consult_ack') === true,
    aiStatus: page.data.aiStatus,
  };
}

// ---------------------------------------------------------------------------
// Seed data
// ---------------------------------------------------------------------------

const SEED_PREFERENCES = {
  aiEnabled: true,
  consentVersion: 1,
  fontSize: 14,
  highContrast: false,
  autoMemory: true,
  demoMode: false,
  updatedAt: '2026-09-01T00:00:00.000Z',
};
const SEED_PROFILE = [
  {
    id: 'prof_seed_1',
    createdAt: '2026-08-01T01:00:00.000Z',
    updatedAt: '2026-08-01T01:00:00.000Z',
    name: '张三',
    ageRange: '60-69',
    gender: '',
    allergies: '青霉素',
    medications: '降压药',
    history: '',
  },
];
const SEED_SYMPTOMS = [
  {
    id: 'sym_seed_1',
    createdAt: '2026-09-01T01:00:00.000Z',
    updatedAt: '2026-09-01T01:00:00.000Z',
    occurredAt: '2026-09-10T02:00:00.000Z',
    duration: '3 天',
    text: '饭后有点胀',
    impact: '没影响睡眠',
    tags: ['饭后'],
    attachment: null,
  },
];
const SEED_NOTES = [
  {
    id: 'note_seed_1',
    createdAt: '2026-09-03T01:00:00.000Z',
    updatedAt: '2026-09-03T01:00:00.000Z',
    name: '体检报告',
    excerpt: '甘油三酯 2.1',
    sourceDate: '2026-08-20',
    attachment: null,
    remark: '',
  },
];
const SEED_QUESTIONS = [
  {
    id: 'ques_seed_1',
    createdAt: '2026-09-04T01:00:00.000Z',
    updatedAt: '2026-09-04T01:00:00.000Z',
    text: '复查时间怎么安排',
    done: false,
    group: '复查',
    source: 'manual',
  },
];
const SEED_MEMORY = [
  {
    id: 'mem_seed_1',
    createdAt: '2026-09-05T01:00:00.000Z',
    updatedAt: '2026-09-05T01:00:00.000Z',
    text: '希望回复更简短',
    source: 'manual',
    enabled: true,
  },
];

// ---------------------------------------------------------------------------
// Small async / process helpers
// ---------------------------------------------------------------------------

let miniProgram = null;

async function evalPage(fn, arg, label, timeoutMs = 30000) {
  const raced = await withTimeout(miniProgram.evaluate(fn, arg), timeoutMs, label);
  if (raced.timedOut === true) {
    fail(`evaluate ${label} timed out`);
    return { __error: 'timed out' };
  }
  if (raced.error !== undefined) {
    fail(`evaluate ${label} failed: ${raced.error}`);
    return { __error: raced.error };
  }
  return raced.value;
}

/** Parse the raw /api/ask request strings captured in the runtime (Node side, where JSON works). */
function parseAskBodies(rawList) {
  if (!Array.isArray(rawList)) return [];
  return rawList.map((raw) => {
    let b = {};
    try {
      b = JSON.parse(String(raw));
    } catch {
      b = {};
    }
    if (b === null || typeof b !== 'object') b = {};
    return {
      mode: b.mode,
      memories: b.memories === undefined ? null : b.memories,
      hasProfile: b.profileSummary !== undefined,
      excerpts: Array.isArray(b.recordExcerpts) ? b.recordExcerpts : null,
      userTexts: Array.isArray(b.messages)
        ? b.messages.filter((m) => m.role === 'user').map((m) => m.content)
        : [],
      raw: typeof raw === 'string' ? raw : '',
    };
  });
}

/** Drive one send through the real page and parse the captured request bodies. */
async function drivePage(args, label, timeoutMs) {
  const d = await evalPage(pageDrive, args, label, timeoutMs);
  if (d && d.__error === undefined) d.askBodies = parseAskBodies(d.askBodiesRaw);
  return d;
}

async function relaunchAi() {
  await withTimeout(miniProgram.reLaunch('/' + AI_ROUTE + '?mode=organize'), 20000, 'reLaunch-1');
  await delay(800);
  await withTimeout(miniProgram.reLaunch('/' + AI_ROUTE + '?mode=organize'), 20000, 'reLaunch-2');
  await delay(800);
}

async function seedStorage(prefs, memory, ack) {
  await withTimeout(
    (async () => {
      for (const raw of STORAGE_KEYS) await miniProgram.callWxMethod('removeStorageSync', 'mhp_' + raw);
      await miniProgram.callWxMethod('setStorageSync', 'mhp_records_preferences', prefs);
      await miniProgram.callWxMethod('setStorageSync', 'mhp_records_profile', SEED_PROFILE);
      await miniProgram.callWxMethod('setStorageSync', 'mhp_records_symptoms', SEED_SYMPTOMS);
      await miniProgram.callWxMethod('setStorageSync', 'mhp_records_notes', SEED_NOTES);
      await miniProgram.callWxMethod('setStorageSync', 'mhp_records_questions', SEED_QUESTIONS);
      await miniProgram.callWxMethod('setStorageSync', 'mhp_records_memory', memory);
      if (ack === true) await miniProgram.callWxMethod('setStorageSync', 'mhp_ai_consult_ack', true);
    })(),
    20000,
    'seed'
  );
}

async function readStored(key) {
  const raced = await withTimeout(miniProgram.callWxMethod('getStorageSync', 'mhp_' + key), 10000, `read-${key}`);
  if (raced.timedOut === true || raced.error !== undefined) return { __error: raced.timedOut ? 'timed out' : raced.error };
  return raced.value;
}

async function captureRender(tag) {
  const shotPath = path.join(os.tmpdir(), `mhp-ai33-${tag}-${Date.now()}.png`);
  await miniProgram.screenshot({ path: shotPath });
  const shot = fs.readFileSync(shotPath);
  fs.unlinkSync(shotPath);
  const stack = await miniProgram.pageStack();
  const top = Array.isArray(stack) && stack.length > 0 ? stack[stack.length - 1] : null;
  return {
    topPath: top ? top.path : null,
    pageStack: stack.length,
    bytes: shot.length,
    md5: md5(shot),
    pngMagic: hasPngMagic(shot),
  };
}

// ---------------------------------------------------------------------------
// Upstream / proxy lifecycle
// ---------------------------------------------------------------------------

function startMock({ adversarial }) {
  return new Promise((resolve, reject) => {
    const env = { ...process.env };
    delete env.MOCK_PORT;
    delete env.PORT;
    if (adversarial === true) env.MOCK_ADVERSARIAL = '1';
    else delete env.MOCK_ADVERSARIAL;
    const child = spawn('node', [MOCK_SCRIPT], { cwd: ROOT, env, stdio: ['ignore', 'pipe', 'pipe'] });
    let out = '';
    let err = '';
    let settled = false;
    const timer = setTimeout(() => {
      if (settled) return;
      settled = true;
      try { child.kill('SIGKILL'); } catch { /* ignore */ }
      reject(new Error(`mock-upstream start timed out; stderr=${err.slice(-500)}`));
    }, 12000);
    child.stdout.on('data', (d) => {
      out += d.toString();
      const match = /listening on (http:\/\/127\.0\.0\.1:\d+)/.exec(out);
      if (match !== null && settled === false) {
        settled = true;
        clearTimeout(timer);
        resolve({ child, url: match[1], stdout: out, adversarial: adversarial === true });
      }
    });
    child.stderr.on('data', (d) => { err += d.toString(); });
    child.on('exit', (code) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      reject(new Error(`mock-upstream exited early (code=${code}); stderr=${err.slice(-500)}`));
    });
  });
}

function startServer(baseUrl) {
  const configPath = path.join(os.tmpdir(), `mhp-t33-config-${process.pid}-${Date.now()}-${Math.random().toString(16).slice(2)}.json`);
  fs.writeFileSync(
    configPath,
    `${JSON.stringify(
      {
        port: PROXY_PORT,
        demo: false,
        llm: { baseUrl, apiKey: 'test-key', model: 'mock-model' },
        search: { baseUrl, apiKey: 'test-key' },
        authorityDomains: AUTHORITY_DOMAINS,
      },
      null,
      2
    )}\n`
  );
  const child = spawn('node', [SERVER_ENTRY], {
    cwd: ROOT,
    env: { ...process.env, MHP_CONFIG_PATH: configPath },
    stdio: ['ignore', 'pipe', 'pipe'],
  });
  let stdout = '';
  child.stdout.on('data', (d) => { stdout += d.toString(); });
  child.stderr.on('data', () => { /* key-free; ignore */ });
  return { child, configPath, stdoutRef: () => stdout };
}


async function stopChild(child) {
  if (child === null || child === undefined) return;
  if (child.exitCode === null && child.signalCode === null) {
    child.kill('SIGTERM');
    const deadline = Date.now() + 3000;
    while (child.exitCode === null && child.signalCode === null && Date.now() < deadline) await delay(100);
    if (child.exitCode === null && child.signalCode === null) child.kill('SIGKILL');
  }
}

async function stopServer(srv) {
  if (srv === null || srv === undefined) return;
  await stopChild(srv.child);
  try {
    fs.rmSync(srv.configPath, { force: true });
  } catch {
    /* ignore */
  }
}

async function postJson(url, body) {
  const res = await fetch(url, {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify(body),
  });
  let data = null;
  try {
    data = await res.json();
  } catch {
    data = null;
  }
  return { status: res.status, data };
}

function probePortFree(port) {
  return spawnSync('lsof', ['-nP', `-iTCP:${port}`, '-sTCP:LISTEN'], { encoding: 'utf8' }).stdout.trim() === '';
}

function hostOf(url) {
  try {
    return new URL(url).hostname.toLowerCase();
  } catch {
    return '';
  }
}

function isAllowlisted(host, domains) {
  return domains.some((d) => host === d || host.endsWith('.' + d));
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  ensureDir(E2E_DIR);
  ensureDir(path.dirname(QA_FAILURE_PATH));
  section('AI MATRIX SPEC (full stack: mock upstream + real server)');

  const startedAt = Date.now();
  const checks = {};
  const failures = [];
  const record = (name, pass, details) => {
    checks[name] = pass === true;
    if (pass !== true) failures.push({ name, details: details ?? null });
    return pass === true;
  };

  const report = {
    command: 'E2E_DEVTOOLS_MINIMIZE=1 node tests/e2e/ai.spec.mjs (cold, hidden)',
    generated_at: new Date().toISOString(),
    platform: `${os.platform()} ${os.release()} (${os.arch()})`,
    node_version: process.version,
    project_path: CONFIG.projectPath,
    authority_domains: AUTHORITY_DOMAINS,
    fixed_strings: null,
    proxy: null,
    phase1: null,
    phase2_adversarial: null,
    phase3_llm_broken: null,
    phase4_proxy_broken: null,
    render: null,
    checks: null,
    failures: null,
    summary: null,
  };

  // ---- 0. fixed strings from their single sources ------------------------
  const sourcesRun = runSourcesHarness();
  report.fixed_strings = sourcesRun.sources
    ? {
        exit: sourcesRun.exit,
        safetyNotice: sourcesRun.sources.safetyNotice,
        consultDisclaimer: sourcesRun.sources.consultDisclaimer,
        controlledDepartments: sourcesRun.sources.controlledDepartments,
        guards: sourcesRun.sources.guards,
      }
    : { exit: sourcesRun.exit, stderr_tail: sourcesRun.stderr };
  const sourcesOk =
    sourcesRun.exit === 0 &&
    sourcesRun.sources !== null &&
    typeof sourcesRun.sources.safetyNotice === 'string' &&
    sourcesRun.sources.safetyNotice.length > 0 &&
    typeof sourcesRun.sources.emergencyCue === 'boolean' &&
    sourcesRun.sources.guards.referral_rejected === true &&
    sourcesRun.sources.guards.dose_rejected === true &&
    sourcesRun.sources.guards.valid_accepted === true;
  record('sources_ok', sourcesOk, report.fixed_strings);
  if (!sourcesOk) {
    log('fixed-string harness failed — cannot assert exact server strings; aborting runtime phases honestly');
  }

  const SC = sourcesOk ? sourcesRun.sources : null;
  const AI = SC ? SC.aiCopy : {};
  const DEG = SC ? SC.degraded : {};
  const PRIVACY = SC ? SC.privacy : {};
  const AUTO_NOTICE = SC ? SC.autoExtractNotice : '';
  const DEPTS = SC ? SC.controlledDepartments : [];
  const REFERRAL = SC ? SC.referralTerms : [];
  const DECISION = SC ? SC.decisionTerms : [];
  const SAFETY_NOTICE = SC ? SC.safetyNotice : '';
  const CONSULT_DISCLAIMER = SC ? SC.consultDisclaimer : '';

  let mock = null;
  let srv = null;
  let mock2 = null;
  let srv2 = null;

  try {
    if (!sourcesOk) throw new Error('fixed-string harness did not produce the expected exports');

    // ---- 1. spin up mock upstream + real (non-demo) server ----------------
    mock = await startMock({ adversarial: false });
    srv = startServer(mock.url);
    const health1 = await waitForHealth(`${PROXY_URL}/api/health`, 12000);
    report.proxy = { mock_url: mock.url, server_config_demo: false, health1: health1.response };
    const healthOk =
      health1.response !== null &&
      health1.response.ok === true &&
      health1.response.demo === false &&
      health1.response.providerReady === true &&
      health1.response.searchReady === true;
    record('health_ok', healthOk, report.proxy.health1);
    if (!healthOk) throw new Error(`server health unexpected: ${JSON.stringify(health1)}`);
    ok(`mock upstream ${mock.url}; real server on ${PROXY_URL} demo=false providerReady=true searchReady=true`);

    // ---- 2. devtools launch (cold hidden) --------------------------------
    const port9420FreeBefore = probePortFree(AUTOMATION_PORT);
    log(`automation port ${AUTOMATION_PORT} free before launch: ${port9420FreeBefore}`);
    if (await tcpProbe(AUTOMATION_PORT, '127.0.0.1', 500)) {
      log(`warning: automation port ${AUTOMATION_PORT} already reachable before launch`);
    }
    miniProgram = await launchMiniProgram();
    // settle: a freshly launched devtools can drop the first evaluate (cold-start race)
    await delay(2500);

    // seed fresh state (no consent ack yet) so the first-use modal can be observed
    await seedStorage(SEED_PREFERENCES, SEED_MEMORY, false);
    await relaunchAi();

    const probe = await evalPage(pageProbe, {}, 'probe', 20000);
    const probeOk =
      !probe.__error &&
      probe.route === AI_ROUTE &&
      probe.mode === 'organize' &&
      probe.hasMessages === false &&
      probe.hasConfirm === 'function' &&
      probe.hasSetMode === 'function' &&
      probe.safetyFixed === (SC.safety ? SC.safety.fixed : probe.safetyFixed);
    record('probe_ok', probeOk, probe);
    if (!probeOk) throw new Error(`page probe unexpected: ${JSON.stringify(probe)}`);
    ok(`probe: route=${probe.route} mode=${probe.mode} status=${probe.aiStatus}`);

    const P1 = {};

    // ---- 2a. consult consent: cancel -> no send, no ack ------------------
    const cancel = await evalPage(pageConsent, { confirm: false }, 'consent-cancel', 20000);
    P1.consent_cancel = cancel;
    const cancelOk =
      !cancel.__error &&
      cancel.switched === false &&
      cancel.mode === 'organize' &&
      cancel.hasConsent === false &&
      cancel.requests === 0 &&
      Array.isArray(cancel.modals) &&
      cancel.modals.length === 1 &&
      typeof cancel.modals[0].content === 'string' &&
      cancel.modals[0].content.indexOf(PRIVACY.externalAiSendScope) !== -1 &&
      cancel.modals[0].content.indexOf(AUTO_NOTICE) !== -1;
    record('consent_cancel_ok', cancelOk, cancel);

    // ---- 2b. consult consent: confirm -> ack persisted, mode consult ------
    const confirm = await evalPage(pageConsent, { confirm: true }, 'consent-confirm', 20000);
    P1.consent_confirm = confirm;
    const confirmOk =
      !confirm.__error &&
      confirm.switched === true &&
      confirm.mode === 'consult' &&
      confirm.hasConsent === true &&
      confirm.ack === true;
    record('consent_confirm_ok', confirmOk, confirm);
    ok(`consult consent: cancel stays organize (no send); confirm persists ack`);

    // ---- 2c. organize round (dual mode) + auto-extract add ----------------
    const organize = await drivePage(
      { mode: 'organize', text: '最近一周头痛，睡不好' },
      'organize-round',
      40000
    );
    P1.organize = organize;
    const orgTitles = organize.last ? organize.last.blocks.map((b) => b.title) : [];
    const organizeOk =
      !organize.__error &&
      organize.send.reason === 'preview' &&
      organize.confirmed.ok === true &&
      organize.confirmed.kind === 'organize' &&
      organize.last.kind === 'organize' &&
      orgTitles.indexOf(AI.sectionPoints) !== -1 &&
      orgTitles.indexOf(AI.sectionExtracted) !== -1 &&
      orgTitles.indexOf(AI.sectionUnknowns) !== -1 &&
      orgTitles.indexOf(AI.sectionQuestions) !== -1 &&
      organize.input === '' &&
      organize.askBodies.length === 1 &&
      organize.askBodies[0].mode === 'organize' &&
      organize.askBodies[0].hasProfile === false;
    record('organize_ok', organizeOk, { titles: orgTitles, confirmed: organize.confirmed, ask: organize.askBodies });
    if (!organizeOk) log(`organize round unexpected: ${JSON.stringify(organize.last)}`);

    const memoryAfterExtract = await readStored('records_memory');
    const aiMemory = Array.isArray(memoryAfterExtract) ? memoryAfterExtract.filter((m) => m.source === 'ai') : [];
    const autoAddOk =
      organize.autoMemoryAdded === 1 &&
      organize.autoMemoryHint === `${AI.autoMemoryHintPrefix} 1 ${AI.autoMemoryHintUnit}` &&
      organize.extractCount >= 1 &&
      aiMemory.length === 1;
    record('autoextract_add_ok', autoAddOk, {
      autoMemoryAdded: organize.autoMemoryAdded,
      hint: organize.autoMemoryHint,
      extractCount: organize.extractCount,
      ai_memories: aiMemory.map((m) => m.text),
    });

    // ---- 2d. consult round: preview + result + citations + memory ---------
    const consult = await drivePage(
      { mode: 'consult', includeProfile: true, text: '最近胃不舒服' },
      'consult-round',
      40000
    );
    P1.consult = consult;
    const conTitles = consult.last ? consult.last.blocks.map((b) => b.title) : [];
    const conPreviewTitles = consult.preview.titles;
    const dirItems = consult.last ? consult.last.blocks.filter((b) => b.type === 'directions').reduce((a, b) => a.concat(b.items), []) : [];
    const sugBlock = consult.last ? consult.last.blocks.filter((b) => b.type === 'suggestions')[0] : undefined;
    const citItems = consult.last ? consult.last.blocks.filter((b) => b.type === 'citations').reduce((a, b) => a.concat(b.items), []) : [];
    const deptBlock = consult.last ? consult.last.blocks.filter((b) => b.type === 'list' && b.title === AI.sectionDepartments)[0] : undefined;
    const deptItems = deptBlock ? deptBlock.items.map((i) => i.text) : [];

    const consultPreviewOk =
      !consult.__error &&
      consult.send.reason === 'preview' &&
      conPreviewTitles.indexOf('档案摘要') !== -1 &&
      conPreviewTitles.indexOf('记录摘录') !== -1 &&
      conPreviewTitles.indexOf('记忆') !== -1 &&
      conPreviewTitles.indexOf('对话') !== -1 &&
      consult.preview.memoryText.indexOf(SEED_MEMORY[0].text) !== -1;
    record('consult_preview_ok', consultPreviewOk, { titles: conPreviewTitles, memory_text: consult.preview.memoryText });

    const consultResultOk =
      consult.confirmed.ok === true &&
      consult.confirmed.kind === 'consult' &&
      consult.last.kind === 'consult' &&
      conTitles.indexOf(AI.sectionDirections) !== -1 &&
      conTitles.indexOf(AI.sectionDepartments) !== -1 &&
      conTitles.indexOf(AI.sectionCitations) !== -1 &&
      conTitles.indexOf(AI.sectionSuggestions) !== -1 &&
      dirItems.length > 0 &&
      dirItems.every((i) => i.sub.indexOf(AI.citationPrefix) === 0 && i.url !== '') &&
      consult.last.disclaimer === CONSULT_DISCLAIMER;
    record('consult_result_ok', consultResultOk, { titles: conTitles, directions: dirItems.length, disclaimer: consult.last.disclaimer });

    const suggestionOk =
      sugBlock !== undefined &&
      sugBlock.title === AI.sectionSuggestions &&
      sugBlock.items.length > 0 &&
      sugBlock.items.every((i) => i.tag === AI.nonAdvice && i.sub.indexOf(AI.citationPrefix) === 0 && i.url !== '');
    record('consult_suggestions_ok', suggestionOk, {
      title: sugBlock ? sugBlock.title : null,
      items: sugBlock ? sugBlock.items : null,
    });

    const allUrls = dirItems.concat(citItems).concat(sugBlock ? sugBlock.items : []).map((i) => i.url).filter((u) => u !== '');
    const citationsOk =
      allUrls.length > 0 &&
      citItems.length > 0 &&
      citItems.every((i) => i.text !== '' && i.sub !== '') &&
      allUrls.every((u) => isAllowlisted(hostOf(u), AUTHORITY_DOMAINS));
    record('citations_allowlisted_ok', citationsOk, { urls: allUrls, citations: citItems });

    const memoryPayloadOk =
      consult.askBodies.length === 1 &&
      Array.isArray(consult.askBodies[0].memories) &&
      consult.askBodies[0].memories.indexOf(SEED_MEMORY[0].text) !== -1 &&
      consult.askBodies[0].hasProfile === true &&
      Array.isArray(consult.askBodies[0].excerpts) &&
      consult.askBodies[0].excerpts.length > 0;
    record('memory_in_payload_ok', memoryPayloadOk, { ask: consult.askBodies });

    // ---- 2e. auto-extract dedupe -----------------------------------------
    const consult2 = await drivePage(
      { mode: 'consult', includeProfile: true, text: '最近还是胃不舒服' },
      'consult-dedupe',
      40000
    );
    P1.consult_dedupe = { added: consult2.autoMemoryAdded, hint: consult2.autoMemoryHint, extractCount: consult2.extractCount };
    const dedupeOk =
      !consult2.__error &&
      consult2.confirmed.ok === true &&
      consult2.autoMemoryAdded === 0 &&
      consult2.autoMemoryHint === '' &&
      consult2.extractCount >= 1;
    record('autoextract_dedupe_ok', dedupeOk, P1.consult_dedupe);

    // ---- 2f. "找哪个医生" -> no specific-doctor / referral content --------
    const doctor = await drivePage(
      { mode: 'consult', includeProfile: true, text: '找哪个医生' },
      'doctor-guard',
      40000
    );
    P1.doctor = doctor;
    const doctorDir = doctor.last ? doctor.last.blocks.filter((b) => b.type === 'directions').reduce((a, b) => a.concat(b.items), []) : [];
    const doctorSug = doctor.last ? doctor.last.blocks.filter((b) => b.type === 'suggestions').reduce((a, b) => a.concat(b.items), []) : [];
    const doctorTexts = doctorDir.concat(doctorSug).map((i) => i.text).join('\n');
    const doctorDept = doctor.last
      ? doctor.last.blocks.filter((b) => b.type === 'list' && b.title === AI.sectionDepartments).reduce((a, b) => a.concat(b.items.map((i) => i.text)), [])
      : [];
    const noReferralText = REFERRAL.length > 0 && REFERRAL.every((term) => doctorTexts.indexOf(term) === -1);
    const deptsControlled = doctorDept.length > 0 && doctorDept.every((d) => DEPTS.indexOf(d) !== -1);
    const doctorOk =
      !doctor.__error &&
      doctor.confirmed.ok === true &&
      doctor.last.kind === 'consult' &&
      noReferralText &&
      deptsControlled;
    record('doctor_guard_page_ok', doctorOk, {
      referral_terms: REFERRAL,
      direction_suggestion_text: doctorTexts,
      departments: doctorDept,
    });

    // ---- 2g. disabled memory -> not sent ---------------------------------
    await seedStorage(SEED_PREFERENCES, [Object.assign({}, SEED_MEMORY[0], { enabled: false })], true);
    const disabled = await drivePage(
      { mode: 'consult', includeProfile: true, text: '最近胃不舒服' },
      'memory-disabled',
      40000
    );
    P1.memory_disabled = disabled;
    const disabledOk =
      !disabled.__error &&
      disabled.confirmed.ok === true &&
      disabled.preview.titles.indexOf('记忆') === -1 &&
      disabled.askBodies.length === 1 &&
      (disabled.askBodies[0].memories === null || disabled.askBodies[0].memories.indexOf(SEED_MEMORY[0].text) === -1);
    record('memory_disabled_not_sent_ok', disabledOk, {
      titles: disabled.preview.titles,
      memories: disabled.askBodies[0] ? disabled.askBodies[0].memories : null,
    });

    // ---- 2h. deleted memory -> not sent ----------------------------------
    await seedStorage(SEED_PREFERENCES, [], true);
    const deleted = await drivePage(
      { mode: 'consult', includeProfile: true, text: '最近胃不舒服' },
      'memory-deleted',
      40000
    );
    P1.memory_deleted = deleted;
    const deletedOk =
      !deleted.__error &&
      deleted.confirmed.ok === true &&
      deleted.preview.titles.indexOf('记忆') === -1 &&
      deleted.askBodies.length === 1 &&
      deleted.askBodies[0].memories === null;
    record('memory_deleted_not_sent_ok', deletedOk, {
      titles: deleted.preview.titles,
      memories: deleted.askBodies[0] ? deleted.askBodies[0].memories : null,
    });

    // ---- 2i. autoMemory off -> zero extract calls ------------------------
    await seedStorage(Object.assign({}, SEED_PREFERENCES, { autoMemory: false }), SEED_MEMORY, true);
    const autoOff = await drivePage(
      { mode: 'consult', includeProfile: true, text: '最近胃不舒服' },
      'automemory-off',
      40000
    );
    P1.auto_memory_off = { extractCount: autoOff.extractCount, added: autoOff.autoMemoryAdded, hint: autoOff.autoMemoryHint, askCount: autoOff.askBodies.length };
    const memoryAfterAutoOff = await readStored('records_memory');
    const autoOffMemoryCount = Array.isArray(memoryAfterAutoOff) ? memoryAfterAutoOff.length : -1;
    const autoOffOk =
      !autoOff.__error &&
      autoOff.confirmed.ok === true &&
      autoOff.extractCount === 0 &&
      autoOff.askBodies.length === 1 &&
      autoOffMemoryCount === 1;
    P1.auto_memory_off.memory_count_after = autoOffMemoryCount;
    record('autoMemory_off_zero_extract_ok', autoOffOk, P1.auto_memory_off);

    // restore autoMemory on for the remaining phase-1 checks
    await seedStorage(SEED_PREFERENCES, SEED_MEMORY, true);

    // ---- 2j. boundary inputs ---------------------------------------------
    const empty = await drivePage({ mode: 'organize', text: '' }, 'boundary-empty', 30000);
    const emptyOk =
      !empty.__error &&
      empty.send.reason === 'empty' &&
      empty.askBodies.length === 0 &&
      empty.extractCount === 0 &&
      empty.hint === AI.sendEmptyHint;
    record('boundary_empty_ok', emptyOk, { send: empty.send, ask: empty.askBodies.length, hint: empty.hint });

    const spaces = await drivePage({ mode: 'organize', text: '     ' }, 'boundary-spaces', 30000);
    const spacesOk = !spaces.__error && spaces.send.reason === 'empty' && spaces.askBodies.length === 0;
    record('boundary_whitespace_ok', spacesOk, { send: spaces.send, ask: spaces.askBodies.length });

    const longText = '最近睡眠不太好白天没有精神。'.repeat(10);
    const long = await drivePage({ mode: 'organize', text: longText }, 'boundary-long', 40000);
    const longOk =
      !long.__error &&
      long.confirmed.ok === true &&
      long.last.kind === 'organize' &&
      long.askBodies.length === 1 &&
      long.askBodies[0].userTexts.length === 1 &&
      long.askBodies[0].userTexts[0] === longText;
    record('boundary_long_ok', longOk, {
      confirmed: long.confirmed,
      askUserTextLen: long.askBodies[0] && long.askBodies[0].userTexts[0] ? long.askBodies[0].userTexts[0].length : -1,
      expectedLen: longText.length,
    });

    // ---- 2k. red-flag inputs -> fixed safety notice only -----------------
    const redflags = await evalPage(pageRedflags, { terms: RED_FLAG_INPUTS }, 'redflags', 90000);
    P1.redflags = redflags;
    // P1-8: SAFETY_NOTICE deliberately carries the emergency call「拨打 120」. That is legal ONLY
    // because the notice also carries an emergency cue (立即/马上/急诊/急救) in the same clause;
    // every other DECISION term stays banned. hasEmergencyCue comes from server/validate.ts so the
    // cue rule has a single definition; it is computed once in the tsx sources harness and read
    // here from the sources payload. The emergency-call term list mirrors validate.ts
    // EMERGENCY_CALL_TERMS. (弱线索「尽快」已于 P1-8 tightening 移除，不再豁免。)
    const emergencyCuePresent = SC.emergencyCue === true;
    const emergencyAllowedTerms = ['拨打', '120'];
    const bannedDecisionTerms = DECISION.filter((t) => {
      if (SAFETY_NOTICE.indexOf(t) === -1) return false;
      return !(emergencyCuePresent && emergencyAllowedTerms.indexOf(t) !== -1);
    });
    const noticeHas120 = SAFETY_NOTICE.indexOf('120') !== -1;
    const safetyClean =
      SAFETY_NOTICE.length > 0 &&
      !DEPTS.some((d) => SAFETY_NOTICE.indexOf(d) !== -1) &&
      !SC.redFlagTerms.some((t) => SAFETY_NOTICE.indexOf(t) !== -1) &&
      bannedDecisionTerms.length === 0 &&
      noticeHas120 &&
      emergencyCuePresent;
    record('redflag_notice_purity_ok', safetyClean, {
      safetyNotice: SAFETY_NOTICE,
      departments: DEPTS,
      redFlagTerms: SC.redFlagTerms,
      decisionTerms: DECISION,
      bannedDecisionTerms,
      emergencyCuePresent,
      noticeHas120,
    });
    const redflagsOk =
      Array.isArray(redflags) &&
      redflags.length === RED_FLAG_INPUTS.length &&
      redflags.every(
        (r) =>
          r.kind === 'redflag' &&
          r.blockCount === 1 &&
          r.blockTypes[0] === 'notice' &&
          r.noticeText === SAFETY_NOTICE &&
          r.disclaimer === CONSULT_DISCLAIMER
      );
    record('redflags_ok', redflagsOk, redflags);

    // ---- 2l. clear -> relaunch -> consistent empty state -----------------
    await evalPage(pageClearAll, { keys: STORAGE_KEYS.map((k) => 'mhp_' + k) }, 'clear', 15000);
    await relaunchAi();
    const empty1 = await evalPage(pageReadState, {}, 'read-empty-page', 20000);
    P1.empty_after_page_relaunch = empty1;
    const emptyPageOk =
      !empty1.__error &&
      empty1.route === AI_ROUTE &&
      empty1.hasMessages === false &&
      empty1.messageCount === 0 &&
      empty1.memoryCount === 0 &&
      empty1.candidateCount === 0 &&
      empty1.hasConsent === false;
    record('clear_relaunch_empty_ok', emptyPageOk, empty1);

    // genuine devtools relaunch (persistence of an empty state)
    try {
      await withTimeout(miniProgram.close(), 8000, 'close');
      miniProgram = null;
    } catch (err) {
      log(`warning: close failed: ${err?.message || err}`);
    }
    await delay(2000);
    miniProgram = await launchMiniProgram();
    await relaunchAi();
    const empty2 = await evalPage(pageReadState, {}, 'read-empty-app-relaunch', 20000);
    P1.empty_after_app_relaunch = empty2;
    const emptyAppOk =
      !empty2.__error &&
      empty2.route === AI_ROUTE &&
      empty2.hasMessages === false &&
      empty2.messageCount === 0 &&
      empty2.memoryCount === 0 &&
      empty2.hasConsent === false;
    record('app_relaunch_empty_ok', emptyAppOk, empty2);
    ok(`clear + relaunch: empty state consistent (page + app relaunch)`);

    report.phase1 = P1;

    // ---- 3. adversarial mock: validator interception ---------------------
    await stopServer(srv);
    srv = null;
    await stopChild(mock.child);
    mock = null;

    mock2 = await startMock({ adversarial: true });
    srv2 = startServer(mock2.url);
    const health2 = await waitForHealth(`${PROXY_URL}/api/health`, 12000);
    report.proxy.health2 = health2.response;
    report.phase2_adversarial = { mock_url: mock2.url, health: health2.response };

    const adverseFetch = await postJson(`${PROXY_URL}/api/ask`, {
      mode: 'consult',
      messages: [{ role: 'user', content: '最近胃不舒服' }],
      consent: true,
    });
    report.phase2_adversarial.fetch = adverseFetch;
    record(
      'adversarial_intercept_ok',
      adverseFetch.status === 200 && adverseFetch.data !== null && adverseFetch.data.error === 'unsafe_output',
      adverseFetch
    );

    // re-seed after the clear, then drive a consult round on the adversarial upstream
    await seedStorage(SEED_PREFERENCES, SEED_MEMORY, true);
    await relaunchAi();
    const adverseDrive = await drivePage(
      { mode: 'consult', includeProfile: true, text: '最近胃不舒服' },
      'adversarial-round',
      40000
    );
    report.phase2_adversarial.drive = adverseDrive;
    const adverseLast = adverseDrive.last;
    const adverseBlocks = adverseLast ? adverseLast.blocks : [];
    const adverseTypes = adverseBlocks.map((b) => b.type);
    const adverseRendered = adverseBlocks
      .reduce((acc, b) => acc.concat(b.items.map((i) => i.text)), [])
      .join('\n');
    const localOnlyTypes = adverseTypes.every((t) => t === 'list' || t === 'extracted');
    const noRestrictedText =
      DECISION.every((t) => adverseRendered.indexOf(t) === -1) &&
      REFERRAL.every((t) => adverseRendered.indexOf(t) === -1);
    const adverseFallbackOk =
      !adverseDrive.__error &&
      adverseDrive.confirmed.ok === false &&
      adverseDrive.confirmed.reason === 'unsafe_output' &&
      adverseLast.kind === 'local' &&
      adverseLast.content === AI.localOrganizeTitle &&
      adverseBlocks.length > 0 &&
      localOnlyTypes &&
      !adverseTypes.includes('directions') &&
      !adverseTypes.includes('suggestions') &&
      !adverseTypes.includes('citations') &&
      noRestrictedText &&
      adverseDrive.hint === DEG.unsafeFallback &&
      adverseDrive.input === '' &&
      adverseDrive.extractCount === 0 &&
      adverseDrive.status !== 'ok';
    record('adversarial_fallback_ok', adverseFallbackOk, {
      confirmed: adverseDrive.confirmed,
      kind: adverseLast ? adverseLast.kind : null,
      content: adverseLast ? adverseLast.content : null,
      types: adverseTypes,
      rendered: adverseRendered.slice(0, 200),
      hint: adverseDrive.hint,
      status: adverseDrive.status,
    });
    ok(`adversarial mock: server returned unsafe_output; page consumed fallback -> local organize (no model content)`);

    // ---- 4. broken LLM upstream (mock killed, server alive) --------------
    await stopChild(mock2.child);
    mock2 = null;
    const brokenFetch = await postJson(`${PROXY_URL}/api/ask`, {
      mode: 'organize',
      messages: [{ role: 'user', content: '最近睡不好' }],
      consent: true,
    });
    report.phase3_llm_broken = { fetch: brokenFetch };
    record(
      'llm_broken_upstream_error_ok',
      brokenFetch.status === 200 && brokenFetch.data !== null && brokenFetch.data.error === 'upstream_error',
      brokenFetch
    );

    const brokenDrive = await drivePage(
      { mode: 'organize', includeProfile: false, text: '最近睡不好' },
      'llm-broken-round',
      40000
    );
    report.phase3_llm_broken.drive = brokenDrive;
    const brokenLast = brokenDrive.last;
    const brokenBlocks = brokenLast ? brokenLast.blocks : [];
    const brokenErrorOk =
      !brokenDrive.__error &&
      brokenDrive.confirmed.ok === false &&
      brokenDrive.confirmed.reason === 'upstream_error' &&
      brokenLast.kind === 'error' &&
      brokenLast.errorText === DEG.aiFailed &&
      brokenLast.canLocalOrganize === true &&
      brokenLast.localText === '最近睡不好' &&
      brokenBlocks.length === 0 &&
      brokenDrive.input === '最近睡不好' &&
      brokenDrive.status !== 'ok';
    record('llm_broken_degradation_ok', brokenErrorOk, {
      confirmed: brokenDrive.confirmed,
      kind: brokenLast ? brokenLast.kind : null,
      errorText: brokenLast ? brokenLast.errorText : null,
      canLocalOrganize: brokenLast ? brokenLast.canLocalOrganize : null,
      blocks: brokenBlocks.length,
      input: brokenDrive.input,
      status: brokenDrive.status,
    });

    // ---- 5. broken proxy (server killed) -> degradation message ----------
    await stopServer(srv2);
    srv2 = null;

    const degradeText = '最近胃不舒服';
    const degrade = await drivePage(
      { mode: 'organize', includeProfile: false, text: degradeText },
      'proxy-down-round',
      40000
    );
    report.phase4_proxy_broken = { drive: degrade };
    const degradeOk =
      !degrade.__error &&
      degrade.confirmed.ok === false &&
      degrade.last.kind === 'error' &&
      degrade.last.errorText === DEG.proxyOffline &&
      degrade.last.blocks.length === 0 &&
      degrade.last.canLocalOrganize === true &&
      degrade.last.localText === degradeText &&
      degrade.input === degradeText &&
      degrade.status === 'offline';
    record('proxy_offline_degradation_ok', degradeOk, {
      confirmed: degrade.confirmed,
      errorText: degrade.last ? degrade.last.errorText : null,
      blocks: degrade.last ? degrade.last.blocks.length : -1,
      input: degrade.input,
      status: degrade.status,
    });

    const autoLocal = await drivePage(
      { mode: 'organize', includeProfile: false, text: degradeText },
      'proxy-down-autolocal',
      40000
    );
    report.phase4_proxy_broken.auto_local = autoLocal;
    const autoLocalOk =
      !autoLocal.__error &&
      autoLocal.last.kind === 'local' &&
      autoLocal.askBodies.length === 0 &&
      autoLocal.extractCount === 0 &&
      autoLocal.status === 'local';
    record('offline_auto_local_ok', autoLocalOk, {
      kind: autoLocal.last ? autoLocal.last.kind : null,
      ask: autoLocal.askBodies.length,
      extract: autoLocal.extractCount,
      status: autoLocal.status,
    });

    // ---- 6. failure artifact ---------------------------------------------
    const failureLines = [
      'T33 AI matrix failure-path evidence (broken upstream / broken proxy; full stack: mock upstream + real server)',
      'command: E2E_DEVTOOLS_MINIMIZE=1 node tests/e2e/ai.spec.mjs',
      `timestamp: ${new Date().toISOString()}`,
      'method: REAL pages/ai/ai.ts driven via miniProgram.evaluate; sends go to the REAL server on 127.0.0.1:8787 (demo=false) which runs the REAL orchestrator; ONLY the LLM/search upstream is server/mock-upstream.mjs.',
      '',
      '## (a) broken LLM upstream (mock killed, local server alive) — degradation message shown',
      `server_fetch_status: ${brokenFetch.status}`,
      `server_fetch_error: ${JSON.stringify(brokenFetch.data && brokenFetch.data.error)} (expected "upstream_error")`,
      `page_result_kind: ${JSON.stringify(brokenLast ? brokenLast.kind : null)} (expected "error")`,
      `page_error_text: ${JSON.stringify(brokenLast ? brokenLast.errorText : null)} (expected ${JSON.stringify(DEG.aiFailed)})`,
      `page_can_local_organize: ${brokenLast ? brokenLast.canLocalOrganize : null}`,
      `page_input_preserved: ${JSON.stringify(brokenDrive.input)}`,
      `page_fake_ai_blocks: ${brokenBlocks.length} (expected 0 — no fabricated AI content)`,
      `page_status: ${JSON.stringify(brokenDrive.status)} (must not be "ok")`,
      'note: the server HTTP-200 error envelope is now consumed by the client; the raw server message is NOT displayed (fixed client copy only).',
      '',
      '## (b) unsafe model output (adversarial mock) — fallback consumed, no model content rendered',
      `server_fetch_error: ${JSON.stringify(adverseFetch.data && adverseFetch.data.error)} (expected "unsafe_output")`,
      `fallback_reason: ${JSON.stringify(adverseDrive.confirmed.reason)} (page kind ${JSON.stringify(adverseLast ? adverseLast.kind : null)})`,
      `page_content_label: ${JSON.stringify(adverseLast ? adverseLast.content : null)} (expected ${JSON.stringify(AI.localOrganizeTitle)})`,
      `page_hint: ${JSON.stringify(adverseDrive.hint)} (expected ${JSON.stringify(DEG.unsafeFallback)})`,
      `page_local_blocks: ${adverseBlocks.length} (types ${JSON.stringify(adverseTypes)})`,
      `page_rendered_local: ${JSON.stringify(adverseRendered)} (local organizer output; contains no model content)`,
      `page_status: ${JSON.stringify(adverseDrive.status)} (must not be "ok")`,
      '',
      '## (c) broken proxy (local server killed) — degradation message + auto local',
      `degraded_returned_ok: ${degrade.confirmed.ok === false}`,
      `degraded_message_kind: ${JSON.stringify(degrade.last ? degrade.last.kind : null)}`,
      `degraded_error_text: ${JSON.stringify(degrade.last ? degrade.last.errorText : null)} (expected ${JSON.stringify(DEG.proxyOffline)})`,
      `degraded_input_preserved: ${JSON.stringify(degrade.input)}`,
      `degraded_can_local_organize: ${degrade.last ? degrade.last.canLocalOrganize : null}`,
      `degraded_fake_ai_blocks: ${degrade.last ? degrade.last.blocks.length : -1} (expected 0)`,
      `degraded_status: ${JSON.stringify(degrade.status)}`,
      `next_send_kind: ${JSON.stringify(autoLocal.last ? autoLocal.last.kind : null)} (local organizer, zero network)`,
      `next_send_ask_requests: ${autoLocal.askBodies.length} (expected 0)`,
      `next_send_extract_requests: ${autoLocal.extractCount} (expected 0)`,
      '',
      'verdict: PASS — server error envelopes are consumed: unsafe_output falls back to labeled local organizing with an honest hint; other codes show the fixed degradation error and preserve the input; no fabricated AI content anywhere.',
    ];
    fs.writeFileSync(QA_FAILURE_PATH, failureLines.join('\n') + '\n');
    log(`failure evidence: ${QA_FAILURE_PATH}`);

    // ---- 7. render evidence ----------------------------------------------
    const render = await withTimeout(captureRender('empty-state'), 15000, 'render');
    if (render.timedOut === true || render.error !== undefined) {
      report.render = { error: render.timedOut ? 'timed out' : render.error };
      record('render_ok', false, report.render);
    } else {
      report.render = render.value;
      record(
        'render_ok',
        render.value.topPath === AI_ROUTE && render.value.pngMagic === true && render.value.bytes > 5000,
        render.value
      );
    }
  } catch (err) {
    fail(`ai matrix run error: ${err?.stack || err}`);
    record('run_completed', false, err?.message || String(err));
  } finally {
    if (miniProgram) {
      const raced = await withTimeout(miniProgram.close(), 8000, 'close');
      if (raced.timedOut === true) log('warning: miniProgram.close() timed out');
      else if (raced.error !== undefined) log(`warning: miniProgram.close() failed: ${raced.error}`);
      try {
        miniProgram.disconnect();
      } catch {
        /* socket already closed */
      }
    }
    await stopServer(srv);
    await stopServer(srv2);
    await stopChild(mock ? mock.child : null);
    await stopChild(mock2 ? mock2.child : null);
  }

  report.checks = checks;
  report.failures = failures;
  const passed = failures.length === 0 && Object.keys(checks).length >= 20 && Object.values(checks).every((v) => v === true);
  report.summary = {
    total: Object.keys(checks).length,
    failed: failures.length,
    passed,
    runtime_ms: Date.now() - startedAt,
  };
  fs.writeFileSync(MATRIX_PATH, JSON.stringify(report, null, 2) + '\n');
  log(`ai-matrix evidence: ${MATRIX_PATH}`);

  section('AI MATRIX RESULT');
  for (const [name, value] of Object.entries(checks)) {
    log(`  ${value === true ? 'PASS' : 'FAIL'} ${name}`);
  }
  if (passed) ok(`AI matrix: ${report.summary.total} checks passed (${report.summary.runtime_ms} ms)`);
  else fail(`AI matrix: ${failures.length} failure(s): ${JSON.stringify(failures.map((f) => f.name))}`);
  log(`runtime: ${report.summary.runtime_ms} ms`);

  return passed;
}

main().then(
  (passed) => {
    process.exit(passed ? 0 : 1);
  },
  (err) => {
    console.error(`[e2e] FAIL ${err?.stack || err}`);
    process.exit(1);
  }
);
