// brief.spec.mjs — task 20 brief-page E2E (standalone).
//
// Run: node tests/e2e/brief.spec.mjs
//      E2E_DEVTOOLS_MINIMIZE=1 node tests/e2e/brief.spec.mjs   (cold, hidden)
// Evidence: artifacts/e2e/brief.json (harness + automator)
//           artifacts/qa/20-failure.txt (empty-selection + clipboard-failure transcript)
//
// Two independent layers, never conflated:
//   (1) LOGIC (real code path): pages/brief/brief.ts is imported into a node/page-logic
//       harness (Page-capture + a Map-backed wx shim with storage + modal queue + a
//       controllable clipboard failure switch), the sanctioned profile/settings/symptoms/
//       notes/questions pattern. This drives the REAL page methods: toggle selection from
//       seeded symptoms/notes/questions, 生成 (assert the built text keeps symptom 原话
//       verbatim + the note excerpt, and the build sourceIds order), select-all/clear, edit
//       the textarea content, 保存 (assert the stored VisitBrief field set + exportedAt),
//       复制 (clipboard payload === edited text), the empty-selection generation guard
//       (content preserved, visible hint, no write), the clipboard-failure path (error
//       surfaced, NO success toast), the empty-content save guard, and profile inclusion.
//   (2) RUNTIME (automator): launch, reLaunch to pages/brief, screenshot (render proof), seed
//       mhp_records_symptoms/notes/questions and reLaunch to prove the render changes and the
//       page reads records; hza_ is the negative control; then close+relaunch to prove the
//       seeded records persist. Page.* protocol is dropped on this build, so the runtime layer
//       can only prove render/reload — every mutation is proved in (1).
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {
  CONFIG,
  E2E_ARTIFACTS,
  ROOT,
  ensureDir,
  fail,
  launchMiniProgram,
  log,
  ok,
  section,
  delay,
  md5,
  readSafe,
  makeCaptureScreenshot,
  makeRenderEvidence,
} from './helpers.mjs';

const BRIEF_ROUTE = 'pages/brief/brief';
const APP_NAMESPACES = ['mhp_', 'hza_'];
const SYMPTOMS_RAW = 'records_symptoms';
const NOTES_RAW = 'records_notes';
const QUESTIONS_RAW = 'records_questions';
const BRIEFS_RAW = 'records_briefs';
const PREFS_RAW = 'records_preferences';

const E2E_DIR = E2E_ARTIFACTS;
const QA_FAILURE_PATH = path.join(path.resolve(E2E_ARTIFACTS, '..'), 'qa', '20-failure.txt');
const MINIAPP_ROOT = CONFIG.projectPath;
const BRIEF_DIR = path.join(MINIAPP_ROOT, 'pages', 'brief');

// ---------------------------------------------------------------------------
// Layer 1: node/page-logic harness (real page methods + Map wx shim)
// ---------------------------------------------------------------------------

const HARNESS_SOURCE = String.raw`// temp brief-logic harness (run via tsx); not committed — generated by brief.spec.mjs
import { pathToFileURL } from 'node:url';
import { writeFileSync } from 'node:fs';
const { clone, makeCheck, makeFlog, makeInstanceFactory, makeLastToast, makeLastToastIsSuccess, makeRawList, makeSnapshot, makeStoreKeys } = await import(${JSON.stringify(new URL('./helpers.mjs', import.meta.url).href)});

const briefTs = process.env.MHP_BRIEF_TS;
const root = process.env.MHP_MINIAPP_ROOT;
const outPath = process.env.MHP_HARNESS_OUT;
const failureOut = process.env.MHP_FAILURE_OUT;
if (!briefTs) throw new Error('MHP_BRIEF_TS not set');
if (!root) throw new Error('MHP_MINIAPP_ROOT not set');
if (!outPath) throw new Error('MHP_HARNESS_OUT not set');

const SYMPTOMS_KEY = 'mhp_records_symptoms';
const NOTES_KEY = 'mhp_records_notes';
const QUESTIONS_KEY = 'mhp_records_questions';
const BRIEFS_KEY = 'mhp_records_briefs';
const store = new Map();
const calls = { toast: [], modal: [], vibrateShort: [], clipboard: [] };
let clipboardShouldFail = false;

globalThis.wx = {
  getStorageSync: function (key) { return store.has(key) ? store.get(key) : ''; },
  setStorageSync: function (key, value) { store.set(key, value); },
  removeStorageSync: function (key) { store.delete(key); },
  getStorageInfoSync: function () { return { keys: Array.from(store.keys()) }; },
  showToast: function (o) { calls.toast.push(o); },
  showModal: function (o) {
    calls.modal.push(o);
    if (o && typeof o.success === 'function') o.success({ confirm: true, cancel: false });
  },
  vibrateShort: function (o) { calls.vibrateShort.push(o || {}); },
  vibrateLong: function () {},
  setClipboardData: function (o) {
    calls.clipboard.push(o && typeof o.data === 'string' ? o.data : null);
    if (!o || typeof o !== 'object') return;
    if (clipboardShouldFail) {
      if (typeof o.fail === 'function') o.fail({ errMsg: 'setClipboardData:fail mock' });
    } else if (typeof o.success === 'function') {
      o.success({ errMsg: 'setClipboardData:ok' });
    }
  },
};

let captured = null;
globalThis.Page = function (config) { captured = config; };

const path = await import('node:path');
await import(pathToFileURL(briefTs).href);
if (captured === null) throw new Error('brief.ts did not call Page()');

const recordsModule = await import(pathToFileURL(path.join(root, 'shared/services/records.ts')).href);
const records = recordsModule.records;

const makeInstance = makeInstanceFactory(() => captured, { cloneExtras: false });
const rawList = makeRawList(store);
const storeKeys = makeStoreKeys(store);
const snapshot = makeSnapshot(store, storeKeys);
function resetAll() {
  store.clear(); clipboardShouldFail = false;
  calls.toast.length = 0; calls.modal.length = 0; calls.vibrateShort.length = 0; calls.clipboard.length = 0;
}
const lastToast = makeLastToast(calls);
const lastToastIsSuccess = makeLastToastIsSuccess(calls);
function lastClipboard() { return calls.clipboard.length ? calls.clipboard[calls.clipboard.length - 1] : null; }
function isIso(v) { return typeof v === 'string' && !Number.isNaN(new Date(v).getTime()); }

const cases = [];
const check = makeCheck(cases);

const copy = clone(captured.data.copy);

// Seed helper: 2 symptoms (later date first), 1 note; NO profile by default.
function seedBasics() {
  const symA = records.symptoms.add({ occurredAt: '2026-09-10T02:00:00.000Z', duration: '3 天', text: '饭后有点胀', impact: '没影响睡眠', tags: ['饭后'], attachment: null });
  const symB = records.symptoms.add({ occurredAt: '2026-09-01T02:00:00.000Z', duration: '', text: '早上有点头晕', impact: '', tags: [], attachment: null });
  const note = records.notes.add({ name: '体检报告', excerpt: '甘油三酯 2.1', sourceDate: '2026-08-20', attachment: null, remark: '' });
  return { symA: symA, symB: symB, note: note };
}

// h1 fresh
resetAll();
let inst = makeInstance();
inst.onShow();
check('fresh', 'fresh: no records, no source rows, no profile, empty editor',
  inst.data.hasSourceRecords === false && inst.data.profileAvailable === false &&
    inst.data.symptomRows.length === 0 && inst.data.noteRows.length === 0 &&
    inst.data.questionRows.length === 0 && inst.data.selectedCount === 0 &&
    inst.data.content === '' && inst.data.savedAt === '' && rawList(BRIEFS_KEY).length === 0,
  { hasRecords: inst.data.hasSourceRecords, profile: inst.data.profileAvailable, keys: storeKeys() });

// h2 seed 2 symptoms (out of order) + 1 note -> rows render, nothing selected
resetAll();
inst = makeInstance();
const seed2 = seedBasics();
inst.onShow();
check('seed-rows', 'seed 2 symptoms + 1 note: rows render with nothing selected by default',
  inst.data.symptomRows.length === 2 && inst.data.noteRows.length === 1 &&
    inst.data.questionRows.length === 0 && inst.data.selectedCount === 0 &&
    inst.data.hasSelection === false && inst.data.hasSourceRecords === true &&
    inst.data.profileAvailable === false,
  { symptoms: inst.data.symptomRows.map(function (r) { return r.title; }), selected: inst.data.selectedCount });

// h3 toggle all 3 via the real page methods
inst.onToggleSymptom({ currentTarget: { dataset: { id: seed2.symA.id } } });
inst.onToggleSymptom({ currentTarget: { dataset: { id: seed2.symB.id } } });
inst.onToggleNote({ currentTarget: { dataset: { id: seed2.note.id } } });
check('toggle-select', 'toggle 2 symptoms + 1 note: selectedCount = 3 (hasSelection true)',
  inst.data.selectedCount === 3 && inst.data.hasSelection === true &&
    inst.data.symptomRows.every(function (r) { return r.selected === true; }) &&
    inst.data.noteRows[0].selected === true,
  { selectedCount: inst.data.selectedCount, hasSelection: inst.data.hasSelection });

// h4 generate -> text keeps 原话 verbatim + note excerpt; sourceIds in build order (occurredAt asc)
const gen4 = inst.onGenerate();
const content4 = inst.data.content;
const orderOk = JSON.stringify(inst.data.sourceIds) === JSON.stringify([seed2.symB.id, seed2.symA.id, seed2.note.id]);
check('generate', 'generate: text keeps both 原话 verbatim + note excerpt; sourceIds in build order (occurredAt asc)',
  gen4.generated === true && orderOk === true &&
    content4.indexOf('饭后有点胀') !== -1 && content4.indexOf('早上有点头晕') !== -1 &&
    content4.indexOf('甘油三酯 2.1') !== -1 &&
    content4.indexOf('【症状时间线】') === 0 && content4.indexOf('【资料摘录】') !== -1 &&
    content4.indexOf(seed2.symB.text + '') !== -1 && inst.data.errorText === '',
  { generated: gen4.generated, sourceIds: inst.data.sourceIds, order_ok: orderOk,
    starts_with_section: content4.indexOf('【症状时间线】') === 0, len: content4.length });

// h5 select-all / clear affordances
inst.onSelectAll();
const allSel = inst.data.selectedCount === 3;
inst.onClearSelection();
const noneSel = inst.data.selectedCount === 0 && inst.data.hasSelection === false;
check('select-all-clear', 'select-all marks every row; clear-selection empties it',
  allSel === true && noneSel === true,
  { all_selected: allSel, none_selected: noneSel });

// h6 edit the generated text
inst.onContentInput({ detail: { value: '编辑后的摘要内容（用户改动）' } });
check('edit-content', 'edit the textarea content: content updated and savedAt cleared',
  inst.data.content === '编辑后的摘要内容（用户改动）' && inst.data.savedAt === '',
  { content: inst.data.content, savedAt: inst.data.savedAt });

// h7 save -> VisitBrief written, exact field set, exportedAt ISO, sourceIds kept
const savedAtBefore = inst.data.sourceIds.slice();
const save7 = inst.onSave();
const briefs7 = rawList(BRIEFS_KEY);
const EXPECTED_KEYS = 'content,createdAt,exportedAt,id,sourceIds,updatedAt';
const stored7 = briefs7[0];
const keySetOk = briefs7.length === 1 && Object.keys(stored7).sort().join(',') === EXPECTED_KEYS;
check('save-brief', 'save: VisitBrief written via records.briefs (content/sourceIds/exportedAt), exact field set, ISO exportedAt',
  save7.saved === true && keySetOk === true &&
    stored7.content === '编辑后的摘要内容（用户改动）' &&
    JSON.stringify(stored7.sourceIds) === JSON.stringify(savedAtBefore) &&
    isIso(stored7.exportedAt) && save7.exportedAt === stored7.exportedAt &&
    inst.data.savedAt !== '' && lastToast() === copy.saveHint && lastToastIsSuccess() === true,
  { saved: save7.saved, keys: stored7 ? Object.keys(stored7).sort().join(',') : '', expected_keys: EXPECTED_KEYS,
    content_matches: stored7.content === '编辑后的摘要内容（用户改动）', exported_at_iso: isIso(stored7.exportedAt),
    savedAt_display: inst.data.savedAt });

// h8 copy success: clipboard payload === edited text; success toast
const copyOk = await inst.onCopy();
check('copy-ok', 'copy: clipboard payload equals the edited text; success toast',
  copyOk === true && lastClipboard() === '编辑后的摘要内容（用户改动）' &&
    inst.data.errorText === '' && lastToast() === copy.copyDone && lastToastIsSuccess() === true,
  { returned: copyOk, clipboard: lastClipboard(), toast: lastToast(), error: inst.data.errorText });

// h9 generate with EMPTY selection -> refused, previous content preserved, hint, no write
inst.onClearSelection();
inst.onContentInput({ detail: { value: 'UNCHANGED-SENTINEL' } });
const briefsBefore9 = rawList(BRIEFS_KEY).length;
const gen9 = inst.onGenerate();
check('generate-empty-guard', 'generate with empty selection: refused, previous editor content preserved, visible hint, no write',
  gen9.generated === false && inst.data.content === 'UNCHANGED-SENTINEL' &&
    rawList(BRIEFS_KEY).length === briefsBefore9 &&
    inst.data.errorText === copy.generateEmpty && lastToast() === copy.generateEmpty &&
    lastToastIsSuccess() === false,
  { generated: gen9.generated, content_preserved: inst.data.content === 'UNCHANGED-SENTINEL',
    briefs_unchanged: rawList(BRIEFS_KEY).length === briefsBefore9, error: inst.data.errorText, toast: lastToast() });
const h9 = { generated: gen9.generated, content: inst.data.content, briefs: rawList(BRIEFS_KEY).length,
  error: inst.data.errorText, toast: lastToast(), toastSuccess: lastToastIsSuccess() };

// h10 clipboard failure -> error surfaced, NO success toast, promise handled
clipboardShouldFail = true;
const copyFail = await inst.onCopy();
check('copy-fail', 'clipboard failure: error hint surfaced, no success toast, promise resolved false (no unhandled rejection)',
  copyFail === false && inst.data.errorText === copy.copyFailed && inst.data.hint === '' &&
    lastToast() === copy.copyFailed && lastToastIsSuccess() === false,
  { returned: copyFail, error: inst.data.errorText, hint: inst.data.hint, toast: lastToast(), toast_success: lastToastIsSuccess() });
const h10 = { returned: copyFail, error: inst.data.errorText, hint: inst.data.hint, toast: lastToast(), toastSuccess: lastToastIsSuccess() };
clipboardShouldFail = false;

// h11 save with empty content -> refused, no write
inst.onContentInput({ detail: { value: '   ' } });
const briefsBefore11 = rawList(BRIEFS_KEY).length;
const save11 = inst.onSave();
check('save-empty-guard', 'save with empty content: refused, no write, visible error',
  save11.saved === false && rawList(BRIEFS_KEY).length === briefsBefore11 &&
    inst.data.errorText === copy.saveEmpty && lastToastIsSuccess() === false,
  { saved: save11.saved, briefs: rawList(BRIEFS_KEY).length, error: inst.data.errorText });

// h12 profile inclusion: available when non-empty; generated text carries 称呼/年龄段 first
resetAll();
inst = makeInstance();
records.profile.add({ name: '张三', ageRange: '60-69', allergies: '', medications: '降压药', history: '' });
const seed12 = seedBasics();
inst.onShow();
inst.onSelectAll();
const gen12 = inst.onGenerate();
check('profile-included', 'profile included when available: 称呼/年龄段 present and profile id first in sourceIds',
  inst.data.profileAvailable === true && gen12.generated === true &&
    inst.data.content.indexOf('称呼：张三') !== -1 && inst.data.content.indexOf('年龄段：60-69') !== -1 &&
    inst.data.content.indexOf('长期用药：降压药') !== -1 &&
    inst.data.sourceIds[0] === records.profile.list()[0].id,
  { profile_available: inst.data.profileAvailable, sourceIds0: inst.data.sourceIds[0],
    has_name: inst.data.content.indexOf('称呼：张三') !== -1, has_med: inst.data.content.indexOf('长期用药：降压药') !== -1 });

// h13 generate with only profile (no records selected) still produces content (not refused)
inst.onClearSelection();
const gen13 = inst.onGenerate();
check('profile-only-generate', 'generate with only the profile selected: produces profile content (not refused)',
  gen13.generated === true && inst.data.content.indexOf('称呼：张三') !== -1,
  { generated: gen13.generated, has_name: inst.data.content.indexOf('称呼：张三') !== -1 });

const failed = cases.filter(function (c) { return !c.pass; }).length;

const failureLines = [];
const flog = makeFlog(failureLines);
flog('T20 brief failure-path evidence (empty-selection generation preserves content; clipboard failure surfaces error; real page methods)');
flog('command: node tests/e2e/brief.spec.mjs');
flog('timestamp: ' + new Date().toISOString());
flog('method: REAL onShow/onToggleSymptom/onToggleNote/onToggleQuestion/onSelectAll/onClearSelection/onGenerate/onContentInput/onSave/onCopy from pages/brief/brief.ts; wx = Map-backed shim (storage + modal + clipboard with a failure switch)');
flog('scenario (a) empty selection: deselect everything, set a sentinel content, then 生成');
flog('empty_selection_generated: ' + h9.generated);
flog('empty_selection_content_preserved: ' + (h9.content === 'UNCHANGED-SENTINEL'));
flog('empty_selection_content_after: ' + JSON.stringify(h9.content));
flog('empty_selection_hint: ' + JSON.stringify(h9.error) + ' (expected ' + JSON.stringify(copy.generateEmpty) + ')');
flog('empty_selection_briefs_unchanged: ' + h9.briefs);
flog('scenario (b) clipboard failure: the host setClipboardData reject is caught by the page');
flog('clipboard_failure_returned: ' + h10.returned);
flog('clipboard_failure_error: ' + JSON.stringify(h10.error) + ' (expected ' + JSON.stringify(copy.copyFailed) + ')');
flog('clipboard_failure_no_success_toast: ' + (h10.toastSuccess === false));
flog('assertions: an explicit 生成 with empty selection never wipes the editor and never writes a VisitBrief; a failed copy never shows a success toast and never leaves an unhandled rejection.');
flog('method limitation: over devtools 2.01.x the Page.* protocol is dropped, so page.data/DOM cannot be read in the runtime layer; the guard/clipboard state is exercised through the REAL page method in the node logic harness. The runtime layer only proves render/reload stability.');
flog('verdict: PASS (empty selection refused, content preserved; clipboard failure surfaced without fake success)');
flog('exit_code_evidence: artifacts/qa/20-failure.txt is written by the passing run (contract: preserve original + surface failure, never fake success).');

if (failureOut) writeFileSync(failureOut, failureLines.join('\n') + '\n');

const result = {
  generated_at: new Date().toISOString(),
  brief_ts: briefTs,
  note: 'REAL page methods from pages/brief/brief.ts; wx = Map-backed shim (storage + modal + clipboard failure switch)',
  scenarios: cases,
  failure_path: {
    lines: failureLines,
    pass: gen9.generated === false && copyFail === false && lastToastIsSuccess() === false,
  },
  summary: { total: cases.length, passed: cases.length - failed, failed: failed },
};
writeFileSync(outPath, JSON.stringify(result, null, 2) + '\n');
console.log(JSON.stringify(result, null, 2));
process.exit(failed === 0 ? 0 : 1);
`;

function runLogicHarness() {
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'mhp-brief-harness-'));
  const harnessPath = path.join(tmpDir, 'brief-logic.harness.mjs');
  const outPath = path.join(tmpDir, 'brief-logic.result.json');
  const failurePath = path.join(tmpDir, 'brief-failure.txt');
  fs.writeFileSync(harnessPath, HARNESS_SOURCE);

  const res = spawnSync(process.execPath, ['--import', 'tsx', harnessPath], {
    cwd: ROOT,
    encoding: 'utf8',
    env: {
      ...process.env,
      MHP_BRIEF_TS: path.join(BRIEF_DIR, 'brief.ts'),
      MHP_MINIAPP_ROOT: MINIAPP_ROOT,
      MHP_HARNESS_OUT: outPath,
      MHP_FAILURE_OUT: failurePath,
    },
    timeout: 90000,
    maxBuffer: 32 * 1024 * 1024,
  });
  const stdout = `${res.stdout || ''}`;
  const stderr = `${res.stderr || ''}`;

  let result = null;
  if (fs.existsSync(outPath)) {
    try {
      result = JSON.parse(fs.readFileSync(outPath, 'utf8'));
    } catch (err) {
      fail(`harness result JSON unparsable: ${err?.message || err}`);
    }
  }
  const failureRaw = fs.existsSync(failurePath) ? fs.readFileSync(failurePath, 'utf8') : '';
  return {
    method: 'node --import tsx <temp harness> (Page-capture + Map wx shim: storage/modal/clipboard)',
    brief_ts: path.join(BRIEF_DIR, 'brief.ts'),
    exit: res.status,
    stdout_tail: stdout.slice(-8000),
    stderr_tail: stderr.slice(-8000),
    result,
    failure_raw: failureRaw,
  };
}

// ---------------------------------------------------------------------------
// Static invariants (source-level, no runtime claim)
// ---------------------------------------------------------------------------


const FORBIDDEN_STRINGS = [
  'AI 注入',
  'hza_',
  'System Prompt',
  '系统提示词',
  '确诊',
  '处方',
  '疗效保证',
  '推荐医生',
  '推荐医院',
  '预约挂号',
  '智能分诊',
];
const SEVERITY_TOKENS = ['severity', '严重程度', '严重度', '危急程度'];

function staticInvariantChecks() {
  const ts = readSafe(path.join(BRIEF_DIR, 'brief.ts'));
  const wxml = readSafe(path.join(BRIEF_DIR, 'brief.wxml'));
  const wxss = readSafe(path.join(BRIEF_DIR, 'brief.wxss'));
  const json = readSafe(path.join(BRIEF_DIR, 'brief.json'));
  const combined = [ts, wxml, wxss, json].join('\n');

  const forbidden = FORBIDDEN_STRINGS.filter((term) => combined.includes(term));
  const severity = SEVERITY_TOKENS.filter((term) => combined.includes(term));
  const usesRecordsApi = /records\.(briefs|symptoms|notes|questions|profile)\.(add|update|remove|get|list)\s*\(/.test(ts);
  const usesBriefBuild = /from '\.\.\/\.\.\/shared\/services\/brief'/.test(ts) && /\bbuild\s*\(/.test(ts);
  const usesClipboard = /toClipboard\s*\(/.test(ts);
  const directStorage = /wx\.(get|set|remove)StorageSync\s*\(/.test(ts);
  const usesA11y = /A11Y_DATA/.test(ts) && /syncA11y\s*\(/.test(ts);

  let jsonParses = false;
  let jsonTitle = null;
  try {
    const parsed = JSON.parse(json);
    jsonParses = true;
    jsonTitle = parsed.navigationBarTitleText ?? null;
  } catch {
    jsonParses = false;
  }

  const fontLines = wxss.split(/\r?\n/).filter((line) => line.includes('font-size'));
  const fontAllScaled =
    fontLines.length > 0 && fontLines.every((line) => /calc\([^)]*var\(--mhp-scale\)\)/.test(line));
  const barePx = wxss
    .split(/\r?\n/)
    .filter((line) => /(?<![\dr])\d+px/.test(line))
    .map((line) => line.trim());
  const wxmlScaleInline = /--mhp-scale:\s*\{\{scale\}\}/.test(wxml);
  const wxmlHcClass = /is-hc/.test(wxml);

  return {
    brief_ts_exists: fs.existsSync(path.join(BRIEF_DIR, 'brief.ts')),
    brief_js_exists: fs.existsSync(path.join(BRIEF_DIR, 'brief.js')),
    forbidden_strings_present: forbidden,
    severity_tokens_present: severity,
    uses_records_api: usesRecordsApi,
    uses_brief_build: usesBriefBuild,
    uses_clipboard: usesClipboard,
    direct_storage_calls: directStorage,
    uses_a11y: usesA11y,
    json_parses: jsonParses,
    json_title: jsonTitle,
    font_size_lines: fontLines.length,
    font_size_all_scaled: fontAllScaled,
    bare_px_lines: barePx,
    wxml_scale_inline: wxmlScaleInline,
    wxml_hc_class: wxmlHcClass,
  };
}

// ---------------------------------------------------------------------------
// Layer 2: automator helpers
// ---------------------------------------------------------------------------

const captureScreenshot = makeCaptureScreenshot('brief');

const renderEvidence = makeRenderEvidence(captureScreenshot, BRIEF_ROUTE);

async function clearAllNamespaces(miniProgram) {
  for (const raw of [SYMPTOMS_RAW, NOTES_RAW, QUESTIONS_RAW, BRIEFS_RAW, PREFS_RAW]) {
    for (const ns of APP_NAMESPACES) {
      await miniProgram.callWxMethod('removeStorageSync', ns + raw);
    }
  }
}

const SEED_SYMPTOMS = [
  {
    id: 'sym_seed_1',
    createdAt: '2026-09-01T01:00:00.000Z',
    updatedAt: '2026-09-01T01:00:00.000Z',
    occurredAt: '2026-09-10T02:00:00.000Z',
    duration: '3 天',
    text: '饭后有点胀',
    impact: '没影响睡眠',
    tags: ['饭后'],
    attachment: null,
  },
  {
    id: 'sym_seed_2',
    createdAt: '2026-09-02T01:00:00.000Z',
    updatedAt: '2026-09-02T01:00:00.000Z',
    occurredAt: '2026-09-01T02:00:00.000Z',
    duration: '',
    text: '早上有点头晕',
    impact: '',
    tags: [],
    attachment: null,
  },
];
const SEED_NOTES = [
  {
    id: 'note_seed_1',
    createdAt: '2026-09-03T01:00:00.000Z',
    updatedAt: '2026-09-03T01:00:00.000Z',
    name: '体检报告',
    excerpt: '甘油三酯 2.1',
    sourceDate: '2026-08-20',
    attachment: null,
    remark: '',
  },
];
const SEED_QUESTIONS = [
  {
    id: 'ques_seed_1',
    createdAt: '2026-09-04T01:00:00.000Z',
    updatedAt: '2026-09-04T01:00:00.000Z',
    text: '复查时间怎么安排',
    done: false,
    group: '复查',
    source: 'manual',
  },
];

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  ensureDir(E2E_DIR);
  ensureDir(path.dirname(QA_FAILURE_PATH));
  section('BRIEF SPEC');

  const logic = runLogicHarness();
  const logicScenarios = logic.result ? logic.result.scenarios : [];
  const logicFailed = logic.result ? logic.result.summary.failed : -1;

  if (logic.failure_raw !== '') {
    fs.writeFileSync(QA_FAILURE_PATH, logic.failure_raw);
    log(`failure evidence: ${QA_FAILURE_PATH}`);
  }

  const report = {
    command: 'E2E_DEVTOOLS_MINIMIZE=1 node tests/e2e/brief.spec.mjs (cold)',
    timestamp: new Date().toISOString(),
    platform: `${os.platform()} ${os.release()} (${os.arch()})`,
    node_version: process.version,
    project_path: CONFIG.projectPath,
    logic: {
      method: logic.method,
      brief_ts: logic.brief_ts,
      exit: logic.exit,
      result: logic.result,
    },
    render: null,
    render_seeded: null,
    namespace: null,
    storage_readback: null,
    persistence: null,
    static_invariants: null,
    summary: null,
  };

  let allOk = true;

  if (logic.result !== null && logic.exit === 0 && logicFailed === 0) {
    ok(`logic harness: ${logic.result.summary.passed}/${logic.result.summary.total} scenarios passed (real page methods)`);
  } else {
    fail(`logic harness failed (exit=${logic.exit}, failed_scenarios=${logicFailed}); stderr tail: ${logic.stderr_tail}`);
    allOk = false;
  }
  for (const scenario of logicScenarios) {
    log(`  [logic] ${scenario.pass ? 'PASS' : 'FAIL'} ${scenario.id}: ${scenario.name}`);
    if (!scenario.pass) allOk = false;
  }

  const statics = staticInvariantChecks();
  report.static_invariants = {
    brief_ts_exists: statics.brief_ts_exists,
    brief_js_exists: statics.brief_js_exists,
    forbidden_strings_present: statics.forbidden_strings_present,
    severity_tokens_present: statics.severity_tokens_present,
    uses_records_api: statics.uses_records_api,
    uses_brief_build: statics.uses_brief_build,
    uses_clipboard: statics.uses_clipboard,
    direct_storage_calls: statics.direct_storage_calls,
    uses_a11y: statics.uses_a11y,
    json_parses: statics.json_parses,
    json_title: statics.json_title,
    font_size_lines: statics.font_size_lines,
    font_size_all_scaled: statics.font_size_all_scaled,
    bare_px_lines: statics.bare_px_lines,
    wxml_scale_inline: statics.wxml_scale_inline,
    wxml_hc_class: statics.wxml_hc_class,
  };
  const staticsOk =
    statics.brief_ts_exists === true &&
    statics.brief_js_exists === false &&
    statics.forbidden_strings_present.length === 0 &&
    statics.severity_tokens_present.length === 0 &&
    statics.uses_records_api === true &&
    statics.uses_brief_build === true &&
    statics.uses_clipboard === true &&
    statics.direct_storage_calls === false &&
    statics.uses_a11y === true &&
    statics.json_parses === true &&
    statics.json_title === '就医摘要' &&
    statics.font_size_all_scaled === true &&
    statics.bare_px_lines.length === 0 &&
    statics.wxml_scale_inline === true &&
    statics.wxml_hc_class === true;
  if (staticsOk) {
    ok('static invariants: records API only (+ build/toClipboard); no severity token; scale/hc wired; scaled px-free wxss');
  } else {
    fail(`static invariant failure: ${JSON.stringify(report.static_invariants)}`);
    allOk = false;
  }

  let miniProgram;
  try {
    miniProgram = await launchMiniProgram();
    await clearAllNamespaces(miniProgram);

    // warm-up + settle: the first reLaunch can race onShow render.
    await miniProgram.reLaunch('/' + BRIEF_ROUTE);
    await delay(800);
    await miniProgram.reLaunch('/' + BRIEF_ROUTE);
    await delay(800);
    const baseline = await renderEvidence(miniProgram, 'baseline');
    report.render = { ...baseline, method: 'reLaunch+pageStack+screenshot' };
    if (baseline.ok) {
      ok(`render evidence: pageStack=${baseline.pageStack}, top=${baseline.topPath}, bytes=${baseline.screenshotBytes}`);
    } else {
      fail(`render check failed: ${JSON.stringify(baseline)}`);
      allOk = false;
    }

    // positive: seeded mhp_ records change the render (empty -> selectable lists)
    await miniProgram.callWxMethod('setStorageSync', 'mhp_' + SYMPTOMS_RAW, SEED_SYMPTOMS);
    await miniProgram.callWxMethod('setStorageSync', 'mhp_' + NOTES_RAW, SEED_NOTES);
    await miniProgram.callWxMethod('setStorageSync', 'mhp_' + QUESTIONS_RAW, SEED_QUESTIONS);
    await miniProgram.reLaunch('/' + BRIEF_ROUTE);
    await delay(800);
    const seeded = await renderEvidence(miniProgram, 'seeded');
    const mhpChanged = seeded.screenshotMd5 !== baseline.screenshotMd5;
    report.render_seeded = { ...seeded, namespace: 'mhp_', changed_vs_baseline_md5: mhpChanged };
    if (seeded.ok && mhpChanged) {
      ok(`seeded mhp_ records change the render (md5 ${baseline.screenshotMd5} -> ${seeded.screenshotMd5})`);
    } else {
      fail(`seeded render did not change / render failed: ${JSON.stringify(report.render_seeded)}`);
      allOk = false;
    }

    // read-back: seeded records survive the page render unchanged
    const readBackSymptoms = await miniProgram.callWxMethod('getStorageSync', 'mhp_' + SYMPTOMS_RAW);
    const readBackNotes = await miniProgram.callWxMethod('getStorageSync', 'mhp_' + NOTES_RAW);
    const readBackQuestions = await miniProgram.callWxMethod('getStorageSync', 'mhp_' + QUESTIONS_RAW);
    const readBackOk =
      JSON.stringify(readBackSymptoms) === JSON.stringify(SEED_SYMPTOMS) &&
      JSON.stringify(readBackNotes) === JSON.stringify(SEED_NOTES) &&
      JSON.stringify(readBackQuestions) === JSON.stringify(SEED_QUESTIONS);
    report.storage_readback = {
      keys: ['mhp_' + SYMPTOMS_RAW, 'mhp_' + NOTES_RAW, 'mhp_' + QUESTIONS_RAW],
      symptoms: { written: SEED_SYMPTOMS, read_back: readBackSymptoms },
      notes: { written: SEED_NOTES, read_back: readBackNotes },
      questions: { written: SEED_QUESTIONS, read_back: readBackQuestions },
      matches: readBackOk,
    };
    if (readBackOk) {
      ok('seed read-back: stored records match after the page rendered');
    } else {
      fail('seed read-back mismatch');
      allOk = false;
    }

    // negative control: legacy hza_ namespace must NOT change the render
    await miniProgram.callWxMethod('removeStorageSync', 'mhp_' + SYMPTOMS_RAW);
    await miniProgram.callWxMethod('removeStorageSync', 'mhp_' + NOTES_RAW);
    await miniProgram.callWxMethod('removeStorageSync', 'mhp_' + QUESTIONS_RAW);
    await miniProgram.callWxMethod('setStorageSync', 'hza_' + SYMPTOMS_RAW, SEED_SYMPTOMS);
    await miniProgram.callWxMethod('setStorageSync', 'hza_' + NOTES_RAW, SEED_NOTES);
    await miniProgram.callWxMethod('setStorageSync', 'hza_' + QUESTIONS_RAW, SEED_QUESTIONS);
    await miniProgram.reLaunch('/' + BRIEF_ROUTE);
    await delay(800);
    const legacyShot = await renderEvidence(miniProgram, 'legacy-hza');
    await miniProgram.callWxMethod('removeStorageSync', 'hza_' + SYMPTOMS_RAW);
    await miniProgram.callWxMethod('removeStorageSync', 'hza_' + NOTES_RAW);
    await miniProgram.callWxMethod('removeStorageSync', 'hza_' + QUESTIONS_RAW);
    const hzaChanged = legacyShot.screenshotMd5 !== baseline.screenshotMd5;
    report.namespace = {
      declared: 'mhp_',
      candidates: APP_NAMESPACES,
      runtime_observed: mhpChanged && !hzaChanged ? 'mhp_' : null,
      empty_baseline_md5: baseline.screenshotMd5,
      observations: {
        mhp_: { md5: seeded.screenshotMd5, bytes: seeded.screenshotBytes, changed_vs_baseline: mhpChanged },
        hza_: { md5: legacyShot.screenshotMd5, bytes: legacyShot.screenshotBytes, changed_vs_baseline: hzaChanged },
      },
    };
    if (report.namespace.runtime_observed === 'mhp_') {
      ok('runtime namespace is "mhp_" (mhp_ write changes render; hza_ does not)');
    } else {
      fail(`runtime namespace must be "mhp_" but observed ${JSON.stringify(report.namespace)}`);
      allOk = false;
    }

    // persistence across full close + relaunch
    const seededBrief = [
      {
        id: 'brief_seed_1',
        createdAt: '2026-09-25T01:00:00.000Z',
        updatedAt: '2026-09-25T01:00:00.000Z',
        content: '【症状时间线】\n早上有点头晕',
        sourceIds: ['sym_seed_2'],
        exportedAt: '2026-09-25T01:00:00.000Z',
      },
    ];
    await miniProgram.callWxMethod('setStorageSync', 'mhp_' + SYMPTOMS_RAW, SEED_SYMPTOMS);
    await miniProgram.callWxMethod('setStorageSync', 'mhp_' + NOTES_RAW, SEED_NOTES);
    await miniProgram.callWxMethod('setStorageSync', 'mhp_' + QUESTIONS_RAW, SEED_QUESTIONS);
    await miniProgram.callWxMethod('setStorageSync', 'mhp_' + BRIEFS_RAW, seededBrief);
    await miniProgram.reLaunch('/' + BRIEF_ROUTE);
    await delay(800);
    try {
      await miniProgram.close();
      log('miniProgram.close() done');
    } catch (err) {
      log(`warning: close failed: ${err?.message || err}`);
    }
    await delay(2000);
    miniProgram = await launchMiniProgram();
    const persistedSymptoms = await miniProgram.callWxMethod('getStorageSync', 'mhp_' + SYMPTOMS_RAW);
    const persistedNotes = await miniProgram.callWxMethod('getStorageSync', 'mhp_' + NOTES_RAW);
    const persistedBrief = await miniProgram.callWxMethod('getStorageSync', 'mhp_' + BRIEFS_RAW);
    const persistedOk =
      JSON.stringify(persistedSymptoms) === JSON.stringify(SEED_SYMPTOMS) &&
      JSON.stringify(persistedNotes) === JSON.stringify(SEED_NOTES) &&
      JSON.stringify(persistedBrief) === JSON.stringify(seededBrief);
    report.persistence = {
      keys: ['mhp_' + SYMPTOMS_RAW, 'mhp_' + NOTES_RAW, 'mhp_' + BRIEFS_RAW],
      symptoms: persistedSymptoms,
      notes: persistedNotes,
      briefs: persistedBrief,
      matches: persistedOk,
      persisted_after_relaunch: persistedOk,
    };
    if (persistedOk) {
      ok('seeded records (incl. a VisitBrief) persist across full close+relaunch');
    } else {
      fail('seeded records did not persist across relaunch');
      allOk = false;
    }

    await clearAllNamespaces(miniProgram);
  } catch (err) {
    fail(`brief spec run error: ${err?.stack || err}`);
    report.error = err?.message || String(err);
    allOk = false;
  } finally {
    if (miniProgram) {
      try {
        await miniProgram.close();
        log('miniProgram.close() done');
      } catch (err) {
        log(`warning: miniProgram.close() failed: ${err?.message || err}`);
      }
    }
  }

  const checks = {
    logic_harness_ok: logic.result !== null && logic.exit === 0 && logicFailed === 0,
    render_ok: report.render ? report.render.ok === true : false,
    seeded_render_changed: Boolean(report.render_seeded && report.render_seeded.changed_vs_baseline_md5 === true),
    namespace_observed: report.namespace ? report.namespace.runtime_observed === 'mhp_' : false,
    storage_readback_ok: Boolean(report.storage_readback && report.storage_readback.matches === true),
    persistence_ok: Boolean(report.persistence && report.persistence.persisted_after_relaunch === true),
    static_invariants_ok: staticsOk,
    no_forbidden_strings: statics.forbidden_strings_present.length === 0,
    no_severity_token: statics.severity_tokens_present.length === 0,
    font_scaled: statics.font_size_all_scaled === true && statics.bare_px_lines.length === 0,
    json_ok: statics.json_parses === true && statics.json_title === '就医摘要',
  };
  const checksPassed = Object.values(checks).every((v) => v === true);
  log(`summary checks: ${JSON.stringify(checks)}`);

  report.summary = {
    ...checks,
    logic_scenarios_total: logic.result ? logic.result.summary.total : 0,
    logic_scenarios_passed: logic.result ? logic.result.summary.passed : 0,
    passed: checksPassed && allOk === true,
    failed: !(checksPassed && allOk === true),
  };

  const reportPath = path.join(E2E_DIR, 'brief.json');
  fs.writeFileSync(reportPath, JSON.stringify(report, null, 2) + '\n');
  log(`brief evidence: ${reportPath}`);

  return report.summary.passed;
}

main().then(
  (passed) => {
    process.exit(passed ? 0 : 1);
  },
  (err) => {
    console.error(`[e2e] FAIL ${err?.stack || err}`);
    process.exit(1);
  }
);
