// brief-image.spec.mjs — task 21: brief poster image export (canvas) E2E (standalone).
//
// Run: node tests/e2e/brief-image.spec.mjs
//      E2E_DEVTOOLS_MINIMIZE=1 node tests/e2e/brief-image.spec.mjs   (cold, hidden)
// Evidence: artifacts/e2e/brief-image.json
//           artifacts/screenshots/brief-image.png   (the REAL 750x1334 export, read back)
//           artifacts/qa/21-failure.txt             (album-denied -> settings guidance transcript)
//
// Two independent layers, never conflated:
//   (1) LOGIC (real code path): pages/brief/brief.ts + shared/services/poster.ts are imported
//       into a node harness (Page-capture + a Map-backed wx shim with storage + toast/modal +
//       a canvas selector-query shim + controllable canvasToTempFilePath/saveImageToPhotosAlbum
//       failure switches). It asserts the PURE draw plan (750x1334, exact header/footer/body,
//       deterministic wrapping, no forbidden token) and drives the REAL page methods
//       (生成 -> onExportImage -> previewPath + canvasToTempFilePath options + drawn texts;
//        onSaveImage success / auth-deny -> settings guidance / other failure; guard paths;
//        onShareAppMessage).
//   (2) RUNTIME (REAL, via miniProgram.evaluate): seeds records + a profile, reLaunch to
//       pages/brief, then drives the REAL flow INSIDE the app (onSelectAll -> onGenerate ->
//       await onExportImage), reads page.data.previewPath, reads the exported file back as
//       base64 (wx.getFileSystemManager().readFileSync(path,'base64')), writes it to
//       artifacts/screenshots/brief-image.png and asserts PNG magic + IHDR 750x1334. The album
//       path is exercised with the REAL wx.saveImageToPhotosAlbum (recorded honestly) AND the
//       denied -> guidance branch is proven deterministically with a stubbed host API inside an
//       evaluate call (labeled "runtime with stubbed host API"). Success is never faked.
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {
  CONFIG,
  E2E_ARTIFACTS,
  ROOT,
  ensureDir,
  fail,
  launchMiniProgram,
  log,
  ok,
  section,
  delay,
  md5,
  readSafe,
  withTimeout,
  hasPngMagic,
  makeCaptureScreenshot,
  makeRenderEvidence,
} from './helpers.mjs';

const BRIEF_ROUTE = 'pages/brief/brief';
const APP_NAMESPACES = ['mhp_', 'hza_'];
const SYMPTOMS_RAW = 'records_symptoms';
const NOTES_RAW = 'records_notes';
const QUESTIONS_RAW = 'records_questions';
const PROFILE_RAW = 'records_profile';

const E2E_DIR = E2E_ARTIFACTS;
const QA_FAILURE_PATH = path.join(ROOT, 'artifacts', 'qa', '21-failure.txt');
const SCREENSHOT_DIR = path.join(ROOT, 'artifacts', 'screenshots');
const POSTER_IMAGE_PATH = path.join(SCREENSHOT_DIR, 'brief-image.png');
const MINIAPP_ROOT = CONFIG.projectPath;
const BRIEF_DIR = path.join(MINIAPP_ROOT, 'pages', 'brief');
const POSTER_TS = path.join(MINIAPP_ROOT, 'shared', 'services', 'poster.ts');
const TEXTS_TS = path.join(MINIAPP_ROOT, 'config', 'texts.ts');


// ---------------------------------------------------------------------------
// Layer 1: node/page-logic harness (real page methods + Map wx shim + canvas shim)
// ---------------------------------------------------------------------------

const HARNESS_SOURCE = String.raw`// temp brief-image logic harness (run via tsx); not committed — generated by brief-image.spec.mjs
import { pathToFileURL } from 'node:url';
import { writeFileSync } from 'node:fs';
import path from 'node:path';
const { clone, makeCheck, makeFlog, makeInstanceFactory, makeLastToast, makeLastToastIsSuccess } = await import(${JSON.stringify(new URL('./helpers.mjs', import.meta.url).href)});

const briefTs = process.env.MHP_BRIEF_TS;
const posterTs = process.env.MHP_POSTER_TS;
const root = process.env.MHP_MINIAPP_ROOT;
const outPath = process.env.MHP_HARNESS_OUT;
const failureOut = process.env.MHP_FAILURE_OUT;
if (!briefTs || !posterTs || !root || !outPath) throw new Error('missing harness env');

const TEMP_PATH = '/tmp/mhp-brief-poster-mock.png';
const store = new Map();
const calls = { toast: [], modal: [], vibrateShort: [], clipboard: [], loading: [], canvasToTemp: [], saveAlbum: [], openSetting: [] };
let clipboardShouldFail = false;
let albumMode = 'ok';
let canvasToTempShouldFail = false;
const canvasState = { ctx: null, node: null };

function makeCtx() {
  return {
    fillStyle: '', strokeStyle: '', lineWidth: 0, font: '', textAlign: '', textBaseline: '',
    rects: [], lines: [], texts: [],
    fillRect: function (x, y, w, h) { this.rects.push({ x: x, y: y, w: w, h: h }); },
    fillText: function (t, x, y) { this.texts.push({ text: t, x: x, y: y }); },
    beginPath: function () {}, moveTo: function () {}, lineTo: function () {}, arcTo: function () {},
    closePath: function () {}, fill: function () {}, stroke: function () {},
  };
}

globalThis.wx = {
  getStorageSync: function (k) { return store.has(k) ? store.get(k) : ''; },
  setStorageSync: function (k, v) { store.set(k, v); },
  removeStorageSync: function (k) { store.delete(k); },
  getStorageInfoSync: function () { return { keys: Array.from(store.keys()) }; },
  showToast: function (o) { calls.toast.push(o); },
  showModal: function (o) { calls.modal.push(o); if (o && typeof o.success === 'function') o.success({ confirm: true, cancel: false }); },
  showLoading: function (o) { calls.loading.push(o); },
  hideLoading: function () {},
  vibrateShort: function (o) { calls.vibrateShort.push(o || {}); },
  vibrateLong: function () {},
  setClipboardData: function (o) {
    calls.clipboard.push(o && o.data);
    if (clipboardShouldFail) { if (o && typeof o.fail === 'function') o.fail({ errMsg: 'setClipboardData:fail mock' }); }
    else if (o && typeof o.success === 'function') o.success({ errMsg: 'setClipboardData:ok' });
  },
  openSetting: function (o) { calls.openSetting.push(true); if (o && typeof o.success === 'function') o.success({ authSetting: {} }); },
  createSelectorQuery: function () {
    return {
      select: function (sel) { this._sel = sel; return this; },
      fields: function (f) { this._fields = f; return this; },
      exec: function (cb) {
        const ctx = makeCtx();
        const node = { width: 0, height: 0, getContext: function () { return ctx; } };
        canvasState.ctx = ctx; canvasState.node = node;
        if (cb) cb([{ node: node, size: { width: 750, height: 1334 } }]);
      },
    };
  },
  canvasToTempFilePath: function (o) {
    calls.canvasToTemp.push({ hasCanvas: !!(o && o.canvas), x: o.x, y: o.y, width: o.width, height: o.height, destWidth: o.destWidth, destHeight: o.destHeight, fileType: o.fileType });
    if (canvasToTempShouldFail) { if (o && typeof o.fail === 'function') o.fail({ errMsg: 'canvasToTempFilePath:fail mock' }); return; }
    if (o && typeof o.success === 'function') o.success({ tempFilePath: TEMP_PATH, errMsg: 'canvasToTempFilePath:ok' });
  },
  saveImageToPhotosAlbum: function (o) {
    calls.saveAlbum.push({ filePath: o && o.filePath });
    if (albumMode === 'ok') { if (o && typeof o.success === 'function') o.success({ errMsg: 'saveImageToPhotosAlbum:ok' }); return; }
    const errMsg = albumMode === 'deny' ? 'saveImageToPhotosAlbum:fail auth deny' : (albumMode === 'cancel' ? 'saveImageToPhotosAlbum:fail cancel' : 'saveImageToPhotosAlbum:fail disk error');
    if (o && typeof o.fail === 'function') o.fail({ errMsg: errMsg });
  },
};

let captured = null;
globalThis.Page = function (config) { captured = config; };

const posterModule = await import(pathToFileURL(posterTs).href);
await import(pathToFileURL(briefTs).href);
if (captured === null) throw new Error('brief.ts did not call Page()');

const recordsModule = await import(pathToFileURL(path.join(root, 'shared/services/records.ts')).href);
const records = recordsModule.records;

const makeInstance = makeInstanceFactory(() => captured, { cloneExtras: false });
function resetAll() {
  store.clear(); clipboardShouldFail = false; albumMode = 'ok'; canvasToTempShouldFail = false;
  calls.toast.length = 0; calls.modal.length = 0; calls.vibrateShort.length = 0; calls.clipboard.length = 0;
  calls.canvasToTemp.length = 0; calls.saveAlbum.length = 0; calls.openSetting.length = 0; calls.loading.length = 0;
  canvasState.ctx = null; canvasState.node = null;
}
const lastToast = makeLastToast(calls);
const lastToastIsSuccess = makeLastToastIsSuccess(calls);
function ctxTexts() { return canvasState.ctx ? canvasState.ctx.texts.map(function (t) { return t.text; }) : []; }

const cases = [];
const check = makeCheck(cases);
const posterCopy = clone(captured.data.poster);

function seedBasics() {
  records.symptoms.add({ occurredAt: '2026-09-10T02:00:00.000Z', duration: '3 天', text: '饭后有点胀', impact: '没影响睡眠', tags: ['饭后'], attachment: null });
  records.symptoms.add({ occurredAt: '2026-09-01T02:00:00.000Z', duration: '', text: '早上有点头晕', impact: '', tags: [], attachment: null });
  records.notes.add({ name: '体检报告', excerpt: '甘油三酯 2.1', sourceDate: '2026-08-20', attachment: null, remark: '' });
}

const FORBIDDEN = ['AI 结论', '医疗级', '处方', '确诊', '疗效保证', '推荐医生', '推荐医院', '预约挂号', '智能分诊'];

// ----- pure poster plan -----
const plan = posterModule.buildPosterPlan({ body: '【症状时间线】\n早上有点头晕\n饭后有点胀', generatedAt: '2026-09-27 03:30' });
check('plan-size', 'plan: 750 x 1334', plan.width === 750 && plan.height === 1334, { width: plan.width, height: plan.height });
check('plan-header', 'plan header is the fixed title', plan.header === '就医准备助手', { header: plan.header });
check('plan-footer-notice', 'plan footer notice is the fixed disclaimer', plan.footer.notice === '用户自述 / 待医生确认', { notice: plan.footer.notice });
check('plan-footer-time', 'plan footer carries the generated-at label', plan.footer.generatedAt === '生成时间：2026-09-27 03:30', { generatedAt: plan.footer.generatedAt });
check('plan-body-lines', 'plan body lines are deterministic', JSON.stringify(plan.bodyLines) === JSON.stringify(['【症状时间线】', '早上有点头晕', '饭后有点胀']), { bodyLines: plan.bodyLines });
const planTexts = posterModule.planTexts(plan);
const hasHeaderText = planTexts.indexOf('就医准备助手') !== -1;
const hasFooterText = planTexts.indexOf('用户自述 / 待医生确认') !== -1 && planTexts.some(function (t) { return t.indexOf('生成时间：') === 0; });
const hasBodyText = planTexts.some(function (t) { return t === '饭后有点胀'; });
check('plan-command-texts', 'plan commands carry header + body + footer texts', hasHeaderText && hasFooterText && hasBodyText, { planTexts: planTexts });
const planForbidden = FORBIDDEN.filter(function (w) { return JSON.stringify(plan).indexOf(w) !== -1; });
check('plan-no-forbidden', 'plan contains no forbidden token', planForbidden.length === 0, { hits: planForbidden });

const wrapCjk = posterModule.wrapBodyLines('甲'.repeat(30), 23);
check('wrap-cjk', 'wrap: CJK fills exactly the per-line budget', wrapCjk.length === 2 && wrapCjk[0].length === 23 && wrapCjk[1].length === 7 && wrapCjk.join('') === '甲'.repeat(30), { line_lengths: wrapCjk.map(function (l) { return l.length; }) });
const wrapEmoji = posterModule.wrapBodyLines('😀😀😀', 2);
check('wrap-surrogate', 'wrap: surrogate pairs are never split', wrapEmoji.length === 3 && wrapEmoji.every(function (l) { return l === '😀'; }), { lines: wrapEmoji });
const wrapWord = posterModule.wrapBodyLines('abcdefghij', 4);
check('wrap-longword', 'wrap: an over-budget word hard-splits by code point', JSON.stringify(wrapWord) === JSON.stringify(['abcd', 'efgh', 'ij']), { lines: wrapWord });
const wrapAscii = posterModule.wrapBodyLines('hello world', 8);
check('wrap-ascii', 'wrap: ASCII words stay whole when they fit', JSON.stringify(wrapAscii) === JSON.stringify(['hello ', 'world']), { lines: wrapAscii });
check('plan-fits-summary', 'plan: a realistic summary is NOT truncated (auto-fit picks a font that fits)', plan.bodyOverflow === false, { overflow: plan.bodyOverflow, fontPx: plan.bodyFontPx });
const bigPlan = posterModule.buildPosterPlan({ body: '乙'.repeat(34 * 40), generatedAt: 't' });
check('plan-overflow', 'plan: an extremely long body truncates at the smallest font with an ellipsis', bigPlan.bodyOverflow === true && bigPlan.bodyLines.length >= 1 && bigPlan.bodyLines[bigPlan.bodyLines.length - 1].slice(-1) === '…', { overflow: bigPlan.bodyOverflow, lines: bigPlan.bodyLines.length, fontPx: bigPlan.bodyFontPx });

// ----- real page methods: generate + export -----
resetAll();
let inst = makeInstance();
records.profile.add({ name: '张三', ageRange: '60-69', allergies: '', medications: '降压药', history: '' });
seedBasics();
inst.onShow();
inst.onSelectAll();
const gen = inst.onGenerate();
check('page-generate', 'page: 生成 fills the editor from the selected records (build())', gen.generated === true && inst.data.content.indexOf('饭后有点胀') !== -1 && inst.data.content.indexOf('称呼：张三') !== -1, { generated: gen.generated, has_body: inst.data.content.indexOf('饭后有点胀') !== -1 });

const exp = await inst.onExportImage();
const opts = calls.canvasToTemp[0] || {};
const ctxTextsAfter = ctxTexts();
const exportOk = exp.exported === true && exp.path === TEMP_PATH && inst.data.previewPath === TEMP_PATH &&
  inst.data.exporting === false && inst.data.hint === posterCopy.exportDone &&
  calls.canvasToTemp.length === 1 && opts.destWidth === 750 && opts.destHeight === 1334 &&
  opts.width === 750 && opts.height === 1334 && opts.hasCanvas === true &&
  canvasState.node !== null && canvasState.node.width === 750 && canvasState.node.height === 1334;
check('page-export-ok', 'page: onExportImage draws + exports a 750x1334 temp file into previewPath', exportOk,
  { exported: exp.exported, path: exp.path, previewPath: inst.data.previewPath, opts: opts, canvasSize: canvasState.node ? { w: canvasState.node.width, h: canvasState.node.height } : null });
check('page-export-draws-header', 'page: canvas received the header text', ctxTextsAfter.indexOf('就医准备助手') !== -1, { texts: ctxTextsAfter.slice(0, 4) });
check('page-export-draws-body', 'page: canvas received the summary body text', ctxTextsAfter.some(function (t) { return t.indexOf('饭后有点胀') !== -1; }), { body_texts: ctxTextsAfter.filter(function (t) { return t.indexOf('饭后') !== -1; }) });
const footerDrawn = ctxTextsAfter.indexOf('用户自述 / 待医生确认') !== -1 && ctxTextsAfter.some(function (t) { return t.indexOf('生成时间：') === 0; });
check('page-export-draws-footer', 'page: canvas received footer time + the fixed disclaimer', footerDrawn, { footer: ctxTextsAfter.filter(function (t) { return t.indexOf('生成时间') === 0 || t.indexOf('用户自述') === 0; }) });
const drawnForbidden = FORBIDDEN.filter(function (w) { return ctxTextsAfter.join(' ').indexOf(w) !== -1; });
check('page-export-no-forbidden', 'page: rendered texts contain no forbidden token', drawnForbidden.length === 0, { hits: drawnForbidden });

albumMode = 'ok';
const saveOk = await inst.onSaveImage();
check('page-save-ok', 'page: onSaveImage success -> success toast + hint', saveOk === true && inst.data.hint === posterCopy.saveImageDone && lastToast() === posterCopy.saveImageDone && lastToastIsSuccess() === true && calls.saveAlbum.length === 1 && calls.saveAlbum[0].filePath === TEMP_PATH,
  { saved: saveOk, toast: lastToast(), album: calls.saveAlbum });

const modalBefore = calls.modal.length;
const openBefore = calls.openSetting.length;
albumMode = 'deny';
const savedDenied = await inst.onSaveImage();
const deniedModal = calls.modal[calls.modal.length - 1] || {};
const deniedFacts = {
  returned: savedDenied,
  modal_title: deniedModal.title,
  modal_content: deniedModal.content,
  modal_confirm: deniedModal.confirmText,
  open_setting_called: calls.openSetting.length - openBefore,
  error_text: inst.data.errorText,
};
check('page-save-denied-guidance', 'page: album auth deny -> showModal settings guidance -> openSetting', savedDenied === false && calls.modal.length === modalBefore + 1 && deniedModal.title === posterCopy.permissionTitle && deniedModal.content === posterCopy.permissionContent && deniedModal.confirmText === posterCopy.permissionConfirm && calls.openSetting.length === openBefore + 1 && inst.data.errorText === posterCopy.permissionHint,
  deniedFacts);

albumMode = 'other';
const savedOther = await inst.onSaveImage();
check('page-save-other-fail', 'page: non-auth album failure -> error hint, no extra guidance modal', savedOther === false && inst.data.errorText === posterCopy.saveImageFailed && calls.modal.length === modalBefore + 1 && lastToastIsSuccess() === false,
  { saved: savedOther, error: inst.data.errorText });

albumMode = 'cancel';
const savedCancel = await inst.onSaveImage();
check('page-save-cancel', 'page: user cancels album save -> false, no success toast', savedCancel === false && lastToastIsSuccess() === false, { saved: savedCancel });

inst.onContentInput({ detail: { value: '   ' } });
const canvasBefore = calls.canvasToTemp.length;
const expEmpty = await inst.onExportImage();
check('page-export-empty-guard', 'page: empty content -> export refused, no canvas call', expEmpty.exported === false && calls.canvasToTemp.length === canvasBefore && inst.data.errorText === posterCopy.exportEmpty,
  { exported: expEmpty.exported, error: inst.data.errorText, canvas_calls: calls.canvasToTemp.length });
albumMode = 'ok';
inst.setData({ previewPath: '' });
const albumBefore = calls.saveAlbum.length;
const saveNoPreview = await inst.onSaveImage();
check('page-save-no-preview-guard', 'page: no preview -> save refused', saveNoPreview === false && calls.saveAlbum.length === albumBefore && inst.data.errorText === posterCopy.exportFirst,
  { saved: saveNoPreview, error: inst.data.errorText });

resetAll();
inst = makeInstance();
seedBasics();
inst.onShow();
inst.onSelectAll();
inst.onGenerate();
canvasToTempShouldFail = true;
const expFail = await inst.onExportImage();
check('page-export-fail', 'page: canvasToTempFilePath failure -> error hint, exporting reset', expFail.exported === false && inst.data.errorText === posterCopy.exportFailed && inst.data.exporting === false,
  { exported: expFail.exported, error: inst.data.errorText, exporting: inst.data.exporting });
canvasToTempShouldFail = false;

const share = inst.onShareAppMessage();
check('page-share', 'page: onShareAppMessage returns a title + the brief path', !!share && share.title === posterCopy.shareTitle && share.path === '/pages/brief/brief', { share: share });

const failed = cases.filter(function (c) { return !c.pass; }).length;

const failureLines = [];
const flog = makeFlog(failureLines);
flog('T21 brief-image failure-path evidence (album permission denied -> settings guidance; real page method + canvas shim)');
flog('command: node tests/e2e/brief-image.spec.mjs');
flog('timestamp: ' + new Date().toISOString());
flog('method: REAL onShow/onSelectAll/onGenerate/onExportImage/onSaveImage/onShareAppMessage from pages/brief/brief.ts; wx = Map-backed shim (storage + modal + canvas selector query + canvasToTempFilePath + saveImageToPhotosAlbum with a deny switch + openSetting)');
flog('scenario: album auth denied (host returns saveImageToPhotosAlbum:fail auth deny)');
flog('denied_returned: ' + deniedFacts.returned);
flog('denied_modal_title: ' + JSON.stringify(deniedFacts.modal_title) + ' (expected ' + JSON.stringify(posterCopy.permissionTitle) + ')');
flog('denied_modal_content: ' + JSON.stringify(deniedFacts.modal_content));
flog('denied_modal_confirm: ' + JSON.stringify(deniedFacts.modal_confirm));
flog('denied_open_setting_called: ' + deniedFacts.open_setting_called);
flog('denied_error_text: ' + JSON.stringify(deniedFacts.error_text));
flog('scenario: empty content export refused (no canvas call, no fake success)');
flog('evidence: an auth-denied album save surfaces a settings modal (permissionTitle/permissionContent/permissionConfirm) and calls wx.openSetting on confirm; the failure branch never shows a success toast.');
flog('verdict: PASS (album denial -> settings guidance; empty export refused; canvas failure surfaced)');
flog('exit_code_evidence: artifacts/qa/21-failure.txt is written by the passing run (contract: surface failure + settings guidance, never fake success).');

if (failureOut) writeFileSync(failureOut, failureLines.join('\n') + '\n');

const result = {
  generated_at: new Date().toISOString(),
  brief_ts: briefTs,
  poster_ts: posterTs,
  note: 'REAL page methods from pages/brief/brief.ts; wx = Map-backed shim (storage + modal + canvas selector query + saveImageToPhotosAlbum deny switch + openSetting)',
  scenarios: cases,
  failure_path: {
    lines: failureLines,
    pass: savedDenied === false && deniedFacts.modal_title === posterCopy.permissionTitle && deniedFacts.open_setting_called === 1 && expEmpty.exported === false,
  },
  summary: { total: cases.length, passed: cases.length - failed, failed: failed },
};
writeFileSync(outPath, JSON.stringify(result, null, 2) + '\n');
console.log(JSON.stringify(result, null, 2));
process.exit(failed === 0 ? 0 : 1);
`;

function runLogicHarness() {
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'mhp-brief-image-harness-'));
  const harnessPath = path.join(tmpDir, 'brief-image-logic.harness.mjs');
  const outPath = path.join(tmpDir, 'brief-image-logic.result.json');
  const failurePath = path.join(tmpDir, 'brief-image-failure.txt');
  fs.writeFileSync(harnessPath, HARNESS_SOURCE);

  const res = spawnSync(process.execPath, ['--import', 'tsx', harnessPath], {
    cwd: ROOT,
    encoding: 'utf8',
    env: {
      ...process.env,
      MHP_BRIEF_TS: path.join(BRIEF_DIR, 'brief.ts'),
      MHP_POSTER_TS: POSTER_TS,
      MHP_MINIAPP_ROOT: MINIAPP_ROOT,
      MHP_HARNESS_OUT: outPath,
      MHP_FAILURE_OUT: failurePath,
    },
    timeout: 90000,
    maxBuffer: 32 * 1024 * 1024,
  });
  const stdout = `${res.stdout || ''}`;
  const stderr = `${res.stderr || ''}`;

  let result = null;
  if (fs.existsSync(outPath)) {
    try {
      result = JSON.parse(fs.readFileSync(outPath, 'utf8'));
    } catch (err) {
      fail(`harness result JSON unparsable: ${err?.message || err}`);
    }
  }
  const failureRaw = fs.existsSync(failurePath) ? fs.readFileSync(failurePath, 'utf8') : '';
  return {
    method: 'node --import tsx <temp harness> (Page-capture + Map wx shim: storage/modal/canvas/save-album/open-setting)',
    brief_ts: path.join(BRIEF_DIR, 'brief.ts'),
    poster_ts: POSTER_TS,
    exit: res.status,
    stdout_tail: stdout.slice(-8000),
    stderr_tail: stderr.slice(-8000),
    result,
    failure_raw: failureRaw,
  };
}

// ---------------------------------------------------------------------------
// Static invariants (source-level, no runtime claim)
// ---------------------------------------------------------------------------


const FORBIDDEN_STRINGS = [
  'AI 注入',
  'hza_',
  'System Prompt',
  '系统提示词',
  '确诊',
  '处方',
  '疗效保证',
  '推荐医生',
  '推荐医院',
  '预约挂号',
  '智能分诊',
  'AI 结论',
  '医疗级',
];
const SEVERITY_TOKENS = ['severity', '严重程度', '严重度', '危急程度'];

/** Extract the POSTER copy block from config/texts.ts (so the blanket DISCLAIMERS 免责 copy is excluded). */
function posterCopyBlock() {
  const src = readSafe(TEXTS_TS);
  const start = src.indexOf('export const POSTER');
  if (start === -1) return '';
  const end = src.indexOf('} as const;', start);
  return end === -1 ? src.slice(start) : src.slice(start, end);
}

function staticInvariantChecks() {
  const ts = readSafe(path.join(BRIEF_DIR, 'brief.ts'));
  const wxml = readSafe(path.join(BRIEF_DIR, 'brief.wxml'));
  const wxss = readSafe(path.join(BRIEF_DIR, 'brief.wxss'));
  const json = readSafe(path.join(BRIEF_DIR, 'brief.json'));
  const posterSrc = readSafe(POSTER_TS);
  const posterCopy = posterCopyBlock();

  const pageScanned = [ts, wxml, wxss, json].join('\n');
  const allScanned = [pageScanned, posterSrc].join('\n');
  const forbidden = FORBIDDEN_STRINGS.filter((term) => allScanned.includes(term));
  const posterForbidden = FORBIDDEN_STRINGS.filter((term) => posterCopy.includes(term));
  const severity = SEVERITY_TOKENS.filter((term) => allScanned.includes(term));

  const usesRecordsApi = /records\.(briefs|symptoms|notes|questions|profile)\.(add|update|remove|get|list)\s*\(/.test(ts);
  const usesBriefBuild = /from '\.\.\/\.\.\/shared\/services\/brief'/.test(ts) && /\bbuild\s*\(/.test(ts);
  const usesPoster = /from '\.\.\/\.\.\/shared\/services\/poster'/.test(ts) && /buildPosterPlan\s*\(/.test(ts) && /drawPoster\s*\(/.test(ts);
  const directStorage = /wx\.(get|set|remove)StorageSync\s*\(/.test(ts);
  const usesA11y = /A11Y_DATA/.test(ts) && /syncA11y\s*\(/.test(ts);

  const canvasWired = /createSelectorQuery/.test(ts) && /#briefPoster/.test(ts);
  const exportWired = /canvasToTempFilePath/.test(ts) && /saveImageToPhotosAlbum/.test(ts) && /openSetting/.test(ts);
  const wxmlCanvas = /<canvas/.test(wxml) && /type="2d"/.test(wxml) && /id="briefPoster"/.test(wxml);
  const wxmlPreview = /<image/.test(wxml) && /previewPath/.test(wxml);
  const wxmlShare = /open-type="share"/.test(wxml);

  const posterConstants = /POSTER_WIDTH\s*=\s*750/.test(posterSrc) && /POSTER_HEIGHT\s*=\s*1334/.test(posterSrc);
  const posterNoWx = !/\bwx\./.test(posterSrc);

  let jsonParses = false;
  let jsonTitle = null;
  try {
    const parsed = JSON.parse(json);
    jsonParses = true;
    jsonTitle = parsed.navigationBarTitleText ?? null;
  } catch {
    jsonParses = false;
  }

  const fontLines = wxss.split(/\r?\n/).filter((line) => line.includes('font-size'));
  const fontAllScaled =
    fontLines.length > 0 && fontLines.every((line) => /calc\([^)]*var\(--mhp-scale\)\)/.test(line));
  const barePx = pageScanned
    ? wxss
        .split(/\r?\n/)
        .filter((line) => /(?<![\dr])\d+px/.test(line))
        .map((line) => line.trim())
    : [];
  const wxmlScaleInline = /--mhp-scale:\s*\{\{scale\}\}/.test(wxml);
  const wxmlHcClass = /is-hc/.test(wxml);

  return {
    brief_ts_exists: fs.existsSync(path.join(BRIEF_DIR, 'brief.ts')),
    poster_ts_exists: fs.existsSync(POSTER_TS),
    texts_has_poster_block: posterCopy.length > 0,
    poster_uses_poster_copy: /from '\.\.\/\.\.\/config\/texts'/.test(posterSrc) && /POSTER\./.test(posterSrc),
    forbidden_strings_present: forbidden,
    poster_copy_forbidden_present: posterForbidden,
    severity_tokens_present: severity,
    uses_records_api: usesRecordsApi,
    uses_brief_build: usesBriefBuild,
    uses_poster: usesPoster,
    direct_storage_calls: directStorage,
    uses_a11y: usesA11y,
    canvas_wired: canvasWired,
    export_wired: exportWired,
    wxml_canvas: wxmlCanvas,
    wxml_preview: wxmlPreview,
    wxml_share: wxmlShare,
    poster_constants: posterConstants,
    poster_no_wx: posterNoWx,
    json_parses: jsonParses,
    json_title: jsonTitle,
    font_size_lines: fontLines.length,
    font_size_all_scaled: fontAllScaled,
    bare_px_lines: barePx,
    wxml_scale_inline: wxmlScaleInline,
    wxml_hc_class: wxmlHcClass,
  };
}

// ---------------------------------------------------------------------------
// Layer 2: automator helpers
// ---------------------------------------------------------------------------


/**
 * Race an automator promise against a timeout. The automator Connection has NO reply
 * timeout, so a host call that never invokes its callback (e.g. the devtools album path
 * behind a hidden window) would otherwise hang the whole spec. Resolves — never rejects —
 * with { timedOut } or { value } / { error } so callers can record the truth honestly.
 */

/** Parse width/height from the PNG IHDR (no deps): width at bytes 16-19, height at 20-23 (big-endian). */
function parsePngSize(buffer) {
  if (!hasPngMagic(buffer) || buffer.length < 24) return { width: null, height: null };
  const type = buffer.subarray(12, 16).toString('ascii');
  if (type !== 'IHDR') return { width: null, height: null };
  return { width: buffer.readUInt32BE(16), height: buffer.readUInt32BE(20) };
}

const captureScreenshot = makeCaptureScreenshot('brief-image');

const renderEvidence = makeRenderEvidence(captureScreenshot, BRIEF_ROUTE);

async function clearAllNamespaces(miniProgram) {
  for (const raw of [SYMPTOMS_RAW, NOTES_RAW, QUESTIONS_RAW, PROFILE_RAW]) {
    for (const ns of APP_NAMESPACES) {
      await miniProgram.callWxMethod('removeStorageSync', ns + raw);
    }
  }
}

const SEED_PROFILE = [
  {
    id: 'prof_seed_1',
    createdAt: '2026-08-01T01:00:00.000Z',
    updatedAt: '2026-08-01T01:00:00.000Z',
    name: '张三',
    ageRange: '60-69',
    gender: '',
    allergies: '青霉素',
    medications: '降压药',
    history: '',
  },
];
const SEED_SYMPTOMS = [
  {
    id: 'sym_seed_1',
    createdAt: '2026-09-01T01:00:00.000Z',
    updatedAt: '2026-09-01T01:00:00.000Z',
    occurredAt: '2026-09-10T02:00:00.000Z',
    duration: '3 天',
    text: '饭后有点胀',
    impact: '没影响睡眠',
    tags: ['饭后'],
    attachment: null,
  },
  {
    id: 'sym_seed_2',
    createdAt: '2026-09-02T01:00:00.000Z',
    updatedAt: '2026-09-02T01:00:00.000Z',
    occurredAt: '2026-09-01T02:00:00.000Z',
    duration: '',
    text: '早上有点头晕',
    impact: '',
    tags: [],
    attachment: null,
  },
];
const SEED_NOTES = [
  {
    id: 'note_seed_1',
    createdAt: '2026-09-03T01:00:00.000Z',
    updatedAt: '2026-09-03T01:00:00.000Z',
    name: '体检报告',
    excerpt: '甘油三酯 2.1',
    sourceDate: '2026-08-20',
    attachment: null,
    remark: '',
  },
];
const SEED_QUESTIONS = [
  {
    id: 'ques_seed_1',
    createdAt: '2026-09-04T01:00:00.000Z',
    updatedAt: '2026-09-04T01:00:00.000Z',
    text: '复查时间怎么安排',
    done: false,
    group: '复查',
    source: 'manual',
  },
];

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  ensureDir(E2E_DIR);
  ensureDir(path.dirname(QA_FAILURE_PATH));
  ensureDir(SCREENSHOT_DIR);
  section('BRIEF IMAGE SPEC');

  const logic = runLogicHarness();
  const logicScenarios = logic.result ? logic.result.scenarios : [];
  const logicFailed = logic.result ? logic.result.summary.failed : -1;

  if (logic.failure_raw !== '') {
    fs.writeFileSync(QA_FAILURE_PATH, logic.failure_raw);
    log(`failure evidence: ${QA_FAILURE_PATH}`);
  }

  const report = {
    command: 'E2E_DEVTOOLS_MINIMIZE=1 node tests/e2e/brief-image.spec.mjs (cold)',
    timestamp: new Date().toISOString(),
    platform: `${os.platform()} ${os.release()} (${os.arch()})`,
    node_version: process.version,
    project_path: CONFIG.projectPath,
    logic: {
      method: logic.method,
      brief_ts: logic.brief_ts,
      poster_ts: logic.poster_ts,
      exit: logic.exit,
      result: logic.result,
    },
    static_invariants: null,
    evaluate_probe: null,
    drive: null,
    poster_png: null,
    album_real: null,
    album_denied_stub: null,
    render: null,
    summary: null,
  };

  let allOk = true;

  if (logic.result !== null && logic.exit === 0 && logicFailed === 0) {
    ok(`logic harness: ${logic.result.summary.passed}/${logic.result.summary.total} scenarios passed (real page methods)`);
  } else {
    fail(`logic harness failed (exit=${logic.exit}, failed_scenarios=${logicFailed}); stderr tail: ${logic.stderr_tail}`);
    allOk = false;
  }
  for (const scenario of logicScenarios) {
    log(`  [logic] ${scenario.pass ? 'PASS' : 'FAIL'} ${scenario.id}: ${scenario.name}`);
    if (!scenario.pass) allOk = false;
  }

  const statics = staticInvariantChecks();
  report.static_invariants = statics;
  const staticsOk =
    statics.brief_ts_exists === true &&
    statics.poster_ts_exists === true &&
    statics.texts_has_poster_block === true &&
    statics.poster_uses_poster_copy === true &&
    statics.forbidden_strings_present.length === 0 &&
    statics.poster_copy_forbidden_present.length === 0 &&
    statics.severity_tokens_present.length === 0 &&
    statics.uses_records_api === true &&
    statics.uses_brief_build === true &&
    statics.uses_poster === true &&
    statics.direct_storage_calls === false &&
    statics.uses_a11y === true &&
    statics.canvas_wired === true &&
    statics.export_wired === true &&
    statics.wxml_canvas === true &&
    statics.wxml_preview === true &&
    statics.wxml_share === true &&
    statics.poster_constants === true &&
    statics.poster_no_wx === true &&
    statics.json_parses === true &&
    statics.json_title === '就医摘要' &&
    statics.font_size_all_scaled === true &&
    statics.bare_px_lines.length === 0 &&
    statics.wxml_scale_inline === true &&
    statics.wxml_hc_class === true;
  if (staticsOk) {
    ok('static invariants: poster.ts pure (no wx, 750x1334); canvas/export wired; records API only; scale/hc wired; scaled px-free wxss; no forbidden token');
  } else {
    fail(`static invariant failure: ${JSON.stringify(report.static_invariants)}`);
    allOk = false;
  }

  let miniProgram;
  try {
    miniProgram = await launchMiniProgram();
    await clearAllNamespaces(miniProgram);

    await miniProgram.callWxMethod('setStorageSync', 'mhp_' + PROFILE_RAW, SEED_PROFILE);
    await miniProgram.callWxMethod('setStorageSync', 'mhp_' + SYMPTOMS_RAW, SEED_SYMPTOMS);
    await miniProgram.callWxMethod('setStorageSync', 'mhp_' + NOTES_RAW, SEED_NOTES);
    await miniProgram.callWxMethod('setStorageSync', 'mhp_' + QUESTIONS_RAW, SEED_QUESTIONS);

    // warm-up + settle (first reLaunch can race onShow render)
    await miniProgram.reLaunch('/' + BRIEF_ROUTE);
    await delay(800);
    await miniProgram.reLaunch('/' + BRIEF_ROUTE);
    await delay(800);

    // evaluate capability probe
    let probe = null;
    {
      const raced = await withTimeout(
        miniProgram.evaluate(() => {
          const pages = getCurrentPages();
          const page = pages[pages.length - 1];
          return {
            route: page.route,
            hasGenerate: typeof page.onGenerate,
            hasExport: typeof page.onExportImage,
            hasSave: typeof page.onSaveImage,
            hasShare: typeof page.onShareAppMessage,
            previewPath: typeof page.data.previewPath,
          };
        }),
        15000,
        'evaluate-probe'
      );
      if (raced.timedOut === true) {
        report.evaluate_probe = { ok: false, error: 'timed out' };
        fail('evaluate probe timed out');
        allOk = false;
      } else if (raced.error !== undefined) {
        report.evaluate_probe = { ok: false, error: raced.error };
        fail(`evaluate probe failed: ${raced.error}`);
        allOk = false;
      } else {
        probe = raced.value;
        report.evaluate_probe = { ok: true, value: probe };
        ok(`miniProgram.evaluate probe: ${JSON.stringify(probe)}`);
      }
    }

    // drive the REAL flow inside the app
    let drive = null;
    const probeOk = Boolean(probe && probe.route === BRIEF_ROUTE && probe.hasExport === 'function');
    if (probeOk) {
      const raced = await withTimeout(
        miniProgram.evaluate(async () => {
          const pages = getCurrentPages();
          const page = pages[pages.length - 1];
          page.onSelectAll();
          const gen = page.onGenerate();
          const exported = await page.onExportImage();
          return {
            generated: !!(gen && gen.generated === true),
            contentLen: typeof page.data.content === 'string' ? page.data.content.length : -1,
            previewPath: page.data.previewPath,
            exported: !!(exported && exported.exported === true),
            exportPath: exported ? exported.path : '',
            posterOverflow: page.data.posterOverflow,
          };
        }),
        20000,
        'evaluate-drive'
      );
      if (raced.timedOut === true) {
        report.drive = { error: 'timed out' };
        fail('real flow drive timed out');
        allOk = false;
      } else if (raced.error !== undefined) {
        report.drive = { error: raced.error };
        fail(`real flow drive error: ${raced.error}`);
        allOk = false;
      } else {
        drive = raced.value;
        report.drive = drive;
        const driveOk = drive && drive.generated === true && drive.exported === true && typeof drive.previewPath === 'string' && drive.previewPath !== '' && drive.previewPath === drive.exportPath && drive.posterOverflow === false;
        if (driveOk) {
          ok(`real flow driven: generated=true, previewPath=${drive.previewPath}, contentLen=${drive.contentLen}`);
        } else {
          fail(`real flow drive failed: ${JSON.stringify(drive)}`);
          allOk = false;
        }
      }
    }

    // read the exported temp file back as base64 and write the artifact PNG
    if (drive && typeof drive.previewPath === 'string' && drive.previewPath !== '') {
      const raced = await withTimeout(
        miniProgram.evaluate((p) => {
          const manager = wx.getFileSystemManager();
          const base64 = manager.readFileSync(p, 'base64');
          return { ok: typeof base64 === 'string' && base64.length > 0, base64Length: typeof base64 === 'string' ? base64.length : 0, base64: base64 };
        }, drive.previewPath),
        20000,
        'evaluate-readback'
      );
      if (raced.timedOut === true) {
        report.poster_png = { error: 'read-back timed out' };
        fail('file read-back timed out');
        allOk = false;
      } else if (raced.error !== undefined) {
        report.poster_png = { error: raced.error };
        fail(`file read-back error: ${raced.error}`);
        allOk = false;
      } else {
        const file = raced.value;
        if (file && file.ok === true && typeof file.base64 === 'string') {
          const buffer = Buffer.from(file.base64, 'base64');
          fs.writeFileSync(POSTER_IMAGE_PATH, buffer);
          const size = parsePngSize(buffer);
          const posterPng = {
            path: POSTER_IMAGE_PATH,
            source: 'wx.getFileSystemManager().readFileSync(previewPath, base64) read inside miniProgram.evaluate',
            bytes: buffer.length,
            md5: md5(buffer),
            pngMagic: hasPngMagic(buffer),
            width: size.width,
            height: size.height,
          };
          report.poster_png = posterPng;
          const pngOk = posterPng.pngMagic === true && posterPng.width === 750 && posterPng.height === 1334;
          if (pngOk) {
            ok(`exported PNG written: ${POSTER_IMAGE_PATH} (${posterPng.bytes} bytes, ${posterPng.width}x${posterPng.height}, md5 ${posterPng.md5})`);
          } else {
            fail(`exported PNG check failed: ${JSON.stringify(posterPng)}`);
            allOk = false;
          }
        } else {
          report.poster_png = { error: 'base64 read returned no data', raw: file };
          fail(`could not read the exported file: ${JSON.stringify(file)}`);
          allOk = false;
        }
      }
    }

    // deterministic denied -> guidance branch with a stubbed host API (runtime)
    if (drive && typeof drive.previewPath === 'string' && drive.previewPath !== '') {
      const raced = await withTimeout(
        miniProgram.evaluate(async () => {
          const pages = getCurrentPages();
          const page = pages[pages.length - 1];
          const originalSave = wx.saveImageToPhotosAlbum;
          const originalModal = wx.showModal;
          const originalOpen = wx.openSetting;
          const modals = [];
          let openSettingCalls = 0;
          wx.saveImageToPhotosAlbum = function (options) {
            if (options && typeof options.fail === 'function') options.fail({ errMsg: 'saveImageToPhotosAlbum:fail auth deny' });
          };
          wx.showModal = function (options) {
            modals.push({ title: options && options.title, content: options && options.content, confirmText: options && options.confirmText });
            if (options && typeof options.success === 'function') options.success({ confirm: true, cancel: false });
          };
          wx.openSetting = function (options) {
            openSettingCalls += 1;
            if (options && typeof options.success === 'function') options.success({ authSetting: {} });
          };
          let saved = false;
          try {
            saved = await page.onSaveImage();
          } finally {
            wx.saveImageToPhotosAlbum = originalSave;
            wx.showModal = originalModal;
            wx.openSetting = originalOpen;
          }
          return { saved: saved, modals: modals, openSettingCalls: openSettingCalls, errorText: page.data.errorText };
        }),
        15000,
        'evaluate-stub-denied'
      );
      if (raced.timedOut === true) {
        report.album_denied_stub = { error: 'timed out' };
        fail('album-denied stub timed out');
        allOk = false;
      } else if (raced.error !== undefined) {
        report.album_denied_stub = { error: raced.error };
        fail(`album-denied stub error: ${raced.error}`);
        allOk = false;
      } else {
        const deniedStub = raced.value;
        report.album_denied_stub = { mode: 'runtime with stubbed host API (wx.saveImageToPhotosAlbum forced auth-deny)', observed: deniedStub };
        const stubOk =
          deniedStub &&
          deniedStub.saved === false &&
          Array.isArray(deniedStub.modals) &&
          deniedStub.modals.length >= 1 &&
          typeof deniedStub.modals[0].title === 'string' &&
          deniedStub.modals[0].title.indexOf('相册权限') !== -1 &&
          typeof deniedStub.modals[0].confirmText === 'string' &&
          deniedStub.modals[0].confirmText.indexOf('设置') !== -1 &&
          deniedStub.openSettingCalls >= 1;
        if (stubOk) {
          ok(`album-denied runtime (stubbed host API): guidance modal + openSetting proven ${JSON.stringify(deniedStub.modals)}`);
        } else {
          fail(`album-denied runtime guidance not proven: ${JSON.stringify(deniedStub)}`);
          allOk = false;
        }
      }
    }

    // render evidence (captured BEFORE the risky real album call)
    {
      const raced = await withTimeout(renderEvidence(miniProgram, 'after-export'), 15000, 'render');
      if (raced.timedOut === true) {
        report.render = { error: 'timed out' };
        fail('render evidence timed out');
        allOk = false;
      } else if (raced.error !== undefined) {
        report.render = { error: raced.error };
        fail(`render evidence error: ${raced.error}`);
        allOk = false;
      } else {
        const render = raced.value;
        report.render = { ...render, method: 'reLaunch+pageStack+screenshot (after export)' };
        if (render.ok) {
          ok(`render evidence after export: top=${render.topPath}, bytes=${render.screenshotBytes}`);
        } else {
          fail(`render check failed: ${JSON.stringify(render)}`);
          allOk = false;
        }
      }
    }

    {
      const raced = await withTimeout(clearAllNamespaces(miniProgram), 10000, 'clear-namespaces');
      if (raced.timedOut === true) log('warning: clearAllNamespaces timed out');
    }

    // real album attempt LAST: in devtools the save may never call back (hidden window);
    // recorded honestly, timeout-guarded so it cannot hang the spec.
    if (drive && typeof drive.previewPath === 'string' && drive.previewPath !== '') {
      const raced = await withTimeout(
        miniProgram.evaluate(async (p) => {
          return await new Promise((resolve) => {
            wx.saveImageToPhotosAlbum({
              filePath: p,
              success: () => resolve({ ok: true, errMsg: 'saveImageToPhotosAlbum:ok' }),
              fail: (error) => resolve({ ok: false, errMsg: error && error.errMsg ? error.errMsg : String(error) }),
            });
          });
        }, drive.previewPath),
        8000,
        'evaluate-real-album'
      );
      if (raced.timedOut === true) {
        report.album_real = { mode: 'real wx.saveImageToPhotosAlbum (devtools, hidden)', observed: 'no callback within 8000ms' };
        log('real album save: no callback within 8000ms (recorded honestly)');
      } else if (raced.error !== undefined) {
        report.album_real = { mode: 'real wx.saveImageToPhotosAlbum (devtools, hidden)', error: raced.error };
        log(`real album save errored: ${raced.error}`);
      } else {
        report.album_real = { mode: 'real wx.saveImageToPhotosAlbum (devtools, hidden)', observed: raced.value };
        log(`real album save observed: ${JSON.stringify(raced.value)}`);
      }
    }
  } catch (err) {
    fail(`brief-image spec run error: ${err?.stack || err}`);
    report.error = err?.message || String(err);
    allOk = false;
  } finally {
    if (miniProgram) {
      const raced = await withTimeout(miniProgram.close(), 8000, 'close');
      if (raced.timedOut === true) log('warning: miniProgram.close() timed out');
      else if (raced.error !== undefined) log(`warning: miniProgram.close() failed: ${raced.error}`);
      else log('miniProgram.close() done');
      try {
        miniProgram.disconnect();
      } catch {
        /* socket already closed */
      }
    }
  }

  const checks = {
    logic_harness_ok: logic.result !== null && logic.exit === 0 && logicFailed === 0,
    static_invariants_ok: staticsOk,
    evaluate_probe_ok: Boolean(
      report.evaluate_probe && report.evaluate_probe.ok === true && report.evaluate_probe.value && report.evaluate_probe.value.route === BRIEF_ROUTE
    ),
    drive_real_flow_ok: Boolean(
      report.drive &&
        report.drive.generated === true &&
        report.drive.exported === true &&
        typeof report.drive.previewPath === 'string' &&
        report.drive.previewPath !== '' &&
        report.drive.posterOverflow === false
    ),
    poster_png_ok: Boolean(
      report.poster_png && report.poster_png.pngMagic === true && report.poster_png.width === 750 && report.poster_png.height === 1334
    ),
    album_denied_guidance_ok: Boolean(
      report.album_denied_stub &&
        report.album_denied_stub.observed &&
        report.album_denied_stub.observed.saved === false &&
        Array.isArray(report.album_denied_stub.observed.modals) &&
        report.album_denied_stub.observed.modals.length >= 1 &&
        report.album_denied_stub.observed.openSettingCalls >= 1
    ),
    render_ok: Boolean(report.render && report.render.ok === true),
    no_forbidden_strings: statics.forbidden_strings_present.length === 0 && statics.poster_copy_forbidden_present.length === 0,
    no_severity_token: statics.severity_tokens_present.length === 0,
    font_scaled: statics.font_size_all_scaled === true && statics.bare_px_lines.length === 0,
  };
  const checksPassed = Object.values(checks).every((v) => v === true);
  log(`summary checks: ${JSON.stringify(checks)}`);

  report.summary = {
    ...checks,
    logic_scenarios_total: logic.result ? logic.result.summary.total : 0,
    logic_scenarios_passed: logic.result ? logic.result.summary.passed : 0,
    passed: checksPassed && allOk === true,
    failed: !(checksPassed && allOk === true),
  };

  const reportPath = path.join(E2E_DIR, 'brief-image.json');
  fs.writeFileSync(reportPath, JSON.stringify(report, null, 2) + '\n');
  log(`brief-image evidence: ${reportPath}`);

  return report.summary.passed;
}

main().then(
  (passed) => {
    process.exit(passed ? 0 : 1);
  },
  (err) => {
    console.error(`[e2e] FAIL ${err?.stack || err}`);
    process.exit(1);
  }
);
