// demo-mode.spec.mjs — task 32: deterministic demo mode (standalone).
//
// Run: node tests/e2e/demo-mode.spec.mjs
//      E2E_DEVTOOLS_MINIMIZE=1 node tests/e2e/demo-mode.spec.mjs   (cold, hidden)
// Evidence: artifacts/e2e/demo-mode.json
//           artifacts/qa/32-failure.txt   (no-key / zero-outbound transcript)
//
// Two independent layers, never conflated:
//   (1) LOGIC (real code path): pages/ai/ai.ts is imported into a node harness (Page-capture +
//       Map-backed wx shim with storage + programmable modal + a request counter/mock). It
//       drives the REAL page methods with demoMode on: status === 'demo' (never ok/offline/local),
//       an independent preview-demo notice line, organize/consult rendered from the local
//       fixtures with ZERO wx.request (ask + extract), and deep-equal blocks for identical
//       input. It also proves the switch flips behaviour (demoMode off -> real requests) and
//       that demoMode is self-sufficient: it still works with aiEnabled=false and stays ZERO
//       outbound (no external-AI consent needed, because nothing leaves the device). The pure
//       fixtures module is imported directly and checked for determinism.
//   (2) RUNTIME (REAL, via miniProgram.evaluate): seeds the preferences/records, reLaunches the
//       page, and drives the REAL page inside the app twice per mode. It counts wx.request
//       (must be 0 for demo) and captures page screenshots to sha256: same-state double capture
//       back-to-back, then a second full cycle (reLaunch + same seed + same drive) — the ACTUAL
//       byte-equality is reported, never assumed. A demoMode=false control drives the real
//       request path (with a success stub) to prove the switch is not a no-op.
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {
  CONFIG,
  E2E_ARTIFACTS,
  ROOT,
  ensureDir,
  fail,
  launchMiniProgram,
  log,
  ok,
  section,
  delay,
  readSafe,
  readPageBundle,
  withTimeout,
  hasPngMagic,
  sha256,
} from './helpers.mjs';

const AI_ROUTE = 'pages/ai/ai';
const MINIAPP_ROOT = CONFIG.projectPath;
const AI_DIR = path.join(MINIAPP_ROOT, 'pages', 'ai');
const TEXTS_TS = path.join(MINIAPP_ROOT, 'config', 'texts.ts');
const DEMO_TS = path.join(MINIAPP_ROOT, 'shared', 'services', 'demoAi.ts');
const AI_RENDER_TS = path.join(MINIAPP_ROOT, 'shared', 'services', 'aiRender.ts');
const AI_TS = path.join(AI_DIR, 'ai.ts');

const E2E_DIR = E2E_ARTIFACTS;
const QA_FAILURE_PATH = path.join(ROOT, 'artifacts', 'qa', '32-failure.txt');


// ---------------------------------------------------------------------------
// Layer 1: node/page-logic harness (real page methods + Map wx shim)
// ---------------------------------------------------------------------------

const HARNESS_SOURCE = String.raw`// temp demo-mode logic harness (run via tsx); not committed — generated by demo-mode.spec.mjs
import { pathToFileURL } from 'node:url';
import { writeFileSync } from 'node:fs';
import path from 'node:path';
const { hasBlock, lastMsg, makeCheck, makeFlog, makeInstanceFactory, makeSeedRecords } = await import(${JSON.stringify(new URL('./helpers.mjs', import.meta.url).href)});

const aiTs = process.env.MHP_AI_TS;
const demoTs = process.env.MHP_DEMO_TS;
const root = process.env.MHP_MINIAPP_ROOT;
const outPath = process.env.MHP_HARNESS_OUT;
const failureOut = process.env.MHP_FAILURE_OUT;
if (!aiTs || !demoTs || !root || !outPath) throw new Error('missing harness env');

const ORGANIZE = {
  points: ['近一周出现头痛'],
  extracted: { symptoms: ['头痛'], medications: [], allergies: [], history: [], exams: [] },
  unknowns: ['诱因未说明'],
  questions: ['头痛多久一次？'],
};
const CONSULT = {
  directions: [
    { text: '注意休息与规律作息', citation: { title: '示例来源', url: 'https://nhc.gov.cn/demo', domain: 'nhc.gov.cn' } },
  ],
  suggestedDepartments: ['全科'],
  citations: [{ title: '示例来源', url: 'https://nhc.gov.cn/demo', domain: 'nhc.gov.cn' }],
  suggestions: [
    { text: '作息规律、避免熬夜', citation: { title: '示例来源', url: 'https://nhc.gov.cn/demo', domain: 'nhc.gov.cn' } },
  ],
  unknowns: [],
  questions: [],
  disclaimer: '以上内容仅为信息整理与一般性提示。',
};
const EXTRACT = { candidates: [{ text: '希望回复简短' }, { text: '多在夜间记录' }, { text: '不要催我' }] };

const store = new Map();
const calls = { toast: [], modal: [], navigate: [], request: [] };
let modalAnswer = true;
let requestMode = 'ok';

globalThis.wx = {
  getStorageSync: function (key) { return store.has(key) ? store.get(key) : ''; },
  setStorageSync: function (key, value) { store.set(key, value); },
  removeStorageSync: function (key) { store.delete(key); },
  getStorageInfoSync: function () { return { keys: Array.from(store.keys()) }; },
  showToast: function (o) { calls.toast.push(o); },
  showModal: function (o) {
    calls.modal.push({ title: o && o.title, content: o && o.content });
    if (o && typeof o.success === 'function') o.success({ confirm: modalAnswer, cancel: !modalAnswer });
  },
  vibrateShort: function () {},
  vibrateLong: function () {},
  navigateTo: function (o) { calls.navigate.push(o); if (o && typeof o.success === 'function') o.success({}); },
  request: function (options) {
    calls.request.push({ url: options.url, data: options.data });
    setTimeout(function () {
      if (requestMode === 'unreachable') { options.fail({ errMsg: 'request:fail' }); return; }
      const url = String(options.url || '');
      if (url.indexOf('/api/extract-memory') !== -1) { options.success({ statusCode: 200, data: EXTRACT }); return; }
      let body = {};
      try { body = JSON.parse(options.data); } catch (e) { body = {}; }
      options.success({ statusCode: 200, data: body.mode === 'organize' ? ORGANIZE : CONSULT });
    }, 0);
    return { abort: function () {} };
  },
};

let captured = null;
globalThis.Page = function (config) { captured = config; };

const textsModule = await import(pathToFileURL(path.join(root, 'config/texts.ts')).href);
const AI = textsModule.AI;
const DEMO = textsModule.DEMO;
const DEGRADED = textsModule.DEGRADED;

const demoModule = await import(pathToFileURL(demoTs).href);

await import(pathToFileURL(aiTs).href);
if (captured === null) throw new Error('ai.ts did not call Page()');

const recordsModule = await import(pathToFileURL(path.join(root, 'shared/services/records.ts')).href);
const records = recordsModule.records;

const makeInstance = makeInstanceFactory(() => captured, { cloneExtras: true });
function resetAll() {
  store.clear();
  calls.toast.length = 0; calls.modal.length = 0; calls.navigate.length = 0; calls.request.length = 0;
  modalAnswer = true; requestMode = 'ok';
}
function seedPrefs(aiEnabled, autoMemory, demoMode) {
  records.preferences.update({ aiEnabled: aiEnabled === true, consentVersion: 1, fontSize: 14, highContrast: false, autoMemory: autoMemory !== false, demoMode: demoMode === true });
}
const seedRecords = makeSeedRecords(records);
function askCount() { return calls.request.filter(function (r) { return String(r.url).indexOf('/api/ask') !== -1; }).length; }
function extractCount() { return calls.request.filter(function (r) { return String(r.url).indexOf('/api/extract-memory') !== -1; }).length; }
async function drive(inst, mode, text) {
  if (mode === 'consult' && inst.data.mode !== 'consult') { await inst.setMode('consult'); }
  inst.onInput({ detail: { value: text } });
  const send = await inst.onSend();
  const preview = {
    reason: send.reason,
    open: inst.data.previewOpen,
    demoNotice: inst.data.previewDemoNotice,
    memoryNotice: inst.data.previewMemoryNotice,
    titles: inst.data.previewSections.map(function (s) { return s.title; }),
  };
  const confirmed = await inst.onConfirmSend();
  const last = lastMsg(inst);
  return {
    preview: preview,
    confirmed: confirmed,
    kind: last.kind,
    blocks: last.blocks,
    status: inst.data.aiStatus,
    statusText: inst.data.aiStatusText,
  };
}

const cases = [];
const check = makeCheck(cases);

// ----- pure fixtures determinism (no page) -----
const orgInput = { mode: 'organize', messages: [] };
const conInput = { mode: 'consult', messages: [] };
const askOrg1 = demoModule.demoAsk(orgInput);
const askOrg2 = demoModule.demoAsk(orgInput);
const askCon1 = demoModule.demoAsk(conInput);
const askCon2 = demoModule.demoAsk(conInput);
const ex1 = demoModule.demoExtractMemory({ messages: [{ role: 'user', content: 'x' }] });
const ex2 = demoModule.demoExtractMemory({ messages: [{ role: 'user', content: 'x' }] });
const exCandidates = ex1.data.candidates;
check('fixtures-deterministic', 'pure demoAsk/demoExtractMemory: identical input -> deep-equal output; extract <= 3 text candidates',
  JSON.stringify(askOrg1) === JSON.stringify(askOrg2) && JSON.stringify(askCon1) === JSON.stringify(askCon2) &&
    JSON.stringify(ex1) === JSON.stringify(ex2) && askOrg1.ok === true && askOrg1.status === 200 &&
    Array.isArray(exCandidates) && exCandidates.length > 0 && exCandidates.length <= 3 &&
    exCandidates.every(function (c) { return typeof c.text === 'string' && c.text.length > 0; }),
  { ask_organize_equal: JSON.stringify(askOrg1) === JSON.stringify(askOrg2), extract_len: exCandidates.length });

// ----- demo ON: organize, zero request, status demo -----
resetAll();
seedPrefs(true, true, true);
seedRecords();
let inst = makeInstance();
inst.onLoad({});
inst.onShow();
const statusFresh = { status: inst.data.aiStatus, text: inst.data.aiStatusText, demoMode: inst.data.demoMode };
const orgDrive = await drive(inst, 'organize', '最近一周头痛，睡不好');
const orgRequests = calls.request.length;
check('demo-organize-zero-request', 'demo on: status demo (not ok/offline/local), preview carries the demo notice line, organize renders from fixtures with zero wx.request (ask + extract)',
  statusFresh.status === 'demo' && statusFresh.text === DEMO.statusDemo && statusFresh.demoMode === true &&
    orgDrive.preview.reason === 'preview' && orgDrive.preview.open === true &&
    orgDrive.preview.demoNotice === DEMO.previewNotice && orgDrive.preview.titles.indexOf('对话') !== -1 &&
    orgDrive.confirmed.ok === true && orgDrive.confirmed.kind === 'organize' && orgDrive.kind === 'organize' &&
    hasBlock({ blocks: orgDrive.blocks }, 'list', AI.sectionPoints) && hasBlock({ blocks: orgDrive.blocks }, 'extracted', AI.sectionExtracted) &&
    orgDrive.status === 'demo' && orgDrive.statusText === DEMO.statusDemo && orgRequests === 0,
  { status_fresh: statusFresh, preview: orgDrive.preview, kind: orgDrive.kind, status: orgDrive.status, requests: orgRequests });

// ----- demo ON: consult, zero request -----
const conDrive = await drive(inst, 'consult', '最近胃不舒服');
const conRequests = calls.request.length - orgRequests;
check('demo-consult-zero-request', 'demo on: consult renders directions/departments from fixtures with zero wx.request',
  conDrive.confirmed.ok === true && conDrive.confirmed.kind === 'consult' && conDrive.kind === 'consult' &&
    hasBlock({ blocks: conDrive.blocks }, 'directions', AI.sectionDirections) &&
    hasBlock({ blocks: conDrive.blocks }, 'list', AI.sectionDepartments) && conDrive.status === 'demo' && conRequests === 0,
  { kind: conDrive.kind, status: conDrive.status, requests_delta: conRequests });

// ----- demo ON: two identical inputs -> deep-equal blocks (organize + consult) -----
async function captureBlocks(mode) {
  resetAll();
  seedPrefs(true, true, true);
  seedRecords();
  const i = makeInstance();
  i.onLoad({});
  i.onShow();
  const d = await drive(i, mode, '近一周头痛');
  return d.blocks;
}
const orgBlocksA = await captureBlocks('organize');
const orgBlocksB = await captureBlocks('organize');
const conBlocksA = await captureBlocks('consult');
const conBlocksB = await captureBlocks('consult');
check('demo-identical-input-deep-equal', 'demo on: two identical inputs (organize + consult) yield deep-equal rendered blocks',
  JSON.stringify(orgBlocksA) === JSON.stringify(orgBlocksB) && JSON.stringify(conBlocksA) === JSON.stringify(conBlocksB) &&
    orgBlocksA.length > 0 && conBlocksA.length > 0,
  { organize_equal: JSON.stringify(orgBlocksA) === JSON.stringify(orgBlocksB), consult_equal: JSON.stringify(conBlocksA) === JSON.stringify(conBlocksB) });

// ----- demo OFF control: real request path -----
resetAll();
seedPrefs(true, true, false);
seedRecords();
const offInst = makeInstance();
offInst.onLoad({});
offInst.onShow();
const offDrive = await drive(offInst, 'organize', '最近睡不好');
const offAsk = askCount();
const offExtract = extractCount();
check('demo-off-real-requests', 'demo off: the real request path is used (ask >= 1, extract >= 1) and status is ok, proving the switch flips behaviour',
  offDrive.kind === 'organize' && offDrive.status === 'ok' && offAsk >= 1 && offExtract >= 1,
  { kind: offDrive.kind, status: offDrive.status, ask_requests: offAsk, extract_requests: offExtract });

// ----- demo ON + aiEnabled false: demo is self-sufficient (still zero outbound) -----
resetAll();
seedPrefs(false, true, true);
seedRecords();
const disInst = makeInstance();
disInst.onLoad({});
disInst.onShow();
const disStatus = disInst.data.aiStatus;
disInst.onInput({ detail: { value: '最近睡不好' } });
const disSend = await disInst.onSend();
const disPreview = { open: disInst.data.previewOpen, demoNotice: disInst.data.previewDemoNotice };
const disConfirm = await disInst.onConfirmSend();
const disLast = lastMsg(disInst);
check('demo-standalone-ai-disabled', 'demo on + aiEnabled false: demo runs standalone (status demo, fixture organize result, notice line) with ZERO wx.request — it needs no external-AI consent because nothing leaves the device',
  disStatus === 'demo' && disSend.reason === 'preview' && disPreview.open === true &&
    disPreview.demoNotice === DEMO.previewNotice && disConfirm.ok === true && disLast.kind === 'organize' &&
    disInst.data.aiStatus === 'demo' && calls.request.length === 0,
  { status: disStatus, preview: disPreview, confirmed: disConfirm, kind: disLast.kind, requests: calls.request.length });

// ----- preview sections unchanged (no demo text folded into sections) -----
check('preview-sections-unchanged', 'the demo notice is a separate field — previewSections still renders the T29/T31 structure with no demo text inside',
  orgDrive.preview.titles.indexOf('对话') !== -1 &&
    orgDrive.preview.demoNotice !== '' && orgDrive.preview.titles.indexOf(DEMO.previewNotice) === -1,
  { titles: orgDrive.preview.titles, demo_notice: orgDrive.preview.demoNotice });

const failed = cases.filter(function (c) { return !c.pass; }).length;

const failureLines = [];
const flog = makeFlog(failureLines);
flog('T32 demo-mode failure-path evidence (demo path carries no key and issues zero outbound requests)');
flog('command: node tests/e2e/demo-mode.spec.mjs');
flog('timestamp: ' + new Date().toISOString());
flog('method: REAL pages/ai/ai.ts methods driven by a node harness; wx = Map-backed shim (storage + modal + request counter/mock). The demo fixtures module is imported directly.');
flog('scenario: demo on, organize + consult — request counter must stay at 0 for ask AND extract');
flog('demo_organize_requests: ' + orgRequests + ' (expected 0)');
flog('demo_consult_requests_delta: ' + conRequests + ' (expected 0)');
flog('demo_status_never_ok_offline_local: ' + (orgDrive.status === 'demo' && conDrive.status === 'demo'));
flog('scenario: demo off control — the real request path is used');
flog('demo_off_ask_requests: ' + offAsk + ' (expected >= 1)');
flog('demo_off_extract_requests: ' + offExtract + ' (expected >= 1)');
flog('scenario: demo on + aiEnabled false — demo is self-sufficient, still zero outbound');
flog('standalone_requests: ' + calls.request.length + ' (expected 0)');
flog('verdict: PASS (the demo path sends nothing and needs no key or consent; switching demo off restores the real request path).');
flog('exit_code_evidence: artifacts/qa/32-failure.txt is written by the passing run (contract: demo carries no key / zero outbound).');

if (failureOut) writeFileSync(failureOut, failureLines.join('\n') + '\n');

const result = {
  generated_at: new Date().toISOString(),
  ai_ts: aiTs,
  demo_ts: demoTs,
  note: 'REAL page methods from pages/ai/ai.ts; wx = Map-backed shim; demo fixtures module imported directly',
  scenarios: cases,
  failure_path: { lines: failureLines, pass: orgRequests === 0 && conRequests === 0 && offAsk >= 1 && offExtract >= 1 && calls.request.length === 0 },
  summary: { total: cases.length, passed: cases.length - failed, failed: failed },
};
writeFileSync(outPath, JSON.stringify(result, null, 2) + '\n');
console.log(JSON.stringify(result, null, 2));
process.exit(failed === 0 ? 0 : 1);
`;

function runLogicHarness() {
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'mhp-demo-mode-harness-'));
  const harnessPath = path.join(tmpDir, 'demo-mode-logic.harness.mjs');
  const outPath = path.join(tmpDir, 'demo-mode-logic.result.json');
  const failurePath = path.join(tmpDir, 'demo-mode-failure.txt');
  fs.writeFileSync(harnessPath, HARNESS_SOURCE);

  const res = spawnSync(process.execPath, ['--import', 'tsx', harnessPath], {
    cwd: ROOT,
    encoding: 'utf8',
    env: {
      ...process.env,
      MHP_AI_TS: AI_TS,
      MHP_DEMO_TS: DEMO_TS,
      MHP_MINIAPP_ROOT: MINIAPP_ROOT,
      MHP_HARNESS_OUT: outPath,
      MHP_FAILURE_OUT: failurePath,
    },
    timeout: 90000,
    maxBuffer: 32 * 1024 * 1024,
  });
  const stdout = `${res.stdout || ''}`;
  const stderr = `${res.stderr || ''}`;

  let result = null;
  if (fs.existsSync(outPath)) {
    try {
      result = JSON.parse(fs.readFileSync(outPath, 'utf8'));
    } catch (err) {
      fail(`harness result JSON unparsable: ${err?.message || err}`);
    }
  }
  const failureRaw = fs.existsSync(failurePath) ? fs.readFileSync(failurePath, 'utf8') : '';
  return {
    method: 'node --import tsx <temp harness> (Page-capture + Map wx shim: storage/modal/request counter)',
    ai_ts: AI_TS,
    demo_ts: DEMO_TS,
    exit: res.status,
    stdout_tail: stdout.slice(-8000),
    stderr_tail: stderr.slice(-8000),
    result,
    failure_raw: failureRaw,
  };
}

// ---------------------------------------------------------------------------
// Static invariants (source-level, no runtime claim)
// ---------------------------------------------------------------------------


const FORBIDDEN_STRINGS = [
  'AI 注入',
  'hza_',
  'System Prompt',
  '系统提示词',
  '确诊',
  '诊断结论',
  '处方',
  '疗效保证',
  '急症拦截',
  '自动拨号',
  '预约挂号',
  '挂号成功',
  '候诊叫号',
  '推荐医生',
  '推荐医院',
  '智能分诊',
  'AI 结论',
  '医疗级',
];
const SEVERITY_TOKENS = ['severity', '严重程度', '严重度', '危急程度'];
const KEY_TOKENS = ['apikey', 'api_key', 'bearer', 'secret', 'token', 'password', 'sk-'];

function staticInvariantChecks() {
  const demo = readSafe(DEMO_TS);
  const aiTs = readPageBundle('ai', 'ts');
  const aiWxml = readPageBundle('ai', 'wxml');
  const aiWxss = readPageBundle('ai', 'wxss');
  const settingsTs = readPageBundle('settings', 'ts');
  const settingsWxml = readPageBundle('settings', 'wxml');
  const texts = readSafe(TEXTS_TS);
  const aiRenderTs = readSafe(AI_RENDER_TS);

  const demoWx = /\bwx\s*\./.test(demo);
  const demoNetwork = /\b(request|fetch|XMLHttpRequest)\s*\(/.test(demo);
  const demoKeyHits = KEY_TOKENS.filter((t) => demo.toLowerCase().includes(t));
  const demoForbidden = FORBIDDEN_STRINGS.filter((t) => demo.includes(t));
  const demoSeverity = SEVERITY_TOKENS.filter((t) => demo.includes(t));
  const demoTypeImport = /import\s+type\s*\{[^}]*\}\s*from\s*['"]\.\/aiClient['"]/.test(demo);
  const demoExports = /export\s+function\s+demoAsk\s*\(/.test(demo) && /export\s+function\s+demoExtractMemory\s*\(/.test(demo);

  const aiWired =
    /from\s*['"]\.\.\/\.\.\/shared\/services\/demoAi['"]/.test(aiTs) &&
    /demoAsk\s*\(/.test(aiTs) &&
    /demoExtractMemory\s*\(/.test(aiTs);
  // The demo->copy mapping was extracted out of the page into the render service
  // (shared/services/aiRender.ts: statusTextFor returns DEMO.statusDemo); the page
  // keeps the 'demo' status value + previewDemoNotice. All three conditions stay.
  const aiDemoState = /'demo'/.test(aiTs) && /DEMO\.statusDemo/.test(aiRenderTs) && /previewDemoNotice/.test(aiTs);
  const aiPreviewField = /previewDemoNotice/.test(aiWxml);
  const aiStatusVar = /statusbar--demo|statusbar--\{\{aiStatus\}\}/.test(aiWxml) && /statusbar--demo/.test(aiWxss);
  const aiForbidden = FORBIDDEN_STRINGS.filter((t) => (demo + aiTs + aiWxml + aiWxss).includes(t));
  const aiSeverity = SEVERITY_TOKENS.filter((t) => (demo + aiTs + aiWxml + aiWxss).includes(t));

  const settingsGate =
    /getAccountInfoSync/.test(settingsTs) && /envVersion\s*===\s*'develop'/.test(settingsTs) && /try\s*\{/.test(settingsTs);
  const settingsSwitch = /onDemoModeChange/.test(settingsTs) && /onDemoModeChange/.test(settingsWxml) && /demoVisible/.test(settingsWxml);
  const settingsTexts = /demoMode/.test(settingsTs) && /DEMO/.test(settingsTs) && /demo\.toggleLabel/.test(settingsWxml);
  const textsDemo = /export const DEMO/.test(texts) && /statusDemo/.test(texts) && /previewNotice/.test(texts);

  const fontLines = aiWxss.split(/\r?\n/).filter((line) => line.includes('font-size'));
  const fontAllScaled = fontLines.length > 0 && fontLines.every((line) => /calc\([^)]*var\(--mhp-scale\)\)/.test(line));
  const barePx = aiWxss
    .split(/\r?\n/)
    .filter((line) => /(?<![\dr])\d+px/.test(line))
    .map((line) => line.trim());

  return {
    demo_ts_exists: fs.existsSync(DEMO_TS),
    demo_js_exists: fs.existsSync(DEMO_TS.replace(/\.ts$/, '.js')),
    demo_no_wx_reference: !demoWx,
    demo_no_network_call: !demoNetwork,
    demo_no_key_tokens: demoKeyHits,
    demo_forbidden_present: demoForbidden,
    demo_severity_present: demoSeverity,
    demo_type_only_import: demoTypeImport,
    demo_exports_present: demoExports,
    ai_demo_wired: aiWired,
    ai_demo_state: aiDemoState,
    ai_preview_demo_field: aiPreviewField,
    ai_statusbar_demo: aiStatusVar,
    ai_forbidden_present: aiForbidden,
    ai_severity_present: aiSeverity,
    settings_demo_gate: settingsGate,
    settings_demo_switch: settingsSwitch,
    settings_demo_texts: settingsTexts,
    texts_demo_copy: textsDemo,
    font_size_all_scaled: fontAllScaled,
    bare_px_lines: barePx,
  };
}

// ---------------------------------------------------------------------------
// Layer 2: automator helpers
// ---------------------------------------------------------------------------

async function captureShot(miniProgram, tag) {
  const shotPath = path.join(os.tmpdir(), `mhp-e2e-demo-${tag}-${Date.now()}.png`);
  await miniProgram.screenshot({ path: shotPath });
  const shot = fs.readFileSync(shotPath);
  fs.unlinkSync(shotPath);
  return { bytes: shot.length, sha256: sha256(shot), pngMagic: hasPngMagic(shot) };
}

const STORAGE_KEYS = [
  'records_preferences',
  'records_profile',
  'records_symptoms',
  'records_notes',
  'records_questions',
  'records_memory',
  'ai_messages',
  'ai_consult_ack',
];

const SEED_PROFILE = [
  {
    id: 'prof_seed_1',
    createdAt: '2026-08-01T01:00:00.000Z',
    updatedAt: '2026-08-01T01:00:00.000Z',
    name: '张三',
    ageRange: '60-69',
    gender: '',
    allergies: '',
    medications: '',
    history: '',
  },
];
const SEED_SYMPTOMS = [
  {
    id: 'sym_seed_1',
    createdAt: '2026-09-01T01:00:00.000Z',
    updatedAt: '2026-09-01T01:00:00.000Z',
    occurredAt: '2026-09-10T02:00:00.000Z',
    duration: '3 天',
    text: '饭后有点胀',
    impact: '',
    tags: [],
    attachment: null,
  },
];
const SEED_MEMORY = [
  {
    id: 'mem_seed_1',
    createdAt: '2026-09-05T01:00:00.000Z',
    updatedAt: '2026-09-05T01:00:00.000Z',
    text: '希望回复简短一些',
    source: 'manual',
    enabled: true,
  },
];

function seedPreferences(demoMode) {
  return {
    aiEnabled: true,
    consentVersion: 1,
    fontSize: 14,
    highContrast: false,
    autoMemory: true,
    demoMode,
    updatedAt: '2026-09-01T00:00:00.000Z',
  };
}

async function seedAndReload(miniProgram, demoMode) {
  await withTimeout(
    (async () => {
      for (const raw of STORAGE_KEYS) await miniProgram.callWxMethod('removeStorageSync', 'mhp_' + raw);
      await miniProgram.callWxMethod('setStorageSync', 'mhp_records_preferences', seedPreferences(demoMode));
      await miniProgram.callWxMethod('setStorageSync', 'mhp_records_profile', SEED_PROFILE);
      await miniProgram.callWxMethod('setStorageSync', 'mhp_records_symptoms', SEED_SYMPTOMS);
      await miniProgram.callWxMethod('setStorageSync', 'mhp_records_memory', SEED_MEMORY);
      await miniProgram.callWxMethod('setStorageSync', 'mhp_ai_consult_ack', true);
    })(),
    15000,
    'seed'
  );
  await withTimeout(miniProgram.reLaunch('/' + AI_ROUTE + '?mode=organize'), 20000, 'reLaunch-1');
  await delay(800);
  await withTimeout(miniProgram.reLaunch('/' + AI_ROUTE + '?mode=organize'), 20000, 'reLaunch-2');
  await delay(800);
}

const ORGANIZE_FIXTURE = {
  points: ['近一周出现头痛'],
  extracted: { symptoms: ['头痛'], medications: [], allergies: [], history: [], exams: [] },
  unknowns: [],
  questions: [],
};

// Drives one full send inside the runtime page and returns serializable facts.
function driveInPage(mode, text, stubRequest) {
  return async (args) => {
    const pages = getCurrentPages();
    const page = pages[pages.length - 1];
    const originalRequest = wx.request;
    let count = 0;
    wx.request = function (options) {
      count += 1;
      if (args.stubRequest) {
        setTimeout(function () {
          const url = String(options.url || '');
          if (url.indexOf('/api/extract-memory') !== -1) {
            if (options.success) options.success({ statusCode: 200, data: { candidates: [] } });
            return;
          }
          if (options.success) options.success({ statusCode: 200, data: args.organize });
        }, 0);
        return { abort: function () {} };
      }
      return originalRequest.call(wx, options);
    };
    let facts = {};
    try {
      if (args.mode === 'consult' && page.data.mode !== 'consult') {
        await page.setMode('consult');
      }
      page.onInput({ detail: { value: args.text } });
      const send = await page.onSend();
      facts.preview = {
        reason: send.reason,
        open: page.data.previewOpen,
        demoNotice: page.data.previewDemoNotice,
        titles: page.data.previewSections.map((s) => s.title),
      };
      const confirmed = await page.onConfirmSend();
      const msgs = page.data.messages;
      const last = msgs[msgs.length - 1];
      facts.result = {
        confirmedOk: confirmed.ok,
        kind: confirmed.kind,
        lastKind: last ? last.kind : '',
        blockTitles: last ? last.blocks.map((b) => b.title) : [],
        blocksJson: last ? JSON.stringify(last.blocks) : '',
      };
      facts.status = page.data.aiStatus;
      facts.statusText = page.data.aiStatusText;
      facts.demoMode = page.data.demoMode;
      facts.requests = count;
    } finally {
      wx.request = originalRequest;
    }
    return facts;
  };
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  ensureDir(E2E_DIR);
  ensureDir(path.dirname(QA_FAILURE_PATH));
  section('DEMO MODE SPEC');

  const logic = runLogicHarness();
  const logicScenarios = logic.result ? logic.result.scenarios : [];
  const logicFailed = logic.result ? logic.result.summary.failed : -1;

  const statics = staticInvariantChecks();

  const staticLines = [
    '--- static scan (demo path carries no key / no outbound) ---',
    'demo_ts: ' + DEMO_TS,
    'demo_no_wx_reference: ' + statics.demo_no_wx_reference,
    'demo_no_network_call: ' + statics.demo_no_network_call,
    'demo_no_key_tokens: ' + JSON.stringify(statics.demo_no_key_tokens),
    'demo_forbidden_present: ' + JSON.stringify(statics.demo_forbidden_present),
    'demo_type_only_import: ' + statics.demo_type_only_import,
    'ai_demo_wired: ' + statics.ai_demo_wired,
    'settings_demo_gate: ' + statics.settings_demo_gate,
    '',
  ];

  if (logic.failure_raw !== '') {
    fs.writeFileSync(QA_FAILURE_PATH, logic.failure_raw + staticLines.join('\n') + '\n');
    log(`failure evidence: ${QA_FAILURE_PATH}`);
  }

  const report = {
    command: 'E2E_DEVTOOLS_MINIMIZE=1 node tests/e2e/demo-mode.spec.mjs (cold)',
    timestamp: new Date().toISOString(),
    platform: `${os.platform()} ${os.release()} (${os.arch()})`,
    node_version: process.version,
    project_path: CONFIG.projectPath,
    logic: { method: logic.method, ai_ts: logic.ai_ts, demo_ts: logic.demo_ts, exit: logic.exit, result: logic.result },
    static_invariants: statics,
    evaluate_probe: null,
    cycles: null,
    determinism: null,
    demo_off: null,
    render: null,
    summary: null,
  };

  let allOk = true;

  if (logic.result !== null && logic.exit === 0 && logicFailed === 0) {
    ok(`logic harness: ${logic.result.summary.passed}/${logic.result.summary.total} scenarios passed (real page methods)`);
  } else {
    fail(`logic harness failed (exit=${logic.exit}, failed_scenarios=${logicFailed}); stderr tail: ${logic.stderr_tail}`);
    allOk = false;
  }
  for (const scenario of logicScenarios) {
    log(`  [logic] ${scenario.pass ? 'PASS' : 'FAIL'} ${scenario.id}: ${scenario.name}`);
    if (!scenario.pass) allOk = false;
  }

  const staticsOk =
    statics.demo_ts_exists === true &&
    statics.demo_js_exists === false &&
    statics.demo_no_wx_reference === true &&
    statics.demo_no_network_call === true &&
    statics.demo_no_key_tokens.length === 0 &&
    statics.demo_forbidden_present.length === 0 &&
    statics.demo_severity_present.length === 0 &&
    statics.demo_type_only_import === true &&
    statics.demo_exports_present === true &&
    statics.ai_demo_wired === true &&
    statics.ai_demo_state === true &&
    statics.ai_preview_demo_field === true &&
    statics.ai_statusbar_demo === true &&
    statics.ai_forbidden_present.length === 0 &&
    statics.ai_severity_present.length === 0 &&
    statics.settings_demo_gate === true &&
    statics.settings_demo_switch === true &&
    statics.settings_demo_texts === true &&
    statics.texts_demo_copy === true &&
    statics.font_size_all_scaled === true &&
    statics.bare_px_lines.length === 0;
  if (staticsOk) {
    ok('static invariants: demo module is wx-free/key-free/type-only; ai + settings + texts wired; scaled px-free wxss');
  } else {
    fail(`static invariant failure: ${JSON.stringify(report.static_invariants)}`);
    allOk = false;
  }

  let miniProgram;
  try {
    miniProgram = await launchMiniProgram();

    // evaluate capability probe (demo seed)
    await seedAndReload(miniProgram, true);
    {
      const raced = await withTimeout(
        miniProgram.evaluate(() => {
          const pages = getCurrentPages();
          const page = pages[pages.length - 1];
          return {
            route: page.route,
            demoMode: page.data.demoMode,
            status: page.data.aiStatus,
            statusText: page.data.aiStatusText,
            hasSend: typeof page.onSend === 'function',
            hasConfirm: typeof page.onConfirmSend === 'function',
          };
        }),
        15000,
        'evaluate-probe'
      );
      if (raced.timedOut === true || raced.error !== undefined) {
        report.evaluate_probe = raced.timedOut ? { ok: false, error: 'timed out' } : { ok: false, error: raced.error };
        fail(`evaluate probe failed: ${JSON.stringify(report.evaluate_probe)}`);
        allOk = false;
      } else {
        const p = raced.value;
        report.evaluate_probe = { ok: true, value: p };
        if (p && p.route === AI_ROUTE && p.demoMode === true && p.status === 'demo' && p.hasSend === true && p.hasConfirm === true) {
          ok(`evaluate probe: ${JSON.stringify(p)}`);
        } else {
          fail(`evaluate probe unexpected: ${JSON.stringify(p)}`);
          allOk = false;
        }
      }
    }

    // up to 4 driven cycles + 1 same-state extra capture
    const cycleData = [];
    async function runCycle(mode, text, tag) {
      await seedAndReload(miniProgram, true);
      const raced = await withTimeout(miniProgram.evaluate(driveInPage(mode, text, false), { mode, text, stubRequest: false }), 30000, `drive-${tag}`);
      if (raced.timedOut === true || raced.error !== undefined) {
        fail(`drive ${tag} failed: ${JSON.stringify(raced.timedOut ? { error: 'timed out' } : { error: raced.error })}`);
        allOk = false;
        return null;
      }
      // settle (e.g. in-page transitions / keyboard hide) so every cycle frame is
      // captured at the same elapsed point — required for a fair byte comparison.
      await delay(1200);
      const shotRaced = await withTimeout(captureShot(miniProgram, tag), 15000, `shot-${tag}`);
      if (shotRaced.timedOut === true || shotRaced.error !== undefined) {
        fail(`screenshot ${tag} failed: ${JSON.stringify(shotRaced.timedOut ? { error: 'timed out' } : { error: shotRaced.error })}`);
        allOk = false;
        return null;
      }
      return { tag, facts: raced.value, shot: shotRaced.value };
    }

    const orgA = await runCycle('organize', '近一周头痛，睡不好', 'organize-a');
    const orgB = await runCycle('organize', '近一周头痛，睡不好', 'organize-b');
    const conA = await runCycle('consult', '最近胃不舒服', 'consult-a');
    const conB = await runCycle('consult', '最近胃不舒服', 'consult-b');
    cycleData.push(orgA, orgB, conA, conB);

    // same-state double capture: let the page settle, then capture the identical
    // state twice in a row (no drive in between) and compare the bytes.
    await delay(1500);
    let sameA = null;
    let sameB = null;
    {
      const a = await withTimeout(captureShot(miniProgram, 'settled-a'), 15000, 'shot-settled-a');
      const b = await withTimeout(captureShot(miniProgram, 'settled-b'), 15000, 'shot-settled-b');
      sameA = a.timedOut === true || a.error !== undefined ? null : a.value;
      sameB = b.timedOut === true || b.error !== undefined ? null : b.value;
      if (sameA === null || sameB === null) {
        fail(`same-state double capture failed: ${JSON.stringify({ a: a.timedOut ? 'timed out' : a.error, b: b.timedOut ? 'timed out' : b.error })}`);
        allOk = false;
      }
    }

    const cycleFactsOk = [orgA, orgB, conA, conB].every(
      (c) =>
        c !== null &&
        c.facts &&
        c.facts.preview.reason === 'preview' &&
        c.facts.preview.demoNotice !== '' &&
        c.facts.result.confirmedOk === true &&
        c.facts.status === 'demo' &&
        c.facts.demoMode === true &&
        c.facts.requests === 0 &&
        c.shot.pngMagic === true &&
        c.shot.bytes > 5000
    );
    if (cycleFactsOk) ok('runtime demo cycles: preview demo notice + status demo + zero wx.request for all 4 driven sends');
    else {
      fail(`runtime demo cycles unexpected: ${JSON.stringify(cycleData)}`);
      allOk = false;
    }

    report.cycles = cycleData.map((c) =>
      c === null
        ? null
        : {
            tag: c.tag,
            status: c.facts.status,
            statusText: c.facts.statusText,
            kind: c.facts.result.kind,
            lastKind: c.facts.result.lastKind,
            previewDemoNotice: c.facts.preview.demoNotice,
            blockTitles: c.facts.result.blockTitles,
            requests: c.facts.requests,
            shotBytes: c.shot.bytes,
            shotSha256: c.shot.sha256,
            shotPngMagic: c.shot.pngMagic,
          }
    );

    const determinism = {
      organize_blocks_equal: orgA !== null && orgB !== null && orgA.facts.result.blocksJson === orgB.facts.result.blocksJson,
      consult_blocks_equal: conA !== null && conB !== null && conA.facts.result.blocksJson === conB.facts.result.blocksJson,
      same_state_double_capture_sha256_equal: sameA !== null && sameB !== null && sameA.sha256 === sameB.sha256,
      cross_cycle_organize_sha256_equal: orgA !== null && orgB !== null && orgA.shot.sha256 === orgB.shot.sha256,
      cross_cycle_consult_sha256_equal: conA !== null && conB !== null && conA.shot.sha256 === conB.shot.sha256,
      organize_sha256: orgA !== null && orgB !== null ? [orgA.shot.sha256, orgB.shot.sha256] : [],
      consult_sha256: conA !== null && conB !== null ? [conA.shot.sha256, conB.shot.sha256] : [],
      same_state_sha256: sameA !== null && sameB !== null ? [sameA.sha256, sameB.sha256] : [],
      same_state_bytes: sameA !== null && sameB !== null ? [sameA.bytes, sameB.bytes] : [],
    };
    report.determinism = determinism;

    if (determinism.organize_blocks_equal && determinism.consult_blocks_equal) {
      ok('runtime determinism: identical input -> deep-equal rendered blocks (organize + consult)');
    } else {
      fail(`runtime determinism (blocks) failed: ${JSON.stringify(determinism)}`);
      allOk = false;
    }
    if (determinism.same_state_double_capture_sha256_equal) {
      ok(`same-state double capture SHA256 equal (${determinism.same_state_sha256[0]})`);
    } else {
      fail(`same-state double capture SHA256 differ: ${JSON.stringify(determinism.same_state_sha256)}`);
      allOk = false;
    }
    log(
      `cross-cycle SHA256: organize ${JSON.stringify(determinism.organize_sha256)} equal=${determinism.cross_cycle_organize_sha256_equal}; ` +
        `consult ${JSON.stringify(determinism.consult_sha256)} equal=${determinism.cross_cycle_consult_sha256_equal}`
    );

    // demo OFF runtime control: real request path (success stub) issues requests
    await seedAndReload(miniProgram, false);
    const offRaced = await withTimeout(
      miniProgram.evaluate(driveInPage('organize', '最近睡不好', true), {
        mode: 'organize',
        text: '最近睡不好',
        stubRequest: true,
        organize: ORGANIZE_FIXTURE,
      }),
      25000,
      'drive-off'
    );
    if (offRaced.timedOut === true || offRaced.error !== undefined) {
      report.demo_off = offRaced.timedOut ? { error: 'timed out' } : { error: offRaced.error };
      fail(`demo-off control failed: ${JSON.stringify(report.demo_off)}`);
      allOk = false;
    } else {
      const o = offRaced.value;
      report.demo_off = { requests: o.requests, status: o.status, kind: o.result.kind, demoMode: o.demoMode };
      if (o.requests >= 1 && o.status === 'ok' && o.result.kind === 'organize' && o.demoMode === false) {
        ok(`demo off control: real request path used (${o.requests} request(s)), status ${o.status}`);
      } else {
        fail(`demo off control unexpected: ${JSON.stringify(report.demo_off)}`);
        allOk = false;
      }
    }

    // final render evidence on the demo page
    await seedAndReload(miniProgram, true);
    {
      const stackRaced = await withTimeout(miniProgram.pageStack(), 10000, 'pageStack');
      const shotRaced = await withTimeout(captureShot(miniProgram, 'render'), 15000, 'shot-render');
      if (stackRaced.timedOut === true || stackRaced.error !== undefined || shotRaced.timedOut === true || shotRaced.error !== undefined) {
        report.render = { ok: false };
        fail(`render evidence failed: ${JSON.stringify(report.render)}`);
        allOk = false;
      } else {
        const stack = stackRaced.value;
        const top = Array.isArray(stack) && stack.length > 0 ? stack[stack.length - 1] : null;
        report.render = {
          pageStack: stack.length,
          topPath: top ? top.path : null,
          shotBytes: shotRaced.value.bytes,
          shotSha256: shotRaced.value.sha256,
          pngMagic: shotRaced.value.pngMagic,
          ok: stack.length >= 1 && top !== null && top.path === AI_ROUTE && shotRaced.value.pngMagic && shotRaced.value.bytes > 5000,
        };
        if (report.render.ok) ok(`render evidence: top=${report.render.topPath}, bytes=${report.render.shotBytes}, sha256=${report.render.shotSha256}`);
        else {
          fail(`render check failed: ${JSON.stringify(report.render)}`);
          allOk = false;
        }
      }
    }

    await withTimeout(
      (async () => {
        for (const raw of STORAGE_KEYS) await miniProgram.callWxMethod('removeStorageSync', 'mhp_' + raw);
      })(),
      10000,
      'clear-keys'
    );
  } catch (err) {
    fail(`demo-mode spec run error: ${err?.stack || err}`);
    report.error = err?.message || String(err);
    allOk = false;
  } finally {
    if (miniProgram) {
      const raced = await withTimeout(miniProgram.close(), 8000, 'close');
      if (raced.timedOut === true) log('warning: miniProgram.close() timed out');
      else if (raced.error !== undefined) log(`warning: miniProgram.close() failed: ${raced.error}`);
      else log('miniProgram.close() done');
      try {
        miniProgram.disconnect();
      } catch {
        /* socket already closed */
      }
    }
  }

  const cycles = report.cycles || [];
  const checks = {
    logic_harness_ok: logic.result !== null && logic.exit === 0 && logicFailed === 0,
    static_invariants_ok: staticsOk,
    evaluate_probe_ok: Boolean(
      report.evaluate_probe && report.evaluate_probe.ok === true && report.evaluate_probe.value && report.evaluate_probe.value.route === AI_ROUTE && report.evaluate_probe.value.status === 'demo'
    ),
    runtime_demo_zero_request_ok: cycles.length === 4 && cycles.every((c) => c !== null && c.requests === 0 && c.status === 'demo'),
    runtime_demo_preview_notice_ok: cycles.length === 4 && cycles.every((c) => c !== null && c.previewDemoNotice !== ''),
    runtime_blocks_equal_ok: Boolean(report.determinism && report.determinism.organize_blocks_equal === true && report.determinism.consult_blocks_equal === true),
    same_state_sha256_equal_ok: Boolean(report.determinism && report.determinism.same_state_double_capture_sha256_equal === true),
    demo_off_control_ok: Boolean(report.demo_off && report.demo_off.requests >= 1 && report.demo_off.status === 'ok'),
    render_ok: Boolean(report.render && report.render.ok === true),
    no_forbidden_strings: statics.demo_forbidden_present.length === 0 && statics.ai_forbidden_present.length === 0,
    no_severity_token: statics.demo_severity_present.length === 0 && statics.ai_severity_present.length === 0,
    no_key_tokens: statics.demo_no_key_tokens.length === 0,
    demo_module_no_wx: statics.demo_no_wx_reference === true && statics.demo_no_network_call === true,
    font_scaled: statics.font_size_all_scaled === true && statics.bare_px_lines.length === 0,
  };
  const checksPassed = Object.values(checks).every((v) => v === true);
  log(`summary checks: ${JSON.stringify(checks)}`);

  report.summary = {
    ...checks,
    logic_scenarios_total: logic.result ? logic.result.summary.total : 0,
    logic_scenarios_passed: logic.result ? logic.result.summary.passed : 0,
    cross_cycle_organize_sha256_equal: Boolean(report.determinism && report.determinism.cross_cycle_organize_sha256_equal === true),
    cross_cycle_consult_sha256_equal: Boolean(report.determinism && report.determinism.cross_cycle_consult_sha256_equal === true),
    passed: checksPassed && allOk === true,
    failed: !(checksPassed && allOk === true),
  };

  const reportPath = path.join(E2E_DIR, 'demo-mode.json');
  fs.writeFileSync(reportPath, JSON.stringify(report, null, 2) + '\n');
  log(`demo-mode evidence: ${reportPath}`);

  return report.summary.passed;
}

main().then(
  (passed) => {
    process.exit(passed ? 0 : 1);
  },
  (err) => {
    console.error(`[e2e] FAIL ${err?.stack || err}`);
    process.exit(1);
  }
);
