// profile.spec.mjs — task 14 minimal-local-profile E2E (standalone).
//
// Run: node tests/e2e/profile.spec.mjs
// Evidence: artifacts/e2e/profile.json (harness + automator)
//           artifacts/qa/14-failure.txt (guard failure-path transcript)
//
// Two independent layers, never conflated:
//   (1) LOGIC (real code path): the page's own methods are exercised by importing
//       pages/profile/profile.ts into a node/page-logic harness (Page-capture + a
//       Map-backed wx shim), exactly the sanctioned pattern from check-brief.mjs.
//       This is the only way to reach onSave/onClear over this devtools build:
//       the Page.* automator protocol (page.$/page.data/evaluate) is dropped and
//       hangs, so the runtime cannot tap the form. The guard (both empty -> prompt,
//       no write) and save/read-back/update/clear are all driven through the REAL
//       page methods.
//   (2) RUNTIME (automator): launch the miniprogram, reLaunch to pages/profile,
//       screenshot (render proof), write a record into the runtime storage via
//       callWxMethod, reLaunch and observe the render change (namespace + read-back),
//       then relaunch to prove persistence. The runtime namespace is asserted to be
//       exactly `mhp_` (legacy `hza_` write is the negative control).
//
// Transport notes (WeChat DevTools 2.01.x): only App-level calls respond —
// currentPage/pageStack/screenshot/callWxMethod/reLaunch/close. Do NOT use Page.*.
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {
  CONFIG,
  E2E_ARTIFACTS,
  ROOT,
  ensureDir,
  fail,
  launchMiniProgram,
  log,
  ok,
  section,
  delay,
  md5,
  readPageBundle,
  makeCaptureScreenshot,
} from './helpers.mjs';

const PROFILE_ROUTE = 'pages/profile/profile';
const APP_NAMESPACES = ['mhp_', 'hza_'];
const PROFILE_RAW = 'records_profile';

const E2E_DIR = E2E_ARTIFACTS;
const QA_FAILURE_PATH = path.join(path.resolve(E2E_ARTIFACTS, '..'), 'qa', '14-failure.txt');
const PROFILE_DIR = path.join(CONFIG.projectPath, 'pages', 'profile');

// ---------------------------------------------------------------------------
// Layer 1: node/page-logic harness (real page methods + Map wx shim)
// ---------------------------------------------------------------------------

const HARNESS_SOURCE = `// temp profile-logic harness (run via tsx); not committed — generated by profile.spec.mjs
import { pathToFileURL } from 'node:url';
import { writeFileSync } from 'node:fs';
const { clone, makeCheck, makeInstanceFactory } = await import(${JSON.stringify(new URL('./helpers.mjs', import.meta.url).href)});

const profileTs = process.env.MHP_PROFILE_TS;
const outPath = process.env.MHP_HARNESS_OUT;
if (!profileTs) throw new Error('MHP_PROFILE_TS not set');
if (!outPath) throw new Error('MHP_HARNESS_OUT not set');

const store = new Map();
const calls = { toast: [], modal: [], vibrateShort: [] };

globalThis.wx = {
  getStorageSync: function (key) { return store.has(key) ? store.get(key) : ''; },
  setStorageSync: function (key, value) { store.set(key, value); },
  removeStorageSync: function (key) { store.delete(key); },
  getStorageInfoSync: function () { return { keys: Array.from(store.keys()) }; },
  showToast: function (options) { calls.toast.push(options); },
  showModal: function (options) {
    calls.modal.push(options);
    if (options && typeof options.success === 'function') options.success({ confirm: true, cancel: false });
  },
  vibrateShort: function (options) { calls.vibrateShort.push(options || {}); },
  vibrateLong: function () {},
};

let captured = null;
globalThis.Page = function (config) { captured = config; };

await import(pathToFileURL(profileTs).href);
if (captured === null) throw new Error('profile.ts did not call Page()');

const RAW_KEY = 'mhp_records_profile';
const snapshot = function () {
  return JSON.stringify(
    Array.from(store.entries()).sort(function (a, b) { return a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0; })
  );
};
const keys = function () { return Array.from(store.keys()); };
const recordList = function () { const v = store.get(RAW_KEY); return Array.isArray(v) ? v : []; };

const makeInstance = makeInstanceFactory(() => captured, { cloneExtras: false });
function input(inst, key, value) {
  inst.onFieldInput({ currentTarget: { dataset: { key: key } }, detail: { value: value } });
}
function toastTitle() {
  const last = calls.toast[calls.toast.length - 1];
  return last && typeof last.title === 'string' ? last.title : null;
}
function reset() { store.clear(); calls.toast.length = 0; calls.modal.length = 0; calls.vibrateShort.length = 0; }

const cases = [];
const check = makeCheck(cases);

reset();
let inst = makeInstance();
inst.onShow();
check('fresh', 'fresh: empty form, no record',
  inst.data.hasRecord === false && inst.data.form.name === '' && inst.data.form.ageRange === '' && recordList().length === 0,
  { data: clone(inst.data), storage_keys: keys() });

reset();
inst = makeInstance();
inst.onShow();
const gBefore = snapshot();
inst.onSave();
const gAfter = snapshot();
check('guard-empty', 'guard: empty name+ageRange -> prompt, no write',
  recordList().length === 0 && gBefore === gAfter && toastTitle() !== null && inst.data.errorText !== '',
  { before_bytes: gBefore, after_bytes: gAfter, bytes_identical: gBefore === gAfter, toast: calls.toast[calls.toast.length - 1] || null, errorText: inst.data.errorText, storage_keys: keys() });

reset();
inst = makeInstance();
inst.onShow();
input(inst, 'name', '   ');
inst.setData({ form: Object.assign({}, inst.data.form, { ageRange: '  ' }) });
const wBefore = snapshot();
inst.onSave();
const wAfter = snapshot();
check('guard-whitespace', 'guard: whitespace-only name+ageRange -> no write',
  recordList().length === 0 && wBefore === wAfter && toastTitle() !== null,
  { before_bytes: wBefore, after_bytes: wAfter, bytes_identical: wBefore === wAfter, toast: calls.toast[calls.toast.length - 1] || null, storage_keys: keys() });

reset();
inst = makeInstance();
inst.onShow();
input(inst, 'name', '  李阿姨  ');
inst.setGender({ currentTarget: { dataset: { value: '女' } } });
inst.onAgeRangeChange({ detail: { value: '3' } });
input(inst, 'allergies', '青霉素');
input(inst, 'medications', '氨氯地平');
input(inst, 'history', '高血压');
inst.onSave();
const added = recordList();
const addedRec = added.length === 1 ? added[0] : null;
const idOk = addedRec !== null && /^prof_\\d+_[a-z0-9]+$/.test(addedRec.id);
check('save-add', 'save: valid input -> single profile record (trimmed, six fields)',
  addedRec !== null && addedRec.name === '李阿姨' && addedRec.ageRange === '60-69' && addedRec.gender === '女' &&
    addedRec.allergies === '青霉素' && addedRec.medications === '氨氯地平' && addedRec.history === '高血压' &&
    idOk && typeof addedRec.createdAt === 'string' && addedRec.createdAt !== '' && typeof addedRec.updatedAt === 'string' && addedRec.updatedAt !== '',
  { record: addedRec, record_count: added.length, id_shape_ok: idOk, save_toast: toastTitle() });

const readInst = makeInstance();
readInst.onShow();
check('readback', 'read-back: onShow repopulates form + timestamps from storage',
  addedRec !== null && readInst.data.hasRecord === true && readInst.data.form.name === '李阿姨' &&
    readInst.data.form.ageRange === '60-69' && readInst.data.form.gender === '女' &&
    readInst.data.form.allergies === '青霉素' && readInst.data.form.medications === '氨氯地平' &&
    readInst.data.form.history === '高血压' && readInst.data.recordId === addedRec.id &&
    readInst.data.createdAtLabel !== '' && readInst.data.updatedAtLabel !== '',
  { form: clone(readInst.data.form), recordId: readInst.data.recordId, createdAtLabel: readInst.data.createdAtLabel, updatedAtLabel: readInst.data.updatedAtLabel });

input(readInst, 'name', '李叔叔');
readInst.onSave();
const updated = recordList();
const updatedRec = updated.length === 1 ? updated[0] : null;
check('update', 'update: existing record updated in place (id/createdAt stable, updatedAt non-decreasing)',
  addedRec !== null && updatedRec !== null && updatedRec.id === addedRec.id && updatedRec.createdAt === addedRec.createdAt &&
    updatedRec.name === '李叔叔' && updatedRec.updatedAt >= addedRec.updatedAt,
  { before: addedRec, after: updatedRec });

input(readInst, 'name', '');
readInst.setData({ form: Object.assign({}, readInst.data.form, { ageRange: '' }) });
const cBefore = snapshot();
readInst.onSave();
const cAfter = snapshot();
const kept = recordList();
check('guard-no-clobber', 'guard: existing record preserved when both empty (no clobber)',
  cBefore === cAfter && kept.length === 1 && kept[0].name === '李叔叔',
  { before_bytes: cBefore, after_bytes: cAfter, bytes_identical: cBefore === cAfter, record: kept[0] || null, toast: calls.toast[calls.toast.length - 1] || null });

readInst.onClear();
const cleared = recordList();
check('clear', 'clear: remove -> empty store + empty view',
  cleared.length === 0 && readInst.data.hasRecord === false && readInst.data.form.name === '' && readInst.data.recordId === '',
  { record_count: cleared.length, modal: calls.modal[calls.modal.length - 1] || null, clear_toast: toastTitle(), data: clone(readInst.data) });

input(readInst, 'name', '王大爷');
readInst.onSave();
const resaved = recordList();
check('save-after-guard', 'save-after-guard: valid save still works after guard/clear',
  resaved.length === 1 && resaved[0].name === '王大爷' && resaved[0].ageRange === '' && resaved[0].gender === '',
  { record: resaved[0] || null });

const failed = cases.filter(function (c) { return !c.pass; }).length;
const result = {
  generated_at: new Date().toISOString(),
  profile_ts: profileTs,
  note: 'REAL page methods from pages/profile/profile.ts; wx = Map-backed shim (isolated from devtools storage)',
  scenarios: cases,
  raw_toast_calls: calls.toast,
  summary: { total: cases.length, passed: cases.length - failed, failed: failed },
};
writeFileSync(outPath, JSON.stringify(result, null, 2) + '\\n');
console.log(JSON.stringify(result, null, 2));
process.exit(failed === 0 ? 0 : 1);
`;

function runLogicHarness() {
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'mhp-profile-harness-'));
  const harnessPath = path.join(tmpDir, 'profile-logic.harness.mjs');
  const outPath = path.join(tmpDir, 'profile-logic.result.json');
  fs.writeFileSync(harnessPath, HARNESS_SOURCE);

  const profileTsPath = path.join(PROFILE_DIR, 'profile.ts');
  const res = spawnSync(process.execPath, ['--import', 'tsx', harnessPath], {
    cwd: ROOT,
    encoding: 'utf8',
    env: { ...process.env, MHP_PROFILE_TS: profileTsPath, MHP_HARNESS_OUT: outPath },
    timeout: 60000,
    maxBuffer: 16 * 1024 * 1024,
  });
  const stdout = `${res.stdout || ''}`;
  const stderr = `${res.stderr || ''}`;

  let result = null;
  if (fs.existsSync(outPath)) {
    try {
      result = JSON.parse(fs.readFileSync(outPath, 'utf8'));
    } catch (err) {
      fail(`harness result JSON unparsable: ${err?.message || err}`);
    }
  }
  return {
    method: 'node --import tsx <temp harness> (Page-capture + Map wx shim)',
    profile_ts: profileTsPath,
    exit: res.status,
    stdout_tail: stdout.slice(-6000),
    stderr_tail: stderr.slice(-6000),
    result,
  };
}

// ---------------------------------------------------------------------------
// Static invariants (source-level, no runtime claim)
// ---------------------------------------------------------------------------


const FORBIDDEN_STRINGS = ['AI 注入', 'health_profile', 'hza_', 'System Prompt', '系统提示词'];

function staticInvariantChecks() {
  const ts = readPageBundle('profile', 'ts');
  const wxml = readPageBundle('profile', 'wxml');
  const wxss = readPageBundle('profile', 'wxss');
  const json = readPageBundle('profile', 'json');
  const combined = [ts, wxml, wxss, json].join('\n');

  const forbidden = FORBIDDEN_STRINGS.filter((term) => combined.includes(term));
  const usesRecordsApi = /records\.profile\.(add|update|remove|list)\s*\(/.test(ts);
  const directStorage = /wx\.(get|set|remove)StorageSync\s*\(/.test(ts);

  let jsonParses = false;
  let jsonTitle = null;
  try {
    const parsed = JSON.parse(json);
    jsonParses = true;
    jsonTitle = parsed.navigationBarTitleText ?? null;
  } catch {
    jsonParses = false;
  }

  const fontLines = wxss.split(/\r?\n/).filter((line) => line.includes('font-size'));
  const fontAllScaled =
    fontLines.length > 0 && fontLines.every((line) => /calc\([^)]*var\(--mhp-scale\)\)/.test(line));

  return {
    profile_js_exists: fs.existsSync(path.join(PROFILE_DIR, 'profile.js')),
    profile_ts_exists: fs.existsSync(path.join(PROFILE_DIR, 'profile.ts')),
    forbidden_strings_present: forbidden,
    uses_records_api: usesRecordsApi,
    direct_storage_calls: directStorage,
    json_parses: jsonParses,
    json_title: jsonTitle,
    font_size_lines: fontLines.length,
    font_size_all_scaled: fontAllScaled,
  };
}

// ---------------------------------------------------------------------------
// Layer 2: automator helpers
// ---------------------------------------------------------------------------

const captureScreenshot = makeCaptureScreenshot('profile');

async function renderEvidence(miniProgram, tag) {
  const stack = await miniProgram.pageStack();
  const top = Array.isArray(stack) && stack.length > 0 ? stack[stack.length - 1] : null;
  const shot = await captureScreenshot(miniProgram, tag);
  return {
    pageStack: stack.length,
    topPath: top ? top.path : null,
    topQuery: top ? top.query : null,
    screenshotBytes: shot.bytes,
    screenshotMd5: shot.md5,
    pngMagic: shot.pngMagic,
    ok:
      stack.length >= 1 &&
      top !== null &&
      top.path === PROFILE_ROUTE &&
      shot.pngMagic &&
      shot.bytes > 5000,
  };
}

// ---------------------------------------------------------------------------
// Failure transcript (built from the real guard-path harness output)
// ---------------------------------------------------------------------------

function scenarioById(result, id) {
  if (!result || !Array.isArray(result.scenarios)) return null;
  return result.scenarios.find((s) => s.id === id) || null;
}

function buildFailureTranscript(logic) {
  const bar = '='.repeat(72);
  const r = logic.result;
  const empty = scenarioById(r, 'guard-empty');
  const ws = scenarioById(r, 'guard-whitespace');
  const clob = scenarioById(r, 'guard-no-clobber');
  const save = scenarioById(r, 'save-after-guard');
  const lines = [];
  const push = (line) => lines.push(line);

  push(bar);
  push('# artifacts/qa/14-failure.txt — task 14 failure-path evidence');
  push('# command: node tests/e2e/profile.spec.mjs');
  push(`# timestamp: ${new Date().toISOString()}`);
  push(`# project: ${CONFIG.projectPath}`);
  push(`# method: real page methods from pages/profile/profile.ts via node tsx harness`);
  push(bar);
  push('');
  push('## (a) 称呼与年龄段均空 -> 提示且不写入（真实代码路径）');
  push('');
  if (empty !== null) {
    push(`scenario: ${empty.name}`);
    push('  input: form.name = "" , form.ageRange = "" (both empty after trim)');
    push(`  storage BEFORE: ${empty.details.before_bytes}`);
    push('  call: inst.onSave()  (pages/profile/profile.ts onSave)');
    push(`  toast recorded: ${JSON.stringify(empty.details.toast)}`);
    push(`  view errorText: ${JSON.stringify(empty.details.errorText)}`);
    push(`  storage AFTER : ${empty.details.after_bytes}`);
    push(`  bytes identical: ${empty.details.bytes_identical}`);
    push(`  storage keys after: ${JSON.stringify(empty.details.storage_keys)}`);
    push(`  assertion pass: ${empty.pass}`);
  } else {
    push('  MISSING: guard-empty scenario not found in harness result');
  }
  push('');
  push('assertion: 守卫在 records.profile.write 之前 return，存储逐字节不变（无 health_profile / records_profile 写入）。');
  push('');
  push('## (b) 纯空白同样被拦截');
  push('');
  if (ws !== null) {
    push(`scenario: ${ws.name}`);
    push('  input: form.name = "   " , form.ageRange = "  " (whitespace only)');
    push(`  storage BEFORE: ${ws.details.before_bytes}`);
    push(`  storage AFTER : ${ws.details.after_bytes}`);
    push(`  bytes identical: ${ws.details.bytes_identical}`);
    push(`  toast recorded: ${JSON.stringify(ws.details.toast)}`);
    push(`  assertion pass: ${ws.pass}`);
  } else {
    push('  MISSING: guard-whitespace scenario');
  }
  push('');
  push('## (c) 已有记录时守卫不覆盖（不写成空记录）');
  push('');
  if (clob !== null) {
    push(`scenario: ${clob.name}`);
    push(`  storage BEFORE: ${clob.details.before_bytes}`);
    push(`  storage AFTER : ${clob.details.after_bytes}`);
    push(`  bytes identical: ${clob.details.bytes_identical}`);
    push(`  record after attempt: ${JSON.stringify(clob.details.record)}`);
    push(`  assertion pass: ${clob.pass}`);
  } else {
    push('  MISSING: guard-no-clobber scenario');
  }
  push('');
  push('## (d) 守卫失败后保存路径仍然可用');
  push('');
  if (save !== null) {
    push(`scenario: ${save.name}`);
    push(`  record after valid save: ${JSON.stringify(save.details.record)}`);
    push(`  assertion pass: ${save.pass}`);
  } else {
    push('  MISSING: save-after-guard scenario');
  }
  push('');
  push('## verdict');
  push('');
  const verdict =
    empty !== null &&
    empty.pass &&
    empty.details.bytes_identical === true &&
    ws !== null &&
    ws.pass &&
    clob !== null &&
    clob.pass &&
    save !== null &&
    save.pass;
  push(`PASS=${verdict} (empty guard no-write; whitespace guard no-write; no clobber; save-after-guard works)`);
  push(bar);
  push('');
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  ensureDir(E2E_DIR);
  ensureDir(path.dirname(QA_FAILURE_PATH));
  section('PROFILE SPEC');

  const report = {
    command: 'node tests/e2e/profile.spec.mjs',
    timestamp: new Date().toISOString(),
    platform: `${os.platform()} ${os.release()} (${os.arch()})`,
    node_version: process.version,
    project_path: CONFIG.projectPath,
    logic: null,
    render: null,
    render_saved: null,
    namespace: null,
    storage_readback: null,
    static_invariants: null,
    summary: null,
  };

  let allOk = true;

  // ---- Layer 1: real page logic ----
  const logic = runLogicHarness();
  report.logic = {
    method: logic.method,
    profile_ts: logic.profile_ts,
    exit: logic.exit,
    result: logic.result,
  };
  const logicScenarios = logic.result ? logic.result.scenarios : [];
  const logicFailed = logic.result ? logic.result.summary.failed : -1;
  if (logic.result !== null && logic.exit === 0 && logicFailed === 0) {
    ok(`logic harness: ${logic.result.summary.passed}/${logic.result.summary.total} scenarios passed (real page methods)`);
  } else {
    fail(`logic harness failed (exit=${logic.exit}, failed_scenarios=${logicFailed}); stderr tail: ${logic.stderr_tail}`);
    allOk = false;
  }
  for (const scenario of logicScenarios) {
    log(`  [logic] ${scenario.pass ? 'PASS' : 'FAIL'} ${scenario.id}: ${scenario.name}`);
    if (!scenario.pass) allOk = false;
  }

  // ---- Static invariants ----
  const statics = staticInvariantChecks();
  report.static_invariants = {
    profile_js_exists: statics.profile_js_exists,
    profile_ts_exists: statics.profile_ts_exists,
    forbidden_strings_present: statics.forbidden_strings_present,
    uses_records_api: statics.uses_records_api,
    direct_storage_calls: statics.direct_storage_calls,
    json_parses: statics.json_parses,
    json_title: statics.json_title,
    font_size_lines: statics.font_size_lines,
    font_size_all_scaled: statics.font_size_all_scaled,
  };
  if (
    statics.profile_js_exists === false &&
    statics.profile_ts_exists === true &&
    statics.forbidden_strings_present.length === 0 &&
    statics.uses_records_api &&
    !statics.direct_storage_calls &&
    statics.json_parses &&
    statics.json_title === '个人档案' &&
    statics.font_size_all_scaled
  ) {
    ok('static invariants: profile.js deleted; records API only; tokens/scale wxss; no forbidden strings');
  } else {
    fail(`static invariant failure: ${JSON.stringify(report.static_invariants)}`);
    allOk = false;
  }

  // ---- Layer 2: runtime ----
  let miniProgram;
  try {
    miniProgram = await launchMiniProgram();

    for (const ns of APP_NAMESPACES) {
      await miniProgram.callWxMethod('removeStorageSync', ns + PROFILE_RAW);
    }

    // warm-up + settle: the very first reLaunch can race the page's onShow render,
    // so the empty baseline is captured only after two settled reLaunches.
    await miniProgram.reLaunch('/' + PROFILE_ROUTE);
    await delay(800);
    await miniProgram.reLaunch('/' + PROFILE_ROUTE);
    await delay(800);
    const emptyRender = await renderEvidence(miniProgram, 'empty');
    report.render = { ...emptyRender, method: 'reLaunch+pageStack+screenshot' };
    if (emptyRender.ok) {
      ok(`render evidence: pageStack=${emptyRender.pageStack}, top=${emptyRender.topPath}, bytes=${emptyRender.screenshotBytes}, bytes>5000=${emptyRender.screenshotBytes > 5000}`);
    } else {
      fail(`render check failed: ${JSON.stringify(emptyRender)}`);
      allOk = false;
    }

    const sample = {
      id: 'prof_demo_1',
      createdAt: '2026-02-01T00:00:00.000Z',
      updatedAt: '2026-02-01T00:00:00.000Z',
      name: '李建国',
      ageRange: '60-69',
      gender: '男',
      allergies: '青霉素',
      medications: '氯沙坦',
      history: '高血压',
    };

    // negative control: legacy hza_ write must NOT change the render
    await miniProgram.callWxMethod('setStorageSync', 'hza_' + PROFILE_RAW, [sample]);
    await miniProgram.reLaunch('/' + PROFILE_ROUTE);
    await delay(800);
    const legacyShot = await captureScreenshot(miniProgram, 'legacy-hza');
    await miniProgram.callWxMethod('removeStorageSync', 'hza_' + PROFILE_RAW);
    const hzaChanged = legacyShot.md5 !== emptyRender.screenshotMd5;

    // positive: mhp_ write changes the render
    await miniProgram.callWxMethod('setStorageSync', 'mhp_' + PROFILE_RAW, [sample]);
    await miniProgram.reLaunch('/' + PROFILE_ROUTE);
    await delay(800);
    const savedRender = await renderEvidence(miniProgram, 'saved');
    const mhpChanged = savedRender.screenshotMd5 !== emptyRender.screenshotMd5;

    report.namespace = {
      declared: 'mhp_',
      candidates: APP_NAMESPACES,
      runtime_observed: mhpChanged && !hzaChanged ? 'mhp_' : null,
      empty_baseline_md5: emptyRender.screenshotMd5,
      observations: {
        mhp_: { md5: savedRender.screenshotMd5, bytes: savedRender.screenshotBytes, changed_vs_empty: mhpChanged },
        hza_: { md5: legacyShot.md5, bytes: legacyShot.bytes, changed_vs_empty: hzaChanged },
      },
    };
    report.render_saved = {
      ...savedRender,
      namespace: 'mhp_',
      changed_vs_empty_md5: mhpChanged,
    };

    if (report.namespace.runtime_observed === 'mhp_') {
      ok('runtime namespace is "mhp_" (mhp_ write changes render; hza_ does not)');
    } else {
      fail(`runtime namespace must be "mhp_" but observed ${JSON.stringify(report.namespace)}`);
      allOk = false;
    }
    if (savedRender.ok && mhpChanged) {
      ok('profile render reads the saved record (md5 changed vs empty)');
    } else {
      fail(`profile did not render the saved record: ${JSON.stringify(report.render_saved)}`);
      allOk = false;
    }

    // storage-level save -> read-back
    const readBack = await miniProgram.callWxMethod('getStorageSync', 'mhp_' + PROFILE_RAW);
    const matches = JSON.stringify(readBack) === JSON.stringify([sample]);
    report.storage_readback = {
      key: 'mhp_records_profile',
      written: [sample],
      read_back: readBack,
      matches,
      persisted_after_relaunch: null,
    };
    if (matches) {
      ok('storage read-back matches the written record exactly');
    } else {
      fail(`storage read-back mismatch: ${JSON.stringify(readBack)}`);
      allOk = false;
    }

    // relaunch persistence
    try {
      await miniProgram.close();
      log('miniProgram.close() done');
    } catch (err) {
      log(`warning: close failed: ${err?.message || err}`);
    }
    await delay(2000);
    miniProgram = await launchMiniProgram();
    const persisted = await miniProgram.callWxMethod('getStorageSync', 'mhp_' + PROFILE_RAW);
    const persistedOk = JSON.stringify(persisted) === JSON.stringify([sample]);
    report.storage_readback.persisted_after_relaunch = persistedOk;
    if (persistedOk) {
      ok('saved record persists across a full relaunch');
    } else {
      fail(`record did not persist across relaunch: ${JSON.stringify(persisted)}`);
      allOk = false;
    }

    // cleanup runtime storage (leave the project clean)
    for (const ns of APP_NAMESPACES) {
      await miniProgram.callWxMethod('removeStorageSync', ns + PROFILE_RAW);
    }
  } catch (err) {
    fail(`profile spec run error: ${err?.stack || err}`);
    report.error = err?.message || String(err);
    allOk = false;
  } finally {
    if (miniProgram) {
      try {
        await miniProgram.close();
        log('miniProgram.close() done');
      } catch (err) {
        log(`warning: miniProgram.close() failed: ${err?.message || err}`);
      }
    }
  }

  // ---- Failure transcript ----
  fs.writeFileSync(QA_FAILURE_PATH, buildFailureTranscript(logic));
  log(`failure evidence: ${QA_FAILURE_PATH}`);

  // ---- Summary ----
  const checks = {
    logic_harness_ok: logic.result !== null && logic.exit === 0 && logicFailed === 0,
    render_ok: report.render ? report.render.ok === true : false,
    namespace_observed: report.namespace ? report.namespace.runtime_observed === 'mhp_' : false,
    render_saved_ok: Boolean(
      report.render_saved && report.render_saved.ok && report.render_saved.changed_vs_empty_md5
    ),
    storage_readback_ok: Boolean(report.storage_readback && report.storage_readback.matches === true),
    relaunch_persistence_ok: Boolean(
      report.storage_readback && report.storage_readback.persisted_after_relaunch === true
    ),
    profile_js_deleted: statics.profile_js_exists === false,
    no_forbidden_strings: statics.forbidden_strings_present.length === 0,
    records_api_only: statics.uses_records_api === true && statics.direct_storage_calls === false,
    font_scaled: statics.font_size_all_scaled === true,
    json_ok: statics.json_parses === true && statics.json_title === '个人档案',
  };
  const checksPassed = Object.values(checks).every((v) => v === true);
  log(`summary checks: ${JSON.stringify(checks)}`);

  report.summary = {
    ...checks,
    logic_scenarios_total: logic.result ? logic.result.summary.total : 0,
    logic_scenarios_passed: logic.result ? logic.result.summary.passed : 0,
    passed: checksPassed && allOk === true,
    failed: !(checksPassed && allOk === true),
  };

  const reportPath = path.join(E2E_DIR, 'profile.json');
  fs.writeFileSync(reportPath, JSON.stringify(report, null, 2) + '\n');
  log(`profile evidence: ${reportPath}`);

  return report.summary.passed;
}

main().then(
  (passed) => {
    process.exit(passed ? 0 : 1);
  },
  (err) => {
    console.error(`[e2e] FAIL ${err?.stack || err}`);
    process.exit(1);
  }
);
