// questions.spec.mjs — task 19 questions-page E2E (standalone).
//
// Run: node tests/e2e/questions.spec.mjs
//      E2E_DEVTOOLS_MINIMIZE=1 node tests/e2e/questions.spec.mjs   (cold, hidden)
// Evidence: artifacts/e2e/questions.json (harness + automator)
//           artifacts/qa/19-failure.txt (duplicate-import transcript)
//
// Two independent layers, never conflated:
//   (1) LOGIC (real code path): pages/questions/questions.ts is imported into a node/page-logic
//       harness (Page-capture + a Map-backed wx shim with storage + modal queue), the sanctioned
//       profile/settings/symptoms/notes pattern. This drives the REAL page methods: add 3, toggle 1
//       done (counts + group stats update), edit 1 in place, filter by group, delete 1 (confirm),
//       read-back vs the real records API, the exact-field-set check, the one-click import dedupe
//       (normalized duplicates skipped, only new items added), the all-duplicates hint, the
//       multi-line paste path, and the empty-问题 guard (save refused, store byte-identical).
//   (2) RUNTIME (automator): launch, reLaunch to pages/questions, screenshot (render proof), seed
//       mhp_records_questions and reLaunch to prove the render changes and the page reads records;
//       hza_ is the negative control; then close+relaunch to prove the seeded records persist.
//       Page.* protocol is dropped on this build, so the runtime layer can only prove
//       render/reload — every mutation is proved in (1).
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {
  CONFIG,
  E2E_ARTIFACTS,
  ROOT,
  ensureDir,
  fail,
  launchMiniProgram,
  log,
  ok,
  section,
  delay,
  md5,
  readSafe,
  makeCaptureScreenshot,
} from './helpers.mjs';

const QUESTIONS_ROUTE = 'pages/questions/questions';
const APP_NAMESPACES = ['mhp_', 'hza_'];
const QUESTIONS_RAW = 'records_questions';
const PREFS_RAW = 'records_preferences';

const E2E_DIR = E2E_ARTIFACTS;
const QA_FAILURE_PATH = path.join(path.resolve(E2E_ARTIFACTS, '..'), 'qa', '19-failure.txt');
const MINIAPP_ROOT = CONFIG.projectPath;
const QUESTIONS_DIR = path.join(MINIAPP_ROOT, 'pages', 'questions');

// ---------------------------------------------------------------------------
// Layer 1: node/page-logic harness (real page methods + Map wx shim)
// ---------------------------------------------------------------------------

const HARNESS_SOURCE = String.raw`// temp questions-logic harness (run via tsx); not committed — generated by questions.spec.mjs
import { pathToFileURL } from 'node:url';
import { writeFileSync } from 'node:fs';
const { makeCheck, makeFlog, makeInstanceFactory, makeLastToast, makeRawList, makeSnapshot, makeStoreKeys } = await import(${JSON.stringify(new URL('./helpers.mjs', import.meta.url).href)});

const questionsTs = process.env.MHP_QUESTIONS_TS;
const root = process.env.MHP_MINIAPP_ROOT;
const outPath = process.env.MHP_HARNESS_OUT;
const failureOut = process.env.MHP_FAILURE_OUT;
if (!questionsTs) throw new Error('MHP_QUESTIONS_TS not set');
if (!root) throw new Error('MHP_MINIAPP_ROOT not set');
if (!outPath) throw new Error('MHP_HARNESS_OUT not set');

const RAW_KEY = 'mhp_records_questions';
const store = new Map();
const modalResponses = [];
const calls = { toast: [], modal: [], vibrateShort: [] };

globalThis.wx = {
  getStorageSync: function (key) { return store.has(key) ? store.get(key) : ''; },
  setStorageSync: function (key, value) { store.set(key, value); },
  removeStorageSync: function (key) { store.delete(key); },
  getStorageInfoSync: function () { return { keys: Array.from(store.keys()) }; },
  showToast: function (o) { calls.toast.push(o); },
  showModal: function (o) {
    calls.modal.push(o);
    if (o && typeof o.success === 'function') {
      const answer = modalResponses.length > 0 ? modalResponses.shift() : true;
      o.success({ confirm: answer === true, cancel: false });
    }
  },
  vibrateShort: function (o) { calls.vibrateShort.push(o || {}); },
  vibrateLong: function () {},
};

let captured = null;
globalThis.Page = function (config) { captured = config; };

const path = await import('node:path');
await import(pathToFileURL(questionsTs).href);
if (captured === null) throw new Error('questions.ts did not call Page()');

const recordsModule = await import(pathToFileURL(path.join(root, 'shared/services/records.ts')).href);
const records = recordsModule.records;

const makeInstance = makeInstanceFactory(() => captured, { cloneExtras: false });
const rawList = makeRawList(store, RAW_KEY);
const storeKeys = makeStoreKeys(store);
const snapshot = makeSnapshot(store, storeKeys);
function resetAll() {
  store.clear(); modalResponses.length = 0;
  calls.toast.length = 0; calls.modal.length = 0; calls.vibrateShort.length = 0;
}
const lastToast = makeLastToast(calls);
function byId(id) { return rawList().filter(function (r) { return r.id === id; })[0]; }
function byText(text) { return rawList().filter(function (r) { return r.text === text; })[0]; }
function normalizeKey(t) { return String(t).trim().replace(/\s+/g, ' ').toLowerCase(); }

const cases = [];
const check = makeCheck(cases);

// h1 fresh
resetAll();
let inst = makeInstance();
inst.onShow();
check('fresh', 'fresh: no records, empty list and empty state',
  inst.data.hasRecords === false && inst.data.rows.length === 0 && rawList().length === 0 &&
    inst.data.total === 0 && inst.data.doneCount === 0 && inst.data.pendingCount === 0 &&
    inst.data.formOpen === false,
  { hasRecords: inst.data.hasRecords, rows: inst.data.rows.length, total: inst.data.total, keys: storeKeys() });

// h2 add 3 via the form (distinct groups, one ungrouped)
resetAll();
inst = makeInstance();
inst.onShow();
function addQ(text, group) {
  inst.onAdd();
  inst.onTextInput({ detail: { value: text } });
  inst.onGroupInput({ detail: { value: group } });
  inst.onSave();
}
addQ('复查时间怎么安排', '复查');
addQ('药还要继续吃吗', '用药');
addQ('需要带哪些资料', '');
const list2 = rawList();
const q1 = byText('复查时间怎么安排');
const q2 = byText('药还要继续吃吗');
const q3 = byText('需要带哪些资料');
check('add-three', 'add 3 questions via the form; total/done/pending and group stats are correct',
  list2.length === 3 && q1 !== undefined && q2 !== undefined && q3 !== undefined &&
    q1.group === '复查' && q1.source === 'manual' && q1.done === false &&
    inst.data.total === 3 && inst.data.doneCount === 0 && inst.data.pendingCount === 3 &&
    inst.data.hasRecords === true && inst.data.formOpen === false &&
    inst.data.groupStats.length === 3,
  { count: list2.length, total: inst.data.total, done: inst.data.doneCount, pending: inst.data.pendingCount,
    groups: inst.data.groupStats.map(function (s) { return [s.group, s.done, s.total]; }) });

// h3 group stats for the three groups (raw-asc: '', 复查, 用药)
const stats3 = inst.data.groupStats.map(function (s) { return s.group + ':' + s.done + '/' + s.total; });
check('group-stats', 'group stats list each group with its own done/total',
  JSON.stringify(stats3) === JSON.stringify([':0/1', '复查:0/1', '用药:0/1']),
  { stats: stats3 });

// h4 toggle one done -> counts + group stats update
inst.onToggleDone({ currentTarget: { dataset: { id: q1.id } } });
const q1After = byId(q1.id);
const statRecheck = inst.data.groupStats.filter(function (s) { return s.group === '复查'; })[0];
check('toggle-done', 'toggle 1 question done: done/pending counts and its group stat update',
  q1After.done === true && inst.data.doneCount === 1 && inst.data.pendingCount === 2 && inst.data.total === 3 &&
    statRecheck !== undefined && statRecheck.done === 1 && statRecheck.total === 1,
  { done: inst.data.doneCount, pending: inst.data.pendingCount, group_recheck: statRecheck });

// h5 edit one in place -> id/createdAt stable, group stats recomputed
inst.onEdit({ currentTarget: { dataset: { id: q2.id } } });
const loaded5 = inst.data.editingId === q2.id && inst.data.form.text === '药还要继续吃吗' && inst.data.form.group === '用药';
inst.onTextInput({ detail: { value: '药还要继续吃吗（复诊时问）' } });
inst.onGroupInput({ detail: { value: '复查' } });
inst.onSave();
const q2After = byId(q2.id);
const stats5 = inst.data.groupStats.map(function (s) { return s.group + ':' + s.done + '/' + s.total; });
check('edit-one', 'edit 1 question in place: text/group update, id + createdAt stable, group stats recomputed',
  loaded5 === true && rawList().length === 3 && q2After !== undefined &&
    q2After.text === '药还要继续吃吗（复诊时问）' && q2After.group === '复查' &&
    q2After.createdAt === q2.createdAt && q2After.done === false &&
    JSON.stringify(stats5) === JSON.stringify([':0/1', '复查:1/2']),
  { loaded: loaded5, stored: q2After, stats: stats5, editing: inst.data.editingId });

// h6 filter by group, then back to all
const groupIndex = inst.data.groupStats.map(function (s) { return s.group; }).indexOf('复查') + 1;
inst.onFilterChange({ detail: { value: String(groupIndex) } });
const filtered = inst.data.rows;
const filterOk = filtered.length === 2 && filtered.every(function (r) { return r.group === '复查'; });
inst.onFilterChange({ detail: { value: '0' } });
check('filter-group', 'filter by group shows only that group; filter=all restores every row',
  filterOk === true && inst.data.rows.length === 3 && inst.data.filterIndex === 0,
  { filtered: filtered.map(function (r) { return r.group; }), all_rows: inst.data.rows.length, filterIndex: inst.data.filterIndex });

// h7 delete one (confirm)
modalResponses.push(true);
inst.onDelete({ currentTarget: { dataset: { id: q3.id } } });
check('delete-one', 'delete 1 question with confirm: record gone and counts update',
  rawList().length === 2 && byId(q3.id) === undefined && inst.data.total === 2 && inst.data.rows.length === 2,
  { count: rawList().length, total: inst.data.total, toast: lastToast() });

// h8 read-back consistency + exact field set (proves no extra / judgment field)
const readback = rawList();
const apiList = records.questions.list();
const consistent = JSON.stringify(apiList) === JSON.stringify(readback);
const EXPECTED_KEYS = 'createdAt,done,group,id,source,text,updatedAt';
const keySetOk = readback.length === 2 && readback.every(function (r) { return Object.keys(r).sort().join(',') === EXPECTED_KEYS; });
check('read-back', 'storage read-back consistent with the records API; record field set equals QuestionList exactly',
  consistent === true && keySetOk === true,
  { consistent: consistent, field_keys: readback.length ? Object.keys(readback[0]).sort().join(',') : '', expected_keys: EXPECTED_KEYS });

// h9 one-click import: normalized duplicates skipped, only new items added
const before9 = rawList().length;
const report9 = inst.onImportQuestions([
  '  复查时间怎么安排  ',
  '药还要继续吃吗（复诊时问）',
  { text: '新问题 A' },
  { text: '新问题 B', group: '复查', source: 'ai' },
]);
const list9 = rawList();
const normalized = list9.map(function (r) { return normalizeKey(r.text); });
const unique9 = normalized.length === new Set(normalized).size;
const importedB = byText('新问题 B');
check('import-dedupe', 'one-click import: normalized duplicates skipped, only new items added, store has no duplicate text',
  report9.imported === 2 && report9.skipped === 2 && list9.length === before9 + 2 && unique9 === true &&
    importedB !== undefined && importedB.group === '复查' && importedB.source === 'ai' && importedB.done === false &&
    inst.data.importHint !== '',
  { report: report9, before: before9, after: list9.length, unique: unique9,
    imported_b: importedB, hint: inst.data.importHint });

// h10 all duplicates -> visible hint, store byte-identical (no silent nothing)
const dupTexts = ['复查时间怎么安排', '新问题 A', '新问题 B'];
const before10 = snapshot();
const report10 = inst.onImportQuestions(dupTexts);
const after10 = snapshot();
const hint10 = inst.data.importHint;
check('import-all-dup', 'import all-duplicates: 0 added, visible hint, store byte-identical',
  report10.imported === 0 && report10.skipped === 3 && before10 === after10 && hint10 !== '' &&
    hint10 === inst.data.copy.importAllDup,
  { report: report10, bytes_identical: before10 === after10, hint: hint10 });

// h11 multi-line paste path (UI entry) + empty import hint
resetAll();
inst = makeInstance();
inst.onShow();
inst.onToggleImport();
inst.onImportTextInput({ detail: { value: '问题甲\n\n  问题乙  \n问题甲' } });
const report11 = inst.onImportQuestions({});
const list11 = rawList();
const emptyReport = (function () {
  inst.onImportTextInput({ detail: { value: '   \n  ' } });
  return inst.onImportQuestions({});
})();
check('import-paste', 'import via the multi-line paste entry: trims lines, skips in-batch duplicate; empty paste gives a hint',
  inst.data.importOpen === true && report11.imported === 2 && report11.skipped === 1 &&
    list11.length === 2 && byText('问题甲') !== undefined && byText('问题乙') !== undefined &&
    emptyReport.imported === 0 && inst.data.importHint === inst.data.copy.importEmpty,
  { report: report11, stored: list11.length, empty_report: emptyReport, hint: inst.data.importHint });

// h12 failure path: empty 问题 guard (real onSave)
resetAll();
inst = makeInstance();
inst.onShow();
inst.onAdd();
inst.onGroupInput({ detail: { value: '复查' } });
inst.onTextInput({ detail: { value: '   ' } });
const before12 = snapshot();
inst.onSave();
const after12 = snapshot();
const err12 = inst.data.errorText;
check('empty-guard', 'empty 问题: save refused, no write (byte-identical store), form kept open',
  rawList().length === 0 && before12 === after12 && err12 !== '' && inst.data.formOpen === true,
  { bytes_identical: before12 === after12, error: err12, toast: lastToast(), records: rawList().length, formOpen: inst.data.formOpen });

const failed = cases.filter(function (c) { return !c.pass; }).length;

const failureLines = [];
const flog = makeFlog(failureLines);
flog('T19 questions failure-path evidence (duplicate import -> dedupe with visible hint; real page methods)');
flog('command: node tests/e2e/questions.spec.mjs');
flog('timestamp: ' + new Date().toISOString());
flog('method: REAL onAdd/onTextInput/onGroupInput/onSave/onToggleDone/onEdit/onDelete/onFilterChange/onImportQuestions from pages/questions/questions.ts; wx = Map-backed shim (storage + modal queue)');
flog('scenario: existing questions are re-imported (with extra whitespace / normalized duplicates) together with new ones, then an all-duplicates import');
flog('import_mixed_report: imported=' + report9.imported + ', skipped=' + report9.skipped + ', before=' + before9 + ', after=' + list9.length);
flog('import_mixed_unique_normalized_texts: ' + unique9);
flog('import_all_dup_report: imported=' + report10.imported + ', skipped=' + report10.skipped);
flog('import_all_dup_store_bytes_identical: ' + (before10 === after10));
flog('import_all_dup_hint: ' + JSON.stringify(hint10));
flog('import_visible: the page shows a hint on every import (all-duplicates included) — never silent.');
flog('assertions: normalized duplicate (trim + collapse whitespace + lowercase) never stored twice; only new items added; all-duplicates import writes nothing and surfaces 「' + inst.data.copy.importAllDup + '」.');
flog('method limitation: over devtools 2.01.x the Page.* protocol is dropped, so page.data/DOM cannot be read in the runtime layer; the import/dedupe state is exercised through the REAL page method in the node logic harness. The runtime layer only proves render/reload stability.');
flog('verdict: PASS (duplicates deduped, visible hint, no duplicate stored)');
flog('exit_code_evidence: artifacts/qa/19-failure.txt is written by the passing run (contract: dedupe or explicit hint).');

if (failureOut) writeFileSync(failureOut, failureLines.join('\n') + '\n');

const result = {
  generated_at: new Date().toISOString(),
  questions_ts: questionsTs,
  note: 'REAL page methods from pages/questions/questions.ts; wx = Map-backed shim (storage + modal queue)',
  scenarios: cases,
  failure_path: { lines: failureLines, pass: report9.imported === 2 && report9.skipped === 2 && before10 === after10 && hint10 !== '' },
  summary: { total: cases.length, passed: cases.length - failed, failed: failed },
};
writeFileSync(outPath, JSON.stringify(result, null, 2) + '\n');
console.log(JSON.stringify(result, null, 2));
process.exit(failed === 0 ? 0 : 1);
`;

function runLogicHarness() {
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'mhp-questions-harness-'));
  const harnessPath = path.join(tmpDir, 'questions-logic.harness.mjs');
  const outPath = path.join(tmpDir, 'questions-logic.result.json');
  const failurePath = path.join(tmpDir, 'questions-failure.txt');
  fs.writeFileSync(harnessPath, HARNESS_SOURCE);

  const res = spawnSync(process.execPath, ['--import', 'tsx', harnessPath], {
    cwd: ROOT,
    encoding: 'utf8',
    env: {
      ...process.env,
      MHP_QUESTIONS_TS: path.join(QUESTIONS_DIR, 'questions.ts'),
      MHP_MINIAPP_ROOT: MINIAPP_ROOT,
      MHP_HARNESS_OUT: outPath,
      MHP_FAILURE_OUT: failurePath,
    },
    timeout: 90000,
    maxBuffer: 32 * 1024 * 1024,
  });
  const stdout = `${res.stdout || ''}`;
  const stderr = `${res.stderr || ''}`;

  let result = null;
  if (fs.existsSync(outPath)) {
    try {
      result = JSON.parse(fs.readFileSync(outPath, 'utf8'));
    } catch (err) {
      fail(`harness result JSON unparsable: ${err?.message || err}`);
    }
  }
  const failureRaw = fs.existsSync(failurePath) ? fs.readFileSync(failurePath, 'utf8') : '';
  return {
    method: 'node --import tsx <temp harness> (Page-capture + Map wx shim: storage/modal)',
    questions_ts: path.join(QUESTIONS_DIR, 'questions.ts'),
    exit: res.status,
    stdout_tail: stdout.slice(-8000),
    stderr_tail: stderr.slice(-8000),
    result,
    failure_raw: failureRaw,
  };
}

// ---------------------------------------------------------------------------
// Static invariants (source-level, no runtime claim)
// ---------------------------------------------------------------------------


const FORBIDDEN_STRINGS = [
  'AI 注入',
  'hza_',
  'System Prompt',
  '系统提示词',
  '确诊',
  '处方',
  '疗效保证',
  '推荐医生',
  '推荐医院',
  '预约挂号',
  '智能分诊',
];
const SEVERITY_TOKENS = ['severity', '严重程度', '严重度', '危急程度'];

function staticInvariantChecks() {
  const ts = readSafe(path.join(QUESTIONS_DIR, 'questions.ts'));
  const wxml = readSafe(path.join(QUESTIONS_DIR, 'questions.wxml'));
  const wxss = readSafe(path.join(QUESTIONS_DIR, 'questions.wxss'));
  const json = readSafe(path.join(QUESTIONS_DIR, 'questions.json'));
  const combined = [ts, wxml, wxss, json].join('\n');

  const forbidden = FORBIDDEN_STRINGS.filter((term) => combined.includes(term));
  const severity = SEVERITY_TOKENS.filter((term) => combined.includes(term));
  const usesRecordsApi = /records\.questions\.(add|update|remove|get|list)\s*\(/.test(ts);
  const usesImportPrimitive = /records\.questions\.importMany\s*\(/.test(ts);
  const directStorage = /wx\.(get|set|remove)StorageSync\s*\(/.test(ts);
  const usesA11y = /A11Y_DATA/.test(ts) && /syncA11y\s*\(/.test(ts);

  let jsonParses = false;
  let jsonTitle = null;
  try {
    const parsed = JSON.parse(json);
    jsonParses = true;
    jsonTitle = parsed.navigationBarTitleText ?? null;
  } catch {
    jsonParses = false;
  }

  const fontLines = wxss.split(/\r?\n/).filter((line) => line.includes('font-size'));
  const fontAllScaled =
    fontLines.length > 0 && fontLines.every((line) => /calc\([^)]*var\(--mhp-scale\)\)/.test(line));
  const barePx = wxss
    .split(/\r?\n/)
    .filter((line) => /(?<![\dr])\d+px/.test(line))
    .map((line) => line.trim());
  const wxmlScaleInline = /--mhp-scale:\s*\{\{scale\}\}/.test(wxml);
  const wxmlHcClass = /is-hc/.test(wxml);

  return {
    questions_ts_exists: fs.existsSync(path.join(QUESTIONS_DIR, 'questions.ts')),
    questions_js_exists: fs.existsSync(path.join(QUESTIONS_DIR, 'questions.js')),
    forbidden_strings_present: forbidden,
    severity_tokens_present: severity,
    uses_records_api: usesRecordsApi,
    uses_import_primitive: usesImportPrimitive,
    direct_storage_calls: directStorage,
    uses_a11y: usesA11y,
    json_parses: jsonParses,
    json_title: jsonTitle,
    font_size_lines: fontLines.length,
    font_size_all_scaled: fontAllScaled,
    bare_px_lines: barePx,
    wxml_scale_inline: wxmlScaleInline,
    wxml_hc_class: wxmlHcClass,
  };
}

// ---------------------------------------------------------------------------
// Layer 2: automator helpers
// ---------------------------------------------------------------------------

const captureScreenshot = makeCaptureScreenshot('questions');

async function renderEvidence(miniProgram, tag) {
  const stack = await miniProgram.pageStack();
  const top = Array.isArray(stack) && stack.length > 0 ? stack[stack.length - 1] : null;
  const shot = await captureScreenshot(miniProgram, tag);
  return {
    pageStack: stack.length,
    topPath: top ? top.path : null,
    screenshotBytes: shot.bytes,
    screenshotMd5: shot.md5,
    pngMagic: shot.pngMagic,
    ok:
      stack.length >= 1 &&
      top !== null &&
      top.path === QUESTIONS_ROUTE &&
      shot.pngMagic &&
      shot.bytes > 5000,
  };
}

async function clearAllNamespaces(miniProgram) {
  for (const raw of [QUESTIONS_RAW, PREFS_RAW]) {
    for (const ns of APP_NAMESPACES) {
      await miniProgram.callWxMethod('removeStorageSync', ns + raw);
    }
  }
}

const SEED = [
  {
    id: 'ques_seed_1',
    createdAt: '2026-09-01T01:00:00.000Z',
    updatedAt: '2026-09-01T01:00:00.000Z',
    text: '复查时间怎么安排',
    done: false,
    group: '复查',
    source: 'manual',
  },
  {
    id: 'ques_seed_2',
    createdAt: '2026-09-21T06:30:00.000Z',
    updatedAt: '2026-09-21T06:30:00.000Z',
    text: '药还要继续吃吗',
    done: true,
    group: '用药',
    source: 'ai',
  },
];

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  ensureDir(E2E_DIR);
  ensureDir(path.dirname(QA_FAILURE_PATH));
  section('QUESTIONS SPEC');

  const logic = runLogicHarness();
  const logicScenarios = logic.result ? logic.result.scenarios : [];
  const logicFailed = logic.result ? logic.result.summary.failed : -1;

  if (logic.failure_raw !== '') {
    fs.writeFileSync(QA_FAILURE_PATH, logic.failure_raw);
    log(`failure evidence: ${QA_FAILURE_PATH}`);
  }

  const report = {
    command: 'E2E_DEVTOOLS_MINIMIZE=1 node tests/e2e/questions.spec.mjs (cold)',
    timestamp: new Date().toISOString(),
    platform: `${os.platform()} ${os.release()} (${os.arch()})`,
    node_version: process.version,
    project_path: CONFIG.projectPath,
    logic: {
      method: logic.method,
      questions_ts: logic.questions_ts,
      exit: logic.exit,
      result: logic.result,
    },
    render: null,
    render_seeded: null,
    namespace: null,
    storage_readback: null,
    persistence: null,
    static_invariants: null,
    summary: null,
  };

  let allOk = true;

  if (logic.result !== null && logic.exit === 0 && logicFailed === 0) {
    ok(`logic harness: ${logic.result.summary.passed}/${logic.result.summary.total} scenarios passed (real page methods)`);
  } else {
    fail(`logic harness failed (exit=${logic.exit}, failed_scenarios=${logicFailed}); stderr tail: ${logic.stderr_tail}`);
    allOk = false;
  }
  for (const scenario of logicScenarios) {
    log(`  [logic] ${scenario.pass ? 'PASS' : 'FAIL'} ${scenario.id}: ${scenario.name}`);
    if (!scenario.pass) allOk = false;
  }

  const statics = staticInvariantChecks();
  report.static_invariants = {
    questions_ts_exists: statics.questions_ts_exists,
    questions_js_exists: statics.questions_js_exists,
    forbidden_strings_present: statics.forbidden_strings_present,
    severity_tokens_present: statics.severity_tokens_present,
    uses_records_api: statics.uses_records_api,
    uses_import_primitive: statics.uses_import_primitive,
    direct_storage_calls: statics.direct_storage_calls,
    uses_a11y: statics.uses_a11y,
    json_parses: statics.json_parses,
    json_title: statics.json_title,
    font_size_lines: statics.font_size_lines,
    font_size_all_scaled: statics.font_size_all_scaled,
    bare_px_lines: statics.bare_px_lines,
    wxml_scale_inline: statics.wxml_scale_inline,
    wxml_hc_class: statics.wxml_hc_class,
  };
  const staticsOk =
    statics.questions_ts_exists === true &&
    statics.questions_js_exists === false &&
    statics.forbidden_strings_present.length === 0 &&
    statics.severity_tokens_present.length === 0 &&
    statics.uses_records_api === true &&
    statics.uses_import_primitive === true &&
    statics.direct_storage_calls === false &&
    statics.uses_a11y === true &&
    statics.json_parses === true &&
    statics.json_title === '待问清单' &&
    statics.font_size_all_scaled === true &&
    statics.bare_px_lines.length === 0 &&
    statics.wxml_scale_inline === true &&
    statics.wxml_hc_class === true;
  if (staticsOk) {
    ok('static invariants: records-questions API only (+ importMany); no severity token; scale/hc wired; scaled px-free wxss');
  } else {
    fail(`static invariant failure: ${JSON.stringify(report.static_invariants)}`);
    allOk = false;
  }

  let miniProgram;
  try {
    miniProgram = await launchMiniProgram();
    await clearAllNamespaces(miniProgram);

    // warm-up + settle: the first reLaunch can race onShow render.
    await miniProgram.reLaunch('/' + QUESTIONS_ROUTE);
    await delay(800);
    await miniProgram.reLaunch('/' + QUESTIONS_ROUTE);
    await delay(800);
    const baseline = await renderEvidence(miniProgram, 'baseline');
    report.render = { ...baseline, method: 'reLaunch+pageStack+screenshot' };
    if (baseline.ok) {
      ok(`render evidence: pageStack=${baseline.pageStack}, top=${baseline.topPath}, bytes=${baseline.screenshotBytes}`);
    } else {
      fail(`render check failed: ${JSON.stringify(baseline)}`);
      allOk = false;
    }

    // positive: seeded mhp_ records change the render (empty -> list)
    await miniProgram.callWxMethod('setStorageSync', 'mhp_' + QUESTIONS_RAW, SEED);
    await miniProgram.reLaunch('/' + QUESTIONS_ROUTE);
    await delay(800);
    const seeded = await renderEvidence(miniProgram, 'seeded');
    const mhpChanged = seeded.screenshotMd5 !== baseline.screenshotMd5;
    report.render_seeded = { ...seeded, namespace: 'mhp_', changed_vs_baseline_md5: mhpChanged };
    if (seeded.ok && mhpChanged) {
      ok(`seeded mhp_ records change the render (md5 ${baseline.screenshotMd5} -> ${seeded.screenshotMd5})`);
    } else {
      fail(`seeded render did not change / render failed: ${JSON.stringify(report.render_seeded)}`);
      allOk = false;
    }

    // read-back: seeded records survive the page render unchanged
    const readBackSeeded = await miniProgram.callWxMethod('getStorageSync', 'mhp_' + QUESTIONS_RAW);
    const readBackOk = JSON.stringify(readBackSeeded) === JSON.stringify(SEED);
    report.storage_readback = {
      key: 'mhp_records_questions',
      written: SEED,
      read_back: readBackSeeded,
      matches: readBackOk,
    };
    if (readBackOk) {
      ok('seed read-back: stored records match after the page rendered');
    } else {
      fail('seed read-back mismatch');
      allOk = false;
    }

    // negative control: legacy hza_ namespace must NOT change the render
    await miniProgram.callWxMethod('removeStorageSync', 'mhp_' + QUESTIONS_RAW);
    await miniProgram.callWxMethod('setStorageSync', 'hza_' + QUESTIONS_RAW, SEED);
    await miniProgram.reLaunch('/' + QUESTIONS_ROUTE);
    await delay(800);
    const legacyShot = await renderEvidence(miniProgram, 'legacy-hza');
    await miniProgram.callWxMethod('removeStorageSync', 'hza_' + QUESTIONS_RAW);
    const hzaChanged = legacyShot.screenshotMd5 !== baseline.screenshotMd5;
    report.namespace = {
      declared: 'mhp_',
      candidates: APP_NAMESPACES,
      runtime_observed: mhpChanged && !hzaChanged ? 'mhp_' : null,
      empty_baseline_md5: baseline.screenshotMd5,
      observations: {
        mhp_: { md5: seeded.screenshotMd5, bytes: seeded.screenshotBytes, changed_vs_baseline: mhpChanged },
        hza_: { md5: legacyShot.screenshotMd5, bytes: legacyShot.screenshotBytes, changed_vs_baseline: hzaChanged },
      },
    };
    if (report.namespace.runtime_observed === 'mhp_') {
      ok('runtime namespace is "mhp_" (mhp_ write changes render; hza_ does not)');
    } else {
      fail(`runtime namespace must be "mhp_" but observed ${JSON.stringify(report.namespace)}`);
      allOk = false;
    }

    // persistence across full close + relaunch
    await miniProgram.callWxMethod('setStorageSync', 'mhp_' + QUESTIONS_RAW, SEED);
    await miniProgram.reLaunch('/' + QUESTIONS_ROUTE);
    await delay(800);
    try {
      await miniProgram.close();
      log('miniProgram.close() done');
    } catch (err) {
      log(`warning: close failed: ${err?.message || err}`);
    }
    await delay(2000);
    miniProgram = await launchMiniProgram();
    const persisted = await miniProgram.callWxMethod('getStorageSync', 'mhp_' + QUESTIONS_RAW);
    const persistedOk = JSON.stringify(persisted) === JSON.stringify(SEED);
    report.persistence = {
      key: 'mhp_records_questions',
      read_back: persisted,
      matches: persistedOk,
      persisted_after_relaunch: persistedOk,
    };
    if (persistedOk) {
      ok('seeded questions persist across full close+relaunch');
    } else {
      fail('seeded questions did not persist across relaunch');
      allOk = false;
    }

    await clearAllNamespaces(miniProgram);
  } catch (err) {
    fail(`questions spec run error: ${err?.stack || err}`);
    report.error = err?.message || String(err);
    allOk = false;
  } finally {
    if (miniProgram) {
      try {
        await miniProgram.close();
        log('miniProgram.close() done');
      } catch (err) {
        log(`warning: miniProgram.close() failed: ${err?.message || err}`);
      }
    }
  }

  const checks = {
    logic_harness_ok: logic.result !== null && logic.exit === 0 && logicFailed === 0,
    render_ok: report.render ? report.render.ok === true : false,
    seeded_render_changed: Boolean(report.render_seeded && report.render_seeded.changed_vs_baseline_md5 === true),
    namespace_observed: report.namespace ? report.namespace.runtime_observed === 'mhp_' : false,
    storage_readback_ok: Boolean(report.storage_readback && report.storage_readback.matches === true),
    persistence_ok: Boolean(report.persistence && report.persistence.persisted_after_relaunch === true),
    static_invariants_ok: staticsOk,
    no_forbidden_strings: statics.forbidden_strings_present.length === 0,
    no_severity_token: statics.severity_tokens_present.length === 0,
    font_scaled: statics.font_size_all_scaled === true && statics.bare_px_lines.length === 0,
    json_ok: statics.json_parses === true && statics.json_title === '待问清单',
  };
  const checksPassed = Object.values(checks).every((v) => v === true);
  log(`summary checks: ${JSON.stringify(checks)}`);

  report.summary = {
    ...checks,
    logic_scenarios_total: logic.result ? logic.result.summary.total : 0,
    logic_scenarios_passed: logic.result ? logic.result.summary.passed : 0,
    passed: checksPassed && allOk === true,
    failed: !(checksPassed && allOk === true),
  };

  const reportPath = path.join(E2E_DIR, 'questions.json');
  fs.writeFileSync(reportPath, JSON.stringify(report, null, 2) + '\n');
  log(`questions evidence: ${reportPath}`);

  return report.summary.passed;
}

main().then(
  (passed) => {
    process.exit(passed ? 0 : 1);
  },
  (err) => {
    console.error(`[e2e] FAIL ${err?.stack || err}`);
    process.exit(1);
  }
);
