// settings.spec.mjs — task 15 settings-page E2E (standalone).
//
// Run: node tests/e2e/settings.spec.mjs
//      node tests/e2e/settings.spec.mjs --simulate-wipe-partial   (failure mode, exit 1)
// Evidence: artifacts/e2e/settings.json (harness + automator)
//           artifacts/qa/15-failure.txt (raw wipe partial-failure transcript)
//
// Two independent layers, never conflated:
//   (1) LOGIC (real code path): pages/settings/settings.ts is imported into a
//       node/page-logic harness (Page-capture + a Map-backed wx shim with storage,
//       file system and a modal-response queue), exactly the sanctioned pattern
//       from profile.spec.mjs. This is the only way to reach the real page methods
//       over this devtools build (Page.* protocol dropped): font slider, high
//       contrast, AI consent (cancel/confirm/off), memory CRUD/enable/clear,
//       autoMemory, export product, two-step wipe, and a fault-injected partial
//       wipe + retry.
//   (2) RUNTIME (automator): launch, reLaunch to pages/settings, screenshot
//       (render proof), write a preferences record into each candidate namespace
//       to prove the font-size render effect AND that the runtime reads `mhp_`,
//       then full close+relaunch to prove preferences persist.
//
// Transport notes (WeChat DevTools 2.01.x): only App-level calls respond —
// currentPage/pageStack/screenshot/callWxMethod/reLaunch/close. Do NOT use Page.*.
// Consent modals never appear under devtools automation, so they are exercised in
// the logic harness; this spec never fakes a modal tap.
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {
  CONFIG,
  E2E_ARTIFACTS,
  ROOT,
  ensureDir,
  fail,
  launchMiniProgram,
  log,
  ok,
  section,
  delay,
  md5,
  readSafe,
  makeCaptureScreenshot,
} from './helpers.mjs';

const SETTINGS_ROUTE = 'pages/settings/settings';
const APP_NAMESPACES = ['mhp_', 'hza_'];
const RAW_KEYS = {
  preferences: 'records_preferences',
  profile: 'records_profile',
  symptoms: 'records_symptoms',
  notes: 'records_notes',
  questions: 'records_questions',
  briefs: 'records_briefs',
  memory: 'records_memory',
};
const ALL_RAW = Object.values(RAW_KEYS);

const E2E_DIR = E2E_ARTIFACTS;
const QA_FAILURE_PATH = path.join(path.resolve(E2E_ARTIFACTS, '..'), 'qa', '15-failure.txt');
const MINIAPP_ROOT = CONFIG.projectPath;
const SETTINGS_DIR = path.join(MINIAPP_ROOT, 'pages', 'settings');

// ---------------------------------------------------------------------------
// Layer 1: node/page-logic harness (real page methods + Map wx shim)
// ---------------------------------------------------------------------------

const HARNESS_SOURCE = String.raw`// temp settings-logic harness (run via tsx); not committed — generated by settings.spec.mjs
import { pathToFileURL } from 'node:url';
import { writeFileSync } from 'node:fs';
const { makeCheck, makeInstanceFactory, makeLastToast, makeStoreKeys } = await import(${JSON.stringify(new URL('./helpers.mjs', import.meta.url).href)});

const settingsTs = process.env.MHP_SETTINGS_TS;
const appTs = process.env.MHP_APP_TS;
const root = process.env.MHP_MINIAPP_ROOT;
const outPath = process.env.MHP_HARNESS_OUT;
const failureOut = process.env.MHP_FAILURE_OUT;
if (!settingsTs) throw new Error('MHP_SETTINGS_TS not set');
if (!appTs) throw new Error('MHP_APP_TS not set');
if (!root) throw new Error('MHP_MINIAPP_ROOT not set');
if (!outPath) throw new Error('MHP_HARNESS_OUT not set');

const USER_DATA = '/tmp/mhp-settings-harness/usr';
const ATTACH_DIR = USER_DATA + '/attachments/';
const store = new Map();
const files = new Map();
const modalResponses = [];
let faultArmed = false;
let faultKey = null;
let failWrites = false;
const calls = { toast: [], modal: [], vibrateShort: [], writeFile: [], unlink: [] };

function modalResult() {
  if (modalResponses.length > 0) return modalResponses.shift() === true;
  return true;
}

const fsManager = {
  writeFile: function (options) {
    if (failWrites) {
      failWrites = false;
      if (typeof options.fail === 'function') options.fail({ errMsg: 'writeFile:fail mocked' });
      return;
    }
    calls.writeFile.push({ filePath: options.filePath, data: options.data, encoding: options.encoding });
    files.set(options.filePath, String(options.data));
    if (typeof options.success === 'function') options.success({});
  },
  readdirSync: function (dir) {
    const prefix = dir.endsWith('/') ? dir : dir + '/';
    const names = [];
    for (const key of Array.from(files.keys())) {
      if (key.indexOf(prefix) === 0) {
        const rest = key.slice(prefix.length);
        if (rest !== '' && rest.indexOf('/') === -1) names.push(rest);
      }
    }
    return names;
  },
  unlinkSync: function (p) { calls.unlink.push(p); files.delete(p); },
  statSync: function (p) { return { size: files.has(p) ? String(files.get(p)).length : 0 }; },
  mkdirSync: function () {},
  saveFileSync: function (src, dest) { files.set(dest, files.has(src) ? files.get(src) : ''); return dest; },
};

globalThis.wx = {
  env: { USER_DATA_PATH: USER_DATA },
  getStorageSync: function (key) { return store.has(key) ? store.get(key) : ''; },
  setStorageSync: function (key, value) { store.set(key, value); },
  removeStorageSync: function (key) {
    if (faultArmed && key === faultKey) {
      faultArmed = false;
      throw new Error('mocked removeStorageSync failure for ' + key);
    }
    store.delete(key);
  },
  getStorageInfoSync: function () { return { keys: Array.from(store.keys()) }; },
  showToast: function (options) { calls.toast.push(options); },
  showModal: function (options) {
    calls.modal.push(options);
    if (options && typeof options.success === 'function') options.success({ confirm: modalResult(), cancel: false });
  },
  vibrateShort: function (options) { calls.vibrateShort.push(options || {}); },
  vibrateLong: function () {},
  getFileSystemManager: function () { return fsManager; },
};

globalThis.App = function () {};
let captured = null;
globalThis.Page = function (config) { captured = config; };

const path = await import('node:path');
const appModule = await import(pathToFileURL(appTs).href);
const recordsModule = await import(pathToFileURL(path.join(root, 'shared/services/records.ts')).href);
const attachmentsModule = await import(pathToFileURL(path.join(root, 'shared/services/attachments.ts')).href);
const oplogModule = await import(pathToFileURL(path.join(root, 'shared/services/oplog.ts')).href);
const records = recordsModule.records;
const PRIVACY_NOTICE_VERSION = appModule.PRIVACY_NOTICE_VERSION;

await import(pathToFileURL(settingsTs).href);
if (captured === null) throw new Error('settings.ts did not call Page()');

const makeInstance = makeInstanceFactory(() => captured, { cloneExtras: false });
function prefsRaw() { return store.has('mhp_records_preferences') ? store.get('mhp_records_preferences') : null; }
function memoryRaw() { const v = store.get('mhp_records_memory'); return Array.isArray(v) ? v : []; }
const storeKeys = makeStoreKeys(store);
function snapshotKeysValues() { return JSON.stringify(storeKeys().map(function (k) { return [k, store.get(k)]; })); }
function resetAll() {
  store.clear(); files.clear();
  modalResponses.length = 0;
  calls.toast.length = 0; calls.modal.length = 0; calls.vibrateShort.length = 0;
  calls.writeFile.length = 0; calls.unlink.length = 0;
  faultArmed = false; faultKey = null; failWrites = false;
}
const lastToast = makeLastToast(calls);
function lastModal() { return calls.modal[calls.modal.length - 1] || null; }
function seedMemory(texts) { const out = []; for (const t of texts) out.push(records.memory.add({ text: t, source: 'manual' })); return out; }

const cases = [];
const check = makeCheck(cases);

// s1 fresh defaults
resetAll();
let inst = makeInstance();
inst.onShow();
check('fresh', 'fresh: defaults (fontSize 14, scale 1, ai off, autoMemory on, no memory)',
  inst.data.fontSize === 14 && inst.data.scale === 1 && inst.data.highContrast === false &&
    inst.data.aiEnabled === false && inst.data.consentVersion === null && inst.data.autoMemory === true &&
    inst.data.memories.length === 0 && inst.data.hasMemories === false,
  { fontSize: inst.data.fontSize, scale: inst.data.scale, highContrast: inst.data.highContrast, aiEnabled: inst.data.aiEnabled, autoMemory: inst.data.autoMemory, memories: inst.data.memories.length, keys: storeKeys() });

// s2 font persist
resetAll(); inst = makeInstance(); inst.onShow();
inst.onFontSizeChange({ detail: { value: 24 } });
const p2 = prefsRaw();
check('font-persist', 'font slider: onFontSizeChange writes fontSize and updates page scale',
  p2 !== null && p2.fontSize === 24 && inst.data.fontSize === 24 && Math.abs(inst.data.scale - 24 / 14) < 1e-9,
  { prefs: p2, data_fontSize: inst.data.fontSize, scale: inst.data.scale });

// s3 clamp
resetAll(); inst = makeInstance(); inst.onShow();
inst.onFontSizeChange({ detail: { value: 40 } });
const p3 = prefsRaw();
check('font-clamp', 'font slider: out-of-range value clamped to 32 by records',
  p3 !== null && p3.fontSize === 32 && inst.data.fontSize === 32 && Math.abs(inst.data.scale - 32 / 14) < 1e-9,
  { prefs: p3, data_fontSize: inst.data.fontSize });

// s4 drag preview does not persist
resetAll(); inst = makeInstance(); inst.onShow();
inst.onFontSizeChanging({ detail: { value: 30 } });
check('font-preview', 'font slider: drag preview scales without writing storage',
  store.has('mhp_records_preferences') === false && inst.data.fontSize === 30 && Math.abs(inst.data.scale - 30 / 14) < 1e-9,
  { prefs_present: store.has('mhp_records_preferences'), data_fontSize: inst.data.fontSize, scale: inst.data.scale });

// s5 high contrast
resetAll(); inst = makeInstance(); inst.onShow();
inst.onHighContrastChange({ detail: { value: true } });
const p5 = prefsRaw();
check('high-contrast', 'high contrast: switch writes highContrast and page reflects it',
  p5 !== null && p5.highContrast === true && inst.data.highContrast === true,
  { prefs: p5, data_highContrast: inst.data.highContrast });

// s6 AI consent cancel
resetAll(); inst = makeInstance(); inst.onShow();
modalResponses.push(false);
inst.onAiEnabledChange({ detail: { value: true } });
const p6 = prefsRaw();
const m6 = lastModal();
check('ai-consent-cancel', 'AI toggle ON + cancel: stays off, no consent written; modal shows send scope',
  inst.data.aiEnabled === false && (p6 === null || p6.aiEnabled === false) &&
    (p6 === null || p6.consentVersion === null) &&
    m6 !== null && typeof m6.content === 'string' && m6.content.indexOf('当前输入') >= 0 && m6.content.indexOf('记忆') >= 0,
  { prefs: p6, data_aiEnabled: inst.data.aiEnabled, modal: m6 });

// s7 AI consent confirm
resetAll(); inst = makeInstance(); inst.onShow();
modalResponses.push(true);
inst.onAiEnabledChange({ detail: { value: true } });
const p7 = prefsRaw();
check('ai-consent-confirm', 'AI toggle ON + confirm: writes aiEnabled + consentVersion === PRIVACY_NOTICE_VERSION',
  inst.data.aiEnabled === true && p7 !== null && p7.aiEnabled === true && p7.consentVersion === PRIVACY_NOTICE_VERSION &&
    typeof PRIVACY_NOTICE_VERSION === 'number',
  { prefs: p7, privacy_notice_version: PRIVACY_NOTICE_VERSION, data_aiEnabled: inst.data.aiEnabled });

// s8 AI off immediate
inst.onAiEnabledChange({ detail: { value: false } });
const p8 = prefsRaw();
check('ai-off-immediate', 'AI toggle OFF: aiEnabled=false immediately, consentVersion kept',
  inst.data.aiEnabled === false && p8 !== null && p8.aiEnabled === false && p8.consentVersion === PRIVACY_NOTICE_VERSION,
  { prefs: p8, data_aiEnabled: inst.data.aiEnabled });

// s9 memory add
resetAll(); inst = makeInstance(); inst.onShow();
inst.onMemoryDraftInput({ detail: { value: '  偏好简短  ' } });
inst.onMemorySave();
const m9 = memoryRaw();
check('memory-add', 'memory add: draft saved trimmed, source=manual, enabled=true; view refreshed',
  m9.length === 1 && m9[0].text === '偏好简短' && m9[0].source === 'manual' && m9[0].enabled === true &&
    inst.data.memories.length === 1 && inst.data.hasMemories === true && inst.data.memoryDraft === '',
  { stored: m9, data_memories: inst.data.memories, draft: inst.data.memoryDraft });

// s10 memory empty guard
resetAll(); inst = makeInstance(); inst.onShow();
inst.onMemoryDraftInput({ detail: { value: '   ' } });
const before10 = snapshotKeysValues();
inst.onMemorySave();
const after10 = snapshotKeysValues();
check('memory-empty-guard', 'memory add guard: whitespace-only draft rejected, no write',
  memoryRaw().length === 0 && before10 === after10 && inst.data.memoryError !== '',
  { bytes_identical: before10 === after10, error: inst.data.memoryError, toast: lastToast() });

// s11 memory edit
resetAll(); inst = makeInstance(); inst.onShow();
const seed11 = records.memory.add({ text: '原始记忆' });
inst.refreshMemories();
inst.onMemoryEdit({ currentTarget: { dataset: { id: seed11.id } } });
const loaded11 = inst.data.editingId === seed11.id && inst.data.memoryDraft === '原始记忆';
inst.onMemoryDraftInput({ detail: { value: '修改后的记忆' } });
inst.onMemorySave();
const after11 = memoryRaw();
check('memory-edit', 'memory edit: tap row loads form, save updates text in place (id stable)',
  loaded11 && after11.length === 1 && after11[0].text === '修改后的记忆' && after11[0].id === seed11.id && inst.data.editingId === '',
  { loaded: loaded11, stored: after11, editingId: inst.data.editingId });

// s12 memory toggle
resetAll(); inst = makeInstance(); inst.onShow();
const seed12 = records.memory.add({ text: '启停记忆' });
inst.refreshMemories();
inst.onMemoryToggle({ currentTarget: { dataset: { id: seed12.id } }, detail: { value: false } });
const after12 = memoryRaw();
check('memory-toggle', 'memory enable switch: writes enabled=false and reflects in list',
  after12.length === 1 && after12[0].enabled === false && inst.data.memories.length === 1 && inst.data.memories[0].enabled === false,
  { stored: after12, data_memories: inst.data.memories });

// s13 memory delete
resetAll(); inst = makeInstance(); inst.onShow();
const seed13 = records.memory.add({ text: '待删除' });
inst.refreshMemories();
modalResponses.push(true);
inst.onMemoryDelete({ currentTarget: { dataset: { id: seed13.id } } });
check('memory-delete', 'memory single delete: confirm removes the row',
  memoryRaw().length === 0 && inst.data.memories.length === 0 && inst.data.hasMemories === false,
  { stored: memoryRaw(), modal: lastModal() });

// s14 memory clear all
resetAll(); inst = makeInstance(); inst.onShow();
seedMemory(['a', 'b', 'c']);
inst.refreshMemories();
modalResponses.push(true);
inst.onMemoryClearAll();
check('memory-clear-all', 'memory clear all: confirm deletes every memory',
  memoryRaw().length === 0 && inst.data.memories.length === 0 && inst.data.hasMemories === false && inst.data.resultText.indexOf('3') >= 0,
  { stored: memoryRaw(), resultText: inst.data.resultText });

// s15 autoMemory
resetAll(); inst = makeInstance(); inst.onShow();
inst.onAutoMemoryChange({ detail: { value: false } });
const off15 = prefsRaw();
inst.onAutoMemoryChange({ detail: { value: true } });
const on15 = prefsRaw();
check('auto-memory', 'autoMemory switch: false persists, then true persists (default was true)',
  off15 !== null && off15.autoMemory === false && on15 !== null && on15.autoMemory === true,
  { off: off15, on: on15 });

// s16 wipe end-to-end
resetAll(); inst = makeInstance(); inst.onShow();
records.profile.add({ name: '李阿姨', ageRange: '60-69', gender: '女', allergies: '', medications: '', history: '' });
records.symptoms.add({ occurredAt: '2026-09-01T09:00:00.000Z', duration: '', text: '咳嗽', impact: '', tags: [], attachment: null });
records.notes.add({ name: '体检单', excerpt: '血压偏高', sourceDate: '2026-08', attachment: null, remark: '' });
records.memory.add({ text: '记忆A' });
records.preferences.update({ fontSize: 24, aiEnabled: true, consentVersion: PRIVACY_NOTICE_VERSION, autoMemory: false });
store.set('hza_legacy', 'legacy-value');
files.set(ATTACH_DIR + 'att_1.png', 'PNGDATA');
files.set(ATTACH_DIR + 'att_2.jpg', 'JPGDATA');
const before16Keys = storeKeys();
modalResponses.push(true, true);
inst.onWipe();
const after16Keys = storeKeys();
const mhpRecordKeysAfter = after16Keys.filter(function (k) { return k.indexOf('mhp_records') === 0; });
const oplogAfter = store.get('mhp_oplog');
const opTypes = Array.isArray(oplogAfter) ? oplogAfter.map(function (e) { return e.type; }) : [];
const attachLeft = Array.from(files.keys()).filter(function (k) { return k.indexOf(ATTACH_DIR) === 0; });
check('wipe-e2e', 'wipe: two-step confirm clears mhp_ records + legacy ns + attachments; counts + oplog audit',
  before16Keys.length > 0 && mhpRecordKeysAfter.length === 0 && store.has('hza_legacy') === false &&
    attachLeft.length === 0 && calls.unlink.length >= 2 && opTypes.indexOf('clear') >= 0 &&
    after16Keys.length === 1 && after16Keys[0] === 'mhp_oplog' &&
    inst.data.fontSize === 14 && inst.data.aiEnabled === false && inst.data.resultText.indexOf('附件文件 2') >= 0,
  { before_keys: before16Keys, after_keys: after16Keys, mhp_record_keys_after: mhpRecordKeysAfter, unlink_calls: calls.unlink.length, oplog_types: opTypes, resultText: inst.data.resultText, data_fontSize: inst.data.fontSize });

// s17 export content
resetAll(); inst = makeInstance(); inst.onShow();
records.symptoms.add({ occurredAt: '2026-09-01T09:00:00.000Z', duration: '3 天', text: '夜里咳嗽', impact: '', tags: [], attachment: ATTACH_DIR + 'att_9.png' });
records.memory.add({ text: '偏好简短' });
files.set(ATTACH_DIR + 'att_9.png', 'PNGDATA');
inst.onExport();
const wf = calls.writeFile[0] || null;
let parsed17 = null;
try { parsed17 = wf ? JSON.parse(wf.data) : null; } catch (e) {}
check('export-content', 'export: writes JSON under USER_DATA_PATH with records + attachment name/path + notice; logged',
  wf !== null && typeof wf.filePath === 'string' && wf.filePath.indexOf(USER_DATA) === 0 &&
    parsed17 !== null && typeof parsed17.notice === 'string' && parsed17.notice.indexOf('图片文件不随文本导出') >= 0 &&
    Array.isArray(parsed17.records.symptoms) && parsed17.records.symptoms.length === 1 &&
    parsed17.records.symptoms[0].attachment === ATTACH_DIR + 'att_9.png' &&
    Array.isArray(parsed17.attachments) && parsed17.attachments.some(function (a) { return a.name === 'att_9.png' && a.path === ATTACH_DIR + 'att_9.png'; }) &&
    parsed17.records.memory.length === 1 &&
    oplogModule.list().some(function (e) { return e.type === 'export'; }),
  { filePath: wf ? wf.filePath : null, notice: parsed17 ? parsed17.notice : null, attachments: parsed17 ? parsed17.attachments : null, oplog: oplogModule.list() });

// s18 export failure surfaced
resetAll(); inst = makeInstance(); inst.onShow();
failWrites = true;
inst.onExport();
check('export-fail', 'export failure: writeFile fail surfaces readable error, no path shown',
  inst.data.exportError !== '' && inst.data.exportPath === '',
  { exportError: inst.data.exportError, toast: lastToast() });

// ---- Failure path: wipe partial failure (real fault injection) ----
const flines = [];
function flog() {
  const line = Array.prototype.join.call(arguments, ' ');
  flines.push(line);
  console.log(line);
}

resetAll();
const fInst = makeInstance();
fInst.onShow();
records.profile.add({ name: '李阿姨', ageRange: '60-69', gender: '女', allergies: '', medications: '', history: '' });
records.symptoms.add({ occurredAt: '2026-09-01T09:00:00.000Z', duration: '', text: '咳嗽', impact: '', tags: [], attachment: null });
records.memory.add({ text: '记忆1' });
store.set('hza_legacy', 'legacy-value');
files.set(ATTACH_DIR + 'att_1.png', 'PNGDATA');

const fBefore = storeKeys();
faultKey = 'mhp_records_symptoms';
faultArmed = true;
modalResponses.push(true, true);
fInst.onWipe();

const fAfter = storeKeys();
const remainedSymptoms = store.get('mhp_records_symptoms');
const selfConsistent = Array.isArray(remainedSymptoms) && remainedSymptoms.length === 1 && remainedSymptoms[0].text === '咳嗽';
const surfaced = typeof fInst.data.wipeError === 'string' && fInst.data.wipeError !== '';
const progressed = fAfter.length < fBefore.length;

flog('--- wipe partial-failure fault injection (REAL page methods) ---');
flog('command: node tests/e2e/settings.spec.mjs');
flog('timestamp: ' + new Date().toISOString());
flog('method: REAL performWipe() from pages/settings/settings.ts; wx shim removeStorageSync throws once for ' + faultKey);
flog('seeded_keys: ' + JSON.stringify(fBefore));
flog('fault_consumed: ' + (faultArmed === false));
flog('after_failed_attempt_keys: ' + JSON.stringify(fAfter));
flog('wipeError: ' + JSON.stringify(fInst.data.wipeError));
flog('error_surfaced_readably: ' + surfaced);
flog('remaining mhp_records_symptoms byte-intact: ' + selfConsistent);
flog('progress_made_some_keys_removed: ' + progressed);
flog('attachments_left_after_failed_attempt: ' + JSON.stringify(Array.from(files.keys()).filter(function (k) { return k.indexOf(ATTACH_DIR) === 0; })));

modalResponses.push(true, true);
fInst.onWipe();
const fRetry = storeKeys();
const retryUserKeys = fRetry.filter(function (k) { return k.indexOf('mhp_records') === 0 || k === 'hza_legacy'; });
const attachRetry = Array.from(files.keys()).filter(function (k) { return k.indexOf(ATTACH_DIR) === 0; });
const retryOk = fRetry.length === 1 && fRetry[0] === 'mhp_oplog' && retryUserKeys.length === 0 && fInst.data.wipeError === '';
flog('retry_after_keys: ' + JSON.stringify(fRetry));
flog('retry_user_keys_remaining: ' + JSON.stringify(retryUserKeys));
flog('retry_wipeError: ' + JSON.stringify(fInst.data.wipeError));
flog('retry_attachments_left: ' + JSON.stringify(attachRetry));
flog('retry_completed_wipe: ' + retryOk);
flog('');
flog('verdict: partial failure surfaced readably, remaining data self-consistent, retry completes the wipe.');
flog('');

const failurePass = surfaced && selfConsistent && progressed && retryOk;
check('wipe-partial-failure', 'wipe partial failure: error surfaced, data self-consistent, retry completes',
  failurePass,
  { before_keys: fBefore, after_failed_keys: fAfter, wipeError: fInst.data.wipeError, self_consistent: selfConsistent, progressed: progressed, retry_keys: fRetry, retry_ok: retryOk });

if (failureOut) {
  writeFileSync(failureOut, [
    'T15 settings failure-path evidence (wipe partial failure, real fault injection)',
    ...flines,
    'exit_code: 1',
    '',
  ].join('\n'));
}

const failed = cases.filter(function (c) { return !c.pass; }).length;
const result = {
  generated_at: new Date().toISOString(),
  settings_ts: settingsTs,
  privacy_notice_version: PRIVACY_NOTICE_VERSION,
  note: 'REAL page methods from pages/settings/settings.ts; wx = Map-backed shim (storage + file system + modal queue)',
  scenarios: cases,
  failure_path: { lines: flines, pass: failurePass },
  summary: { total: cases.length, passed: cases.length - failed, failed: failed },
};
writeFileSync(outPath, JSON.stringify(result, null, 2) + '\n');
console.log(JSON.stringify(result, null, 2));
process.exit(failed === 0 ? 0 : 1);
`;

function runLogicHarness() {
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'mhp-settings-harness-'));
  const harnessPath = path.join(tmpDir, 'settings-logic.harness.mjs');
  const outPath = path.join(tmpDir, 'settings-logic.result.json');
  const failurePath = path.join(tmpDir, 'settings-failure.txt');
  fs.writeFileSync(harnessPath, HARNESS_SOURCE);

  const res = spawnSync(process.execPath, ['--import', 'tsx', harnessPath], {
    cwd: ROOT,
    encoding: 'utf8',
    env: {
      ...process.env,
      MHP_SETTINGS_TS: path.join(SETTINGS_DIR, 'settings.ts'),
      MHP_APP_TS: path.join(MINIAPP_ROOT, 'app.ts'),
      MHP_MINIAPP_ROOT: MINIAPP_ROOT,
      MHP_HARNESS_OUT: outPath,
      MHP_FAILURE_OUT: failurePath,
    },
    timeout: 90000,
    maxBuffer: 32 * 1024 * 1024,
  });
  const stdout = `${res.stdout || ''}`;
  const stderr = `${res.stderr || ''}`;

  let result = null;
  if (fs.existsSync(outPath)) {
    try {
      result = JSON.parse(fs.readFileSync(outPath, 'utf8'));
    } catch (err) {
      fail(`harness result JSON unparsable: ${err?.message || err}`);
    }
  }
  const failureRaw = fs.existsSync(failurePath) ? fs.readFileSync(failurePath, 'utf8') : '';
  return {
    method: 'node --import tsx <temp harness> (Page-capture + Map wx shim: storage/fs/modal)',
    settings_ts: path.join(SETTINGS_DIR, 'settings.ts'),
    exit: res.status,
    stdout_tail: stdout.slice(-8000),
    stderr_tail: stderr.slice(-8000),
    result,
    failure_raw: failureRaw,
  };
}

// ---------------------------------------------------------------------------
// Static invariants (source-level, no runtime claim)
// ---------------------------------------------------------------------------


const FORBIDDEN_STRINGS = ['AI 注入', 'health_profile', 'hza_', 'System Prompt', '系统提示词'];

function staticInvariantChecks() {
  const ts = readSafe(path.join(SETTINGS_DIR, 'settings.ts'));
  const wxml = readSafe(path.join(SETTINGS_DIR, 'settings.wxml'));
  const wxss = readSafe(path.join(SETTINGS_DIR, 'settings.wxss'));
  const json = readSafe(path.join(SETTINGS_DIR, 'settings.json'));
  const combined = [ts, wxml, wxss, json].join('\n');

  const forbidden = FORBIDDEN_STRINGS.filter((term) => combined.includes(term));
  const usesRecordsApi = /records\.(preferences|memory)\.(get|update|add|remove|list)\s*\(/.test(ts);
  const directStorage = /wx\.(get|set|remove)StorageSync\s*\(/.test(ts);
  const importsConsentVersion =
    /PRIVACY_NOTICE_VERSION/.test(ts) && /from\s+['"]\.\.\/\.\.\/app['"]/.test(ts);
  const usesDeletionApis =
    /deleteAll\s*\(/.test(ts) && /purgeLegacy\s*\(/.test(ts) && /clearAttachments\s*\(/.test(ts);
  const usesExportWrite = /writeFile\s*\(/.test(ts) && /USER_DATA_PATH/.test(ts);
  const usesOplog = /oplog\.append\s*\(/.test(ts);

  let jsonParses = false;
  let jsonTitle = null;
  try {
    const parsed = JSON.parse(json);
    jsonParses = true;
    jsonTitle = parsed.navigationBarTitleText ?? null;
  } catch {
    jsonParses = false;
  }

  const fontLines = wxss.split(/\r?\n/).filter((line) => line.includes('font-size'));
  const fontAllScaled =
    fontLines.length > 0 && fontLines.every((line) => /calc\([^)]*var\(--mhp-scale\)\)/.test(line));
  const wxmlScaleInline = /--mhp-scale:\s*\{\{scale\}\}/.test(wxml);
  const wxssHighContrastVars = wxss.includes('--mhp-hc-bg') && wxss.includes('--mhp-hc-text');

  return {
    settings_ts_exists: fs.existsSync(path.join(SETTINGS_DIR, 'settings.ts')),
    settings_js_exists: fs.existsSync(path.join(SETTINGS_DIR, 'settings.js')),
    forbidden_strings_present: forbidden,
    uses_records_api: usesRecordsApi,
    direct_storage_calls: directStorage,
    imports_consent_version: importsConsentVersion,
    uses_deletion_apis: usesDeletionApis,
    uses_export_write: usesExportWrite,
    uses_oplog: usesOplog,
    json_parses: jsonParses,
    json_title: jsonTitle,
    font_size_lines: fontLines.length,
    font_size_all_scaled: fontAllScaled,
    wxml_scale_inline: wxmlScaleInline,
    wxss_high_contrast_vars: wxssHighContrastVars,
  };
}

// ---------------------------------------------------------------------------
// Layer 2: automator helpers
// ---------------------------------------------------------------------------

const captureScreenshot = makeCaptureScreenshot('settings');

async function renderEvidence(miniProgram, tag) {
  const stack = await miniProgram.pageStack();
  const top = Array.isArray(stack) && stack.length > 0 ? stack[stack.length - 1] : null;
  const shot = await captureScreenshot(miniProgram, tag);
  return {
    pageStack: stack.length,
    topPath: top ? top.path : null,
    topQuery: top ? top.query : null,
    screenshotBytes: shot.bytes,
    screenshotMd5: shot.md5,
    pngMagic: shot.pngMagic,
    ok:
      stack.length >= 1 &&
      top !== null &&
      top.path === SETTINGS_ROUTE &&
      shot.pngMagic &&
      shot.bytes > 5000,
  };
}

async function clearAllNamespaces(miniProgram) {
  for (const raw of ALL_RAW) {
    for (const ns of APP_NAMESPACES) {
      await miniProgram.callWxMethod('removeStorageSync', ns + raw);
    }
  }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  ensureDir(E2E_DIR);
  ensureDir(path.dirname(QA_FAILURE_PATH));
  section('SETTINGS SPEC');

  const failureOnly = process.argv.includes('--simulate-wipe-partial');

  // ---- Layer 1: real page logic ----
  const logic = runLogicHarness();
  const logicScenarios = logic.result ? logic.result.scenarios : [];
  const logicFailed = logic.result ? logic.result.summary.failed : -1;

  if (logic.failure_raw !== '') {
    fs.writeFileSync(QA_FAILURE_PATH, logic.failure_raw);
    log(`failure evidence: ${QA_FAILURE_PATH}`);
  }

  if (failureOnly) {
    process.stdout.write(logic.failure_raw);
    if (logic.result !== null && logicFailed === 0) {
      fail('failure mode: wipe partial-failure scenario did NOT fail as a failure demo');
      process.exit(1);
    }
    process.exit(1);
  }

  const report = {
    command: 'node tests/e2e/settings.spec.mjs',
    timestamp: new Date().toISOString(),
    platform: `${os.platform()} ${os.release()} (${os.arch()})`,
    node_version: process.version,
    project_path: CONFIG.projectPath,
    logic: {
      method: logic.method,
      settings_ts: logic.settings_ts,
      exit: logic.exit,
      result: logic.result,
    },
    render: null,
    render_fontsize: null,
    namespace: null,
    storage_readback: null,
    static_invariants: null,
    summary: null,
  };

  let allOk = true;

  if (logic.result !== null && logic.exit === 0 && logicFailed === 0) {
    ok(`logic harness: ${logic.result.summary.passed}/${logic.result.summary.total} scenarios passed (real page methods)`);
  } else {
    fail(`logic harness failed (exit=${logic.exit}, failed_scenarios=${logicFailed}); stderr tail: ${logic.stderr_tail}`);
    allOk = false;
  }
  for (const scenario of logicScenarios) {
    log(`  [logic] ${scenario.pass ? 'PASS' : 'FAIL'} ${scenario.id}: ${scenario.name}`);
    if (!scenario.pass) allOk = false;
  }

  // ---- Static invariants ----
  const statics = staticInvariantChecks();
  report.static_invariants = {
    settings_ts_exists: statics.settings_ts_exists,
    settings_js_exists: statics.settings_js_exists,
    forbidden_strings_present: statics.forbidden_strings_present,
    uses_records_api: statics.uses_records_api,
    direct_storage_calls: statics.direct_storage_calls,
    imports_consent_version: statics.imports_consent_version,
    uses_deletion_apis: statics.uses_deletion_apis,
    uses_export_write: statics.uses_export_write,
    uses_oplog: statics.uses_oplog,
    json_parses: statics.json_parses,
    json_title: statics.json_title,
    font_size_lines: statics.font_size_lines,
    font_size_all_scaled: statics.font_size_all_scaled,
    wxml_scale_inline: statics.wxml_scale_inline,
    wxss_high_contrast_vars: statics.wxss_high_contrast_vars,
  };
  const staticsOk =
    statics.settings_ts_exists === true &&
    statics.settings_js_exists === false &&
    statics.forbidden_strings_present.length === 0 &&
    statics.uses_records_api === true &&
    statics.direct_storage_calls === false &&
    statics.imports_consent_version === true &&
    statics.uses_deletion_apis === true &&
    statics.uses_export_write === true &&
    statics.uses_oplog === true &&
    statics.json_parses === true &&
    statics.json_title === '设置' &&
    statics.font_size_all_scaled === true &&
    statics.wxml_scale_inline === true &&
    statics.wxss_high_contrast_vars === true;
  if (staticsOk) {
    ok('static invariants: records API only; consent version imported; scale/hc wired; tokens-only scaled wxss');
  } else {
    fail(`static invariant failure: ${JSON.stringify(report.static_invariants)}`);
    allOk = false;
  }

  // ---- Layer 2: runtime ----
  let miniProgram;
  try {
    miniProgram = await launchMiniProgram();
    await clearAllNamespaces(miniProgram);

    // warm-up + settle: the first reLaunch can race onShow render.
    await miniProgram.reLaunch('/' + SETTINGS_ROUTE);
    await delay(800);
    await miniProgram.reLaunch('/' + SETTINGS_ROUTE);
    await delay(800);
    const baseline = await renderEvidence(miniProgram, 'baseline');
    report.render = { ...baseline, method: 'reLaunch+pageStack+screenshot' };
    if (baseline.ok) {
      ok(`render evidence: pageStack=${baseline.pageStack}, top=${baseline.topPath}, bytes=${baseline.screenshotBytes}`);
    } else {
      fail(`render check failed: ${JSON.stringify(baseline)}`);
      allOk = false;
    }

    const prefsLarge = {
      aiEnabled: false,
      consentVersion: null,
      fontSize: 32,
      highContrast: false,
      autoMemory: true,
      updatedAt: '2026-02-01T00:00:00.000Z',
    };

    // positive: mhp_ preferences change the render (font size effect)
    await miniProgram.callWxMethod('setStorageSync', 'mhp_' + RAW_KEYS.preferences, prefsLarge);
    await miniProgram.reLaunch('/' + SETTINGS_ROUTE);
    await delay(800);
    const fontLarge = await renderEvidence(miniProgram, 'font-32');
    const mhpChanged = fontLarge.screenshotMd5 !== baseline.screenshotMd5;
    report.render_fontsize = {
      ...fontLarge,
      namespace: 'mhp_',
      changed_vs_baseline_md5: mhpChanged,
    };

    // negative control: legacy namespace must NOT change the render
    await miniProgram.callWxMethod('removeStorageSync', 'mhp_' + RAW_KEYS.preferences);
    await miniProgram.callWxMethod('setStorageSync', 'hza_' + RAW_KEYS.preferences, prefsLarge);
    await miniProgram.reLaunch('/' + SETTINGS_ROUTE);
    await delay(800);
    const legacyShot = await captureScreenshot(miniProgram, 'legacy-hza');
    await miniProgram.callWxMethod('removeStorageSync', 'hza_' + RAW_KEYS.preferences);
    const hzaChanged = legacyShot.md5 !== baseline.screenshotMd5;

    report.namespace = {
      declared: 'mhp_',
      candidates: APP_NAMESPACES,
      runtime_observed: mhpChanged && !hzaChanged ? 'mhp_' : null,
      empty_baseline_md5: baseline.screenshotMd5,
      observations: {
        mhp_: { md5: fontLarge.screenshotMd5, bytes: fontLarge.screenshotBytes, changed_vs_baseline: mhpChanged },
        hza_: { md5: legacyShot.md5, bytes: legacyShot.bytes, changed_vs_baseline: hzaChanged },
      },
    };

    if (mhpChanged) {
      ok(`font-size 32 render differs from default 14 (md5 ${baseline.screenshotMd5} -> ${fontLarge.screenshotMd5})`);
    } else {
      fail(`font-size change did not change the render: ${JSON.stringify(report.render_fontsize)}`);
      allOk = false;
    }
    if (report.namespace.runtime_observed === 'mhp_') {
      ok('runtime namespace is "mhp_" (mhp_ write changes render; hza_ does not)');
    } else {
      fail(`runtime namespace must be "mhp_" but observed ${JSON.stringify(report.namespace)}`);
      allOk = false;
    }

    // persistence across full close + relaunch
    const persistPrefs = { ...prefsLarge, aiEnabled: true, autoMemory: false };
    await miniProgram.callWxMethod('setStorageSync', 'mhp_' + RAW_KEYS.preferences, persistPrefs);
    await miniProgram.reLaunch('/' + SETTINGS_ROUTE);
    await delay(800);
    try {
      await miniProgram.close();
      log('miniProgram.close() done');
    } catch (err) {
      log(`warning: close failed: ${err?.message || err}`);
    }
    await delay(2000);
    miniProgram = await launchMiniProgram();
    const persisted = await miniProgram.callWxMethod('getStorageSync', 'mhp_' + RAW_KEYS.preferences);
    const persistedOk = JSON.stringify(persisted) === JSON.stringify(persistPrefs);
    report.storage_readback = {
      key: 'mhp_records_preferences',
      written: persistPrefs,
      read_back: persisted,
      matches: persistedOk,
      persisted_after_relaunch: persistedOk,
    };
    if (persistedOk) {
      ok('preferences (fontSize/aiEnabled/autoMemory) persist across full close+relaunch');
    } else {
      fail(`preferences did not persist across relaunch: ${JSON.stringify(persisted)}`);
      allOk = false;
    }

    await clearAllNamespaces(miniProgram);
  } catch (err) {
    fail(`settings spec run error: ${err?.stack || err}`);
    report.error = err?.message || String(err);
    allOk = false;
  } finally {
    if (miniProgram) {
      try {
        await miniProgram.close();
        log('miniProgram.close() done');
      } catch (err) {
        log(`warning: miniProgram.close() failed: ${err?.message || err}`);
      }
    }
  }

  const checks = {
    logic_harness_ok: logic.result !== null && logic.exit === 0 && logicFailed === 0,
    render_ok: report.render ? report.render.ok === true : false,
    font_size_render_changed: Boolean(report.render_fontsize && report.render_fontsize.changed_vs_baseline_md5 === true),
    namespace_observed: report.namespace ? report.namespace.runtime_observed === 'mhp_' : false,
    persistence_ok: Boolean(report.storage_readback && report.storage_readback.persisted_after_relaunch === true),
    static_invariants_ok: staticsOk,
    no_forbidden_strings: statics.forbidden_strings_present.length === 0,
    font_scaled: statics.font_size_all_scaled === true,
    json_ok: statics.json_parses === true && statics.json_title === '设置',
  };
  const checksPassed = Object.values(checks).every((v) => v === true);
  log(`summary checks: ${JSON.stringify(checks)}`);

  report.summary = {
    ...checks,
    logic_scenarios_total: logic.result ? logic.result.summary.total : 0,
    logic_scenarios_passed: logic.result ? logic.result.summary.passed : 0,
    passed: checksPassed && allOk === true,
    failed: !(checksPassed && allOk === true),
  };

  const reportPath = path.join(E2E_DIR, 'settings.json');
  fs.writeFileSync(reportPath, JSON.stringify(report, null, 2) + '\n');
  log(`settings evidence: ${reportPath}`);

  return report.summary.passed;
}

main().then(
  (passed) => {
    process.exit(passed ? 0 : 1);
  },
  (err) => {
    console.error(`[e2e] FAIL ${err?.stack || err}`);
    process.exit(1);
  }
);
